### ISSUE TITLE
List of "Changed files" shows only the last file

### ISSUE THREAD

**Issue by VKostenc** [desktop/desktop#9061]
### Describe the bug
"Changes" tab shows empty space and then the last(by order) changed file.

### Version & OS
GitHub Desktop 2.3.1 & MacOS Mojave 10.14.6

### Steps to reproduce the behavior

1. Make changes in several files
2. Open GitHub Desktop
3. Switch from "Changes" to "History" tab
4. Switch back to the "Changes" tab
5. See error

### Expected behavior

List of changed files should be represented.

### Actual behavior

List of changed files is missed. You can see the space where they should be located and only the last file.

### Screenshots
<img width="1044" alt="Screen Shot 2020-02-06 at 3 14 18 PM" src="https://user-images.githubusercontent.com/13135644/73940156-9dce0980-48f3-11ea-9d7a-a8bf0b7f7481.png">

### Additional context

The issue appears after update to the latest GitHub Desktop.
Tried to reboot the app.

**Comment by steveward** [comment]
@VKostenc thanks for the report! This definitely looks like a bug. Are you able to consistently reproduce this issue across multiple repositories, or is it only happening in one specific repository?

**Comment by tierninho** [comment]
This is the second report of this bug, with the other being: https://github.com/desktop/desktop/issues/8919

**Comment by SmilinBrian** [comment]
I'm seeing this sporadically - same OS and GitHub Desktop version.

**Comment by SmilinBrian** [comment]
I'm seeing this somewhat consistently with the same OS & GitHub Desktop versions.
Log enclosed in case it is helpful.
[2020-02-07.desktop.production.log](https://github.com/desktop/desktop/files/4173162/2020-02-07.desktop.production.log)

**Comment by VKostenc** [comment]
Tried to reproduce with other repositories but without success. 
The issue was disappeared after reboot of the machine.
@steveward Should I close the issue? Or further investigation is needed because of appearing in other users?

**Comment by slawkens** [comment]
Same error happened for me today.

Windows 10 Pro. Latest GitHub Desktop version.

The issue appears when I scroll through History Tab and then switch back to Changes Tab. When I scroll to the top of the History Tab then switch back to Changes Tab then issue disappears.

Screencast:
![github_error](https://user-images.githubusercontent.com/16687302/74373891-9d46de80-4ddd-11ea-83b1-97567aa682a3.gif)

**Comment by tierninho** [comment]
@slawkens Many thanks for that video. I was able to reproduce this. Investigating now for a fix!

**Comment by jason-hernandez-73** [comment]
I am having a similar problem. I make changes to the local repo, but the "Changes" tab says "No Local Changes." I have been having to commit by going to my page and uploading the updated files. The "History" tab then shows the uploaded file added to my history. I have been through several machine restarts, and this problem persists.

**Comment by rifatwahid** [comment]
You could try running `git config core.filemode false` in the repository to see if that resolves things.
