### ISSUE TITLE
git desktop has no way to purge a user who logged on

### ISSUE THREAD

**Issue by kaunglwin** [desktop/desktop#9064]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
Closing this in favor of https://github.com/desktop/desktop/issues/9065
