### ISSUE TITLE
git desktop has no way to easily purge a previous user

### ISSUE THREAD

**Issue by kaunglwin** [desktop/desktop#9065]
### Describe the bug
no way to purge users from GitDesktop APP on windows 10.

on windows 10 it's not easy to purge a user from the git desktop app who should not exisit anymore, logout does not help.  User persists even after logout. 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1 student at school logs on to window 10 pc as jsmith22,
2)   logs on to github desktop app as user janedoe33 because that's a friends account,  
3) teacher asks student to logout and logon with an account they create on git for jsmith22

result is no menu to purge janedoe33

expected to be able to logout and delete account from local windows 10 PC

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@kaunglwin thanks for sharing this. Are you using persistent local user profiles or roaming profiles on these machines? GitHub Desktop installs to `%LocalAppData%` and stores data in `%AppData%` on a per-user basis. If you are using something like roaming profiles then that could definitely be causing this type of issue.

Possible to include your logs? See the Help menu in Desktop.

Regardless, I suggest try a full reinstall by following these steps:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

You will have to add your repos back. The fastest way is drag n drop. Let us know if that helps.

**Comment by tierninho** [comment]
@kaunglwin  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
