### ISSUE TITLE
Ability to add additional message to default commit message

### ISSUE THREAD

**Issue by vrangasam** [desktop/desktop#9068]
### Describe the feature or problem you’d like to solve
The default commit message text is useful, but would like to add some more message to the default commit message with a shortcut.
E.g., `Update config.js` is useful, but if there is a shortcut like option+tab autofills the default message and the cursor waits for the  user to fill additional message like `Update config.js to have userId`.

### Proposed solution

How will it benefit Desktop and its users?
Quickly add some additional info if there's a change in a file

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
Hi @vrangasam, thanks for the issue! The default is intended to be for a really quick update where you're prioritizing speed over being descriptive, and given that you can type whatever you'd like if you prefer being more descriptive, I'm hesitant to blend the two and I'm not sure this would be a very common use case. So I'm going to close this for now, but always open to revisiting if it's something we hear come up a lot from others. Thanks again!
