### ISSUE TITLE
fatal bad config line 1 in file .git/config 

### ISSUE THREAD

**Issue by AmBeulah** [desktop/desktop#9073]
Hi guys

### Steps to reproduce the behavior

1. Go to 'GitHub desktop'
2. Click on 'add repository located in the "select repository"'
3. Scroll down to 'click on clone repository'

### Expected behavior

![gitissue](https://user-images.githubusercontent.com/48661006/74094081-805b9400-4adb-11ea-909e-da2903634164.png)

### Actual behavior
![issue2](https://user-images.githubusercontent.com/48661006/74094088-91a4a080-4adb-11ea-85e1-f2d0a6d73884.png)

A clear and concise description of what actually happened.

![mainissue](https://user-images.githubusercontent.com/48661006/74094092-a123e980-4adb-11ea-9dea-d595dc2b21f5.png)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hi @AmBeulah, thanks for opening this!

The error message you're seeing comes from Git which is attempting to read the configuration file located inside of your repository at `C:\Users\TEMITAYO\Desktop\github\marrsconsults\.git\config` (you might not see the `.git` folder unless you [choose to view hidden files and directories](https://support.microsoft.com/en-us/help/4028316/windows-view-hidden-files-and-folders-in-windows-10).

It would appear as if the config file has become corrupt and Git is therefore unable to read it. In what way it's become corrupt is hard to say without seeing the contents but it should look something like the example below (taken from my config file for the desktop repository so obviously some values will be different)

<img width="431" alt="image" src="https://user-images.githubusercontent.com/634063/74164777-83ae6700-4c24-11ea-8d93-e6d822c7e0c5.png">

Take a look inside of your config file and see if there's anything obviously wrong in there and if you like you can paste a screenshot of the contents and we can try to help you locate the issue.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Comment by JideijeEmeka** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/75017328/119251678-a8e69080-bb5c-11eb-9bac-8cd9e482cc40.png)
this is the error i keep getting.
tried running flutter pub get but still getting same error.
below attached is my config file screenshot.
![Screenshot (20)](https://user-images.githubusercontent.com/75017328/119251769-21e5e800-bb5d-11eb-8818-58890d94667a.png)
