### ISSUE TITLE
Http Proxy Options

### ISSUE THREAD

**Issue by priyanshnama** [desktop/desktop#9075]
### Proxy Settings not Available
no option of configuring proxy and changing proxy settings is available

### Http Proxy Option in Options Window

Beneficial for users who do not know Bash commands and love GUI.

**Comment by niik** [comment]
Hi @priyanshnama, thanks for opening this! We are working on improving our support for proxies and we hope to ship some initial support in the next major release. I'm going to close this issue in favor of https://github.com/desktop/desktop/issues/2789 which is the issue we've chosen to represent the proxy work.
