### ISSUE TITLE
Individual file history/search

### ISSUE THREAD

**Issue by EricSambach** [desktop/desktop#9080]
### Describe the feature or problem you’d like to solve

1. The ability to search for filenames within the change history

2. The ability to list all change history for any individual file.

### Proposed solution

How will it benefit Desktop and its users?
1. Sometimes changes come in and it is not clear who made the change, it would help us to be able to search for a particular filename to find the commit comments and also be able to ask the individual who made the change what the reason for it was (if comment is unclear).
2. Being able to see the history of a single file can help to understand why/when changes were made.

**Comment by niik** [comment]
Hi @EricSambach, thanks for opening this. Just so that I'm on the same page, are you looking for something similar to [Git Blame on GitHub.com](https://help.github.com/en/github/managing-files-in-a-repository/tracking-changes-in-a-file)?

If you are is there something specific you'd expect to be able to get from Desktop that you aren't able to get from GitHub.com today?

**Comment by EricSambach** [comment]
Hello @niik 
Yes, point 2 does appear to be the Blame option, which would be nice if it was also directly available within GitHub Desktop. I was just hoping that GitHub Desktop could be the one-stop-shop for all GitHub functionality.

Point 1 is simply a file search over the change history.
Example: when I know a file was changed, but I don't know who or when the change was made, a search would be nice (some change sets can be very large).
Yes this could be seen by using GitHub directly, but I would prefer to search for it in Desktop directly, if possible.

**Comment by billygriffin** [comment]
Hi @EricSambach, thanks for the issue. I agree that this might be useful, but it hasn't actually come up from users as frequently as I'd expect so it hasn't been a big priority for us. We're tracking this in #3754, and I'll post your thoughts there so we have context. The `future proposal` label just means we'll be revisiting it, so ignore the fact that it's closed for now. Thank you again!
