### ISSUE TITLE
very slow to create new branch

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#9088]
### Describe the bug

since the latest update it's very slow to create new branch based on existing branch

### Version & OS

v2.3.1 on windows 10 Enterprise 1903

### Steps to reproduce the behavior

1. Go to current branch
2. Click on 'New branch'
3. select 'development' branch and enter name for new branch
4. select 'Create Branch'

### Expected behavior

a new branch created after couple seconds

### Actual behavior

the creating branching dialog keeps up for more than 1 minute

and when dismissed it's not checking out the new branch, instead it's still stays on the 'development' branch

### Logs

[2020-02-10.desktop.production.log](https://github.com/desktop/desktop/files/4183358/2020-02-10.desktop.production.log)

**Comment by niik** [comment]
Thanks for the report @Justin-JHG. I'm afraid I don't see anything out of the ordinary in your log file that would help us troubleshoot this but  a common culprit for this type of issue is normally antivirus/security software -- are you running any software on your machine that could be interfering with GitHub Desktop?

**Comment by MylesWardell** [comment]
I have this exact issue that was labelled the same thing. This cant just be me

**Comment by Justin-JHG** [comment]
@niik there is no updates on the antivirus/security software I'm using and I only experienced this issue after the latest update of desktop. It doesn't happen every time when I create a new branch.

**Comment by tierninho** [comment]
@Justin-JHG Is this still happening? Anything specific you have noticed that might help us troubleshoot? Thanks!

**Comment by Justin-JHG** [comment]
haven't happen for the last 2 weeks, so maybe it fixed itself somehow?
________________________________

**Comment by tierninho** [comment]
Thanks for the update. Going to close the issue for as there is not much to go on. Happy to reopen if needed.
