### ISSUE TITLE
Commits not counted on the Contribution while code pushed via Github Desktop

### ISSUE THREAD

**Issue by shyamzzp** [desktop/desktop#9094]
### Describe the bug
While commiting the code using the GithubDesktop, the commits are not reflected in the Contribution page while the commits done from the Github.com page itself are visible for the same.

### Version & OS

Version 2.3.1 - GithubDesktop
OS - Windows10

### Steps to reproduce the behavior

1. Go to GithubDesktop tool and clone or create a new repository.
2. Do some changes in the project or workspace to make a commit and then push the code to the repository from the tool.
3. The commit you wont be able to see it in the Contribution page.

### Expected behavior
Should be able to see the commits in the contribution page.

**Comment by niik** [comment]
Hi @shyamzzp, thanks for opening this!

GitHub uses the email address that you specify in Git (or in the Preferences -> Git dialog in Github Desktop) to associate your commits. It is only used for the purpose of identifying who made the commit. GitHub uses that email address to attribute those commits to your GitHub account. We have a [help article](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/) that explains this further.

Please verify that you are using the correct email address by going to the menu in GitHub Desktop and selecting `File` > `Options` > `Git`. I hope that helps explain things!

**Comment by shyamzzp** [comment]
Hi @niik, I checked the following option that you provided and a valid email address is entered at my end.
Further attaching the screenshot for the same.
Will reinstalling the application help?
![image](https://user-images.githubusercontent.com/8598690/74365599-6af4ab80-4df4-11ea-9411-ffc072acfef4.png)

**Comment by niik** [comment]
Hi @shyamzzp, thanks for getting back to us! No, reinstalling should affect things as the email address used in commits is stored in your global `.gitconfig` file in your home directory.

The best next step would be to read through our documentation on common causes for [contributions not showing up on your profile](https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile). Follow the steps to look at what email address is actually being used when you're committing with GitHub Desktop.

Hope that helps!
