### ISSUE TITLE
Menu Branch>Update from Master of Ctrl+Shift+U missing information (Feature)

### ISSUE THREAD

**Issue by kwhjvdkamp** [desktop/desktop#9095]
### Describe the feature or problem you’d like to solve
See enclosed file (Explanation.gif)
Using menu [Branch > Update from Master or Ctlr+SHIFT +U] 
A) When a repository is 'behind' a message is banner is shown for a second saying the repository is merged with the master
B) When a repository is apparently 'up to date' nothing is shown 
whereas
C) if one choose to take the 'long route'  meaning selecting first a branch > clicking on the down pointed triangle > clicking on the button Choose a branch to merge into... > if 'up-to-date' a message on top of the disabled blue merge button is shown saying 'branch is up-to-date'

This information is NOT shown when using menu Branch > Update from Master or Ctlr+SHIFT +U.

### Proposed Feature
If would suggest, case using 'menu Branch > Update from Master or Ctlr+SHIFT +U' show  a corresponding message 'branch up-to-date' like the one 'branch merged with master' for a few seconds.

### Additional context
![Explanation](https://user-images.githubusercontent.com/9660415/74311502-ee1fee00-4d6f-11ea-8ee1-dca984ba020a.gif)

**Comment by niik** [comment]
Hi @kwhjvdkamp, thanks for opening this! I agree that it's confusing that we don't show any kind of notification when attempting to update from the default branch when already up to date.

It seems we used to show a banner albeit one that said that the merge was "successful". This was brought up as a confusing behavior in https://github.com/desktop/desktop/issues/6282 and was addressed in https://github.com/desktop/desktop/pull/6557 by removing the banner altogether.

I've been confused by the lack of notification myself and I think we should show a banner event when up to date although we should customize the message in the banner to say so.

While the current behavior is confusing it's not a blocking flow nor does it significantly impact users so I'm tentatively marking this as a priority-3 issue.

cc @billygriffin for visibility

**Comment by ruggi99** [comment]
Hi, I've encountered this problem too. When I'm working on a branch that it's not behind the default branch, "Branch" > "Update from (default branch)" is clickable and nothing happens. How about disable that entry from menu in this case? Eventually show a little warning (saying "Already up to date") when user hovers that entry?

**Comment by billygriffin** [comment]
I think what @niik suggested makes a lot of sense so we don't have to deal with maintaining state of whether menu items should be enabled or disabled (this has bitten us in the past). 

@ampinsk I'm curious how you feel about just showing the banner in this case, but with the message that it's already up to date?

**Comment by ampinsk** [comment]
That makes sense to me! I think a banner with a message "This branch is already up to date" is a good solution for this case. 👍
