### ISSUE TITLE
Add cherry-pick option

### ISSUE THREAD

**Issue by Alvin-Seville** [desktop/desktop#9098]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @Alvin-Seville, thanks for opening this. Cherry picking is something we think could be an interesting thing to approach in the future but not something we have planned to work on in the short term. I'm going to close this issue in favor of  https://github.com/desktop/desktop/issues/1685. Please subscribe to that issue and add your emoji reaction to the top to indicate your support of the feature and to get notified about any developments!
