### ISSUE TITLE
Highlight substring matches in the branches and repositories list when filtering

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#910]
Similar to how we do with emoji and issues:

![screen shot 2017-02-07 at 12 33 15 pm](https://cloud.githubusercontent.com/assets/13760/22703284/9c94a270-ed31-11e6-8dc2-0ddff4a26f13.png)

**Comment by redarsurgul** [comment]
may frend ples ples   facebook number an dono  hack

**Comment by mercybe** [comment]
how are you doing
