### ISSUE TITLE
Problems when push and fetch on the same remote point to different repositories

### ISSUE THREAD

**Issue by ogierm** [desktop/desktop#9100]
### Describe the bug

GitHub Desktop doesn't seem to be able to handle fetch and push pointing to different repositories.
![2020-02-13_12-37-16](https://user-images.githubusercontent.com/29630575/74430660-a11a4580-4e5d-11ea-91d2-19e845d8ecd2.gif)

### Version & OS

GitHub Desktop 2.3.1
Windows 10 Pro 1909

### Steps to reproduce the behavior

1. Open a shell
2. Use `git remote set-url origin` and point the origin to a different repository you don't own
3. Use `git remote set-url --push origin` and point the push repository to another one that you do own
4. `git remote -v` should now look like this 
![image](https://user-images.githubusercontent.com/29630575/74430946-36b5d500-4e5e-11ea-8b74-2b6c08bca7e8.png)

### Expected behavior

The hint for fetching should display the commits on the `origin fetch` remote branch since the last local commit, and the hint for pushing should display the amount of commits on the local branch that happened since the last commit on the `origin push` remote branch.

### Actual behavior

The button assumes that the `push`- and `fetch` repositories are the same. So it would for example suggest that I should push my changes when I have done commits that are on my local-, but not on my `fetch` repository, even though they are already on the `push` repository

### Additional context

I don't know if this is something that is usually done, but I'm using my remote repository in this case more to backup my local changes and not really to develop, connect or contribute. So most of the time I'm just merging from the repository where most of the development happens, build and then push that onto my own fork. Therefore I set the `origin fetch` remote to the original, upstream repository and the `origin push` to my own fork.

**Comment by billygriffin** [comment]
Hi @ogierm, thanks so much for the context to help us understand. Desktop is built with the assumption that the fetch and push remotes are the same, and that if someone is doing a workflow that you describe, they're largely doing it via a fork with a separate remote (usually `origin` for the fork vs `upstream` for the parent repo). We've improved the experience of working on a fork more generally in the past few months, and we plan to continue to do so, so hopefully even if it's not quite as convenient as what you're doing, that may work reasonably for you. The best current way to keep your fork up to date is to periodically merge upstream/master while in your fork. Hope that's helpful and sorry that this isn't something we're able to solve for your use case!

**Comment by ogierm** [comment]
I understand that you aren't interested in supporting this kind of setup as it's very much an edge case and rather uncommon.
However I think that this specific behaviour is still a bug. Maybe you can put it on a board with known issues or so?
