### ISSUE TITLE
Delete partner site content

### ISSUE THREAD

**Issue by v-cekenn** [desktop/desktop#9102]
### Describe the feature or problem you’d like to solve
The content in this path is no longer needed: GitHub\fasttrack-docs\partner-site\**ftop-partner-guide** 
A clear and concise description of what the feature or problem is.
Please delete the content in that path. Do not confuse this with Github\fasttrack-docs\partner-site\ftop-partner-**user**-guide
### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi, @v-cekenn, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
