### ISSUE TITLE
GitHUB repository in other after cloning

### ISSUE THREAD

**Issue by mWaltari** [desktop/desktop#9103]
### Describe the bug

Cloned repository easterday, with Clone/Open in desktop from github page, today it (still) was in Other section

### Version & OS

Version 2.3.1, latest WIn10

### Steps to reproduce the behavior

Clone to dekstop with GitHub Desktop app

### Expected behavior

Go in own place, not in Other

### Actual behavior

Appeared in Other section

A clear and concise description of what actually happened.

### Screenshots

![GitHUB repository in other](https://user-images.githubusercontent.com/4082975/74502504-7203e280-4ef6-11ea-8ebf-23c4dcb390e4.jpg)

Add screenshots to help explain your problem, if applicable.

**Comment by niik** [comment]
Hi @mWaltari, thanks for opening this. Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by mWaltari** [comment]
Logs from 4 last days

**Comment by niik** [comment]
Hi @mWaltari, I don't believe the log files made it over. I'm afraid we might not support attaching them to an email.

Nevertheless my colleagues tell me that this is likely related to https://github.com/desktop/desktop/issues/9040 and that there's a workaround that you can try. First, start by closing GitHub Desktop. Then locate the `%APPDATA%/Github Desktop/Cache` folder in Explorer and delete that folder.

Then restart GitHub Desktop again. As long as you just delete the Cache folder you shouldn't loose any settings or added repositories.

Give that a shot and let us know how it went.

**Comment by billygriffin** [comment]
One more quick question if you don't mind @mWaltari - it seems like it's just this one repo you're having this problem with, right? And if so, do you know if that repo was renamed at some point? We're trying to dig into what might be causing this so we can prevent it from happening again.

**Comment by mWaltari** [comment]
No renames, was hit by this last week or so, but didn't take screen shots
then.

Later repository was it's correct place.

-tee-

**Comment by tierninho** [comment]
@mWaltari Glad the repo ended up in the correct place. If you get a chance to upload the logs or if this happens again, please let us know.

Closing the issue for now as it is resolved.
