### ISSUE TITLE
Install process is not straight forward. 

### ISSUE THREAD

**Issue by GilHub1** [desktop/desktop#9105]
It leaves in a limbo stage wondering to do next. You clone the files and then you only have the option to open the windows folder or view it in GitHub. ….and then what? No install. You get some messages to go into the code to modify and attempt to get this installed. Well that is not very user friendly. Why not have your people install the software properly. Simple right.

**Comment by billygriffin** [comment]
Thanks for the issue @GilHub1. We try to make it as user friendly as possible and we regularly do usability tests with users to try to improve that, so without any specific feedback or recommendations, I'm going to close this issue. If you have thoughts on what specifically is falling down or how to improve it, feel free to respond with those.

**Comment by GilHub1** [comment]
You need at least a video tutorial to get through this install. This did not do me any good what so ever.




Gil R Quinones



Test Engineer



619-316-0949 Mobile   gilbert.quinones@cosocloud.com



 [id:image001.png@01D31CBB.591A6340]



________________________________

**Comment by billygriffin** [comment]
Feel free to reference our getting started guide: https://help.github.com/en/desktop/getting-started-with-github-desktop

**Comment by GilHub1** [comment]
This is more simplistic issue. I am just trying to figure out what launches the package to have it execute from GitHub.




Gil R Quinones



Test Engineer



619-316-0949 Mobile   gilbert.quinones@cosocloud.com



 [id:image001.png@01D31CBB.591A6340]



________________________________

**Comment by GilHub1** [comment]
I am a beginner at this. So simply how do you take the package let's say any package like node-red-dashboard and launch it from GitHub?




Gil R Quinones



Test Engineer



619-316-0949 Mobile   gilbert.quinones@cosocloud.com



 [id:image001.png@01D31CBB.591A6340]



________________________________
