### ISSUE TITLE
CyGWIN.DLL mismatch

### ISSUE THREAD

**Issue by deraeler** [desktop/desktop#9106]
### Describe the bug
Attempted Download of of GIT repository using GIT URL fails. Log errors included.
Others have reported this error in the forum and have gone completely unanswered.
Hoping someone will address why this latest version of Desktop fails.
This has happened on other repos also.

### Version & OS

2.31 (LATEST)
Windows 10 Pro

### Steps to reproduce the behavior
Ge here and attempt to download using URL.
https://github.com/idg10/prog-cs-8-examples

### Expected behavior
successful download

### Actual behavior
complete fail

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs
2020-02-14T16:35:08.095Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/idg10/prog-cs-8-examples.git - deraeler (has token)
2020-02-14T16:35:26.631Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/idg10/prog-cs-8-examples.git C:\dev\GitHub\prog-cs-8-examples (took 18.323s)
2020-02-14T16:35:26.637Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/idg10/prog-cs-8-examples.git C:\dev\GitHub\prog-cs-8-examples` exited with an unexpected code: 254.
stderr:
Cloning into 'C:\dev\GitHub\prog-cs-8-examples'...
remote: Enumerating objects: 736, done.        
.
.
.

      0 [main] sh (17540) C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1331408/0x11E1408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.

### Additional context

      0 [main] sh 774 dofork: child -1 - forked process 17540 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (19192) C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1331408/0x14C1408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1100904 [main] sh 774 dofork: child -1 - forked process 19192 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (3628) C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1331408/0x13C1408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3203989 [main] sh 774 dofork: child -1 - forked process 3628 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (10576) C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1331408/0x1261408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7313009 [main] sh 774 dofork: child -1 - forked process 10576 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (3312) C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1331408/0x1371408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15417471 [main] sh 774 dofork: child -1 - forked process 3312 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\steve\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

**Comment by deraeler** [comment]
I'm running the cygwin install from CYGWIN.COM, end even though I apparently would only need the cygwin.dll file, I selected just the "base" and "doc" component and its installing tons of sh_t on my computer.  I can't believe I have to go through this to get the LATEST VERSION of GITHUB DESKTOP to simply function.

**Comment by deraeler** [comment]
First.  I didn't close this.
Second.  OF COURSE I searched for other occurrences of cygwin.dll.
Issue remains. How has this gone unresolved for multiple users for so long?

**Comment by datapharmer** [comment]
Yep, seeing the same problem. Not sure why it was closed.

**Comment by akoni50** [comment]
Still facing this issue
