### ISSUE TITLE
Support fuzzy substring matching

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#911]
Similar to how Atom does file searching with cmd-T. We should do fuzzy substring matching in all the places we do filtering: branches, repositories, emoji, etc.

**Comment by cheshire137** [comment]
I support this! Would this allow me to type `githb` and match a repository named `github`? Or `gitp` and match a repository named `git-point`?

**Comment by joshaber** [comment]
Yup, that's definitely the goal! 🤘

**Comment by j-f1** [comment]
I took a look at this recently. How does [this demo](https://spangle-marble.glitch.me/) look? I’ve copied the branch list from desktop/desktop.

**Comment by iAmWillShepherd** [comment]
@j-f1, that looks good!

**Comment by iAmWillShepherd** [comment]
@j-f1 nvm, turns out the order does not matter. Are you willing to bring your work into our `filter-list` component?

**Comment by j-f1** [comment]
> Are you willing to bring your work into our filter-list component?

Sure, this afternoon-ish (~4-5+ hours).
