### ISSUE TITLE
Scroll bar nearly invisible in dark mode

### ISSUE THREAD

**Issue by vonas** [desktop/desktop#9114]
### Describe the feature or problem you’d like to solve

When I was browsing my changes I tried to scroll trough the diff view by dragging the scroll bar. Unfortunately it isn't very visible to the naked eye. I really had to look for it to find it. This problem occured when using dark mode.

### Proposed solution

Increase the brightness of the scroll bar or the background.
Maybe also increase the width of the scroll bar to fit the entire scrolling area. Currently it's slimmer than that and it resizes when hovering over it with the mouse. I think it's more visible when it's wider.

### Additional context

-

**Comment by vonas** [comment]
Ok, I've tested around a bit more and it seems different conditions give different impressions.

The file I was reviewing hat a lot of deletions (all red) which made it harder to see the scroll bar.
Also, I had a window right beside the application which was filled with white completely. Consequently my eyes adapted to let in less light which led to me being unable to make out the scroll bar.

Maybe it would make sense to **make the scroll bar white** (or near-white) and **keep it slim**.

Would need different opinions on that though.

**Comment by tierninho** [comment]
@vonas Thanks for filing. Any screenshots you can attach? Also, what operating system are you on?

Here it is in OSX, which is indeed hard to see.

![Screen Shot 2020-02-18 at 8 19 15 AM](https://user-images.githubusercontent.com/14828183/74765349-79ddc280-5227-11ea-8b07-1b627d97328e.png)

cc @desktop/design for thoughts

**Comment by vonas** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/24623262/74771945-66664200-528f-11ea-8e6b-ba9602a404e4.png)

The screenshot was taken on Windows 7.
