### ISSUE TITLE
GitHub does not work if installation path contains Chinese characters

### ISSUE THREAD

**Issue by loveunk** [desktop/desktop#9118]
### Describe the bug

GitHub cannot push if installation path contains Chinese characters

### Version & OS

GitHub Desktop 2.3.1
Windows 10 Pro (1909), English Version

### Steps to reproduce the behavior

1. clone a repo from GitHub
2. make some changes to a file, and commit
3. click the button "Push origin"
4. error dialog box pops

### Expected behavior

Push origin sucessfully

### Actual behavior

Error dialog box pops

### Screenshots

![Snipaste_2020-02-16_11-25-37](https://user-images.githubusercontent.com/1678567/74598699-074ad680-50b1-11ea-8b6a-6ca014a38280.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@loveunk Please see some of the workarounds listed [here](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) and let us know the results. 

In the meantime, please send us your logs if possible. See the Help menu in Desktop. Thank you.

**Comment by loveunk** [comment]
@tierninho thanks for your reply. But I cannot find `HKEY_CURRENT_USER\Software\Microsoft\Command Processor` in the registry.
Should I create it manually?

**Comment by tierninho** [comment]
@steveward Any thoughts on the above question would be appreciated. Thanks.

**Comment by steveward** [comment]
@loveunk the specific issue you are running into is being caused by the characters in your Windows user name. Unfortunately the only way to resolve this is to rename your local Windows user to not have special characters. You could try creating a new test Windows user account to confirm if that resolves this issue.
