### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Benya613** [desktop/desktop#9123]
### Describe the bug
I can't to sign in my GitHub account.When i try programme give me a message : "Unable to fetch authenticated user".

### Version & OS
Windows 10
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
Version 2.3.1

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@Benya613 Please include your logs so we have more insight to your issue. See the Help Menu in Desktop.

**Comment by Benya613** [comment]
Where do i can find logs?

**Comment by Benya613** [comment]
Sorry.I found...

ср, 19 февр. 2020 г. в 16:38, Кирилл Фереман <momster1008@gmail.com>:

**Comment by steveward** [comment]
@Benya613 it looks like you didn't upload the log files -- could you drop them into a reply? Thanks!

**Comment by tierninho** [comment]
@Benya613  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
