### ISSUE TITLE
Dropdown that is a really a button

### ISSUE THREAD

**Issue by spottedmahn** [desktop/desktop#9125]
### Describe the feature or problem you’d like to solve

Clicking this entry is the dropdown is a really a button but the UI doesn't tell me that.  It doesn't look like a button IMHO.

![image](https://user-images.githubusercontent.com/14079228/74678129-13559780-5188-11ea-9907-5d5af6b60f86.png)

### Proposed solution

Make the UI more self-documenting

**Comment by Rexogamer** [comment]
The drop down bit is the arrow; it’s a separate button.

**Comment by spottedmahn** [comment]
Oh, it's [button w/ a dropdown arrow](https://mdbootstrap.com/docs/jquery/components/dropdowns/#:~:text=split%20button), gotcha, thanks!
