### ISSUE TITLE
fatal: unable to access “…”: gnutls_handshake() failed: Handshake failed

### ISSUE THREAD

**Issue by HarishkumarBringiramakannu** [desktop/desktop#9130]
### Describe the bug

I've been using Git for the past few months. Recently when I try to clone or to push, I keep on getting this error. I've researched on the internet but so far no solution has worked for me. Does anyone have an idea?
External note : Now I moved to different country, it was working perfectly where I was before.

### Version & OS

Git Version : 2.11.0 , OS : Debian GNU/Linux 9.11 (stretch)

### Errors

git push
fatal: unable to access 'https://**************/': gnutls_handshake() failed: Handshake failed

**Comment by niik** [comment]
Hi @HarishkumarBringiramakannu, this is the repository for the GitHub Desktop graphical client. This issue appear to be related to the Git CLI so I’m going to close this issue but if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com) or, if the question is not GitHub specific, take a look at general Q/A sites such as https://serverfault.com or https://askubuntu.com.

Best of luck!
