### ISSUE TITLE
permission denied for the clone

### ISSUE THREAD

**Issue by Ruobing-max** [desktop/desktop#9131]
When I want to clone my repository to the desk, I can not do it. I copy the HTTPS to the desk, but the window shows the permission denied.
![2](https://user-images.githubusercontent.com/60984531/74763041-00f16180-524d-11ea-8ca8-101ec09bfe18.png)
![1](https://user-images.githubusercontent.com/60984531/74763042-00f16180-524d-11ea-8b1f-a1ea6d241e46.png)

**Comment by tierninho** [comment]
@Ruobing-max Please include your logs so we can have more insight into what is happening. Open the Help menu in Desktop to view logs for the relevant day.

**Comment by steveward** [comment]
@Ruobing-max it looks like you're trying to clone to `C:\Program Files` -- I'd recommend trying to clone to your User directory.

**Comment by tierninho** [comment]
@Ruobing-max  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
