### ISSUE TITLE
Can't push to github 

### ISSUE THREAD

**Issue by kostnerek** [desktop/desktop#9132]
Hi recently I have encountered this weird bug: 
![image](https://user-images.githubusercontent.com/56977301/74767524-4af73900-5287-11ea-974b-2874ac5441d7.png)
I've tried to reinstall it many times and it didn't do much
Here are logs:
2020-02-18T18:41:28.440Z - info: [main] Error report submitted
2020-02-18T18:43:17.053Z - info: [main] Error report submitted
2020-02-18T18:43:27.599Z - info: [main] Error report submitted
2020-02-18T18:44:01.445Z - info: [ui] Executing tutorial:push: git push -u origin master (took 1.288s)
2020-02-18T18:44:01.445Z - error: [ui] `git push -u origin master` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/kostnerek/desktop-tutorial.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-02-18T18:44:01.616Z - info: [main] Error report submitted

**Comment by outofambit** [comment]
hi @kostnerek sorry you're hitting this. is this is the first time you've installed github desktop on your computer? or did this happen after some use? it looks like you're hitting an authentication bug, so i would verify you are successfully signed in to github desktop. if you've been signed in before, you might need to sign out and re-sign back in.

let us know if you need more help!

**Comment by kostnerek** [comment]
I used github desktop for a quite a time but recently it stopped. I've tried resigning but it didn't do much.

**Comment by steveward** [comment]
@kostnerek can you check to see if your registry has been modified by another application? See this section in our known issues doc for how to do that:

https://github.com/desktop/desktop/blob/development/docs/known-issues.md#authentication-errors-due-to-modified-registry-entries

**Comment by kostnerek** [comment]
The way with clearing register worked to me thanks:)

**Comment by steveward** [comment]
@kostnerek I'm glad to hear that got things working!

**Comment by paulweldon** [comment]
On Feb 18, 2020 1:05 PM, evelyn masso <notifications@github.com> wrote:hi @kostnerek sorry you're hitting this. is this is the first time you've installed github desktop on your computer? or did this happen after some use? it looks like you're hitting an authentication bug, so i would verify you are successfully signed in to github desktop. if you've been signed in before, you might need to sign out and re-sign back in.
let us know if you need more help!
