### ISSUE TITLE
push commit for wiki page in github repo not working or freezes

### ISSUE THREAD

**Issue by Arconapalus** [desktop/desktop#9136]
### Describe the bug
I have a clone locally of wiki page setup with github desktop. When I edit the file and execute a 
push origin, GitHub desktop will freezes operation until I refresh Github in browser of the repo that I'm editing in. Perhaps this only happen with wiki page on GitHub. 

### Version & OS
Version 2.3.1 GitHub desktop 
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'wiki page of repo and click clone locally bottom right corner...'
2. Click on 'local clone and edit file'
3. Open GItHub desktop and commit change 
4. Click push origin (Freezes) 
5. refresh GitHub on web browser 
6. Click back on GitHub Desktop and push origin should change back to fetch origin 

### Expected behavior
As I push origin of commit (from GitHub Desktop) as other repo's, the process will push the origin and make changes to GitHub. 

### Actual behavior
When I push origin of commit (GitHub Desktop) to wiki page, should make changes and respond back to fetch origin status.  
A clear and concise description of what actually happened.

### Screenshots
<img width="536" alt="Screen Shot 2020-02-18 at 4 34 28 PM" src="https://user-images.githubusercontent.com/11588130/74784611-ea0f3700-526d-11ea-9e1b-9fa94f6ae84a.png">
<img width="563" alt="Screen Shot 2020-02-18 at 4 38 38 PM" src="https://user-images.githubusercontent.com/11588130/74784702-1f1b8980-526e-11ea-82a8-e2f7153be5e2.png">

Add screenshots to help explain your problem, if applicable.

### Logs
2020-02-18T21:21:33.182Z - warn: [ui] fetchRepository: 'ORG/repo.wiki' returned a 404
2020-02-18T21:21:33.182Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: repo-.wiki - username (has token)

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context
This is the only part of the repo that isn't working correctly. I have added all repo from clone repository through GitHub desktop. 
I read through this issue https://github.com/desktop/desktop/issues/7469
though, my process isn't stalling it just freezes up until I refresh GitHub. 
Once I toggle developer tools, I troubleshooting from the above example that was in another issue. 
Could this be because of 2FA enabled?

**Comment by billygriffin** [comment]
Hi @Arconapalus, thanks for the issue! I think this has to do with wikis not being properly supported in GitHub Desktop. This is something we have an issue for in https://github.com/desktop/desktop/issues/3839, so I'm going to close this. It's not likely something we'll prioritize anytime soon because cloning .wiki repos locally is a relatively uncommon use case compared to many other things we're planning to work on. Thanks again!
