### ISSUE TITLE
Github Desktop does not check for renamed files.

### ISSUE THREAD

**Issue by john-m-adams** [desktop/desktop#9146]
### Describe the feature or problem you’d like to solve

`git add` checks for renamed/moved files, but Github Desktop does not.

To reproduce current behavior:
Rename `old.txt` to `new.txt`.
Github Desktop shows two changes: delete `old.txt`, and new `new.txt`, rather than a rename operation.
use `git add -A` on the command line, and return to Github Desktop, and GitHub desktop shows the one staged rename operation.

### Proposed solution

Provide a mechanism to check two or more changes versus the same rename checks as `git add`.

UI could put the option in the right-click menu of change lines. Check All for the first line, or Check x Files for selections of one or more changes.

How will it benefit Desktop and its users?

Clean up commits without needing to keep git CMD open.

### Additional context

Same as issue #5959 which was closed for `more-info-needed`.

![github-desktop-check-for-renamed](https://user-images.githubusercontent.com/11334632/74970831-b30f6180-53e4-11ea-822d-edb7741284c8.jpg)

Thank you!

**Comment by billygriffin** [comment]
Hi @john-m-adams, I wasn't here when we last touched this, but I think this has to do with difficulties around detecting a rename reliably while the files are unstaged in the working directory. Your workaround does work, but if what you're after is cleaner commits, Desktop should handle it for you without having to use `git add -A`. During the staging and commit process, we should detect the rename and expose it in the commit history as such. See attached screenshot for that. I realize that can be confusing in the interim, but given that we made this call based on technical limitations and given that it does the proper thing for commit history, I think I'm going to close this. Please let me know if you think I missed anything!

**Comment by shravan2x** [comment]
@billygriffin I think an important use case for this feature is when a renamed file has been modified slightly. I recently found myself renaming .css files to .scss and changing a few lines to use variables. But now I can't see any useful diffs for these via GD. I found no option but to install GitKraken to process this commit.

Most other popular Git GUI tools like SourceTree and GitKraken support this feature. At the very least I think it would be useful to have a toggle in settings to support it.

**Comment by leowill01** [comment]
@shravan2x I'd this this ability too but I can live with GHD detecting and marking renames for the commit after the fact because I'm guessing it's not good practice to both change the file contents _and_ rename the file in the same commit. I could be wrong though as I'm not from a SE background.
