### ISSUE TITLE
Commit failed - code 128

### ISSUE THREAD

**Issue by kVikki** [desktop/desktop#9149]
### Describe the bug
Commit my changes with comment, then tried to push it, but suddenly PC rebooted. After OS loaded I could not do enything on GitHub Desktop any more

### Version & OS
GitHub Desktop V.2.3.1
Windows 10 Pro

### Steps to reproduce the behavior

1. On my current branch (not master), commit changes 
2. Click on "Push to origin"
3. PC reboot
4. Reload program
5. Strange things happened (picture 1 in attachment ). My branch is not showing, i changed only 12-14 files, not all of them (124). What is "HEAD"?
6. Tried to commit (picture  2)
7. Tried to create new branch (picture  3)
![1](https://user-images.githubusercontent.com/56153808/75009835-4c418500-5484-11ea-9ae2-6195663aa6a0.png)
6. Tried to commit (picture  2)
![2](https://user-images.githubusercontent.com/56153808/75009972-a80c0e00-5484-11ea-840c-29dc7773037f.png)
7. Tried to create new branch (picture  3)
![3](https://user-images.githubusercontent.com/56153808/75009990-b3f7d000-5484-11ea-911f-d58ab9bcaee0.png)

### Logs

[2020-02-20.desktop.production.log](https://github.com/desktop/desktop/files/4234606/2020-02-20.desktop.production.log)
[2020-02-21.desktop.production.log](https://github.com/desktop/desktop/files/4234608/2020-02-21.desktop.production.log)

### Additional context

what should I do now? if i Delete GitHub and install it again, would it fix the problem? I`m afraid to lose all my changes while deleting-installing-fatchig process

**Comment by kVikki** [comment]
- backup my project
- in project found hidden folder .git\refs\heads\ (on picture 2 I saw refs/heads/sidebar and decided to find it )
- deleted file "sidebar" (name of my broken branch)
- branch become active and I deleted it (only on desktop version)
- on GitHub (online) merged branches (master and sidebar`s last not corrupted version)
- fetched master branch to desktop
- created new branch, named "sidebar" on desktop
- copied changed files from backup to project folder
- commit changes
- push to origin
- it`s working!!!
Hope it would be helpful for someone

**Comment by steveward** [comment]
@kVikki I'm glad to hear you were able to get things working, and thanks for sharing those steps!
