### ISSUE TITLE
I cant able to clone the repo from my local repo through visual studio

### ISSUE THREAD

**Issue by vimalkumar-92** [desktop/desktop#9150]
I cant able to clone the repo from my local repo through visual studio. Its showing  **git failed with a fatal error. unable to access**

**Comment by steveward** [comment]
@vimalkumar-92 this issue tracker is for GitHub Desktop -- if you are having specific issues with cloning a GitHub repository in Visual Studio I would recommend contacting [GitHub support](https://support.github.com/).
