### ISSUE TITLE
Why GIT command line stopped working suddenly with “SSL Certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by soumali** [desktop/desktop#9151]
Hi,

I have basic idea about GIT. I was able to clone, add, pull, commit, push and run all commands successfully in my GIT windows client, through command line, which suddenly has stopped working. I am able to clone from eclipse, using personal access token, but cloning from command line(or any other command), gives above issue. I modified my github password recently. Also I checked that .gitconfig file has

            ` [http]
             sslCAInfo = <Folder_Name>\\curl-ca-bundle.crt`
and crt file is present in the location, and not modified recently, while I had cloned from command line until recently

my .ssh files (public and private) are also available, and not modified/corrupted

I have deleted my git entry from known_hosts file

`git config -l --show-origin` command output

`<git_repo>>git config -l --show-origin
file:<installation>/installations/etc/gitconfig     core.symlinks=false
file:<installation>/installations/etc/gitconfig     core.autocrlf=true
file:<installation>/installations/etc/gitconfig     core.fscache=true
file:<installation>/installations/etc/gitconfig     color.diff=auto
file:<installation>/installations/etc/gitconfig     color.status=auto
file:<installation>/installations/etc/gitconfig     color.branch=auto
file:<installation>/installations/etc/gitconfig     color.interactive=true
file:<installation>/installations/etc/gitconfig     help.format=html
file:<installation>/installations/etc/gitconfig     diff.astextplain.textconv=astextplain
file:<installation>/installations/etc/gitconfig     rebase.autosquash=true
file:<installation>/installations/etc/gitconfig     filter.lfs.clean=git-lfs clean -- %f
file:<installation>/installations/etc/gitconfig     filter.lfs.smudge=git-lfs smudge -- %f
file:<installation>/installations/etc/gitconfig     filter.lfs.process=git-lfs filter-process
file:<installation>/installations/etc/gitconfig     filter.lfs.required=true
file:<installation>/installations/etc/gitconfig     credential.helper=!"<installation>/mingw64/libexec/git-core/git-credential-store.exe"
file:<user_dir>/.gitconfig        http.sslcainfo=<cacerts_location>\curl-ca-bundle.crt
file:<user_dir>/.gitconfig        user.name=aa bb
file:<user_dir>/.gitconfig        user.email=a.b@x.com
file:<user_dir>/.gitconfig        credential.helperselector.selected=store`

`<git_repo>>git clone https://git.x.com/y/j2ee_abcd.git
Cloning into 'abcd'...
fatal: unable to access 'https://git.x.com/y/j2ee_abcd.git': SSL certificate problem: unable to get local issuer certificate`

**Comment by steveward** [comment]
@soumali thanks for the report. It looks like you are using a custom Git server -- is it a GitHub Enterprise server? Have you added the server's certificate to your local certificate store or to Git's certificate store with a custom certificate bundle?

**Comment by tierninho** [comment]
@soumali  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
