### ISSUE TITLE
Automatic push to origin

### ISSUE THREAD

**Issue by sportshead** [desktop/desktop#9157]
### Describe the feature or problem you’d like to solve

Currently when committing changes users have to manually push to origin.
### Proposed solution

There should be a setting to automatically push to origin once a local commit is made

### Additional context

![Screenshot 2020-02-22 at 2 46 19 PM](https://user-images.githubusercontent.com/32637656/75088001-27cbd280-5582-11ea-9886-e8908760916a.png)

**Comment by steveward** [comment]
Thanks for the feedback @sportshead. This feature was requested in #2191, and please see [@billygriffin's comment](https://github.com/desktop/desktop/issues/2191#issuecomment-431093456) for why this request is not currently on our roadmap. Please feel free to add feedback about your specific use for this feature in that issue.
