### ISSUE TITLE
How to reset some branch to the particular state in the same way how Visual Studio allows?

### ISSUE THREAD

**Issue by Alvin-Seville** [desktop/desktop#9162]
### Describe the feature or problem you’d like to solve

How to reset some branch to the particular state in the same way how `Visual Studio` allows?

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by AndreiMaga** [comment]
It's called rebase you have an option in ```History - > Right Click - >Revert... ```, you should check stackoverflow first before creating an issue.

**Comment by billygriffin** [comment]
Hi @Alvin-Seville, we need more information to be able to understand this request. Can you walk through what problem you're trying to solve and how Visual Studio solves it, preferably with reproduction steps and screenshots so we can dig into it more? Thanks!

**Comment by tierninho** [comment]
@Alvin-Seville  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
