### ISSUE TITLE
Please add default simple built-in text editor like notepad in Windows

### ISSUE THREAD

**Issue by Alvin-Seville** [desktop/desktop#9163]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
Thanks @Alvin-Seville, this isn't something we intend to do in the near future as we think editors do their jobs really well, and Desktop is about your interaction with your repo and efficiently sharing your work. Our goal is to integrate nicely with editors but not to compete with them. Thanks for the idea.
