### ISSUE TITLE
Please add an ability to create branches from specified commits

### ISSUE THREAD

**Issue by Alvin-Seville** [desktop/desktop#9164]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
Thanks @Alvin-Seville, we ask that you fill out the template to give us more information about your problem to help us understand it better and determine if it's something we should tackle.

**Comment by tierninho** [comment]
@Alvin-Seville  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
