### ISSUE TITLE
Add conflict resolution dialog for conflicts resolving

### ISSUE THREAD

**Issue by Alvin-Seville** [desktop/desktop#9165]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by fred652** [comment]
I want earn maney

**Comment by tierninho** [comment]
@Alvin-Seville Thank you for the suggestion. At this time we are focused on other features in our product roadmap. Should we receive more feedback from other users requesting this dialog, we will be happy to take another look at your suggestion.

**Comment by billygriffin** [comment]
Just wanted to note that there is a dialog for conflict resolution @Alvin-Seville. We need you to be more specific in your issues. Please don't continue to open further issues without filling out the template. Thank you.
