### ISSUE TITLE
Copia de la URL del repositorio remoto al directorio local

### ISSUE THREAD

**Issue by Losneil** [desktop/desktop#9173]
### Describe the bug

Un error relacionado con el proxy

### Version & OS

2.3.1

### Actual behavior

A clear and concise description of what actually happened.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@Losneil Gracias por la información. El servidor proxy configurado debe configurarse como parte de la configuración global de Git. Consulte https://stackoverflow.com/a/19213999/1363815 para ver un tutorial sobre cómo configurar esto.

Complete la plantilla anterior e incluya sus registros (consulte el menú Help en Desktop) si necesita más ayuda.

**Comment by tierninho** [comment]
@Losneil  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
