### ISSUE TITLE
Changing local branch does not update submodules

### ISSUE THREAD

**Issue by RichardTea** [desktop/desktop#9174]
### Describe the bug

Changing between branches that call out a different version of the submodule does not update the submodules.
This results in submodule version commits being created that change the submodule version apparently 'at random', depending on which branch a user was previously on.

### Version & OS

2.3.1, Windows

### Steps to reproduce the behavior

In a repository that has submodules, update a submodule in Branch A.
Now switch to Branch B
Note that github desktop has staged a change to Branch B to also use the Branch A submodule.

### Expected behavior

Submodules should be updated to match the current branch.
Submodule specification in a branch should not change unless explicitly done.

### Actual behavior

Submodules are NOT updated.
Submodules specifications are changed without the user intending to do so.

**Comment by steveward** [comment]
@RichardTea apologies for not getting back to you. I'm going to add this to our tracking thread for submodule issues.

**Comment by steveward** [comment]
Reported again in https://github.com/desktop/desktop/issues/13016.

**Comment by sergiou87** [comment]
@RichardTea not sure if this is still interesting to you, but I was taking a look at this issue, and it seems the app already updates submodules on checkout, fetch and pull, but only in [beta builds of the app](https://github.com/desktop/desktop/blob/25b66588c96606a1e39de3a38c2c2289328385e0/app/src/lib/feature-flag.ts#L31-L34).

You can download beta builds from https://desktop.github.com/beta and see if that works for you 😄  I'll discuss with the team if this is something we can promote to production builds, but I'd love to get your feedback first.

**Comment by RichardTea** [comment]
@sergiou87 I gave up on Github Desktop years ago, and have no interest in trying it again.
It's been over two years, I've long since found several git clients that handle submodules in a consistent and useful way.

**Comment by sergiou87** [comment]
I'm sorry to hear that, but thank you for your feedback, I really appreciate it 🙇‍♂️ 

Could you share which git clients work well with submodules in your experience? I'd love to learn from them to improve GitHub Desktop. Thank you!

**Comment by Erraach-walid** [comment]
*****
