### ISSUE TITLE
I can’t “Open in Atom” from GitHub under Repository menu in GitHub Desktop

### ISSUE THREAD

**Issue by XPMai** [desktop/desktop#9176]
### Describe the feature or problem you’d like to solve

I do not have an issue with Atom or launching Atom from Windows, but I have an issue with launching Atom from Github so that I can get the tabs of files at the left. It has never been an issue in the past and I have not taken any action recently that could result in this issue. I have done limited troubleshooting steps because most suggested are not relevant to me, namely opening in safe mode.

I tried one of the debugging step to reset Atom to default with CMD, and the command was successful but I still cannot launch Discord from GitHub.
### Proposed solution

Please advise me what to do or how to troubleshoot this. I don't feel like simply reinstalling it because it could very possibly happen again

### Additional context

There is no errors at all unlike [this](https://github.com/desktop/desktop/issues/9155). I was referred here by [Atom](https://discuss.atom.io/t/i-cant-open-in-atom-from-github-under-repository-menu-in-github-desktop/72204)

Thank you.

**Comment by steveward** [comment]
@XPMai thanks for the report. Just to make sure I understand the issue -- is Atom appearing correctly in your editor list under `File` > `Options` > `Integrations`?

>I tried one of the debugging step to reset Atom to default with CMD, and the command was successful but I still cannot launch Discord from GitHub.

Were these the steps you tried from CMD?

`cd %LOCALAPPDATA%\Atom\`
`atom --squirrel-updated`

**Comment by XPMai** [comment]
> `cd %LOCALAPPDATA%\Atom\`
> `atom --squirrel-updated`

Omg, it works now. Thank you!

Can I know, what is that?

**Comment by Neustradamus** [comment]
@XPMai: What is your Windows version?

**Comment by XPMai** [comment]
@Neustradamus Windows 10 Pro

**Comment by Neustradamus** [comment]
@XPMai: This problem is really on several Windows OS versions...
I do not understand why there is always not the solution (not the temporary solution).
