### ISSUE TITLE
C:\User\>git lfs install 'git' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by cemgoker** [desktop/desktop#9177]
### Describe the feature or problem you’d like to solve

C:\Users\otomat>git lfs install
'git' is not recognized as an internal or external command,
operable program or batch file.

it doesn't work what can I do

**Comment by steveward** [comment]
@cemgoker GitHub Desktop does not install Git on your machine, but you can download it here:

https://git-scm.com/download/win

This will also install Git LFS during the installation process.
