### ISSUE TITLE
Custom paths for external editor and shell

### ISSUE THREAD

**Issue by The-SamminAter** [desktop/desktop#9180]
### Describe the feature or problem you’d like to solve

If an external editor is located on a network drive or thumb drive, then there is no way to integrate it into GitHubDesktop. Same with a shell.

### Proposed solution

I propose that another option be added to the external editor and shell selection. This option will allow the user to provide a custom path to the external editor and shell of their choice.

**Comment by billygriffin** [comment]
Hi @The-SamminAter, I think this is the same as https://github.com/desktop/desktop/issues/5083, so I'm going to roll it into that. Thanks!
