### ISSUE TITLE
Support remote repos/folders

### ISSUE THREAD

**Issue by gugavaro** [desktop/desktop#9181]
VSCode supports remote development, where you can have your repo remotely. A lot of developers are now having their repos in remote machines and using VSCode to connect to it via ssh.
Unfortunately It is not possible to use Github Desktop to point to a folder/repo in a different machine.
Would be nice to have some support of Github desktop for developers using the remote development of VSCode.

**Comment by steveward** [comment]
@gugavaro thanks for contributing! VSCode [suggests](https://code.visualstudio.com/docs/remote/troubleshooting#_using-rsync-to-maintain-a-local-copy-of-your-source-code) using `rsync` to allow you to maintain a local copy of your source code. I'd recommend taking a look through those docs to get this working. This isn't something that we have plans to directly support in GitHub Desktop, so I am going to close this issue out.

**Comment by gugavaro** [comment]
Thank you, @steveward, I don't think rsync solves the scenario I tried to describe. rsync is not a good option for users who are using remote development. Thats exactly what I am trying to avoid to have the source code on my machine. With VSCode remote tools you don't need to use rsync to remote development.
In fact the documentation says:
- The Remote - SSH extension does not provide direct support for sync'ing source code or using local tools with content on a remote host.

VSCode remote allows you to do everything you need, dev, debug, test, etc without having any code locally.
When you have some free time :) try the remote development feature of VSCode and you will understand better how useful this feature could potentially be to Github Desktop.

thanks again!

**Comment by steveward** [comment]
@gugavaro I understand that the feature itself does not require `rysnc`, but they do explicitly state that local tools (like GitHub Desktop) won't work directly. This is why I suggested using `rsync` as a workaround. I have used the feature and agree it is useful, but just not something that we would be able to support in GitHub Desktop at this time.
