### ISSUE TITLE
Mistake: terminal prompts disabled

### ISSUE THREAD

**Issue by klavdiy** [desktop/desktop#9182]
Hello!
When trying to download my private repository through Github Desktop, an error occurs:

```Cloning into 'C:\Users\Клавдий\Documents\GitHub\xxx'... error: cannot spawn C:\Users\xxxxx\AppData\Local\GitHubDesktop\app-2.3.1\resources\app\static\ask-pass-trampoline.bat: No error fatal: could not read Username for 'https://github.com': terminal prompts disabled```

How to solve the error?
Windows 10 64-bit

**Comment by tierninho** [comment]
@klavdiy Thank you for filing this. Please see our list of known issue here which address your problem

https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789

Let us know how it goes.
