### ISSUE TITLE
GitHub Desktop terminal prompts disabled issue

### ISSUE THREAD

**Issue by dudiakash** [desktop/desktop#9184]
### Describe the bug

When I am trying to pull or push the latest code from/to aws code commit repo I am getting error like fatal could not read the username and at the same time terminal prompts disabled
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to GithubDesktop
2. Click on Pull origin

### Expected behavior

I should ask for username and password
### Actual behavior
It is not asking and giving above mentioned error
A clear and concise description of what actually happened.

### Screenshots
![image](https://user-images.githubusercontent.com/23179393/75421749-f9267100-5960-11ea-9ce9-580bc749373c.png)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@dudiakash thanks for the report. Please see this section of our known issues document for debugging this:

https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789

The `Autorun` registry entry issue has been the more common cause that we have seen recently, so I would recommend checking that first.

**Comment by steveward** [comment]
@dudiakash I'm going to close this issue out -- let us know if you have an problems resolving this error.
