### ISSUE TITLE
urls within commits get cut off and cannot get opened by the browser

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#9185]
### Describe the bug

lookup a commits within the history of a project which contains a url.
the url - when displayed cut off - because of its length does not open properly in the browser

### Version & OS

Windows10x64
GHD Version 2.3.1

### Steps to reproduce the behavior

1. clone https://github.com/phpstan/phpstan-src
2. open the history
3. select the commit 7d2ecf9a1f911f4bc3d64373119097e927084221
4. click the url contained in the commit

![image](https://user-images.githubusercontent.com/120441/75432035-130a8880-594e-11ea-8020-aeb315fc61b5.png)

### Expected behavior

the url opens in the browser

### Actual behavior

the browser does not open the actual url from the commit `https://github.com/phpstan/phpstan/issues/3008` but it seem to open the cut-off version of it `https://github.com/phpstan/phpstan/i%E2%80%A6` -> which leads to a 404 http error page on github.com

opening the same url from within github.com works like expected, see https://github.com/phpstan/phpstan-src/commit/7d2ecf9a1f911f4bc3d64373119097e927084221

**Comment by steveward** [comment]
Thanks for the detailed report @staabm! I'm going to label this as a bug.

**Comment by halitogunc** [comment]
Mind if I fix that one ? I have one solution in my mind without breaking truncated summary. The thing is if I choose that way, I have to add an extra optional prop to `<RichText />` component, and also a new parameter for scanForHyperlink function. What do you think ?

**Comment by steveward** [comment]
@halitogunc that'd be great. Pinging @desktop/engineering for thoughts on your question.
