### ISSUE TITLE
Error "Counting objects..." "Enumerating objects..." with no details or explanation

### ISSUE THREAD

**Issue by pha3z** [desktop/desktop#9187]
Windows 10
GitHub Desktop v 2.3.1

The repository holds a .Net Core 3.0 C# Solution.

### Steps to reproduce the behavior

I click Push origin on my development branch.  I'm not aware of having done anything different from what I've done a thousand times before.

### Expected behavior

I expected a normal push to occur. Instead, the error window in the screenshot appears. Clicking Close on the Error window returns me to the prior state -- with the app still showing ^ Push origin.

Screenshot
![image](https://user-images.githubusercontent.com/2966966/75460355-f9b20e00-5946-11ea-96eb-e2704f86893d.png)

### Log File

[redacted_names_2020-02-27.desktop.production.log](https://github.com/desktop/desktop/files/4262524/redacted_names_2020-02-27.desktop.production.log)

**Comment by pha3z** [comment]
UPDATE:
I restarted the app and it fixed the problem. I guess I should have tried that first, but this error window still seems like it could use some improvement if possible to find out what the cause was.

**Comment by outofambit** [comment]
hi @pha3z thanks for reporting this. from looking at the logs, it appears the server receiving the push had an internal error.

```console
remote: Internal Server Error
```

i'm not sure there's much we can do about that server error itself, but for the dialog we have already merged a fix from https://github.com/desktop/desktop/pull/8964 that will go out in the next release! I think this would make it much easier to see the error.

I'm going to close this issue @pha3z but please let us know if you have any questions. Thanks!
