### ISSUE TITLE
Unable to run installer

### ISSUE THREAD

**Issue by Mehzi** [desktop/desktop#9190]
### Describe the bug

Everytime I run the installer it shows two windows.

A: Update   msg is "update has stopped working"

B: GitHubDesktopSetup.exe - msg is " There was an error while installing the application. Check the setup log for more information and contact the author."

### Version & OS

Github version 2.3.1
OS is Win 7 ultimate 64 bit

### Steps to reproduce the behavior

1. Open installer

### Expected behavior

Installation

### Actual behavior

Two windows pop up

A: Update   msg is "update has stopped working"

B: GitHubDesktopSetup.exe - msg is " There was an error while installing the application. Check the setup log for more information and contact the author."

### Screenshots

None needed

### Logs

[SquirrelSetup.log](https://github.com/desktop/desktop/files/4263833/SquirrelSetup.log)

**Comment by vonas** [comment]
Are you sure these are the right logs? The latest timestamps are from end of 2019 and the content doesn't seem like it's about GitHub Desktop at all – I especially like this one:

```
2019-12-13 12:56:36> Program: Install path C:\Users\Administrator\AppData\Local\
Kartridge already exists, burning it to the ground
```

**Comment by tierninho** [comment]
@Mehzi Could you try performing a fresh installation of GitHub Desktop by following these steps?

1. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
2. Go to `%AppData%` and delete the `GitHub Desktop` directory
3. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that doesn't get things working.

**Comment by Mehzi** [comment]
> Are you sure these are the right logs? The latest timestamps are from end of 2019 and the content doesn't seem like it's about GitHub Desktop at all – I especially like this one:
> 
> ```
> 2019-12-13 12:56:36> Program: Install path C:\Users\Administrator\AppData\Local\
> Kartridge already exists, burning it to the ground
> ```

I was very confused by that too but that's the suggested log that my computer popped up

**Comment by Mehzi** [comment]
Okay deleting the folders didn't work but I deleted them again and installed the .msi file three times and then redownloaded a new version of the .exe ran it and it gave the update error but the application opened so I'm gonna call that a win.

**Comment by romadebrian** [comment]
I deleted the directory
\ AppData \ Local \ GitHubDesktop
and
\ AppData \ Roaming \ GitHubDesktop

i still can't install github desktop

**Comment by romadebrian** [comment]
i also have the same problem
but when I try to disable GPU, Github desktop can run

CMD = "C:\Users\roma\AppData\Local\GitHubDesktop\GitHubDesktop.exe --disable-gpu"

but I still can't install it
