### ISSUE TITLE
Main window shade needed

### ISSUE THREAD

**Issue by mSnus** [desktop/desktop#9196]
### Main window blends into other windows on Windows 

The main window has no borders and thus blend into underlying windows (Chrome, VSCode). 
That is visually very frustrating.

### Proposed solution

We should have an option in Appearance section to enable the standard shadow or at least border around the window.

### Additional context

Windows 8.1 (6.3, 9600), other programs has their shadows and borders as enabled system-wide.
![github](https://user-images.githubusercontent.com/12830884/75499200-5f9ba580-59da-11ea-9f8e-b64007c5ea56.png)

**Comment by tierninho** [comment]
@mSnus we've been doing some recent discussing and investigating internally around this. While we'd like to remedy this with a small border, it's too much technical effort to solve this reliably, especially when considered against other work we are doing. Unfortunately the Electron API doesn't really offer us an easy way to do this and our own app's CSS is built in such a way that this isn't as straightforward as it might seem at first glance. Apologies and thanks for reaching out.
