### ISSUE TITLE
Managing gists with the GitHub Desktop app

### ISSUE THREAD

**Issue by seamusdemora** [desktop/desktop#9200]
##### A clear and concise description of what the feature or problem is:

I have a collection of gists on https://gist.github.com/seamusdemora. I created all of these gists some time ago using the online editor through a browser. I would now like to collect all of these gists, and save them to a local folder on my Mac - just as I do for my other content/repos on GitHub.

However, there seems to be no *clean* way to do this. I cannot find a way to clone **all** of my gists at once to a single folder. When I try to clone a single gist, Desktop App insists on having a new/empty directory for each gist! It's as if GitHub's declaration that *"each gist is a repo"* has suspended common sense from the process of managing them.

Surely, there must be a way to house multiple gists in a single folder, and manage them from the Desktop App just as we do other multi-file repositories? 

##### How will it benefit Desktop and its users? : 

IMHO, treating multiple gists (which are typically single files) as a single repository would make things intuitive and consistent with how other repos are treated. Managing under the present scheme, which would seem to require creating 100 repos to house 100 gists is confusing and inconsistent. GitHub's site collects all of a user's gists under a single hierarchy in a fashion very similar to the way that a REPO is displayed. Creating 100 repos for 100 individual gists makes navigation & location in Desktop App awkward and time consuming. 

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

OTOH, it's entirely possible I've *missed the boat*, and GitHub already allows this?! If that's the case, please point me to some **clear** instructions; I've found nothing like that in my searches.

**Comment by billygriffin** [comment]
Hi @seamusdemora, thanks for the issue and the really clear description. While we know there are some folks who like to manage many Gists locally, we haven't seen this as a common enough pattern to prioritize a first class experience in Desktop. There are also lots of other goofy things about Gists that require a significant level of effort to make them work seamlessly in the app. We have #2973 to track that work but isn't something we've chosen to prioritize yet. I'm going to roll this issue into that one to help keep everything consistent. The `future proposal` label indicates that it's still under consideration as something we may want to work on in the future but isn't something we're planning to take on in the next several months at least. Thanks again!

**Comment by seamusdemora** [comment]
Thanks for the feedback @billygriffin. There are some 3rd party apps that I turned up when researching this the other day, so I'll look further into those. One that sounds promising is [`gisto`](https://www.gistoapp.com/)... I've not tried any of these, but any recommendations would be much appreciated; or pointers to someone else's recommendations if you can't be perceived as *endorsing* 3rd party apps :P
