### ISSUE TITLE
Repository needs user-defined grouping function

### ISSUE THREAD

**Issue by 617qqq** [desktop/desktop#9201]
Repository needs user-defined grouping function

**Comment by billygriffin** [comment]
Hi @617qqq, we use issue templates to ensure we get issues that are clearly defined and describe the problem people are facing - we're a small team and we get a lot of issues so it's important to make sure we have sufficient information to give proper consideration to any particular feature request or bug report. If you'd like to fill out a new issue with a template, please do so. Thanks.
