### ISSUE TITLE
Incorrect behaviour on "Merge" action

### ISSUE THREAD

**Issue by LiDReSaR** [desktop/desktop#9205]
### Describe the feature or problem you’d like to solve

When "Merge" action was started and I moved selector to the needed branch, pressing on Enter button doesn't work.

### Proposed solution

Pressing on Enter button should be handled as submit (like mouse left-click).

**Comment by billygriffin** [comment]
Hi @LiDReSaR, would you mind sharing screenshots and reproduction steps for us please? It would also be helpful to know what version of GitHub Desktop you're using and what OS version. Dialogs are very platform-dependent, so we'll need more of that information before we're able to look into this further. Thanks!

**Comment by LiDReSaR** [comment]
Hi @billygriffin.
- OS: Win 10 x64.
- GitHub Desktop Version: 2.3.1.

### Reproduction steps
Open some repository (Ctrl+O) -> Merge (Ctrl+Shift+M) -> Move Selector to some branch (Up or Down) -> Press "Enter" button -> Nothing happens (but if I click on "Merge ... into ..." button all works fine).

![image](https://user-images.githubusercontent.com/18169703/75714179-48133400-5cdc-11ea-90c0-b75cf275f3e2.png)

In the screenshot, the branch has already been merged, so it is not active. I mean the case when the branch has not yet been merged.

Thanks!

**Comment by billygriffin** [comment]
@LiDReSaR Thank you! I expected the behavior to be that if you wanted to select the particular item, you'd use the arrows to find the right branch, tab to the button and hit `Enter` to merge. I'm inclined to leave that behavior as is as we've seen things like this fall down when people accidentally hit a key, so for something like a merge, I think I think (see what I did there?) a tiny bit more friction is acceptable. Thoughts?

**Comment by LiDReSaR** [comment]
@billygriffin Thank you for the clarification! Just pressing Enter, of course, is more convenient, but Tab + Enter is also not difficult.
