### ISSUE TITLE
Suggestion - Add GitHub's Repository Description to be visible while looking for a repository to clone

### ISSUE THREAD

**Issue by J-Likness** [desktop/desktop#9208]
In the GitHub Desktop App, it would be super helpful if the Repositories Description was visible and searchable when you try to clone a repository.

How will it benefit Desktop and its users?
- Helps find the repository needing to be cloned and displays more details about it.

**Comment by steveward** [comment]
Thanks for the feedback @J-Likness. I'm going to group this feedback into #8687 since it aligns with providing information about a repository prior to cloning.
