### ISSUE TITLE
The program freezes on repository remove if the directory is already removed from file system

### ISSUE THREAD

**Issue by nemanjabodroza** [desktop/desktop#9209]
### Describe the bug

The program freezes on repository remove if the directory is already removed from file system.

### Version & OS
2.3.1
### Steps to reproduce the behavior

1. Delete repository in file system
2. Remove repository in Git
3. The app freezes

**Comment by steveward** [comment]
Thanks for the report @nemanjabodroza. What operating system are you running GitHub Desktop on? 

It would also be helpful if you could upload the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by nemanjabodroza** [comment]
I am using Win10 Pro ver. 1903.

[2020-03-03.desktop.production.log](https://github.com/desktop/desktop/files/4285302/2020-03-03.desktop.production.log)

**Comment by tierninho** [comment]
Looks like the log errors are:

```
2020-03-03T07:56:43.827Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/codis-tech/TyrollCx.git/': Could not resolve host: github.com
```

If you are behind a proxy that requires credentials there are some steps you can take to configure it:

1. Go to the file menu and select `Repository` > `Open in Terminal` (macOS) or `Open in <default_command_line_application>` (Windows)
2. Run the following command:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if that doesn't get things working for you!

**Comment by tierninho** [comment]
@nemanjabodroza  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
