### ISSUE TITLE
Trying to fetch master branch origin but github desktop saying connection refused

### ISSUE THREAD

**Issue by Tiago-Altus** [desktop/desktop#9211]
As i try to fetch master branch of a private repository I have been using for the past 6 months I get an error: fatal: unable to access 'https://github.com/etc': Failed to connect to 127.0.0.1 port 8087: connection refused 

Already tried some of the solutions on stackoverflow to no avail.

**Comment by steveward** [comment]
@Tiago-Altus thanks for the report. Are you behind a proxy server or firewall that could be interfering with your connection? Based on some quick research it looks like port 8087 is used for media streaming -- are you running anything like that on your machine?

**Comment by Tiago-Altus** [comment]
Hello @steveward , I must be behind some kind of firewall or proxy server... not too sure as this is my companies computer. I do not think I'm running media streaming of any sort.

**Comment by Tiago-Altus** [comment]
Company enforced new proxy. Had to change npm config proxy/https-proxy and git http/https proxy

**Comment by Ming-Yuan** [comment]
Check your terminal proxy 'env|grep -i proxy'
