### ISSUE TITLE
Expandable Commit Description

### ISSUE THREAD

**Issue by Sherbb** [desktop/desktop#9212]
### Make the description box expandable
![image](https://user-images.githubusercontent.com/13370191/75844971-b53ecc00-5da5-11ea-8de1-3edbdd8a2ca4.png)

When you are writing a long detailed description for a commit the tiny box makes it very hard to read what you are writing. This was reported as an issue before over two years ago and has since been marked closed with no changes.

### Proposed solution
![image](https://user-images.githubusercontent.com/13370191/75844990-c091f780-5da5-11ea-8e33-8ac839f8a617.png)

We can already scale the section of the window horizontally which helps a little, but need to be able to scale the description part vertically.
![image](https://user-images.githubusercontent.com/13370191/75845053-e7502e00-5da5-11ea-943c-89d63e433850.png)

Alternatively, you could have a _detail_ mode that goes full screen and gives you all the editing options you have in browser.

**Comment by Sherbb** [comment]
you can change the size of the field manually,
![image](https://user-images.githubusercontent.com/13370191/75845434-1915c480-5da7-11ea-87e8-a46ff367edf4.png)

**Comment by steveward** [comment]
Thanks for the feedback @Sherbb. I'm going to group this into #1646 where we are tracking improvements to the commit writing experience.
