### ISSUE TITLE
Commit failed

### ISSUE THREAD

**Issue by tlabsim** [desktop/desktop#9214]
### Describe the bug

I am trying to publish some codes in a repository. The files are in this folder:
tools\TLABS.OCR\TLABS.OCR.CHBCR.DatasetCreator

But the Github Desktop is showing the folder as 
tools\TLABS.OCR\TTLABS.OCR.CHBCR.DatasetCreator
Notice the extra T

Also I can't commit any changes in that folder

### Version & OS

Windows 10 version 1909 (18363.657)

### Screenshots

![s1](https://user-images.githubusercontent.com/2876793/75857964-2191ed80-5def-11ea-9f37-2365e5bdd3fb.png)

![s2](https://user-images.githubusercontent.com/2876793/75858393-05428080-5df0-11ea-94b9-4017d5f5e698.png)

![s3](https://user-images.githubusercontent.com/2876793/75857972-25257480-5def-11ea-9f69-3b2c1bf55c1d.png)

### Logs
[2020-03-04.desktop.production.log](https://github.com/desktop/desktop/files/4286075/2020-03-04.desktop.production.log)

**Comment by steveward** [comment]
@tlabsim thanks for the report. Was this file renamed? Could you open the repository in the command line (`Repository` > `Open in <command_line_application>`) and run the following command?

`git ls-files --stage | grep -i tools\TLABS.OCR\TTLABS.OCR.CHBCR.DatasetCreator`

Let me know what that shows.

**Comment by tlabsim** [comment]
Hello, Thanks for replying.I have solved the problem. Actually there was a repository already created in the folder    TLABS.OCR.CHBCR.DatasetCreatorI have moved that inside my new repository. That’s why it was showing like this. Now after deleting previous .git folder, it is working properly.Thanks again. From: Steve WardSent: Wednesday, March 4, 2020 2:42 PMTo: desktop/desktopCc: Iftekhar Mahmud Towhid; MentionSubject: Re: [desktop/desktop] Commit failed (#9214) @tlabsim thanks for the report. Was this file renamed? Could you open the repository in the command line (Repository > Open in <command_line_application>) and run the following command?git ls-files --stage | grep -i tools\TLABS.OCR\TTLABS.OCR.CHBCR.DatasetCreatorLet me know what that shows.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by steveward** [comment]
@tlabsim thanks for the update! I'm glad to hear things are working. Nested git repositories are a known cause of this error.
