### ISSUE TITLE
Set commit e-mail by repository

### ISSUE THREAD

**Issue by bergamin** [desktop/desktop#9218]
### Describe the feature or problem you’d like to solve

When working on multiple repositories, both at work and personal projects, one doesn't want to commit on work repo using personal e-mail and vice/versa.

### Proposed solution

Add the commit e-mail to the repository settings.

### Additional context

I'm trying a few graphic Git clients for helping my colleagues in a migration from SVN and it was a bit confusing when I found out that my commits are using my personal e-mail.

My work repository is not on GitHub

How to reproduce:

* Have the repo already cloned using my work account
* Installed GitHub Desktop and set my personal GitHub account in it (just like I would have done with Sourcetree and a Bitbucket account) thinking it would ask me per repo what I wanted to use.
* Open the already cloned repo
* Fetch. It will ask for authentication. I use my work account and it works as expected
* Commit / Push. It doesn't ask for authentication, but used my personal e-mail instead of the one used for authenticating while fetching.

**Comment by billygriffin** [comment]
Hi @bergamin, thanks for the issue. Desktop respects your global Git config when determining what email to use for commits, so you're correct that there's not a per-repo setting. GitHub allows you to add multiple emails to your GitHub account, and you can override the global Git email manually as a stopgap so at least those commits will be attributed to your GitHub account. I'm going to roll this issue into #610 as we're thinking about the problem more broadly there.

**Comment by bergamin** [comment]
Alright, thanks. Following that one
