### ISSUE TITLE
Github Desktop Not Recognizing SSH Key Added to ssh-agent

### ISSUE THREAD

**Issue by gabessdsp** [desktop/desktop#9225]
### Describe the bug

When using GitHub desktop I am not able to clone a repository from my local git repo via ssh. IT works fine when I pull it via Git Bash so I know the SSH key is associated with my account, and it's added to the ssh-agent. Github desktop just says "Authentication failed" and then says "- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account." which I believe it is given I can pull with git bash.

### Version & OS

GitHub Desktop Version 2.3.1
Windows 10 Pro Version	10.0.18363 Build 18363

### Steps to reproduce the behavior

This is a local company hosted git repo (using gitlab) so I can't put the exact steps in here since it's not available to the world wide web.

1. Go to your repo
2. Click on the SSH URL and copy it: git@ourdomain.com:GROUP/project.git
3. Hit File -> Clone Repository -> URL and paste in the Git SSH URL

### Expected behavior

I expected it work work as if I had just pasted a HTTPS URL and clone the repo.

### Actual behavior

It gave me an authentication error

### Logs

[2020-03-05.desktop.production.log](https://github.com/desktop/desktop/files/4293299/2020-03-05.desktop.production.log)

**Comment by tierninho** [comment]
@gabessdsp GitHub Desktop does support using BitBucket, GitLab, Azure DevOps repos, and it's documented how to clone them here: https://github.com/desktop/desktop/tree/development/docs/integrations

While we intend to continue basic support for repos from other sources, our primary goal is for the GitHub <-> GitHub Desktop experience to shine. We don't intend to support publishing local repos to other hosts from Desktop in the near term, so I'm going to close this issue. Thanks again!

**Comment by Crayder** [comment]
Should this be reopened @tierninho? Because the same issue is preventing me from managing my private repo's wiki (private GitHub repo) in Github Desktop. Latest version.

ssh-agent running and works flawlessly in bash but not GD.
