### ISSUE TITLE
Restore initial protected branch baseline metric logic

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#9228]
When we refactored the protected branch logic to use the new endpoint for whether a given user could push to a given branch, the `commitsToProtectedBranch` metric also inherited that change. Unfortunately this meant that comparing the current metrics to the baseline was impossible and we weren't able to see whether we alleviated any pain.

The goal here is to just restore the initial metrics collection logic so we'll be able to compare before/after, understanding that it won't exactly match the actual implementation. And @outofambit can decide whether to create a new metric to match the new logic, that would likely be named something more like `commitsWhereUserCannotPush` or something like that?

**Comment by mishz** [comment]
https://github.com/desktop/desktop/issues/9228#issue-576594846

**Comment by billygriffin** [comment]
I think the ship has probably sailed on this one unfortunately, but we know for next time!
