### ISSUE TITLE
git 'remote-https'is not a git command.see 'git--help'

### ISSUE THREAD

**Issue by ganeshhappysanz** [desktop/desktop#9229]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @ganeshhappysanz. It would be helpful if you could fill out the issue template and upload a log file from GitHub Desktop. Based on the error message you shared it sounds like there is an issue with our installation of GitHub Desktop. You can try reinstalling by following these steps:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps.

**Comment by steveward** [comment]
@ganeshhappysanz I'm going to close this issue out -- let me know if you are still having problems!

**Comment by Antony12931a0519** [comment]
Facing the same issue saying "git: 'remote-https' is not a git command. See 'git --help'.". 
Try to follow the steps mentioned by @steveward , But no luck facing the same issue.
