### ISSUE TITLE
Changes panel blank

### ISSUE THREAD

**Issue by wisecrmgh** [desktop/desktop#9230]
### Describe the bug
Changes panel blank

### Version & OS
GitHub Desktop: Version 2.3.1
OS: Windows 10

### Steps to reproduce the behavior
1. First, in the `Changes` panel, there are some changes files
2. Click on `History` tab, and scroll down some
3. Click on `Changes` tab
4. See error.

### Screenshots

[Screenshots](https://wbs-qncdn.wisecrm.cn/uploader/20200306/4079534048670102.png)

**Comment by steveward** [comment]
Thanks for the report @wisecrmgh. This bug was reported in https://github.com/desktop/desktop/issues/9061 -- you can follow along there for updates about a fix.
