### ISSUE TITLE
GitHub Desktop authentication primarily through browser flow

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#9231]
GitHub is [deprecating and removing the authorizations API](https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/), which handles how most users of GitHub Desktop sign into GitHub from the app. We've always had a secondary method of authenticating via the browser, but we'll need to make this the main authentication method going forward.

### Considerations

1. We know protocol handlers can be brittle depending on browser and OS, so we need to ensure people know that the sign in was successful and that they can return to the app. We're imagining this as an interstitial after a successful sign in on github.com.
2. To help discover potential pitfalls with moving to 100% browser authentication, we might start by swapping the prominent default initially so people have something to fall back to before we're forced to remove it altogether.
3. We need to make sure the next version of GitHub Enterprise uses both our protocol handlers (including the auth-specific one) so we get backward compatibility on Enterprise.

**Comment by steven351** [comment]
make things work easier

**Comment by gitwdel** [comment]
#9231

**Comment by ampinsk** [comment]
# Designs 

## Transition state

For the period of time when we're transitioning, we'll need to emphasize the browser log in flow, while still keeping the normal login flow

### Welcome screen

This moves all the login options to the first screen, and emphasizes the GitHub.com option.

<img width="1440" alt="Transition-Welcome-Screen" src="https://user-images.githubusercontent.com/10404068/77484135-fe9f9b80-6de6-11ea-8d61-ae8ce6cedd11.png">

### Preferences
The initial login screen should stay the same: 

<img width="1440" alt="Transition-Preferences-1" src="https://user-images.githubusercontent.com/10404068/77484139-019a8c00-6de7-11ea-869e-80cd12d6eaed.png">

Then on this screen, I flipped the options and emphasized the GitHub.com option.

<img width="1440" alt="Transition-Preferences-2" src="https://user-images.githubusercontent.com/10404068/77484141-02332280-6de7-11ea-9de6-498124874a70.png">


## Final state

For when the transition is complete, and the *only* option is to login using your browser

### Welcome screen

After the transition is complete, we can remove the login fields

<img width="1440" alt="Final-Welcome-Screen" src="https://user-images.githubusercontent.com/10404068/77484142-02cbb900-6de7-11ea-9f49-25143d5428b2.png">

### Preferences

After the transition is complete, we can just surface the GitHub.com option directly on this screen.

<img width="1440" alt="Final-Preferences" src="https://user-images.githubusercontent.com/10404068/77484143-03644f80-6de7-11ea-9bf5-7e29121052d6.png">

## Interstitial page

The page on dotcom we send you to for the browser login. I left these Help links just as an idea based on other login flows I looked at, so we can change these or remove them entirely if they're not needed.

<img width="1440" alt="Interstitial Page" src="https://user-images.githubusercontent.com/10404068/77484138-019a8c00-6de7-11ea-8b0c-5ec269122649.png">

**Comment by Rexogamer** [comment]
does this at all impact support for bitbucket repos? iirc we wanted to retain basic support for them but I could be wrong

**Comment by rafeca** [comment]
I'm going to work on this one, by first implementing the transition state designed by @ampinsk

**Comment by billygriffin** [comment]
I shared with @niik today that ideally we would keep the alternative method available until it's actually deprecated so we can use the brownout periods to identify any problems and address them.

He shared that ideally we would add support for detecting when dotcom doesn’t support basic auth any more and dynamically enable/disable the username/password flow based on that. That way we’ll adapt during the brownouts and Desktop will automatically adapt to any changes in the deprecation timeline.

This sounds like a great approach to me assuming the implementation isn't too complex.

@ptoomey3 or @tarebyte: We use the `verifiable_password_authentication` property on the API for GHES to detect whether it supports basic auth. Do you happen to know if we can reliably use that for dotcom as well? Note: this is a public repo so share public things only here. 😄 

@niik Please feel free to add or correct anything I missed, and if anyone else has questions please don't hesitate to ask.

**Comment by ptoomey3** [comment]
TIL `verifiable_password_authentication`. I think that value would also apply to whether the main web login uses built-in auth or not (I think it is just meant to say that the app verifies passwords vs. deferring to an external source using SAML or something). As such, I'm not sure its value would change after password auth support is removed.

**Comment by niik** [comment]
> I think it is just meant to say that the app verifies passwords vs. deferring to an external source using SAML or something

@ptoomey3 It's possible that the meaning of that property have changed over time but it was originally [added specifically for GitHub Desktop](https://github.com/github/github/pull/17306) (or rather GitHub for Mac/GitHub for Windows) to be able to determine whether we'd have to use the web flow to authenticate.

GHfW/GHfM and GHD have [relied on it since 2013](https://github.com/github/Mac/pull/3296) but only for GHES. Our [API documentation for the property](https://developer.github.com/v3/meta/#body) says 

> Whether authentication with username and password is supported.

**Comment by ptoomey3** [comment]
👍 - I think the bit that felt ambiguous to me was the "Whether authentication with username and password is supported." documentation. It isn't clear authentication _to what_? One might think "to the API" is obvious/implicit, but wasn't 100% sure since that meta endpoint returns other data totally unrelated to the API itself (ex. SSH server key fingerprints).

**Comment by niik** [comment]
@ptoomey3 Yeah, I think ambiguous is an understatement here and if I hadn't been there for the discussions to add it way back when I wouldn't have been able to make heads or tails of it either.

We've just merged #10020 which makes Desktop respect `verifiable_password_authentication` for GitHub.com as well as GHES. Is there a tracking issue for the brownouts or another good place where we might add a task so that we remember to flip the property as part of the brownouts?

**Comment by benbalter** [comment]
Over in https://github.com/github/prodsec/issues/265, @github/prodsec is building out tooling to nudge users using basic password auth to upgrade their client to a specific version. 

Based on https://github.com/desktop/desktop/pull/10020 would it be accurate to say that users we detect as using basic password auth on GitHub.com should upgrade to GitHub Desktop 2.5.4 or later?

(Also :wave: Hello @rafeca... great to cross paths with you once again! :smile:)

**Comment by rafeca** [comment]
> Based on #10020 would it be accurate to say that users using basic password auth should upgrade to GitHub Desktop 2.5.4 or later?

Yes, starting in v2.5.4 GitHub Desktop will disable the user/password authentication once GitHub doesn't support it anymore (note that GitHub Desktop has supported browser-based authentication for quite a long time, but the main way users authenticated was still using user/password).
