### ISSUE TITLE
samsung-galaxy-j6

### ISSUE THREAD

**Issue by candracahyono51** [desktop/desktop#9234]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by say25** [comment]
This is just the template so closing.

**Comment by candracahyono51** [comment]
https://www.google.co.id

**Comment by candracahyono51** [comment]
https://www.google.co.id
