### ISSUE TITLE
Github Desktop is not detecting Notepad++

### ISSUE THREAD

**Issue by morozdan2003** [desktop/desktop#9235]
I always used Notepad++ to edit code files, but Github Desktop is not allows to use it. How to fix it?

**Comment by say25** [comment]
@morozdan2003 Bad news, good news.

Bad News: This is not currently supported by GitHub Desktop.
Good News: I just implemented such support. #9238

**Comment by Neustradamus** [comment]
@say25: Thanks for this!

**Comment by tiomanisland** [comment]
How does it work? I use Notepad++ and GitHub desktop. Can you give me example, please?
