### ISSUE TITLE
 cannot import name 'PdfFileReader' from 'pdf'

### ISSUE THREAD

**Issue by saternalia** [desktop/desktop#9237]
### I am using someone else's code from 2014 to stitch pdf chapters together from a website but I don't think it wants to play nice with the most up to date python. 

Here is the error message I am getting:
$ python scraper.py http://onlinelibrary.wiley.com/doi/book/10.1002/9781119028994
Traceback (most recent call last):
  File "scraper.py", line 5, in <module>
    from pyPdf import PdfFileWriter, PdfFileReader
  File "C:\Users\sth60\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyPdf\__init__.py", line 1, in <module>
    from pdf import PdfFileReader, PdfFileWriter
ImportError: cannot import name 'PdfFileReader' from 'pdf' (C:\Users\sth60\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pdf\__init__.py)

### Additional context
This is the code in question.  I am VERY new at this and don't know what to change it make this run properly. 

import os
import urllib
import sys
from bs4 import BeautifulSoup as BS
from pyPdf import PdfFileWriter, PdfFileReader

def append_pdf(input,output):
	[output.addPage(input.getPage(page_num)) for page_num in range(input.numPages)]

baseurl = "http://onlinelibrary.wiley.com"

url = sys.argv[1]

if url.startswith("http"):
	output = PdfFileWriter()
	f = urlopen(url)
	myfile = f.read()
	parsed = BS(myfile,"lxml")
	toc = parsed.find_all(class_="citation")
	title = parsed.find(id="productTitle")
	title_text = ''.join(title.findAll(text=True))
	print("You are downloading " + title_text)
	for counter, item in enumerate(toc):
		pdf = item.find(class_="standardPdfLink")
		pdflink = pdf.get('href')

		if not pdflink.startswith("http"):
			pdflink = baseurl + pdflink

		try:
			response = urlopen(pdflink)
			response_parsed = BS(response,"lxml")
			pdftl = response_parsed.find(id="pdfDocument")
			pdftlink = pdftl.get('src')
		except:
			print("Failed to get resource , Retrying (0/10)")
			flag = 0
			for i in range(10):
				response = urlopen(pdflink)
				response_parsed = BS(response,"lxml")
				pdftl = response_parsed.find(id="pdfDocument")
				if pdftl is not None:
					flag = 1
					break
				print("Failed to get resource , Retrying ("+str(i)+"/10)")
			if flag == 0:
				print ("Couldn't Connect to get resources. Exiting")
				exit()
		pdftlink = pdftl.get('src')
		pdffile = urllib2.urlopen(pdftlink)

		file_seg = open(title_text + str(counter)+".pdf", 'wb')
		file_seg.write(pdffile.read())
		file_seg.close()

		append_pdf(PdfFileReader(file(title_text + str(counter)+".pdf","rb")),output)
		os.remove(title_text + str(counter)+".pdf")

		print ("Finished Processing : " + pdflink)

	output.write(file(title_text+ ".pdf","wb"))
else:
	print ("This is not a valid URL")

**Comment by say25** [comment]
I think this issue is being reported on the wrong repository so I am closing it.
