### ISSUE TITLE
Branch newly created is showing old date

### ISSUE THREAD

**Issue by vijayakumarbathini** [desktop/desktop#9243]
### Describe the feature or problem you’d like to solve
Branch newly created is showing old date

A clear and concise description of what the feature or problem is.
Created a new branch in GitHub enterprise and fetched the changes. Seeing branch created as 20 days ago

### Proposed solution
Branch should be showing the date it is created

How will it benefit Desktop and its users?
User will be knowing exact date the branch created

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@vijayakumarbathini the branch you create will have the same date as the branch tip you created the branch from. If your `master` branch had the most recent commit from `20 days ago` then when you create a `feature` branch off of `master` the branch tip will also be from `20 days ago`. I hope that helps explain things!
