### ISSUE TITLE
Unable to add local repository checked out using repo

### ISSUE THREAD

**Issue by Casper-Bonde-Bose** [desktop/desktop#9256]
### Describe the bug

When trying to add a local repository to the desktop APP the "Add repository" button stays inactive.
The drag/drop do not work either.

### Version & OS

Version 2.3.1
Windows 10

### Steps to reproduce the behavior
1. Checkout a github project using the repo tool (by Google) using WSL - or maybe  in some other way have the .git folder content as symbolic links)
2. Start the app (The Let's get started!" shows up
3. Click on 'Add Existing Repo...'
4. Select the git project folder (with the .git folder inside)
5. See error as the "Add repository" button being inactive

### Expected behavior

I would expect the UI to either show an error message or make the button active.

### Actual behavior

Nothing visable to the user - only an error entry in the logs.

### Logs
```
2020-03-10T08:13:47.878Z - error: [ui] `git rev-parse --is-bare-repository` exited with an unexpected code: 128.
stderr:
warning: unable to access '.git/config': Invalid argument
warning: unable to access '.git/config': Invalid argument
fatal: unknown error occurred while reading the configuration files
```
### Additional context

I have validated that the .git/config is there, but it is a symbolic link to a file located else-where. As I work on many git-projects in parallel I use repo to checkout the projects.

So it seems the github desktop is unable to use symbolic links - I even tried to run the desktop app as administrator(should only be required to create symbolic links) - it does not make any difference.
Content of the .git folder (from an Windows subsystem for Linux Ubuntu shell):
```
drwxrwxrwx 1 user user    512 Feb 24 17:32 .
drwxrwxrwx 1 user user    512 Feb 24 17:32 ..
-rwxrwxrwx 1 user user     41 Feb 24 17:32 HEAD
lrwxrwxrwx 1 user user     54 Feb 24 17:32 config -> ../../../.repo/projects/sources/xxxxx.git/config
lrwxrwxrwx 1 user user     77 Feb 24 17:32 description -> ../../../.repo/project-objects/yyyy-zzzzz-xxxxx.git/description
lrwxrwxrwx 1 user user     71 Feb 24 17:32 hooks -> ../../../.repo/project-objects/yyyy-zzzzz-xxxxx.git/hooks
-rwxrwxrwx 1 user user 296417 Feb 24 17:32 index
lrwxrwxrwx 1 user user     70 Feb 24 17:32 info -> ../../../.repo/project-objects/yyyy-zzzzz-xxxxx.git/info
lrwxrwxrwx 1 user user     52 Feb 24 17:32 logs -> ../../../.repo/projects/sources/xxxxx.git/logs
lrwxrwxrwx 1 user user     73 Feb 24 17:32 objects -> ../../../.repo/project-objects/yyyy-zzzzz-xxxxx.git/objects
lrwxrwxrwx 1 user user     59 Feb 24 17:32 packed-refs -> ../../../.repo/projects/sources/xxxxx.git/packed-refs
lrwxrwxrwx 1 user user     52 Feb 24 17:32 refs -> ../../../.repo/projects/sources/xxxxx.git/refs
lrwxrwxrwx 1 user user     74 Feb 24 17:32 rr-cache -> ../../../.repo/project-objects/yyyy-zzzzz-xxxxx.git/rr-cache
lrwxrwxrwx 1 user user     69 Feb 24 17:32 svn -> ../../../.repo/project-objects/yyyy-zzzzz-xxxxx.git/svn
```

If this feature is unsupported(I hope not), the very least would be for the UI to show an error message. Currently it simply does nothing.

**Comment by Casper-Bonde-Bose** [comment]
Just noticed that other windows application are not able to follow the symbolic links either, hence it might be an WSL issue, that links created with WSL is not correctly ported to the link types used in windows.

**Comment by steveward** [comment]
Thanks for the report @Casper-Bonde-Bose. I'm not too familiar with the `repo` tool -- can you share a few more details about how you are using it?

**Comment by tierninho** [comment]
@Casper-Bonde-Bose  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
