### ISSUE TITLE
"Open with ..." button issue

### ISSUE THREAD

**Issue by BobSaidHi** [desktop/desktop#9260]
### Issue

I (and my friends) use a custom installation of VS Code for FIRST Robotics Competition, which installs in C:/Users/Public/wpilib... .  The installation does not show up in the File/Options/Integrations/External editor menu. 

### Question/ Expected Solution

Is it possible to configure Desktop to have this installation of VS Code display as an external editor in the UI?

### Version & OS

Windows
Version 2.3.1

**Comment by tierninho** [comment]
@BobSaidHi Thanks for reaching out. We do support VS Code. 

To fix, change the "editor" to the application name, for instance "VS Code". 

`cd %LOCALAPPDATA%\editor\`
`editor --squirrel-updated`

You may have to restart Desktop. Let us know how it goes.

**Comment by BobSaidHi** [comment]
I do not seem to have the directory in `%LOCALAPPDATA%` that matches your description.

**Comment by steveward** [comment]
@BobSaidHi unfortunately editor integrations require specific installation paths -- see this document for more information:
