### ISSUE TITLE
Add pcm  wav support

### ISSUE THREAD

**Issue by MartinDelille** [desktop/desktop#9262]
### Describe the feature or problem you’d like to solve

The client handle well various image format, but what about sound?

### Proposed solution

It'll be nice to have a simple audio preview of audio files. Here is the corresponding html code:

```html
<audio controls>
  <source src="audio.wav" type="audio/wav">
</audio>
```

**Comment by steveward** [comment]
Thanks for sharing this idea @MartinDelille. At this time we do not have any plans to support this feature in GitHub Desktop, so I am going to close this issue out to help keep our issue list maintainable.
