### ISSUE TITLE
Present full path of file somewhere in the UI.

### ISSUE THREAD

**Issue by nicholaswright** [desktop/desktop#9263]
### Describe the feature or problem you’d like to solve

If I look at a commit, which contains a number of files that have long paths, I cannot see the full paths of the files anywhere at all in the UI, without hovering over each individual file until the tooltip appears; which is tedious.

### Proposed solution

There's an existing request regarding allowing users to expand the file panel. I really don't understand the logic behind not allowing users to do this. This would by far be the best solution.

As an alternative, could you please simply display the full file path above the code panel? This way I can at least glance at the path whilst using my keyboard's down arrow to skim through the files.

**Comment by tierninho** [comment]
@nicholaswright Thanks for the suggestion. I am going to role this request into https://github.com/desktop/desktop/issues/2745 as they are very similar.
