### ISSUE TITLE
unable to communicate with nexus through docker

### ISSUE THREAD

**Issue by Omar-El** [desktop/desktop#9265]
i'm facing a problem that i cannot comprehend, what i'm trying to achieve is to connect to a private repository in my case it's nexus in order to push some docker images. after setting up the repository on nexus, nginx config file and the self asigned certificate using keytool, i still have the error in the image bellow. keep in my mind that i'm currently working in a corporate that uses a proxy, could it be the issue ?

https://i.stack.imgur.com/kBEfM.png

docker login -u admin repo.nexusidemia.com:48085
Error response from daemon: Get http://repo.nexusidemia.com:48085/v2/: EOF
https://i.stack.imgur.com/yAIDn.png

                 events { worker_connections 768; # multi_accept on; }
     http 
    { proxy_send_timeout 120;
       proxy_read_timeout 300; proxy_buffering    off ;
       keepalive_timeout  5 5;
       tcp_nodelay        on;
      server 
     { listen 48085 ssl; 
     server_name repo.nexusidemia.com; 
     ssl_certificate nexusidemia.cert; 
     ssl_certificate_key  nexusidemia.key;
     ssl_session_cache shared:SSL:50m;
     location / { 
     proxy_set_header        Host $host:$server_port;
     proxy_set_header        X-Real-IP $remote_addr;
     proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header        X-Forwarded-Proto $scheme;
     proxy_redirect          http:// https://; 
     proxy_pass              http://repo.nexusidemia.com:8085;
    client_max_body_size       1024m;
    client_body_buffer_size    128k; } 
    }

Nexus Configuration

https://i.stack.imgur.com/APKld.png

 when i type the url https://repo.nexusidemia.com:48085 i get the secure lock. 
https://i.stack.imgur.com/bVwWq.png

**Comment by steveward** [comment]
@Omar-El this issue tracker is for GitHub Desktop -- if you are having specific issues with a projected hosted on GitHub I would recommend opening an issue directly in that repository's issue tracker.
