### ISSUE TITLE
Desktop does not recognize local changes

### ISSUE THREAD

**Issue by jason-hernandez-73** [desktop/desktop#9269]
### Describe the bug

This is similar to a currently open issue, except that in my case, the "Changes" tab is not blank; it just shows the normal "No local changes," even when I have made local changes. I do not know if it is related, but when I clone the repo to my terminal, it all works normally, until I try to git add; then it shows an error message saying "fatal: not a git repository (or any of the parent directories)" For a few weeks now, the only way I can commit is by going to my GitHub page and uploading the updated files. The app then shows the upload in the "History" tab, as normal.

### Version & OS

Version 2.3.1

Windows 10 64-bit

### Steps to reproduce the behavior

1. Make changes to files in the local repo
2. Bring up desktop
3. Make sure it is on current repository
4. Make sure it is on the Changes tab

### Expected behavior

I expected my local changes to appear in the "Changes" tab, with the option to commit them

### Actual behavior

The "Changes" tab shows no local changes

**Comment by tierninho** [comment]
@jason-hernandez-73 

Based on this error message it looks like the `.git` directory in your repository was deleted -- I am guessing this may have happened when you deleted the project files. Were you wanting to create a fresh repository in this location?

If the `.git` directory was deleted on disk and you would like to restore it it should be available in the `Recycle Bin`. If you would like to create a new repository with the existing project files you will need to remove the repository from GitHub Desktop and then add it again to initialize it. You can also run `git init` from the command line to do the same (go to the file menu and select `Repository` > `Open in <default_command_line_application>` to launch the command line).

Possible to include your logs (See Help menu in Desktop) and any screenshots (if relevant)? Thanks!

**Comment by jason-hernandez-73** [comment]
Got it. I had to delete the local repo folder on my hard drive as well, and re-create it from GitHub.

**Comment by JarmBlueOak** [comment]
Old issue thread but in case anyone lands here for the same issue I had, make sure you confirm which folder your project is linked to in GitHub Desktop, I right clicked the project and did "show in explorer" and realised I had cloned into a folder with a certain name but then was making edits in another folder with a very similar name from an earlier clone attempt.

**Comment by rddprocham** [comment]
Re-bumping this issue in case someone had the same problem as me;
Your problem may be that you downloaded the .zip instead of cloning the repo on your computer; for me git desktop didn't notice any files changed automatically
Hope this helps!

**Comment by torres005** [comment]
i when i am making changes in html file the github dekstop is not recognising any changes

**Comment by flaneurette** [comment]
Bumping it also because GH desktop does not recognize certain changes, this happened after doing a cache clearing. Could this be a bug?

**Comment by jordanade** [comment]
I have to move away and revisit the window for changes (i.e. a commit) to show up. Would be nice for it to use OS affordances to watch the directory and refresh immediately.

**Comment by galijulio29-sudo** [comment]
> I have to move away and revisit the window for changes (i.e. a commit) to show up. Would be nice for it to use OS affordances to watch the directory and refresh immediately.

/###
