### ISSUE TITLE
Crashing on macOS 10.15

### ISSUE THREAD

**Issue by kylefox** [desktop/desktop#9271]
### Describe the bug

GitHub Desktop frequently crashes when using context menus, i.e. right-clicking the mouse. I primarily notice it when right-clicking "Discard All Changes..." and "Discard Changes..." on a particular file.

I believe this only started occurring after I recently upgraded to macOS Catalina 10.15.3.

### Version & OS

* GitHub Desktop Version 2.3.1
* macOS Catalina 10.15.3

### Logs

I'm having trouble recreating the problem (it's sporadic) but will update this issue with logs once I'm able to.

### Additional context

I had a very similar problem (right-clicks causing crashes) with Atom, which turns out to be a [known issue](https://github.com/atom/atom/issues/20034) and possibly related to Electron.

Because GitHub Desktop is also an Electron app, is it possible these issues are similar? There's a temporary fix for Atom, [facebookexperimental/atom-menu-patch-for-catalina](https://github.com/facebookexperimental/atom-menu-patch-for-catalina), so if the issues _are_ related, perhaps it would be possible to put together a similar patch for GitHub Desktop.

**Comment by tierninho** [comment]
@kylefox Thanks for reaching out and providing the suggested patch. This is a known issue and will be fixed in the near future.

See this comment for context: https://github.com/desktop/desktop/issues/8846#issuecomment-584918479
