### ISSUE TITLE
it has committed it but it is not publishing to my remote repo

### ISSUE THREAD

**Issue by ineesh** [desktop/desktop#9275]
i have committed my changes but it is not publishing it to the remote repo.
please help 

it says that "remote -- https" is not a git command please help

![Screenshot (72)](https://user-images.githubusercontent.com/53057298/76656427-8e4a7c00-6595-11ea-8b91-cf10d4e93490.png)

**Comment by tierninho** [comment]
@ineesh Thanks for filing this. Please include your Logs so we can get some more info. See the Help menu in Desktop.

**Comment by tierninho** [comment]
@ineesh  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
