### ISSUE TITLE
Able to switch branch while pull/push is in progress

### ISSUE THREAD

**Issue by EndlessEra** [desktop/desktop#9277]
When pulling/pushing using github desktop, user are allowed to switch branch while it is still loading. This cause an issue to all branch to being corrupted. Propose solution is to disable branch switching when pulling/pushing, or pop up possible error before allowing user to switch.

**Comment by steveward** [comment]
Thanks for the report @EndlessEra. I've updated your issue title and moved it to the body of the issue to reduce the length of the title.

It would be helpful if you could upload a log file from GitHub Desktop, which would give us some more information about this issue. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tierninho** [comment]
@EndlessEra  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
