### ISSUE TITLE
Request : Please add the exact match option when searching the repository.

### ISSUE THREAD

**Issue by arzzcom** [desktop/desktop#9284]
Please add the exact match option when searching the repository.

I added many similarly named repositories.
I use a repository search to move quickly between repositories, but it is difficult to move quickly because of partially matching search results.

So, I would like to add the option of exact match to preferences.

![스크린샷 2020-03-15 오전 10 54 54](https://user-images.githubusercontent.com/4408201/76693659-466a4880-66ac-11ea-9692-be3e2ff63abd.png)

**Comment by steveward** [comment]
Thanks for the feedback on this @arzzcom, and apologies for not getting a response back to you sooner. I'm going to lump this into https://github.com/desktop/desktop/issues/4527.
