### ISSUE TITLE
OAuth is revealing personl information which have not been on Github or were already deleted

### ISSUE THREAD

**Issue by 001101** [desktop/desktop#9285]
### Describe the bug

As I installed Github Desktop now and used the 'sign in on browser' via OAuth in the app my personal .dev email was insered and my real name, which are both not on GitHub and the email is also not even pre-added on Github.

Currently I am not sure if I added the mail to Github directly or maybe to Gitlab or some other Git specific services, but I am completly sure that is not present in my current account, also not my real name!!

So I am really really wondering where does M$ get those information from and why they are still in the system.

### Version & OS

2.3.1 + Win10 Pro
I am not using MS auth, not using Win Apps or any other things on the system and blocking most of the connections to Redmond.

### Steps to reproduce the behavior

1. Install
2. Use OAuth login

### Expected behavior

Get the information passed to the app which are currently set and verified.

### Behavior when not using OAuth

The profile data which is set get correctly filled with normal login, name and Github Email, as it should.

### Additional questions

Where can I see log files about it on desktop?

### Additional research

Checked mostly all OAuth application which I granted access and until than none of them is having this information stored.

**Comment by steveward** [comment]
@001101 thanks for the report. GitHub Desktop first checks your `.gitconfig` file for your name and email address -- were these values configured there prior to you installing GitHub Desktop?

**Comment by 001101** [comment]
Yes that's possible, thanks for letting me know!
