### ISSUE TITLE
Undo does not stage partial files

### ISSUE THREAD

**Issue by shravan2x** [desktop/desktop#9286]
### Describe the bug

When the uncommit button is used, partially selected files are fully unselected (i.e. they have no selected lines anymore).

### Version & OS

Version: 2.3.1
OS: Windows 10 x64

### Steps to reproduce the behavior

1. Partially select a file (i.e. select some lines in it to commit)
2. Commit
3. Uncommit

### Expected behavior

The partially selected file has it's staged lines reselected.

### Actual behavior

The entire file is unselected.

**Comment by outofambit** [comment]
hi @shravan2x thanks for filing this. this sounds like a bug, but i want to make sure i'm understanding the reproduction steps. when you say "uncommit" do you mean the "undo" button below the commit box that undoes your most recent commit? I was able to reproduce this with that approach.

![undo partial](https://user-images.githubusercontent.com/964912/79370892-4c9c5080-7f08-11ea-8b02-c4179cfe415c.gif)

**Comment by shravan2x** [comment]
@outofambit That's right, I was referring to the undo button. It's a feature I use often to include specific lines of code that I missed in the last commit. But when all partial files get unselected, I often forget other lines of code when I commit again.

**Comment by DCzajkowski** [comment]
Can confirm this happens on macOS as well and has been happening at least since the move to Electron.

**Comment by shravan2x** [comment]
Can we bump the priority of this issue to priority-2? I think it affects more users than just the ones participating in this issue.
