### ISSUE TITLE
lost my phone with authenticator on it and trying to put authenticator codes to come through email.

### ISSUE THREAD

**Issue by Leisua** [desktop/desktop#9288]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@Leisua please reach out to [GitHub Support](https://support.github.com/) if you are having issues with two-factor authentication.
