### ISSUE TITLE
how can I get my authenticator codes through my email and not my phone.

### ISSUE THREAD

**Issue by Leisua** [desktop/desktop#9289]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@Leisua GitHub does not allow for authentication codes via email -- you can view the available options for two-factor authentication here:

https://help.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication

If you have any further questions I would recommend reaching out to [GitHub Support](https://support.github.com/).
