### ISSUE TITLE
Bitbucket - captcha

### ISSUE THREAD

**Issue by RyKaj** [desktop/desktop#9291]
### Describe the bug
Bitbucket keeps flagging my account to active captcha every 5 mins or less. I believe it is how this tool checks all repos status it is like DDoS. Is there a way we can run the update without flipping the captcha flag to active. My company will not turn off captcah. 

### Version & OS

Windows 10.0.18363

### Steps to reproduce the behavior
Load Github desktop. Captcha dialog shows. I go to bitbucket, log off, log in, interact wtih captcha. 
Few minutes later. Captcha dialog shows. I go to bitbucket, log off, log in, interact wtih captcha. 
...wash rince...

### Expected behavior
I enter captcha and never have to interact with it. 

### Actual behavior
do while... 
      Captcha dialog shows. 
      I go to bitbucket
      log off
      log in
      interact wtih captcha.
Wait couple minunites 

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@RyKaj Thanks for reaching out. If BitBucket is showing a captcha, please reach out to them to see how it can be altered. We have no control over that. If I misinterpreted your request, please advise.
