### ISSUE TITLE
No pull progress on the pull button

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#9292]
### Describe the bug

There is no pull progress on the pull button. Is it by design or a bug?

### Version & OS

v2.3.1 & windows 10

### Steps to reproduce the behavior

1. Click the pull button when the button indicates to pull

### Expected behavior

There are pull progress detail on the pull button

### Actual behavior

No pull progress detail on the pull button

### Screenshots
![image](https://user-images.githubusercontent.com/5396286/76748441-bb757500-67b5-11ea-8fb3-c17e67ab119d.png)

### Additional context

I added `console.log('pull progress', progress)` in the pullRepo call in app-store.ts as below, and there is no progress log except only one
```jsx
await gitStore.performFailableOperation(
            () =>
              pullRepo(repository, account, remote, progress => {
                console.log('pull progress', progress)
                this.updatePushPullFetchProgress(repository, {
                  ...progress,
                  value: progress.value * pullWeight,
                })
              }),
            {
              gitContext,
              retryAction,
            }
          )
```
![image](https://user-images.githubusercontent.com/5396286/76748724-39398080-67b6-11ea-81c9-af7e4a3024ae.png)

I'm not sure where it's because there is no handle for stdout in createProgressProcessCallback mehod in app\src\lib\progress\from-process.ts file:
![image](https://user-images.githubusercontent.com/5396286/76749035-ca105c00-67b6-11ea-93e0-6e6e4ddef098.png)

**Comment by tierninho** [comment]
@TerryChan To clarify your issue, you selected the Pull option from the Repository menu are asking for Desktop to show a status of any files pulled down, like "Pulling 1 of 10..."? 

If Desktop detects the changed files ahead of you clicking the option in the menu, we show something like this:

![7134b1fa-9481-11e6-9d1c-4216c5f3ad2f](https://user-images.githubusercontent.com/14828183/76791006-09fa2380-6764-11ea-94bd-37918a26a49b.png)

Some background:
> If your branch has fallen behind the remote we’ll give you the option to pull.

> If you’re both ahead and behind, we’ll make you do a pull before giving you the ability to push. This is similar to what Sync does today except we will do a pull and merge but we will not automatically push that merge commit. Instead we'll leave that action to the user so that we'll never push a result that they're not comfortable with. We might consider updating the button text in this state to something like 'Pull and merge'.

> In the scenario where the client thinks you're neither ahead nor behind we'll offer to refresh the repository (a fetch). We've used 'Refresh' as the terminology here. We considered using 'fetch' but we then decided to add the 'Last fetched...' subtitle to all button states as a way of indicating that we do perform background fetches. It'll also give us a place to indicate that a background fetch is underway (we'll spin the sync arrows)

**Comment by tierninho** [comment]
@TerryChan  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
