### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by lucasanguinetti** [desktop/desktop#9296]
Hi!

I am experiencing this problem with a GitHub folder, I've used till two weeks ago. For some reasons, I cannot get updates. I tried to remove it and clone again but it does not work. The log files is reported below:

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Preferences.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-03-16T18:09:24.167Z - info: [ui] Current tutorial step is NotApplicable
2020-03-16T18:09:24.173Z - info: [ui] Background fetch for 3 repositories took 3.216sec
2020-03-16T18:09:49.553Z - info: [ui] Current tutorial step is NotApplicable
2020-03-16T18:11:25.926Z - info: [ui] Current tutorial step is NotApplicable
2020-03-16T18:11:30.746Z - info: [ui] Current tutorial step is NotApplicable
2020-03-16T18:11:41.572Z - info: [ui] Current tutorial step is NotApplicable
2020-03-16T18:23:05.551Z - info: [ui] Current tutorial step is NotApplicable
2020-03-16T18:23:27.193Z - info: [ui] Current tutorial step is NotApplicable
2020-03-16T18:23:29.128Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'gitlab.liu.se' and 'luca.sanguinetti@unipi.it'
2020-03-16T18:23:29.157Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://gitlab.liu.se/ozlde25/cell-free-book.git /cell-free-book` exited with an unexpected code: 128.
stderr:
fatal: could not create work tree dir '/cell-free-book': Permission denied

(The error was parsed as 21: Permission denied.)

I've spent all day to figure out the issue, but I could not find any solution.

I am using MacBook Pro with macOS Mojave version 10.14.6 and GitHub desktop version 2.3.1.

Thank you very much in advance.

**Comment by tierninho** [comment]
@lucasanguinetti thanks for info. We have a specific guide that walks through how to authenticate to GitLab using GitHub Desktop:

https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md

If you run into any issues with that please let us know!

**Comment by lucasanguinetti** [comment]
Thanks for the guide. Unfortunately, I do not receive an 'Authentication Failed error' (as specified in the guide) where one should copy the token, but a 'Permission denied' error without any chance to provide the token.

**Comment by tierninho** [comment]
Could you try cloning using HTTPS to see if the problem persists as Desktop doesn't support repos cloned using SSH very well. Are you on Mac or Windows?

Some other users have had success by doing one of the following:
1. signing out and then back in
2. Go to menu > Repository Settings, Change primary remote repository (Origin) from "git@github.com:<user_name>/<repo_name>.git" to "https://github.com/<user_name>/<repo_name>.git"
3. Update your GitHub keys in credential manager.

**Comment by lucasanguinetti** [comment]
I'll try. I am on Mac...

**Comment by lucasanguinetti** [comment]
Nothing. As soon as I try to clone the directory from the GitLab of the University, I got the 'Permission denied' error.
<img width="960" alt="Screenshot 2020-03-16 at 21 34 02" src="https://user-images.githubusercontent.com/9197061/76797514-0307fb00-67ce-11ea-872e-f65608fa8da8.png">
<img width="960" alt="Screenshot 2020-03-16 at 21 34 15" src="https://user-images.githubusercontent.com/9197061/76797525-09967280-67ce-11ea-8158-cb7a7301a81b.png">

**Comment by tierninho** [comment]
@steveward Any ideas here?

**Comment by steveward** [comment]
@lucasanguinetti the `fatal: could not create work tree dir '/cell-free-book': Permission denied` indicates that Git can't write to the location where you are trying to clone. It looks like you are cloning to `/`, which would cause that error since it's read-only. Try cloning to your user directory to see if that succeeds.

**Comment by lucasanguinetti** [comment]
It worked; but how could I choose to clone it in my Github folder? I am using the same folder for other repositories. Can I change the location afterwards (once the cloning is done)?

**Comment by lucasanguinetti** [comment]
Just to let you know, everything is fine now. It is working properly. Thank you very much for your great and quick help.

**Comment by steveward** [comment]
I'm glad to hear things are working for you now!
