### ISSUE TITLE
Add "Reset" button shortcut to reset current branch

### ISSUE THREAD

**Issue by lifesboy** [desktop/desktop#9298]
### Describe the feature or problem you’d like to solve
I'm working with a large number of repository and branch in a large team
When I switch back to a specific branch of repository, it has been out of date a lot. Pressing "Pull origin" it shows conflict popup and requires to resolve.
I just need to reset local version to latest remote version
( git reset --hard origin/currentbranch )

### Proposed solution
Add short cut button "Reset" to quick reset current branch.

### Additional context

![image](https://user-images.githubusercontent.com/49264651/76819377-90813480-683a-11ea-88eb-d072d4117089.png)

![image](https://user-images.githubusercontent.com/49264651/76819398-a0007d80-683a-11ea-9c89-b9dab44050e6.png)

![image](https://user-images.githubusercontent.com/49264651/76819433-bad2f200-683a-11ea-8928-91a15c7b0514.png)

**Comment by steveward** [comment]
Closing this out since while we may consider adding reset functionality in the future, we don't have any plans of adding more  items to the suggested action list. See https://github.com/desktop/desktop/issues/5860 for some discussion around adding `git reset`.

**Comment by DRGN-DRC** [comment]
Is there a workaround to this problem? Or an equivalent set of procedures in the program to fix states like this?

My current solution is to leave the GUI and resort to the command line with the following:
```
git fetch upstream
git switch <branchName>
git reset --hard upstream/master
git push --set-upstream origin <branchName> --force
```
This seems to work. (Hopefully, this helps others with this issue as well.) Although, despite there being no local changes or unsynced commits between the local repo, remote origin, or even with the upstream master, GitHub Desktop still shows the option with the blue button to "Preview Pull Request", which seems strange to me. (Clicking on the button opens a window that also tells me, "There are no changes.")

I'm sorry if this isn't the best place to ask, considering this is closed. But this seems like the exact issue I've been having. Google and SO weren't providing anything helpful (everything I've seen refers to command-line methods), and I've run into this issue a few times now using GitHub Desktop. I feel like there has to be a better solution.

**Comment by kristeningram** [comment]
Please!
