### ISSUE TITLE
希望可以添加针对不同平台的本地代理功能

### ISSUE THREAD

**Issue by meichangliang** [desktop/desktop#9300]
在中国,github的访问速度实在是太慢了,因为在同时使用多个git平台 , git命令行设置代理的方式虽然可以解决问题,但还是很不方便 , 所以希望desktop可以增加本地代理功能 , 最好是可以分不同平台不同设置.

>In China, the access speed of github is really too slow, because when using multiple git platforms at the same time, although the git command line setting proxy method can solve the problem, it is still very inconvenient, so I hope that desktop can increase the local proxy function. Fortunately, different settings can be divided into different platforms.

**Comment by steveward** [comment]
@meichangliang thanks for contributing. I've updated your issue comment with a translation. GitHub Desktop shipped support for proxies to beta in https://github.com/desktop/desktop/pull/9154. You can [install the beta version](https://github.com/desktop/desktop/pull/9154) if you would like to test it out. Let us know if you run into any problems!
