### ISSUE TITLE
Can not copy dialog box text

### ISSUE THREAD

**Issue by JessFarmerVA** [desktop/desktop#9305]
### Describe the bug

Error modal popups describing any error I may have. Can not copy the error from the dialog box to paste to the internet to help debug.

### Version & OS

Windows 10, Version 2.3.1

### Steps to reproduce the behavior

5. Try to copy 
6. Notice can not select to copy

### Expected behavior

You should be able to copy text in dialog box

### Actual behavior

Can not copy dialog box text

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@JessFarmerVA Thanks for filing this. This was fixed in https://github.com/desktop/desktop/pull/8964 however I am unsure if it applies to `git` generated errors. Any idea what the error said when you experienced this issue? If you attach you logs, I can find there as well. See the Help menu in Desktop

**Comment by tierninho** [comment]
@JessFarmerVA  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by JessFarmerVA** [comment]
Oh no I didn't see this . :( 
The issue was a Git error. It was: 
ssl_choose_client_version:inappropriate fallback

**Comment by tierninho** [comment]
Hi! Does that mean you solved it? If not, please share your logs. Thanks.

**Comment by JessFarmerVA** [comment]
No. The issue was I got a dialog box saying there was a git error. I could not select the text in the dialog box for me to copy and google. I have since deleted GitHub Desktop.

**Comment by JessFarmerVA** [comment]
After reading #8964
"Finally I saw that we were using cursor: text which made one believe it was possible to select text in the dialog but due to us using user-select: auto that wasn't actually the case since the user-select: none got inherited from our global styles."
It appears it is not possible to select the text. And the fix on #8964 removed the select cursor so the user did not think it was possible. However my issue is it should be possible because it is much easier to select and copy then it is to type it out.

Thanks

**Comment by tierninho** [comment]
Thanks for the clarity. We look forward to improving Desktop to the point where you return as a satisfied user! Have a good day.
