### ISSUE TITLE
Multiple instances of the same repository

### ISSUE THREAD

**Issue by valentinptc** [desktop/desktop#9307]
### Problem
I am facing the situation where the same repository is required on different locations on my hard-drive. This scenario is easy to handle with command-line, however the desktop app makes it impossible. I can add multiple instances of the same repository on my hard drive, however they all show up with the exact same name. I can not distinguish them.

### Solutions
1. Allow rename for a repository name in the repository list. Indicate with color that the name has changed.
2. Show folder name of cloned repo instead of git repo name in the list.
3. Allow to add a comment next to the name.

**Comment by steveward** [comment]
@valentinptc thanks for contributing. If you hover over the repo names, you will be able to see the full path of the repositories. I'm going to drop your comment into https://github.com/desktop/desktop/issues/7856 where we are collecting feedback about this.

**Comment by valentinptc** [comment]
Hovering over the name does not do the trick.
A. I need to wait 3 seconds before I get this information
B. Paths can be very long and given the line break in the hovering info, it takes some extra 2 seconds to identify if it is the exact repo

If you enable any of the above option, users will have a clean uninterrupted workflow.

**Comment by andrewtytula** [comment]
The hover solution is not user friendly. Suggest either a way to give a repo an alias or maybe include the path underneath the name.
