### ISSUE TITLE
The revocation function is unable to check revocation for the certificate

### ISSUE THREAD

**Issue by prestonfu** [desktop/desktop#9309]
### Describe the bug

The revocation function was unable to check revocation for the certificate.

### Version & OS

Version 2.3.1; Windows 10 Home, 1903, 64-bit

### Steps to reproduce the behavior

1. Click clone repository from the Internet
2. Click on the repository name
3. Click clone
4. Get an error message

### Expected behavior

Clone properly.

### Actual behavior

Gives an error message.
`fatal: unable to access 'https://github.com/owner/name.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.`

### Additional context

I've read [https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326](url), but it now seems that shell is no longer included with Github Desktop. Is this true, and how can I solve my problem?

**Comment by steveward** [comment]
@prestonfu thanks for contributing. We'll be pushing out a release to address this error -- if you are interested in checking it out right now you can download the beta from here:

https://github.com/desktop/desktop#beta-channel

Let me know if that doesn't help with your issue.
