### ISSUE TITLE
Show the upstream repository on github when clicking on "view on github"

### ISSUE THREAD

**Issue by rafeca** [desktop/desktop#9312]
### Describe the feature or problem you’d like to solve

We're currently redirecting users to the forked repository when clicking on "View on GitHub", but based on #9170 I think we want to default to the parent repository instead.

### Proposed solution

When a user clicks `view on GitHub` while they’re on a fork, we eant to redirect them to the upstream repository on GitHub, not the fork.

### Additional context

In a similar fashion than #9232, this may not be what everyone wants, but based on https://github.com/desktop/desktop/issues/9170 it'll cover the vast majority of use cases, where the fork exists in order to allow someone to contribute to the upstream repository.

**Comment by tierninho** [comment]
Thanks for the issue! @rafeca 

We happen to use an identical "View on GitHub" label for viewing single commits on GitHub.com.

![Screen Shot 2020-03-18 at 7 46 44 AM](https://user-images.githubusercontent.com/14828183/76990932-da2a5780-68ec-11ea-810e-fb5b5fb79197.png)

Although you are referencing repo-level buttons, the identical wording here may cause some confusion. Just wanted to point it out in case we want to rephrase it. I have no option.

**Comment by rafeca** [comment]
Oh thanks for pointing this out @tierninho ! I just talked about this earlier today with @outofambit !

I think that ideally that menu item should also redirect to the upstream repository in normal conditions, but there's something tricky here: we would need to check if the commit is only pushed to the fork and redirect to the fork in that case.
