### ISSUE TITLE
cloned repository is empty

### ISSUE THREAD

**Issue by YouCantPronounceKazotsky** [desktop/desktop#9330]
### Describe the bug

cloned repository, nothing shows up in it, subfolders and files missing, master branch is only shown folder

### Version & OS

version 2.3.1

### Steps to reproduce the behavior

1. clone a repository
2. go to repository

### Expected behavior

subfolders and files should show up

### Actual behavior

they dont

### Screenshots

https://i.imgur.com/hoge5Hp.png

### Logs

[2020-03-20.desktop.production.log](https://github.com/desktop/desktop/files/4361957/2020-03-20.desktop.production.log)

**Comment by tierninho** [comment]
@YouCantPronounceKazotsky Thanks for reaching out. 

I was able to clone the repo successfully and al the files & commits match the GitHub repo. See the History tab in Desktop (View > Show History), does it look like this? Was there something specific you were looking for? 

![Screen Shot 2020-03-20 at 12 22 00 PM](https://user-images.githubusercontent.com/14828183/77210569-6b442e80-6aa5-11ea-8681-dd4d4c069204.png)

**Comment by tierninho** [comment]
@YouCantPronounceKazotsky  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
