### ISSUE TITLE
Issue comments are not shown in Project issue summary

### ISSUE THREAD

**Issue by drdbuck** [desktop/desktop#9333]
### Describe the feature or problem you’d like to solve
The Issue's comments are not shown in Project issue summary panel. Only a comment icon with comment count is shown, with not indication if there is a new comment. If you do realize there is a new comment, you have to go to the issue and then scroll down to the bottom to see the comment.

### Proposed solution

The date of the last comment should be displayed in the Issue summary of the project, If clicked, the comments should be shown in reverse chronological order. The date of last issue update should also be shown on the project card, along with the checkbox summary.

How will it benefit Desktop and its users? It will immediately be clear there is a new comment and save the time of scrolling down and wading through all the edits of the issue, just to get to the latest comment!

As it is now, the project does little to aid in communication of the latest status among the developers.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
![image](https://user-images.githubusercontent.com/11023635/77232641-abc0ac80-6b78-11ea-93a5-bc22c3c0dffa.png)

**Comment by shieldgenerator7** [comment]
+1 this would save me a lot of time when trying to keep track of updates to an issue

**Comment by steveward** [comment]
@drdbuck this issue tracker is for the GitHub Desktop application. For specific feature requests about GitHub (the website) please contact [GitHub Support](https://support.github.com/).
