### ISSUE TITLE
Wrong link on pull request description

### ISSUE THREAD

**Issue by ruggi99** [desktop/desktop#9334]
### Describe the bug

I've forked a repo and I've cloned it locally. When clicking on the link in the image below, Github Desktop opens wrong page on GitHub. It tries to open issue 7163 on my forked repo (that doesn't exist) instead of the correct PR on the upstream one.

### Version & OS

Version: 2.3.1 (latest at the moment).
OS: Windows 10

### Steps to reproduce the behavior

1. Fork a repo and clone it locally
2. Checkout a branch (in this case master) and pull/fetch
3. Go to History tab and choose any commit
4. Click on the id of the pull-request, as in the image below

### Expected behavior

Open PR 7163 on the upstream repo

### Actual behavior

Opens issue 7163 on my forked repo

### Screenshots

![Cattura](https://user-images.githubusercontent.com/25064808/77300402-45f63100-6cee-11ea-998b-e38fd8de6bb1.PNG)

**Comment by rafeca** [comment]
Thanks for reporting the issue!

We've been able to reproduce the wrong behaviour and we'll add this issue to our backlog
