### ISSUE TITLE
Add Jumplists

### ISSUE THREAD

**Issue by diligamer** [desktop/desktop#9339]
### Describe the feature or problem you’d like to solve

Windows Jumplist Support For Repos/Branches

### Proposed solution

It Will Improve Their Workflow

### Additional context

My Editor (VSC) Supports This And It Saves Time

**Comment by steveward** [comment]
@diligamer thanks for contributing. GitHub Desktop has a `Recent` section for both the branch and repository lists -- is that what you are looking for? I believe jump lists are just a quick way to access recently viewed files/folders, which would align with the functionality we built into GitHub Desktop. Let me know if I am misunderstanding your request.

**Comment by diligamer** [comment]
> @diligamer thanks for contributing. GitHub Desktop has a `Recent` section for both the branch and repository lists -- is that what you are looking for? I believe jump lists are just a quick way to access recently viewed files/folders, which would align with the functionality we built into GitHub Desktop. Let me know if I am misunderstanding your request.

Can We Have The Recent Repositories Menu Be A Jumplist As Well.
