### ISSUE TITLE
Blank space in repository history

### ISSUE THREAD

**Issue by kleuter** [desktop/desktop#9341]
Sometimes, the latest version (2.3.2-beta7) on Windows 10 x64 gives the following problem:

![sshot-2](https://user-images.githubusercontent.com/2600624/77321053-e578eb00-6d11-11ea-9087-d92bdd64ec5e.png)

The blank space cannot be clicked. After I restart the app, it's back to normal:

![sshot-3](https://user-images.githubusercontent.com/2600624/77321088-f1fd4380-6d11-11ea-8b79-2e376a31b921.png)

[2020-03-23.desktop.beta.log](https://github.com/desktop/desktop/files/4369618/2020-03-23.desktop.beta.log)

Experienced with multiple repositories, not very often, no exact steps to reproduce.

**Comment by rafeca** [comment]
Thanks for reporting the issue! This one was a tricky one to reproduce 😅

After some digging I've found some repro steps:

1- Make sure that you have access to 2 git repositories in Desktop ("Small Repo" and "Big Repo" . "Big Repo" should have a lot of commits on its default branch (enough to need the scrollbar on the history tab), while "Small Repo" should have only 4-5 commits (to not cause any scrolling on the history tab).
2- Select the "Big Repo" from GitHub Desktop.
3- Restart GitHub desktop.
4- Open the History tab.
5- Scroll a little bit on the history tab and leave the tab scrolled.
6- Select "Small Repo" without from the repo list (without restarting GitHub Desktop!)
7- Go to History tab and see the issue.

A quick video of the issue.

![demo](https://user-images.githubusercontent.com/408035/77354304-e118f600-6d42-11ea-9280-7f6708b7e7e9.gif)
