### ISSUE TITLE
not pull file

### ISSUE THREAD

**Issue by Idreesepic** [desktop/desktop#9353]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tierninho** [comment]
@Idreesepic Please fill out the bug report here so we better assist you. Thank you!

**Comment by tierninho** [comment]
https://github.com/desktop/desktop/issues/new?template=bug_report.md
