### ISSUE TITLE
not push file

### ISSUE THREAD

**Issue by Idreesepic** [desktop/desktop#9354]
### Describe the bug
nothing
not pull file fail in written
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@Idreesepic Please fill in the template and describe the problem in more depth as we do not have enough information yet. Thank you.

**Comment by steveward** [comment]
Closing in favor of #9357.
