### ISSUE TITLE
pre_commit hook output

### ISSUE THREAD

**Issue by giulianozor** [desktop/desktop#9356]
Hello,
I have a repository with pre_commit hooks that takes a while to run. It would be very useful to see the live output of the hook in a window, so the user knows what is going on.

### Proposed solution

How will it benefit Desktop and its users?
The (optional?) window will give the user more informations and there will be less confusion about the client hanging while committing

### Additional context

Probably applies to other hooks to

Thanks

**Comment by rafeca** [comment]
Hey @giulianozor !

Thanks for the suggestion! While we can see that showing the progress of the hooks can be useful for some specific use cases, we're not sure that the investment needed to implement this feature will be worth the benefits.

We currently show a loading indicator when the commit process takes a long time, which already give users a sense of what's going on (maybe we could display a small message mentioning that pre-commit hooks are running, but not sure how useful would that be).

Related to pre-commit hooks, something we want to improve is the experience when a pre-commit hook fails, which can cause a lot of friction to users and it's relatively easy to improve (see https://github.com/desktop/desktop/issues/9351#issuecomment-605212122).

I'm going to close this issue, but thanks again for the suggestion!
