### ISSUE TITLE
Wrong keybind for Developer Tools, after Release 2.4.0

### ISSUE THREAD

**Issue by ruggi99** [desktop/desktop#9364]
### Describe the bug

With version 2.4.0, I'm not able to open Developer Tools with "Ctrl + Shift + I" keybind anymore.

### Version & OS

Version 2.4.0, OS: Windows 10

### Steps to reproduce the behavior

1. Open Github Desktop.
2. Use "Ctrl + Shift + I" keybind.

### Expected behavior

Open developer Tools.

### Actual behavior

Opens browser to create a new issue on Github Web.

### Additional information

Trying to open Developer Tools from "View" > "Toggle developer tools" menu, works
With the previous version, keybind worked

**Comment by outofambit** [comment]
hi @ruggi99 thanks for reporting this! Sorry about this error, this is definitely a bug resulting from work in #9142. We'll find a different key binding for the "create an issue" action and be sure to fix this in the next release.
