### ISSUE TITLE
Add support for JetBrains Rider

### ISSUE THREAD

**Issue by wengfatt** [desktop/desktop#9365]
Currently, JetBrains Rider is not supported as an external editor.

**Comment by tierninho** [comment]
We have documentation here on how to make sure your preferred editor will work with Desktop, and how to add it. https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

Please feel free to open a pull request for a specific editor if you'd like to contribute and add this editor to the ones supported in the app!

**Comment by wengfatt** [comment]
@tierninho I already open a pull request.  https://github.com/desktop/desktop/pull/9368.

**Comment by say25** [comment]
I can take on the Windows side of this.

**Comment by van800** [comment]
Might be worth using https://github.com/JetBrains/resharper-unity/blob/net201/unity/EditorPlugin/RiderPathLocator.cs

**Comment by say25** [comment]
Technically note closed until https://github.com/desktop/desktop/pull/9368 makes it but I think its fine
