### ISSUE TITLE
error: RPC failed; curl 55 Send failure: Connection was aborted

### ISSUE THREAD

**Issue by TheMightyPingu** [desktop/desktop#9367]
I am using GitHub desktop and trying to push a pretty large folder from the local repository on my machine to github. 

For further context, It is a program made in Unreal Engine and so It is reasonably large in size. I set up the source control in Unreal Engine and proceeded to do what I mentioned in the above paragraph. I have tried this multiple times and constantly get the following error messages:

Writing objects: 100% (833/833), 8.66 GiB | 19.33 MiB/s, done.
Total 833 (delta 19), reused 0 (delta 0)
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
error: RPC failed; curl 55 Send failure: Connection was aborted
Everything up-to-date

I did a "git lfs track" in Git Bash before trying to push it on Github using Github Desktop. Any help would be appreciated. Thank you in advance.

**Comment by steveward** [comment]
@TheMightyPingu it looks like you are running into GitHub's 2GB push limit. You can try pushing your repository in chunks via the command line by using the following command:

`git push <remotename> <commit SHA>:<branch>`

Also, if you had already committed a large file to your repository prior to adding it to Git LFS I would recommend using the [`git-lfs-migrate`](https://github.com/bozaro/git-lfs-migrate) tool. Let me know if you run into any issues.

**Comment by TheMightyPingu** [comment]
It turns out i exceeded my quota limit on LFS, but more or less,  everything is working now.

**Comment by JuicyJannis** [comment]
Got the same problem. I bought 50 gb LFS storage but it stills not working

**Comment by bigmamasugar** [comment]
I'm not sure what this is but i keep getting emails.

Sent from Yahoo Mail on Android 
 
  On Wed, Sep 16, 2020 at 12:00 PM, JuicyJannis<notifications@github.com> wrote:   


Got the same problem. I bought 50 gb LFS storage but it stills not working

**Comment by Akash671** [comment]
Enumerating objects: 22, done.
Counting objects: 100% (22/22), done.
Delta compression using up to 4 threads
Compressing objects: 100% (20/20), done.
Writing objects: 100% (21/21), 1.07 MiB | 37.71 MiB/s, done.
Total 21 (delta 2), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 55 Failed sending data to the peer
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

i have this error please help me how to resolve it.

**Comment by nholeg** [comment]
Enumerating objects: 76, done.
Counting objects: 100% (76/76), done.
Delta compression using up to 12 threads
Compressing objects: 100% (61/61), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly
Writing objects: 100% (76/76), 125.41 MiB | 6.96 MiB/s, done.
Total 76 (delta 7), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

same here

**Comment by ferranases** [comment]
Hi, I tried more than 25 commands/solutions, no one worked apart from change the internet conection from another.

**Comment by erickdc7** [comment]
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 8 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 19.21 MiB | 10.22 MiB/s, done.
Total 8 (delta 3), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

:c

**Comment by Tovarow** [comment]
Enumerating objects: 1175, done.
Counting objects: 100% (1175/1175), done.
Delta compression using up to 8 threads
Compressing objects: 100% (956/956), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (966/966), 147.52 MiB | 3.46 MiB/s, done.
Total 966 (delta 242), reused 123 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by PavelPZ** [comment]
The same problem for two only **1.3 MB** files

**Comment by CarouselBunny** [comment]
Same problem here. I did hit the 2G limit in the past, but have since fixed that problem. I changed internet connections and it still isn't working.

Edit: I undid my commits all the way back to when it was <2G, solved the 2G problem, and then pushed again. Seemed to solve it well

**Comment by Overhaul66** [comment]
Mine is not upto 1gb

**Comment by francisohwos** [comment]
Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 8 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (16/16), 953.15 KiB | 21.66 MiB/s, done.
Total 16 (delta 0), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 55 Send failure: Connection was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

please how do I resolve this?

**Comment by ankitjaiswaldxc** [comment]
I resolved the same issue in my case in my commit i am having some image which is causing issue after spent lot of time i started push one by one file & realise all files pushed except image 

please try one by one file push you will get your issue

**Comment by pooja140703** [comment]
Enumerating objects: 31, done.
Counting objects: 100% (31/31), done.
Delta compression using up to 4 threads
Compressing objects: 100% (31/31), done.
Writing objects: 100% (31/31), 72.69 MiB | 12.96 MiB/s, done.
Total 31 (delta 0), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 55 Recv failure: Connection was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

I also got the same problem then I used the revert command and then all files were deleted then to get that files back I used the revert command again and after getting them back , push it again ...!!
It worked for me, Try it if you still facing the above problem...!!

**Comment by pooja140703** [comment]
Enumerating objects: 31, done.
Counting objects: 100% (31/31), done.
Delta compression using up to 4 threads
Compressing objects: 100% (31/31), done.
Writing objects: 100% (31/31), 72.69 MiB | 12.96 MiB/s, done.
Total 31 (delta 0), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 55 Recv failure: Connection was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

I also got the same problem then I used the revert command and then all files were deleted then to get that files back I used the revert command again and after getting them back , push it again ...!!
It worked for me, Try it if you still facing the above problem...!!

**Comment by huabin** [comment]
@pooja140703 

Have the same issue, and tried your solution, but still the same. Sad :(

**Comment by vamshiginna** [comment]
> Hi, I tried more than 25 commands/solutions, no one worked apart from change the internet conection from another.

This worked for me. Thanks

**Comment by manav221** [comment]
Change your internet connection and try again
