### ISSUE TITLE
Unable to install GitHub Desktop on MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by neophiliacNoob** [desktop/desktop#9371]
### Describe the bug
After downloading the installer, unzipping it, and clicking the "GitHub Desktop.app", nothing happens. 

### Version & OS

MacOS Mojave 10.14.6

### Steps to reproduce the behavior

Tried running from terminal with the following response:
"LSOpenURLsWithRole() failed with error -10810 for the file /Applications/GitHub Desktop.app."

Tried also opening the app package contents and running from the MacOS directory with the following response:
"A session ended very soon after starting. Check that the command in profile "Terminator" is correct." Additionally attaching screenshot for both

### Expected behavior

Open or install Github desktop app for mac 

### Actual behavior

No errors or action occurs when double-clicking the app

### Screenshots

![Uploading 2020-03-26_16-56-41.png…]()

**Comment by tierninho** [comment]
@neophiliacNoob Thanks for filing. Looks like you pic above didn't get uploaded.

Curious if you have tried double-clicking the app on the desktop once it downloads? Do you happen to have another version of Desktop still hanging around? Trash it please and try to install again. 

> Tried running from terminal with the following response:
"LSOpenURLsWithRole() failed with error -10810 for the file /Applications/GitHub Desktop.app."

OSX like to quarantine "untrusted" apps so you may need to change permissions like so:
Note: change YourApp to the app name (in both places!)
`chmod +x path/to/YourApp.app/Contents/MacOS/YourApp`

> Tried also opening the app package contents and running from the MacOS directory with the following response:
"A session ended very soon after starting. Check that the command in profile "Terminator" is correct." Additionally attaching screenshot for both

This seems to relate to your Terminator shell settings here: https://terminator-gtk3.readthedocs.io/en/latest/preferences.html#command

This _may_ help with that: https://apple.stackexchange.com/questions/263226/upgrade-bash-without-using-the-terminal-to-fix-iterm-issue-dyld-library-not-loa

Let us know how it goes!

**Comment by neophiliacNoob** [comment]
Thanks for your reply, i have tried the solutions provided without luck. 

I was able to get a crash report since it was failing to write it before. 

> Process:               GitHub Desktop [62852]
Path:                  /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop
Identifier:            GitHub Desktop
Version:               2.4.0 (2.4.0)
Code Type:             X86-64 (Native)
Parent Process:        zsh [62846]
Responsible:           GitHub Desktop [62852]
User ID:               501

Date/Time:             2020-03-27 11:07:25.829 -0700
OS Version:            Mac OS X 10.14.6 (18G3020)
Report Version:        12
Bridge OS Version:     3.0 (14Y906)
Anonymous UUID:        6B1EF5DD-273C-6118-04CB-9CD2249BA071

Sleep/Wake UUID:       F28349B4-BC54-4580-B410-AE25C086EFBC

Time Awake Since Boot: 16000 seconds
Time Since Wake:       11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop
  Reason: no suitable image found.  Did find:
	/Applications/GitHub Desktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/GitHub Desktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x1027d5000 -        0x1027fdfff +com.github.GitHubClient (2.4.0 - 2.4.0) <CD315A0C-AE44-3040-8C05-F56E5800F953> /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop
       0x10575d000 -        0x1057c770f  dyld (655.1.1) <1605ACFC-49C3-33AF-B319-5BE41FC6E208> /usr/lib/dyld
    0x7fff315a2000 -     0x7fff3163cffb  com.apple.MediaPlayer (1.0 - 1.0) <F601EBD5-7A38-3F0D-BA43-6DC535978124> /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer

**Comment by neophiliacNoob** [comment]
@tierninho 

Now i wonder if it has anything to do with the current package from the download site: "https://desktop.github.com/".

I just installed through brew >>> "brew cask install github" and it successfully installed and open. 

system% brew cask install github
==> Downloading https://desktop.githubusercontent.com/releases/2.4.0-568b4113/GitHubDesktop.zip
Downloaded: /Users/user/Library/Caches/Homebrew/downloads/7071c5e27f8eadf34e43ef44d6a095997bd63b4064f6adb391fcde1e27142cfe--GitHubDesktop.zip
==> Verifying SHA-256 checksum for Cask 'github'.
==> Installing Cask github
==> Moving App 'GitHub Desktop.app' to '/Applications/GitHub Desktop.app'.
==> Linking Binary 'github.sh' to '/usr/local/bin/github'.
🍺  github was successfully installed!

**Comment by tierninho** [comment]
Now i wonder if it has anything to do with the current package from the download site: "https://desktop.github.com/".

🤔 Not sure at this point, but thanks for sharing.

Overall, I am glad you got it resolved! I was just about to add that other users had issues with brew and that would be the next area to look into. Enjoy Desktop and reach out anytime with questions.
