### ISSUE TITLE
Scrollbar remains white in dark mode

### ISSUE THREAD

**Issue by khvorov45** [desktop/desktop#9372]
### Describe the bug

Scrollbar remains white in dark mode.

### Version & OS

Version: 2.3.1-linux1
OS: Linux Mint 19.3 Cinnamon

### Screenshots

![Screenshot from 2020-03-27 12-37-57](https://user-images.githubusercontent.com/44919476/77712699-abb52680-7028-11ea-8c52-aa6bf871700a.png)

**Comment by rafeca** [comment]
Hey @khvorov45! 👋

I'm afraid we can't provide any support for GitHub Desktop on Linux at this time as it's not an officially supported platform. See #1525 for the tracking issue related to Linux support.

In the meantime I suggest opening an issue in the repository of the Linux fork of Desktop (https://github.com/shiftkey/desktop/issues).

Kind regards!
