### ISSUE TITLE
Fails to read git history

### ISSUE THREAD

**Issue by stakach** [desktop/desktop#9373]
### Describe the bug

When viewing this project in github desktop https://github.com/PlaceOS/models.git
It fails to show history and constantly pops up with this error (makes the client almost unusable)

### Version & OS

Version 2.4.0
macOS Catalina v10.15.3 (19D76)

### Steps to reproduce the behavior

1. https://github.com/PlaceOS/models.git
2. view the repository history

### Expected behavior

1. No error message pop-ups
2. render the commits that can be read and put some error placeholder text on the bad commit

### Actual behavior

Annoying and constant pop-up, typically builds up over time too so I have to close multiple pop-ups every time i want to commit something

### Screenshots

![image](https://user-images.githubusercontent.com/368013/77716827-2125f480-7033-11ea-9dea-b5f5be15c3b6.png)

### Logs

Nothing related to this issue in logs

**Comment by steveward** [comment]
Thanks for the report @stakach. This looks like the same issue as https://github.com/desktop/desktop/issues/6836. I ran `git show 8d0bb99` in that repository to investigate the problematic commit to confirm:

```
commit 8d0bb99c021aef635fa984e218ed4051fef78099
Author: Caspian Baska <caspianbaska@gmail.com>
Date:   Mon Nov 25 15:21:10 2019 +1100

    feat(settings): `is^__encrypted?` helper
```

You could amend this commit message using interactive rebase from the command line to resolve this error, but this would also require force pushing the repository. See the 'Amending the message of older or multiple commit messages' section in [this help article](https://help.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message) for more information about how to do that.

I'm going to reference this issue in #6386 and close this out.
