### ISSUE TITLE
Add option to ignore untracked folders

### ISSUE THREAD

**Issue by matiasmorant** [desktop/desktop#9374]
### Describe the feature or problem you’d like to solve

I added a new (untracked) folder in my repo folder with hundreds of files I'm not interested in.
I also made a few code changes in my repo that I do care about.
The panel that shows `git status` shows all these hundreds of irrelevant files and not the ones I care about.

### Proposed solution

Either:

1- If there is an untracked folder with lots of files just show there is a new folder, not every file inside
2- Allow to right-click and add a folder to .gitignore not just a file
3- After right-click > Ignore file, show an editor to modify what you added to .gitignore, not just .gitignore diff

### Additional context

![image](https://user-images.githubusercontent.com/5036575/77721252-10d92f80-6fc9-11ea-9e40-36b053546073.png)

**Comment by steveward** [comment]
Thanks for contributing @matiasmorant! I'm going to close this out and add your feedback to #1203 where we are tracking this feature.
