### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by sharonmustri** [desktop/desktop#9375]
I can log in to GitHub Desktop but when I try to push/clone a repo, I get an error saying 'Authetication failed'. I've tried to uninstall and reinstall everything but the error persists.

### Steps to reproduce the behavior

1. Go to 'clone a repo from the internet'
2. Click on one of your repositories
3. Get error 'Authentication failed' and asked for user and password but doesn't accept the correct inputs.
* this only happens if the repo is private.
------
[2020-03-27.desktop.production.log](https://github.com/desktop/desktop/files/4391549/2020-03-27.desktop.production.log)

Alternatively:
1. Go to 'publish branch' on local repo
2. Get error:
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

### Expected behavior

Being able to push and clone repos to/from github.com

### Actual behavior

authentication error.

**Comment by steveward** [comment]
@sharonmustri thanks for the report. Could you walk through the ["Authentication errors due to modified registry entries:](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#authentication-errors-due-to-modified-registry-entries) section of our known issues document to see if that could possible be causing this error on your machine?

**Comment by steveward** [comment]
@sharonmustri I'm going to close this issue out -- if you are still experiencing authentication failures please let me know and we can look into this further.
