### ISSUE TITLE
Add support for Android Studio editor on Windows

### ISSUE THREAD

**Issue by rafeca** [desktop/desktop#9379]
### Describe the feature or problem you’d like to solve

https://github.com/desktop/desktop/pull/9332 added support for Android studio editor on macOS, but it missed adding the editor to Windows.

### Proposed solution

Android Studio users on Windows will be able to quickly open projects from GitHub Desktop

### Additional context

The [`app/src/lib/editors/win32.ts`](https://github.com/desktop/desktop/blob/development/app/src/lib/editors/win32.ts) file needs to be updated to include Android Studio. This requires finding the relevant registry keys for Android Studio (and their potential variants).

For an example of adding an editor to Windows, check out [this PR](https://github.com/desktop/desktop/pull/9238).

**Comment by say25** [comment]
I started this but I dont think this is possible at the moment as there is no install path at 
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Android Studio`.

```diff
diff --git a/app/src/lib/editors/win32.ts b/app/src/lib/editors/win32.ts
index d3cbdf2fe..118cbb07f 100644
--- a/app/src/lib/editors/win32.ts
+++ b/app/src/lib/editors/win32.ts
@@ -25,6 +25,7 @@ export enum ExternalEditor {
   SlickEdit = 'SlickEdit',
   Webstorm = 'JetBrains Webstorm',
   Phpstorm = 'JetBrains Phpstorm',
+  AndroidStudio = 'Android Studio',
 }
 
 export function parse(label: string): ExternalEditor | null {
@@ -64,6 +65,9 @@ export function parse(label: string): ExternalEditor | null {
   if (label === ExternalEditor.Phpstorm) {
     return ExternalEditor.Phpstorm
   }
+  if (label === ExternalEditor.AndroidStudio) {
+    return ExternalEditor.AndroidStudio
+  }
 
   return null
 }
@@ -352,6 +356,14 @@ function getRegistryKeys(
             'SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhpStorm 2020.1',
         },
       ]
+    case ExternalEditor.AndroidStudio:
+      return [
+        {
+          key: HKEY.HKEY_LOCAL_MACHINE,
+          subKey:
+            'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Android Studio',
+        },
+      ]
 
     default:
       return assertNever(editor, `Unknown external editor: ${editor}`)
@@ -393,6 +405,8 @@ function getExecutableShim(
       return Path.join(installLocation, 'bin', 'webstorm.exe')
     case ExternalEditor.Phpstorm:
       return Path.join(installLocation, 'bin', 'phpstorm.exe')
+    case ExternalEditor.AndroidStudio:
+      return Path.join(installLocation, 'bin', 'studio.exe')
     default:
       return assertNever(editor, `Unknown external editor: ${editor}`)
   }
@@ -453,6 +467,10 @@ function isExpectedInstallation(
       return (
         displayName.startsWith('PhpStorm') && publisher === 'JetBrains s.r.o.'
       )
+    case ExternalEditor.AndroidStudio:
+      return (
+        displayName.startsWith('Android Studio') && publisher === 'Google LLC'
+      )
     default:
       return assertNever(editor, `Unknown external editor: ${editor}`)
   }
@@ -612,7 +630,13 @@ function extractApplicationInformation(
         installLocation = item.data
       }
     }
+    return { displayName, publisher, installLocation }
+  }
 
+  if (editor === ExternalEditor.AndroidStudio) {
+    const displayName = getKeyOrEmpty(keys, 'DisplayName')
+    const publisher = getKeyOrEmpty(keys, 'Publisher')
+    const installLocation = getKeyOrEmpty(keys, 'DisplayIcon')
     return { displayName, publisher, installLocation }
   }
 
@@ -679,6 +703,7 @@ export async function getAvailableEditors(): Promise<
     slickeditPath,
     webstormPath,
     phpstormPath,
+    androidStudioPath,
   ] = await Promise.all([
     findApplication(ExternalEditor.Atom),
     findApplication(ExternalEditor.AtomBeta),
@@ -692,6 +717,7 @@ export async function getAvailableEditors(): Promise<
     findApplication(ExternalEditor.SlickEdit),
     findApplication(ExternalEditor.Webstorm),
     findApplication(ExternalEditor.Phpstorm),
+    findApplication(ExternalEditor.AndroidStudio),
   ])
 
   if (atomPath) {
@@ -787,5 +813,12 @@ export async function getAvailableEditors(): Promise<
     })
   }
 
+  if (androidStudioPath) {
+    results.push({
+      editor: ExternalEditor.AndroidStudio,
+      path: androidStudioPath,
+    })
+  }
+
   return results
 }
```

**Comment by Vadimkin448** [comment]
> ### Describe the feature or problem you’d like to solve
> #9332 added support for Android studio editor on macOS, but it missed adding the editor to Windows.
> 
> ### Proposed solution
> Android Studio users on Windows will be able to quickly open projects from GitHub Desktop
> 
> ### Additional context
> The [`app/src/lib/editors/win32.ts`](https://github.com/desktop/desktop/blob/development/app/src/lib/editors/win32.ts) file needs to be updated to include Android Studio. This requires finding the relevant registry keys for Android Studio (and their potential variants).
> 
> For an example of adding an editor to Windows, check out [this PR](https://github.com/desktop/desktop/pull/9238)

**Comment by niik** [comment]
> I started this but I dont think this is possible at the moment as there is no install path at
> `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Android Studio`.

Thanks for checking on that @say25. I think we can close this for now then since there's no clear path forward.
