### ISSUE TITLE
Latest version (2.4.0) is not working in windows 7- 64 bit os

### ISSUE THREAD

**Issue by anoopissac** [desktop/desktop#9380]
### Describe the bug

After upgrade to 2.4.0 from 2.3.1, its stopped working, just a blank black screen is showing, nothing else 

### Version & OS

 2.4.0,   windows 7- 64 bit os

### Steps to reproduce the behavior

just open the app, just a blank black screen is showing, nothing else 

### Expected behavior

The app should work 

### Actual behavior

 just a blank black screen is showing, nothing else

### Screenshots

![Git-2 4 0](https://user-images.githubusercontent.com/20300506/77748240-08730a00-7046-11ea-9344-89ce39886f62.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by frank-e** [comment]
I'm also on Windows 7 x64 SP1, and 2.4.0 was my 1st update: No problems, GitHub Desktop still works for me.

**Comment by steveward** [comment]
@anoopissac could you check [this section of our known issue document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) to see if it fixes this issue for you?

**Comment by anoopissac** [comment]
> @anoopissac could you check [this section of our known issue document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) to see if it fixes this issue for you?

great, its seems working now, thanks steveward.

**Comment by steveward** [comment]
@anoopissac I'm glad to hear that got things working!

**Comment by amitsrivastava2020** [comment]
Same Issue with Window 8 Pro

**Comment by sreekanth-karini** [comment]
https://www.youtube.com/watch?v=2835_ZJGCQA

The above solution in the video worked for me.

**Comment by movethathoof** [comment]
> https://www.youtube.com/watch?v=2835_ZJGCQA
> 
> The above solution in the video worked for me.

This was actually what I needed - the 'Known Issues' Powershell fix did not help, but adding '--disable-gpu' to the shortcut as that video instructed solved the issue (I only wish I hadn't been so incredulous at help coming from a YouTube video, and not specifically for Github Desktop, and saved myself the half an hour haha).
