### ISSUE TITLE
Visually distinguish commits that are just on my branch in history

### ISSUE THREAD

**Issue by ruggi99** [desktop/desktop#9381]
### Describe the feature or problem you’d like to solve

If I'm on a branch (not the default one), It's known that if I want to get all commits that are ahead or behind from default branch (or others, but default one in this example), it's sufficient to go into History tab and do a compare with that branch.

### Proposed solution

I propose to add a spacer (line in image below) to separate ahead commits from default branch, so it's easier focusing on ahead commits only. Moreover it's faster than doing a compare each time.

### Additional context

![Cattura](https://user-images.githubusercontent.com/25064808/77756639-e1114280-702f-11ea-9712-b9a1dda13f51.PNG)

**Comment by billygriffin** [comment]
Hi @ruggi99, thanks for the idea! While we aren't sure about the exact implementation proposed, we think the concept of showing what commits in history are not yet merged to the default branch is an interesting one. We're looking at a somewhat related concept in #9366 to let people know which commits haven't yet been pushed to the remote, so we're going to discuss this a bit more and figure out whether we think we should prioritize improving this as well. Thanks!

**Comment by ruggi99** [comment]
Thank you @billygriffin .
It's to focus quickly on ahead commits from default branch... For example when watching different branches and continuously switch between them, etc..

**Comment by billygriffin** [comment]
Yeah, that makes sense, thanks for the additional context @ruggi99! There are also a lot of cases when the default branch is merged into the feature branch where the "ahead" commits won't be the latest ones shown in the history, so it's not quite as straightforward as using a separator.

**Comment by ruggi99** [comment]
You are right. So putting a separator is not enough in case default branch is merged into current branch. As title suggests, we need some form of ahead commit highlighting. Very good idea.

**Comment by ruggi99** [comment]
I've found a procedure that should retrieve all commits that are just on a specific branch, compared to another.
Tried it multiple times and works.

Here the steps:
1. Get the first oldest commit that is not contained in both branches (--first-parent is necessary):
   ```bash
   git log development...@ --first-parent --format="%h" --reverse | head -n 1
   ```
2. Get the parent of the found commit (not always necessarily, but often is):
   ```bash
   git log (...)^ --format="%h" -1
   ```
3. Log all commits that are just on the specific branch (--first-parent is necessary):
   ```
   git log (...)..@ --first-parent
   ```
All together is:
```bash
git log $(git log $(git log development...@ --first-parent --format="%h" --reverse | head -n 1)^ --format="%h" -1)..@ --first-parent
```
Where (...) means the result of the command of the step before.

In this case, HEAD is compared with the development branch.

**Comment by chrisropherbutler19892020** [comment]
-

**Comment by Siccity** [comment]
Isn't this what the tree-view that every other client has is supposed to solve?

**Comment by goyalyashpal** [comment]
> the tree-view that every other client

ohh yeahhh, i was also thinking about tree view some days ago. using GHD and GL-webIDE, i had almost forgot about it lol.
**Edit:** #9452
