### ISSUE TITLE
Branches are now created against upstream repo instead of the fork

### ISSUE THREAD

**Issue by abraunegg** [desktop/desktop#9384]
### Describe the bug

Prior to this release, a branch would be created against the fork correctly. Now, the 'branch' is created against the original repository.

EG:
```
Your new branch will be based on XXX/YYY default branch
```

Previously this used to say against MY default fork / branch.

Now, when adding in a single 1 line change, it is bringing in 2 years worth of changes.

### Version & OS

Windows 10

### Steps to reproduce the behavior

1. Fork a repository
2. Create a new branch against your fork
3. Branch is created against the source where fork was taken from

### Expected behavior

Branch should be against my fork

### Actual behavior

See above

### Screenshots

**using my fork of a project:**
![using a fork](https://user-images.githubusercontent.com/4956234/77804125-ea9fb680-70d2-11ea-8edf-68167ce71015.PNG)

**branch is created against the origin - not my fork**
![creating_a_branch](https://user-images.githubusercontent.com/4956234/77804155-fe4b1d00-70d2-11ea-9542-487067b172eb.PNG)

**branch shows original repository development, not my fork**
![history_shows_no_development](https://user-images.githubusercontent.com/4956234/77804440-9fd26e80-70d3-11ea-8ddf-aaa77eec2c04.PNG)

### Logs

None atm

### Additional context

How can I roll back this GitHub desktop client to one that works !!

**Comment by billygriffin** [comment]
Hi @abraunegg, thanks for the issue and really sorry the update caused problems with your workflow. This was an intentional change in https://github.com/desktop/desktop/issues/7762 based on the vast majority of forks being used to contribute to the upstream branch. So the previous behavior often would mean people working from forks in Desktop were starting new branches way out of date from the latest commits, and this was intended to help people ensure they're up to date when starting on a new branch.

Would you mind describing your workflow to help us understand your use case better? We've heard from others that in most cases for forks that are maintained independently of the upstream repo, they usually break off entirely as their own repo instead of remaining a fork because the fork relationship no longer adds any value and GitHub generally assumes that forks are used for contributing back to the parent. It'd be helpful for us to understand how you're using your fork and how it differs from our assumptions and what we've seen elsewhere.

Thanks so much, and again I apologize that this is causing problems for you.

**Comment by abraunegg** [comment]
@billygriffin 
Essentially - the original 'repo' - https://github.com/skilion/onedrive - is unmaintained, unmanaged and the user is 100% non contactable. As a result there is no way to transfer ownership to me or even merge any PR or code to it. It has been abandoned.

I forked the original repo (https://github.com/abraunegg/onedrive) to fix the bugs, and maintain the client which I have been doing for the last 2+ years.

So essentially, my 'fork' is the 'master', even though it is a 'fork' and not the original repository.

So - my work flow is this, in the previous version of client, I would just create a new branch against by folk, add in the code changes, then create a PR against my fork. This would just bring in changes as needed.

Now what seems to happen is - the 'branch' is looking at all changes from the 'skilion' as the base - which is 100% wrong - it should be checking this against my fork, as this is where I have created the branch from.

Based on the user documentation as well in the Desktop client - https://help.github.com/en/github/administering-a-repository/setting-the-default-branch - the default 'master' branch is my folk - my 'master' ... so why is this not being adhered to ?

**Comment by billygriffin** [comment]
@abraunegg Thanks so much for the detailed description and how your project has effectively become the primary project. The fork relationship doesn't seem to be adding any value for you at this point, so I'm wondering if it would make sense to detach your fork as its own project. GitHub Support is able to do this for you if you're interested by filling out a support ticket here: https://support.github.com/contact

In Desktop, we're optimizing for the use case that the vast majority of people are using, where their fork is effectively used for the purposes of contributing back to the parent repository. If we get a lot of signal that there are far more maintainers in your situation, we're certainly open to revisiting our assumptions. But for now, I'm curious if decoupling your fork from the upstream repo might be a good solution. Let us know, and thanks again for explaining it so clearly and thoroughly.

**Comment by abraunegg** [comment]
@billygriffin 
Can you not create some sort of 'toggle' or 'option' in the desktop to 'change' this new default behaviour?

This way - we, as users / consumers can decide where Desktop is creating branches? This is much better than 'forcing' a change like this upon users with no way to change the default behavior. in edge cases like this.

Re detach fork - yes I have considered this. Blockers / questions for that scenario:
* What happens to all the exist folk who have forked my repo?
* What happens to all the 'download stats'?
* What happens to all the 'watchers'?
* What happens to all the 'stars'?

**Comment by billygriffin** [comment]
@abraunegg I just checked with someone from support, and I believe that all of those things will come with the detached repo. I'd definitely encourage you to call those things out in your support ticket if you choose to go that route.

The reason why we've chosen not to provide a toggle in this particular case is that we think it's *such* a limited edge case that supporting it across a bunch of different fork-related code paths would be a significant cost, and all of the data we've seen suggests that it's really rare. As I mentioned in my last comment, if we get a lot of evidence that our assumptions were wrong, we're not opposed to exploring alternative solutions.

Unfortunately I know that's not a super helpful answer for you, but I *think* detaching the fork might actually allow you to preserve all the good things and have it work as expected.

**Comment by billygriffin** [comment]
Hi @abraunegg, I wanted to check in and find out if detaching your fork is something you're considering and whether there are other questions you have. You're the only person we've heard this feedback from since the release, and I'd love to help you get to a solution that works well for you.

**Comment by billygriffin** [comment]
Hi @abraunegg, thanks for the issue. Since we haven't heard this come up from anyone else, I'm going to close this issue to indicate that it isn't something we currently intend to change. However, we're definitely not opposed to revisiting down the road if it seems to be a more widespread problem. Thanks, and hope the suggestion helped you resolve it.

**Comment by abraunegg** [comment]
@billygriffin 
FYI I have submitted a support ticket to de-fork - Ticket ID: 649443

**Comment by billygriffin** [comment]
Thanks @abraunegg - looks like it was detached. 🎉 Sorry for the difficulty. I know it can be a pain to have to change things because of our choices, so I appreciate your understanding. ❤️

**Comment by charles-allen** [comment]
@billygriffin - This is laughably inflexible. I've never seen a Git Client that doesn't let me pick where to branch from.

I teach a classroom of students, and this "design choice" means we cannot use GitHub Desktop any more.
