### ISSUE TITLE
git: 'remote-https' is not a git command. See 'git --help'. error when push any file

### ISSUE THREAD

**Issue by MohamedHammad2020** [desktop/desktop#9390]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
Thanks for the report @MohamedHammad2020. It would be helpful if you could fill out the issue template and upload a log file from GitHub Desktop. Based on the error message you shared it sounds like there is an issue with our installation of GitHub Desktop. You can try reinstalling by following these steps:

- Close GitHub Desktop
- Open File Explorer
- Go to %LocalAppData% and delete the GitHubDesktop directory
- Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps.

**Comment by tierninho** [comment]
@MohamedHammad2020  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by mehbooburrehman** [comment]
I tried many possible solution but no luck yet ... nothing  works for me ...still same issue
