### ISSUE TITLE
Add a proper light version

### ISSUE THREAD

**Issue by dvorapa** [desktop/desktop#9393]
### Describe the feature or problem you’d like to solve

There are currently two themes: dark and "light". But light theme has got the whole upper part dark. It is not light, it is semi-.

### Proposed solution

After new themes support, this should be the next step. Add a proper light theme. I have to use dark theme even if I don't like dark themes, because the current "light" theme is not light at all.

**Comment by billygriffin** [comment]
Hi @dvorapa, thanks for the feedback. We don't have any plans to change the default theme of Desktop as it's generally quite well received and is roughly consistent with the feel of GitHub.com the website. Thanks again.

**Comment by dvorapa** [comment]
That would be awesome! Is there some plan to make the colors and design match GitHub.com website better? I miss the typical black, white and gray scheme in Desktop app. The ugly black, ugly white, missing gray, not matching font style, all of it is pretty eye-striking :/ so one has to use dark themes even if one does not like dark themes.

I remember that great design and feel of early versions of GitHub Desktop when the project was just new. These were nice looking and pretty "ergonomic".
