### ISSUE TITLE
Show history of a specific file

### ISSUE THREAD

**Issue by cpetry** [desktop/desktop#9394]
### Describe the feature or problem you’d like to solve

I would like to select a file in a tree view of the repository, right click on it and select a "view file history"

### Proposed solution

I like seeing how the file progressed and when it was changed and how.

### Additional context
Tortoise git can do this but a bit 'overloaded':
![grafik](https://user-images.githubusercontent.com/3867700/77820168-82f06800-70e0-11ea-8436-5e80b1fe9907.png)

**Comment by Rexogamer** [comment]
Hey! I personally agree that this would be a good idea, but this appears to be a dupe of #3754.

**Comment by cpetry** [comment]
Argh I'm sorry!
Didn't find the other one.

**Comment by steveward** [comment]
Closing in favor of #3754.

**Comment by pratimakulkarni** [comment]
We require this feature, now we cannot understand who changed the file, what was changed in last commit. Very important feature
