### ISSUE TITLE
Desktop not compiling if directory path contains a space

### ISSUE THREAD

**Issue by ruggi99** [desktop/desktop#9396]
### Describe the bug

If path of Desktop repo contains a space, then Desktop is not compiled, returning an error.

### Version & OS

Github Desktop: development branch, OS: Windows 10

### Steps to reproduce the behavior

1. Compile Desktop with `yarn build:dev`

### Expected behavior

Compiling without error.

### Actual behavior

Generates an error (image below) during compile.

### Screenshots

![Cattura](https://user-images.githubusercontent.com/25064808/77831889-26b63400-7132-11ea-9283-146abb9d1289.PNG)

### Additional context

If path doesn't contain spaces (in my case) it compiles correctly.
If the error isn't repairable, I suggest to add a note in "docs/contributing/setup.md".
Or add the same note into troubleshooting section.

**Comment by rafeca** [comment]
Thanks for the report! I've been able to reproduce the issue on my Window 10 VM

**Comment by ruggi99** [comment]
How will this issue be fixed?

**Comment by rafeca** [comment]
@ruggi99 I'm doing some quick investigation since the error comes from `electron-packager`: I'm checking whether this is something that we can fix in Desktop or it's a bug on `electron-packager`. I'll give more details soon.

**Comment by rafeca** [comment]
@ruggi99 looks like this is a known problem with `electron-packager` (see https://github.com/electron/electron-packager/issues/1120).

The issue got fixed a few days ago by https://github.com/electron/electron-packager/pull/1139, once a new version gets published with the fix we'll upgrade to it.

**Comment by ruggi99** [comment]
@rafeca thank you for investigating this issue.

**Comment by ruggi99** [comment]
@rafeca how about opening a PR to update only the cross-zip dependency and close this issue? I know it's not the best practice to edit the `yarn.lock` file, but I think it won't break anything.

**Comment by rafeca** [comment]
Sounds good to me as a temporary fix, so feel free to send the PR!

Note that `electron-packager` is moving away from `cross-zip` to `extract-zip` (see https://github.com/electron/electron-packager/pull/1139), but either way upgrading `cross-zip` to v3.1.0 should be fine now.
