### ISSUE TITLE
In clone repository window there are no team repositories only mine (under "Your's repositories")

### ISSUE THREAD

**Issue by skakunm** [desktop/desktop#9397]
### Describe the bug

On Windows GItHub Desktop app when I click clone repository, in the Windows app version I can see one list named "Your's repositories" and bellow it there is a team repository name and bellow it team repositories are listed. On the other hand on the Ubuntu 16.04 Github Desktop app there are only my repositories and no team repositories. Even when I manually copy the url to the URL section it can't authenticate. After that I manually cloned the repository in terminal using the same username and password and it worked.

### Version & OS

I have GitHub Desktop Version 2.4.0-linux1
and Ubuntu 16.04

### Steps to reproduce the behavior

1. Install the app
2. Open the app
3. Click "Clone a repository from the Internet..."
4. Scroll down -> there is no repository
5. Copy repository from the web
6. Click URL tab in the Clone a repository window
7. Paste the URL and click Clone
8. Type adequate username and password

**Comment by billygriffin** [comment]
Thanks for the issue @skakunm. Unfortunately we do not yet provide official support for Linux so I'm going to close this issue. You're welcome to create an issue in the fork here: https://github.com/shiftkey/desktop
