### ISSUE TITLE
RangeError when refreshing repository

### ISSUE THREAD

**Issue by longjohnnicholas** [desktop/desktop#9400]
### Describe the bug

Github desktop quit while refreshing a repo before a commit. Now whenever I restart and try to do the same, Github Desktop quits and I get the message:

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 2147483647. Received 3699669357
    at Function.concat (buffer.js:449:5)
    at ChildProcess.<anonymous> (file:///app/renderer.js:12:62771)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)

Version: 2.4.0
OS: Mac OS 10.15.3

### Version & OS

Version: 2.4.0
OS: Mac OS 10.15.3

### Steps to reproduce the behavior

Open GitHub. That's it - it tries to refresh in the background, CPUs run at about 50% and then after a minute it quits and I get the error message.

### Expected behavior

Successfully refreshes repo, was working until just now.

### Actual behavior

Above

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

The error message I receive:

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 2147483647. Received 3699669357
    at Function.concat (buffer.js:449:5)
    at ChildProcess.<anonymous> (file:///app/renderer.js:12:62771)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)

Version: 2.4.0
OS: Mac OS 10.15.3

**Comment by billygriffin** [comment]
Hi @longjohnnicholas, thanks for the report and sorry for the difficulty you're having. Is this happening persistently or just once and things are working normally upon restarting the app? Additionally, would you mind sharing your log file from the day this occurred? You can find that in `Help` -> `Show Logs in Finder`. Thank you!

**Comment by longjohnnicholas** [comment]
Hi - yes log file attached. It was happening repeatedly. I removed the repo and cloned it again and it now works, I wasn’t able to resolve the issue. It would still be helpful to know suggestions for fixes in case this crops up in the future.

Thanks,

-Nick

**Comment by billygriffin** [comment]
Hi @longjohnnicholas, thanks so much and glad it's working now. Unfortunately we didn't get your log file attachment. Do you mind uploading it using the web interface? That might help us try to figure out what might be causing it, and hopefully help prevent it for you and others in the future. Thanks!

**Comment by tierninho** [comment]
@longjohnnicholas  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. 

PS. I believe this has to do with untracked files that we can list from Node in ~10MB~ 20MB of process output. Ref: https://github.com/desktop/desktop/issues/2449#issuecomment-399564447 Thank you.
