### ISSUE TITLE
Ability to search commits

### ISSUE THREAD

**Issue by michael-coffey** [desktop/desktop#9413]
### Describe the feature or problem you’d like to solve

Add ability to search and filter commits

### Proposed solution

Our company has multiple people working in solutions, including an always building machine.  it would be great if i could filter commits by a search, by person, by date, etc.

**Comment by tierninho** [comment]
@michael-coffey Thanks for the suggestion. We have a similar request [here](https://github.com/desktop/desktop/issues/7022), so please follow along for any updates.
