### ISSUE TITLE
Cannot detect Typora editor on windows

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#9417]
### Describe the bug

GitHub Desktop cannot detect typora editor on my windows 10, when typora is installed on my machine

### Version & OS
GitHub Desktop: v2.4.0
OS: Windows 10 1903
Typora: 0.9.86

### Steps to reproduce the behavior

1. Install latest Typora
1. Open Options - Integrations in GitHub Desktop
2. Select external editor

### Expected behavior

Typora listed in External editor

### Actual behavior

There is no Typora in the list

### Screenshots

![image](https://user-images.githubusercontent.com/5396286/77982954-3acf8080-7340-11ea-8aba-984181e41481.png)

**Comment by rafeca** [comment]
Thanks @TerryChan for reporting the issue and sending a PR!
