### ISSUE TITLE
Trying to install CSM in virtual box but get the following error:  vagrant up ubuntu-19.04

### ISSUE THREAD

**Issue by k2whiteout** [desktop/desktop#9422]
running the following  command gets errors:
_vagrant up ubuntu-19.04

  513 /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/providers/virtualbox/action/is_running.rb
  514 /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/commands/up/middleware/store_box_metadata.rb

[NOTE]
**You may have encountered a bug in the Ruby interpreter or extension libraries.**
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
CrashReporter or DiagnosticReports directory in bug reports.

My variables are:

My current set-up:
 
KKROYMAN-M-148X:csm-vagrant kennethkroymann$ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin16]
 
KKROYMAN-M-148X:csm-vagrant kennethkroymann$ which ruby
/usr/local/opt/ruby/bin/ruby
 
KKROYMAN-M-148X:csm-vagrant kennethkroymann$ vagrant version
Installed Version: 2.2.7
Latest Version: 2.2.7
 
 
KKROYMAN-M-148X:csm-vagrant kennethkroymann$ which vagrant
/usr/local/bin/vagrant

**Comment by billygriffin** [comment]
Hi @k2whiteout, this is the repo for GitHub Desktop. Are you having an issue related to the app, or is this something different?
