### ISSUE TITLE
[Tracking issue] Add, push, and view Git tags in Desktop

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#9424]
Allow a desktop user to:
* create a new git tag
* push tags to remote(s)
* view tags on commits

_more info to come_

original reported issue: https://github.com/desktop/desktop/issues/4829

**Comment by Mishzs** [comment]
تعال ايمو ي عيني

**Comment by billygriffin** [comment]
I think we can close this now that it's all shipped to beta! 🎉
