### ISSUE TITLE
Auto fetch origin

### ISSUE THREAD

**Issue by Lukensteine** [desktop/desktop#9433]
### Describe the feature or problem you’d like to solve
I'd like to create an option for auto fetch origin
A clear and concise description of what the feature or problem is.
The problem is that there's no automatic fetch origin so it gets to conflicts between origin and local.
### Proposed solution
Just add an option to make auto fetch regular
How will it benefit Desktop and its users?
In case the user forgets to fetch the app will automatically do it
### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@Lukensteine thanks for contributing! GitHub Desktop does automatically fetch changes in the background -- there's an [open issue](https://github.com/desktop/desktop/issues/1128) that has discussion around toggling this feature. I'm going to close this issue out, but let me know if I am misunderstanding your feature request.

**Comment by chrisropherbutler19892020** [comment]
I just want my husband in my life please missing him so much I need him please 
--
Sent from myMail for Android Wednesday, 01 April 2020, 11:52AM -04:00 from Steve Ward  notifications@github.com :
