### ISSUE TITLE
Cannot make commits or publish branches due to authentication error

### ISSUE THREAD

**Issue by srishti-krishnan** [desktop/desktop#9441]
### Describe the bug

Installing Github Desktop on my main laptop and trying to push changes to branches, or publish new branches results in the Authentication failed modal.

This only occurs on one of my laptops. On the other laptop I am able to use Github Desktop using the same credentials without issue.

### Version & OS

Github Desktop version 2.4.0
Windows 10 (1909, 18363.752)

### Steps to reproduce the behavior

**Authentication failed modal appears before new repo is created via Github Desktop**
1. Install Github Desktop
2. Log into Github Desktop
3. Create a tutorial repo or a new repo
4. Check published repos on https://github.com

**Authentication failed modal appears when publish branch button is pressed**
1. Commit .txt file to master
2. Click on Publish branch button in Github Desktop

**Authentication failed modal appears when new branch is published**
1. Create new branch
2. Commit .txt file to newly-created branch
3. Merge branch with master and publish master

### Expected behavior

Authentication failed modal will not appear at all. All activities will be carried out as normal.

### Actual behavior

-When creating a new tutorial repo via Github Desktop, the Authentication failed modal appears, but the repo gets published to https://github.com
-When creating a non-tutorial repo via Github Desktop, he Authentication failed modal appears, and the repo **does not get** published to https://github.com
-Every time the Publish branch button is pressed, the Authentication failed modal appears.

### Screenshots

![Authentication_failed_error](https://user-images.githubusercontent.com/61638793/78306620-d8c67500-7511-11ea-8163-3f32b754a820.PNG)

### Logs

[2020-04-02.desktop.production.log](https://github.com/desktop/desktop/files/4424109/2020-04-02.desktop.production.log)

### Additional context

-I can only reproduce this issue on my main laptop. I am able to use the Github Desktop app normally on my secondary laptop.
-I only installed the Github Desktop app yesterday on my main laptop, and today on my secondary laptop.
-I do not use 2FA on Github

Things I have tried doing to solve the issue:
-Uninstalling and reinstalling
-Signing out and signing back in on both https://github.com and through Options > Accounts on Github Desktop
-Removing Github entries from %Appdata% and %Local%
-Removing Github-related credentials from Control Panel > Credential Manager
-Using the command line. Results in a 403 error every time I try to make changes
-Revoking Github Desktop from Authorized OAuth Apps and reinstating it
-Deleting any Personal access tokens from Developer Settings

**Comment by tierninho** [comment]
@srishti-krishnan Thank you for the detailed issue and apologies for trouble. 

Some questions that will help us pinpoint your issue:
- Do you have any antivirus software or firewalls? Are you using a proxy server by chance?
- Are you authenticating the same way on the working laptop? i.e, HTTPS vs SSH
- When you removed the entries from from `%Appdata%` and `%Local%`, did you download a fresh copy of Desktop? I added steps below for this.
- Another cause could be registry entries. Could you walk through the ["Authentication errors due to modified registry entries"](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#authentication-errors-due-to-modified-registry-entries) section of our known issues document to see if that could possible be causing this error on your machine?

Steps:
> If none of these potential causes are present on your machine, try performing a fresh installation of GitHub Desktop to see if that gets things working again. Here are the steps you can take to do that:
>- Close GitHub Desktop
>- Delete the `%AppData%\GitHub Desktop\` directory
>- Delete the `%LocalAppData%\GitHubDesktop\` directory
>- Reinstall GitHub Desktop from desktop.github.com

**Comment by srishti-krishnan** [comment]
> Do you have any antivirus software or firewalls? Are you using a proxy server by chance?

No to both questions.

> Are you authenticating the same way on the working laptop? i.e, HTTPS vs SSH

Not sure. I've always authenticated by logging in with my username and password. 

> When you removed the entries from from `%Appdata%` and `%Local%`, did you download a fresh copy of Desktop? I added steps below for this.

Yes. Whenever I tried this, I deleted %AppData%\GitHub Desktop\ and %LocalAppData%\GitHubDesktop\ from my main laptop before uninstalling and then reinstalling Github Desktop.

>     Another cause could be registry entries. Could you walk through the ["Authentication errors due to modified registry entries"](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#authentication-errors-due-to-modified-registry-entries) section of our known issues document to see if that could possible be causing this error on your machine?

- HKEY_CURRENT_USER\Software\Microsoft\Command Processor\
Found an Autorun entry and deleted it. **This is the solution.** Wish I had found it earlier. Thanks. Now I'm able to use Github Desktop normally on my main laptop. Not seeing the Authentication failed modal at all.

- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\
Did not find any Autorun entry here

**Comment by tierninho** [comment]
@srishti-krishnan Great to hear! Glad we could help. Feel free to reach out with anything else you need and thanks for using Desktop!
