### ISSUE TITLE
代码冲突提供desktop 代码一对一对比

### ISSUE THREAD

**Issue by manxihuanchi** [desktop/desktop#9442]
> Title: Code conflicts provide one-to-one comparison of desktop codes

希望desktop , 在代码产生冲突的时候， 可以提供左右视图， 来发现那些是冲突的地方， 这样会更加的直观解决冲突， 而不是在一个页面中查看

> I hope that desktop, when conflicts occur in the code, can provide left and right views to find those conflicts. This will resolve conflicts more intuitively, instead of viewing them on a page.

**Comment by tierninho** [comment]
@manxihuanchi Thanks for the suggestion. I assume you are talking about some sort of side-by-side diff view to resolve any conflicts. We have an issue for that here https://github.com/desktop/desktop/issues/172 by it is not on our roadmap yet. 

If there are any merge conflicts you need help or if your'e request was misinterpreted please reach out. 
谢谢
