### ISSUE TITLE
Will it support Linux Releases?

### ISSUE THREAD

**Issue by hmsjy2017** [desktop/desktop#9445]
More and more users are using Linux, so I think that it is necessary to support Linux system.

**Comment by steveward** [comment]
At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop helps maintain a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

Closing as a duplicate of https://github.com/desktop/desktop/issues/1525 -- you can follow along there for any updates about Linux support.
