### ISSUE TITLE
Fetch Origin fails with authentication error

### ISSUE THREAD

**Issue by dougbreaux** [desktop/desktop#9448]
### Describe the bug

Very similar, if not identical, to #7337 . I'm connected to an Enterprise instance (IBM), I have ssh-agent running with an appropriate (default) key added. Git Bash command-line works.

### Version & OS

Windows version 2.4.0. The problem has been occurring for at least the past year across multiple versions. I keep trying, hoping it will work. I have a colleague for whom it works fine.

### Steps to reproduce the behavior

1. Add local repository
2. Click on "Fetch origin"
3. See error

### Expected behavior

Successfully update from remote repo

### Actual behavior

Error dialog, no update

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/25640850/78376022-554d6800-7593-11ea-9d4d-048fea4baa0c.png)

### Logs

[2020-04-03.desktop.production.log](https://github.com/desktop/desktop/files/4428206/2020-04-03.desktop.production.log)

### Additional context

I do have multiple key files on my system, but the default one (`ssh-add` with no file specified) is the one loaded by ssh-agent in Git Bash. I also have PuTTY/Pageant installed and usually running, but even if I shut down Pageant, I get the same behavior. 

I've uninstalled & reinstalled GitHub Desktop, including deleting the local Roaming settings folder. The initial start asks for my login, redirects to web browser where our SSO has to be done, succeeds and shows the correct remote repos, but then gets this same error when I try to Fetch after adding a local repo that is connected to the remote.

**Comment by steveward** [comment]
@dougbreaux thanks for the detailed report. Just to clarify -- you have no issues using SSH in Git Bash? If so, try launching GitHub Desktop directly from Git Bash using the `github` command, and let me know if that gets things working for you.

**Comment by steveward** [comment]
@dougbreaux I'm glad to hear that worked -- we're tracking SSH issues in https://github.com/desktop/desktop/issues/2579 so I'm going to close this issue out.
