### ISSUE TITLE
Getting an "exit code 1 received" following a commit fail message

### ISSUE THREAD

**Issue by AnnieGlade4327** [desktop/desktop#9451]
Getting an "exit code 1 received" following a commit fail message when trying to commit to an existing repository through GitHub Slack.  I am a student and we are starting group assignments, and I thought this feature would be helpful if I could just get it to work.  I have no .git files to delete and I filled out everything, I read through the existing comments on this issue.  

![Screenshot (6)](https://user-images.githubusercontent.com/58996371/78418674-bad53f00-75fb-11ea-9d53-edc2e95fb7a5.png)
![Screenshot (7)](https://user-images.githubusercontent.com/58996371/78418680-c0cb2000-75fb-11ea-92ec-b4f914ab97cd.png)
![Screenshot (8)](https://user-images.githubusercontent.com/58996371/78418681-c45ea700-75fb-11ea-85b0-c482ead99306.png)
![Screenshot (9)](https://user-images.githubusercontent.com/58996371/78418683-caed1e80-75fb-11ea-8380-1b5a482620d3.png)
![Screenshot (10)](https://user-images.githubusercontent.com/58996371/78418684-ccb6e200-75fb-11ea-8745-57bf90d7dc03.png)

### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the report @AnnieGlade4327. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by tierninho** [comment]
@AnnieGlade4327  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
