### ISSUE TITLE
Add support for JetBrains IDEs

### ISSUE THREAD

**Issue by van800** [desktop/desktop#9453]
There are multiple problems with current approach:

1. Each of ~15 JetBrains IDEs has to be manually added to ExternalEditor enum.
2. For Windows each new version of each JetBrains IDE requires listing its specific reg key in the list
https://github.com/desktop/desktop/blob/4c68dbc943d3c118a4ec6db883f1fb2f52314a17/app/src/lib/editors/win32.ts#L384
3. For Windows only HKEY_LOCAL_MACHINE installations are detected. HKEY_CURRENT_USER are not.
4. JetBrains Toolbox installations are not detected at all.
More details about detecting Toolbox installations https://github.com/JetBrains/resharper-unity/blob/net201/unity/EditorPlugin/RiderPathLocator.cs

related to https://github.com/desktop/desktop/issues/9365, https://github.com/desktop/desktop/issues/6077, https://github.com/desktop/desktop/issues/7195, https://github.com/desktop/desktop/issues/7065

**Comment by steveward** [comment]
Request for IntellijIDEA in #9853.

**Comment by steveward** [comment]
Requested again in #10101.

**Comment by steveward** [comment]
From #11379:

>Nearly the whole family of JetBrains IDE flavors seems to be supported for integration/as editor - except CLion.
Is there a specific reason fro not supporting C/C++ IDE from JetBrains?

**Comment by Cool-Katt** [comment]
Hi there,
Tried adding support for IntelliJ IDEA & IDEA Community edition in #12566. Waiting for approval to run workflows however and a review.

**Comment by AmdrewAEddy** [comment]
> There are multiple problems with current approach:
> 
> 
> 
> 1. Each of ~15 JetBrains IDEs has to be manually added to ExternalEditor enum.
> 
> 2. For Windows each new version of each JetBrains IDE requires listing its specific reg key in the list
> 
> https://github.com/desktop/desktop/blob/4c68dbc943d3c118a4ec6db883f1fb2f52314a17/app/src/lib/editors/win32.ts#L384
> 
> 3. For Windows only HKEY_LOCAL_MACHINE installations are detected. HKEY_CURRENT_USER are not.
> 
> 4. JetBrains Toolbox installations are not detected at all.
> 
> More details about detecting Toolbox installations https://github.com/JetBrains/resharper-unity/blob/net201/unity/EditorPlugin/RiderPathLocator.cs
> 
> 
> 
- [ ] > related to https://github.com/desktop/desktop/issues/9365, https://github.com/desktop/desktop/issues/6077, https://github.com/desktop/desktop/issues/7195, https://github.com/desktop/desktop/issues/7065
>

**Comment by steveward** [comment]
Adding for tracking: In https://github.com/desktop/desktop/issues/12661 it was reported that we're referencing the 32-bit versions of PHPStorm instead of the 64-bit version.

**Comment by callumgarven** [comment]
For whoever picks this up, a repository I found which implements a phpstorm:// URI protocol has some quite interesting code for detecting JetBrains IDEs, see permalink below:

https://github.com/aik099/PhpStormProtocol/blob/ed849d80ab925a787b9c547191698c3d206f5c35/PhpStorm%20Protocol%20(Win)/run_editor.js

Around L66 onwards.

Could be useful for reference.

**Comment by niik** [comment]
I believe this can be considered fixed as of https://github.com/desktop/desktop/pull/12778. I'm going to close this but feel free to comment if you think there are missing pieces even after #12778 and we'll reopen.
