### ISSUE TITLE
changing the filename capitalization is not being registered as a local change.

### ISSUE THREAD

**Issue by spiraloid** [desktop/desktop#9455]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@spiraloid thanks for the report. If you want to rename a file and have Git track the change (on a case insensitive filesystem) then you will want to run the following command:

`git mv <old_name> <new_name>`

This will be tracked as a rename when you change the case of the file.

There is some good explanation in https://github.com/desktop/desktop/issues/2672 if you are interested in reading more about how Git handles case changes.
