### ISSUE TITLE
Wifi connection

### ISSUE THREAD

**Issue by rexhunt343** [desktop/desktop#9457]
>  "administrator"_+ "hostnames"
="True/false":// 

>  #``decice` `

**Comment by mishry** [comment]
في أحد، ٥ أبريل، ٢٠٢٠ في ٥:٣٤ م، كتب rexhunt343 <notifications@github.com>:

**Comment by mishz** [comment]
https://github.com/desktop/desktop/issues/9457#issue-594486389
