### ISSUE TITLE
error

### ISSUE THREAD

**Issue by StellaMoral77** [desktop/desktop#9458]
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'stell@DESKTOP-H8IKTCU.(none)')

**Comment by steveward** [comment]
Thanks for contributing @StellaMoral77. It looks like your name and email may not be properly set in your .gitconfig file. This is easy to fix.

1. Open GitHub Desktop and go to `File` > `Options` > `Git`
2. Enter your name and email -- make sure the email address matches an email address associated with your currently logged in GitHub account

That should get things working. Let me know if you have any further issues.
