### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by Kattnienika** [desktop/desktop#9464]
Hello,

I would like to translate the application into Czech. How can I do this?

Thank you :)

**Comment by billygriffin** [comment]
Hi @Kattnienika, we've started to discuss what internationalization might look like, but unfortunately we don't have the bandwidth to be able to work on that at this time, so localizing in different languages won't be possible until we're able to do that underlying work. Unfortunately the vast majority of the copy in the app is in-line and therefore not easily portable to a different language without a significant amount of restructuring work to make that possible. Thanks so much for your willingness to help translate ❤️, and I apologize it's not something we can support currently.
