### ISSUE TITLE
Publishing a private repository then making it public doesn't refresh the lock icon upon fetching

### ISSUE THREAD

**Issue by justingolden21** [desktop/desktop#9471]
### Description

Publishing a private repository then making it public doesn't refresh the lock icon upon fetching

### Version & OS

GitHub Desktop Version 2.4.0

Windows 10

### Steps to reproduce the behavior

1. Make a new repository with GitHub Deskop (marked as private)

2. Publish repositry

3. Hit ctrl+shift+G and go to Github Page (or any other way) and go to repository settings

4. Make the repository public and confirm

5. Go to GitHub Desktop and fetch

### Expected behavior

The lock icon adjacent to the repository name under "Current repository" on the top left should be unlocked

### Actual behavior

The lock icon is still locked

### Screenshots

![image](https://user-images.githubusercontent.com/30274440/78746757-8d023a00-791c-11ea-872a-4816dbf5a403.png)

### Logs

N/A

### Additional context

Not sure if this is the same as [this issue](https://github.com/desktop/desktop/issues/7915) or not.

**Comment by tierninho** [comment]
@justingolden21 Thanks for the issue. Try switching repos and coming back to the renamed repo. We grab changes like these at the repo level, and not in a fetch. Have a good day.
