### ISSUE TITLE
origin -> fork -> local, impossible to update the fork (and local) with origin

### ISSUE THREAD

**Issue by Neustradamus** [desktop/desktop#9473]
There is a problem, impossible to have in the fork the up-to-date code from origin:
- origin (2020-04-08) -> fork (done: 2020-04-07) -> local (2020-04-07)

Impossible to have the code from 2020-04-08 in fork and local.

How to solve it in GitHub Desktop?

---
Template 👇 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Hi @Neustradamus, I'm not sure I understand the issue from your description. We have a [template for bug reports](https://github.com/desktop/desktop/issues/new?template=bug_report.md) that would be helpful if you'd fill out (either by editing your post here, or closing this issue and opening a new one) for us to diagnose this with a better understanding. Thanks!

**Comment by bush2769** [comment]
No problems, i understand your issues a little better now, I'm very
possibly starting something that  has a lot of relevance to me,  but
unfortunately not knowledgeable enough to know the interest  its  raised
with a few people, its been an hassle for me  a long time, so I'll head in
the direction I'm told  and see what comes of it, cheers  mate!

**Comment by tierninho** [comment]
I believe you are looking to sync a fork of a repository to keep it up-to-date with the upstream repository. See this guide here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork 

Happy to help further when the template in the above comment is filled out. Thanks!

**Comment by steveward** [comment]
@Neustradamus if you select the branch list in GitHub Desktop you will see branches that look like `upstream/<branch_name>`. You can use the `Merge into current branch` or the `History` > `Select branch to compare` option to select an `upstream` branch to merge into your currently checked-out branch. And to clarify one thing -- the `origin` remote is your repository (the fork) and the `upstream` remote is the 'parent' repository of your fork. Let me know if you have any other questions about this.

**Comment by Neustradamus** [comment]
@steveward: Thanks for your reply!
It is possible to add directly in the Branch menu in more current possibility?
Only one click: "Merge into current branch... -> upstream/master" ?
