### ISSUE TITLE
GitHub Desktop does not detect GitHub Atom on Windows x64

### ISSUE THREAD

**Issue by Neustradamus** [desktop/desktop#9475]
GitHub Desktop does not detect GitHub Atom on Windows x64, please solve it.

**Comment by steveward** [comment]
Could you open up a command prompt (cmd.exe) and run the following commands for me?

`cd %LOCALAPPDATA%\Atom\`
`atom --squirrel-updated`

Then try restarting GitHub Desktop and let me know if you still do not see Atom in the dropdown menu.

**Comment by Neustradamus** [comment]
@steveward: Can you solve this problem in the installer?

**Comment by msphn** [comment]
This didn't work for me.
