### ISSUE TITLE
Installation problem: Not possibility to choice the folder

### ISSUE THREAD

**Issue by Neustradamus** [desktop/desktop#9476]
Installation problem: Not possibility to choice the folder

**Comment by steveward** [comment]
Thanks for the feedback @Neustradamus. Currently it is not possible to customize the installation location of GitHub Desktop. This is a constraint in the installation framework we use, Squirrel.Windows (see https://github.com/Squirrel/Squirrel.Windows#314). This is something we are tracking in https://github.com/desktop/desktop/issues/9476 so you can follow along there for updates about this.

**Comment by Neustradamus** [comment]
@steveward: Thanks, can you change your link, it is not liked to the ticket.

Note that the ticket is closed in Squirrel, you must to see with team for change, a lot of software have this problem.
