### ISSUE TITLE
A lot of not detected editors by Desktop

### ISSUE THREAD

**Issue by Neustradamus** [desktop/desktop#9477]
Several editors are not detected by Desktop on Windows (a lot are not only for Windows)

Can you add the support?

- Atom

- http://www.crimsoneditor.com/

- http://www.editpadlite.com/

- http://www.pspad.com/

- http://www.flos-freeware.ch/notepad2.html

- http://jsimlo.sk/notepad/

- https://www.gammadyne.com/docpad.htm

- http://atpad.sourceforge.net/

- https://www.notetab.com/notetab-light.php

- https://www.outertech.com/en/replacement-for-notepad

- https://www.gnu.org/software/emacs/

- http://www.jedit.org/

- https://www.geany.org/

- http://lighttable.com/

- https://wiki.gnome.org/Apps/Gedit

- https://kate-editor.org/

- http://brackets.io/

- http://bluefish.openoffice.nl/

**Comment by steveward** [comment]
Thanks for contributing @Neustradamus. At this time GitHub Desktop only supports editors that have been specifically integrated into the application. You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

We happily accept pull requests to integrate new editors. There is also a [tracking issue](https://github.com/desktop/desktop/issues/7033) where we are collecting feedback about better support for external editors. You can follow along there for updates about this.
