### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by rakshithkumarmr** [desktop/desktop#9478]
whenever aam cloning am getting error as git: 'clone' is not a git command. see 'git --help'.
how to solve this
![Screenshot (213)](https://user-images.githubusercontent.com/63314382/78784101-5b43ae80-79c2-11ea-82c1-093e46f391ce.png)

**Comment by steveward** [comment]
Thanks for the report @rakshithkumarmr.

Could you try performing a fresh installation of GitHub Desktop by following these steps?

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

That should get things working. Let me know if you run into any further issues.
