### ISSUE TITLE
Apply our source maps to exception stack traces before reporting them

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#948]
We currently report uncaught exceptions to [Haystack](https://haystack.githubapp.com/desktop?from=1mon&i=1d), but their stack traces are less than ideal. We should apply our source maps to the stack trace before we submit it to Central.

It looks like there are a number of packages out there that do this, e.g., https://www.npmjs.com/package/source-map-support.

**Comment by shiftkey** [comment]
Tentatively M5-ing this to see it it'll help make our error reporting more sane to parse.

**Comment by shiftkey** [comment]
Giving this @niik as I think he's got this wired up.

**Comment by niik** [comment]
Fixed in #1562
