### ISSUE TITLE
How can i upload more than 100files to git hub

### ISSUE THREAD

**Issue by Sagar-code-14** [desktop/desktop#9483]
### Describe the bug
How can i upload more than 100files to git hub

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by outofambit** [comment]
Hi and thanks for reaching out! We need more information to understand your issue. Please fill out the template above with all the information you can. Thanks!

If you have a general question about github, please see https://support.github.com/.

**Comment by tierninho** [comment]
In addition to the above request... should you have meant adding 100MB+ files to GitHub via Desktop: https://help.github.com/en/github/managing-large-files/working-with-large-files
