### ISSUE TITLE
Pushing Changes Not on Prod

### ISSUE THREAD

**Issue by blakelightstreet101** [desktop/desktop#9493]
Hello- I am pushing changes that don't appear to be showing up on our website. Interestingly, my coworkers can pull and see the changed files on their local repos. So the only issue is with production not showing changes. 

One of my other team members has had the same issue today.

Template 👇 

---

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Hi @blakelightstreet101, would you mind editing your post to fill out the template to help us figure out what might be happening? Without additional details it's really hard to reproduce and diagnose. Thanks!

**Comment by tierninho** [comment]
@blakelightstreet101  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
