### ISSUE TITLE
Latest version 2.4 is not working on my system

### ISSUE THREAD

**Issue by amitsrivastava2020** [desktop/desktop#9497]
### Black screen is showing

When i am opening github desktop 2.4, it's showing a black screen. I have window 8 pro 64 bit. I have to uninstall the latest version & again reinstall the previous version 2.3 this version is working fine. but not the latest one 2.4

**Comment by steveward** [comment]
@amitsrivastava2020 thanks for the report. Can you try following [the steps here](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) to see if it gets things working on your machine?

**Comment by amitsrivastava2020** [comment]
How can I SET GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION variable?  What are the steps to set this variable?

**Comment by steveward** [comment]
@amitsrivastava2020 you can open up CMD.exe and run this command:

`set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1`

**Comment by steveward** [comment]
@amitsrivastava2020 I'm going to close this issue out due to inactivity. Hopefully my reply got things working for you -- let me know if you are still having any issues.

**Comment by amitsrivastava2020** [comment]
No, I am facing same issue black screen.

**Comment by steveward** [comment]
@amitsrivastava2020 try following these steps to reset GitHub Desktop:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

Let me know if that doesn't get things working for you.

**Comment by amitsrivastava2020** [comment]
Same problem arrised, I am unable to use this version, but previous version
is working, but this version automatically updated to the latest version,
so plz can you tell me how to disable automatic update for the older
version? So that I can use older version 2.3.
