### ISSUE TITLE
how to sign out in github desktop

### ISSUE THREAD

**Issue by moaxzam** [desktop/desktop#9501]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by kospl** [comment]
File - Options - Account - Sign out

**Comment by steveward** [comment]
@moaxzam what @kospl shared is correct (thanks @kospl). You can find a guide here with screenshots:

https://help.github.com/en/desktop/getting-started-with-github-desktop/authenticating-to-github

**Comment by kospl** [comment]
You are welcome, Mr. Ward.
By the way, link you shared have no mention of how to log out from GitHub Desktop.

**Comment by steveward** [comment]
@kospl it shows how to access the authentication pane where you can sign out, which is why I shared it.
