### ISSUE TITLE
Application flickers when open, doesn't seem to show controls

### ISSUE THREAD

**Issue by T4zzuu** [desktop/desktop#9502]
When opening the application, it flickers in a black and gray-blue. You can still click on all elements (exit, etc.) but they wont show. I have already reinstalled Github Desktop and cleared the "Github Desktop" directory in my appdata.

**Comment by steveward** [comment]
@T4zzuu thanks for the report. Can you try [disabling hardware acceleration](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) to see if that helps with this issue?

**Comment by tierninho** [comment]
@T4zzuu  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
