### ISSUE TITLE
Invalid Libary

### ISSUE THREAD

**Issue by llbuhler** [desktop/desktop#9503]
Hello,
   I have cloned the library, when I compile the example for a ESP32 after upload and reset I get the following error:
Invalid library found in \\db2\Audrino\libraries\libraries\Downloads: no headers files (.h) found in \\db2\Audrino\libraries\libraries\Downloads

**Comment by steveward** [comment]
@llbuhler this issue tracker is for GiHub Desktop. If you are having issues with a specific project that is hosted on GitHub I'd recommend opening an issue in that project's repository.
