### ISSUE TITLE
Discard changes dialog: moving between buttons with arrow keys

### ISSUE THREAD

**Issue by kospl** [desktop/desktop#9504]
### Describe the bug

When you right-click on selected file in changed files list, then select `Discard changes...`, dialog opens. You cannot move with keyboard buttons (`left arrow` or `right arrow`) between `Discard changes` and `Cancel` buttons.

### Version & OS

Version 2.4.0, Win10.

### Steps to reproduce the behavior

1. Go to `Changes` tab
2. Right-click on any file
3. Select `Discard changes...`
4. Press left arrow on keyboard (to move from `Cancel` to `Discard changes` button)
5. Press `Enter` key to confirm discarding changes.

### Expected behavior

On step 4 `Discard changes` button gets focused.
On step 5 dialog closes and file changes are getting discarded

### Actual behavior

On step 4 focus stays on `Cancel` button
On step 5 dialog closes as canceled

### Screenshots

![image](https://user-images.githubusercontent.com/26386660/79055010-4b41fe00-7c52-11ea-93c4-117c68359a93.png)

**Comment by billygriffin** [comment]
Hi @kospl, thanks for the issue. This is intended behavior and conforms with platform-specific expectations, as described here: https://github.com/desktop/desktop/blob/development/docs/technical/button-order.md

You can tab between buttons to focus there and select the button you want. Thanks again and sorry that it didn't meet your initial expectations!

**Comment by kospl** [comment]
@billygriffin this issue is not about ordering, but for **keyboard navigation** which is against any possible UI guidelines in any OS.

**Comment by billygriffin** [comment]
Hi @kospl, the doc I linked to shares how we approach not only button ordering but also the expectation of focus and the human interface guidelines for each platform. If you're suggesting that our approach goes against expected guidelines, would you mind linking to the ones you're referencing so we can revisit? We tried to make our approach adhere as closely to expectations as possible. Thanks!

**Comment by kospl** [comment]
@billygriffin 

> Arrow keys. The arrow keys move input focus among the controls within a group. Pressing the right arrow key moves input focus to the next control in tab order, whereas pressing the left arrow moves input focus to the previous control. Home, End, Up, and Down also have their expected behavior within a group. Users can't navigate out of a control group using arrow keys.

https://docs.microsoft.com/en-us/windows/win32/uxguide/inter-keyboard

This can be checked in Windows 10 file deletion dialogs, trash emptying dialog etc.
