### ISSUE TITLE
"Rebase will require force push" dialog window: Cancel button does not work

### ISSUE THREAD

**Issue by Neustradamus** [desktop/desktop#9507]
"Rebase will require force push" dialog window: Cancel button does not work
- https://i.ibb.co/LvTLDjx/github-desktop-rebase-will-require-force-push-cancel-does-not-work.png

**Comment by billygriffin** [comment]
@Neustradamus Thank you for the issue. Would you mind using our bug report issue template please and open a new issue? https://github.com/desktop/desktop/issues/new/choose

This is one of many issues you've opened recently and we always ask for you to use the template so we can better diagnose, so I'm going to close this issue until we get further information that will help us look into the problem with you further.

**Comment by tierninho** [comment]
Tested this and labeling it a bug. Both OSX and Windows do not work and user has no recourse except to close Desktop.

**Comment by Neustradamus** [comment]
@tierninho: Thanks to confirm me!

**Comment by Neustradamus** [comment]
@outofambit: Thanks for your job!
