### ISSUE TITLE
index.html isn't linking css files, images and other html files...

### ISSUE THREAD

**Issue by MilandeepSingh** [desktop/desktop#9508]
Linking isn't working at all
Be it CSS files, images or even other html pages, nothing is accessible

Kindly help![https://github.com/MilandeepSingh/Love-With-Baking-Items](url)

Template 👇 

---

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@MilandeepSingh Please fill out the above template so we have more information to help diagnose your issue. Thank you!

**Comment by tierninho** [comment]
@MilandeepSingh As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
