### ISSUE TITLE
Cannot fetch a 2-factor authentication repository

### ISSUE THREAD

**Issue by alexchandel** [desktop/desktop#9515]
### Describe the bug

GitHub Desktop cannot fetch a repository with 2-factor authentication from the hard drive.

### Version & OS

Version 2.4.0, macOS 10.14.6

### Steps to reproduce the behavior

1. From the command line, clone a private repository (that you have >= Maintain access to) from a GitHub organization that requires two-factor authentication.  Use an API key to authenticate the `git clone`.
2. Add the repository folder to GitHub Desktop
3. Click `Fetch origin` in GitHub Desktop

### Expected behavior

It should fetch.

### Actual behavior

The error popup: `The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.`

### Screenshots

![Screen Shot 2020-04-14](https://user-images.githubusercontent.com/637714/79247652-67a38d80-7e40-11ea-9123-790162b1f1f9.png)

Even WORSE, the error message doesn't say which remote failed, even though there are multiple remotes, and even though the log files make clear that GitHub Desktop doesn't just fetch `origin` even when you click `Fetch origin`:

### Logs

```
2020-04-14T16:03:43.245Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: example-repo - alexchandel (has token)
2020-04-14T16:03:44.790Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.519s)
2020-04-14T16:03:45.303Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/example-upstream-org/example-repo.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
```

### Additional context

Other repositories work fine in the app.  `git pull` from the terminal works fine for this repository.

**Comment by steveward** [comment]
@alexchandel are you logged in to your GitHub account in GitHub Desktop? GitHub Desktop won't use the personal access token you generated for authentication on the command line. You can check to see if you are authenticated by going to `GitHub Desktop` > `Preferences` > `Accounts`.

**Comment by steveward** [comment]
@alexchandel as we have not heard back from you I am going to close this issue out. Let me know if you are still having any problems.
