### ISSUE TITLE
Error Actualizando proyecto

### ISSUE THREAD

**Issue by jtorresnuvi** [desktop/desktop#9523]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by jtorresnuvi** [comment]
error: cannot spawn C:\Users\JTorres\AppData\Local\GitHubDesktop\app-2.4.1\resources\app\static\ask-pass-trampoline.bat: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by steveward** [comment]
Thanks for the report @jtorresnuvi. Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been the modified `Autorun` registry entry -- I would recommend checking that first. Let me know if you have any questions about the steps.

**Comment by steveward** [comment]
@jtorresnuvi I'm going to close this issue out -- let me know if you are still having any problems.
