### ISSUE TITLE
Add support for Git Flow

### ISSUE THREAD

**Issue by deviloper** [desktop/desktop#9526]
### Describe the feature or problem you’d like to solve

I'm developing software using the git flow approach.
At this moment I'm forced to use command line or SourceTree (by Atlassian) to manage branches.

### Proposed solution

- Add options to enable git flow in a repository and if enabled add git flow action buttons for main actions in branch menu (Feature, Release, Hotfix) and a button to finish a feature near the feature item.

### Additional context

Git flow start buttons:
![immagine](https://user-images.githubusercontent.com/5602328/79332490-33ea6580-7f1d-11ea-9dab-91f309e2e635.png)

Git flow finis button:
![immagine](https://user-images.githubusercontent.com/5602328/79332454-23d28600-7f1d-11ea-8fae-ffad8d71c258.png)

This would make easier to work with GitFlow

**Comment by billygriffin** [comment]
Hi @deviloper, thanks for the issue! This is under consideration in #2139, and something we haven't prioritized yet but may consider down the road. It's a very specific workflow that we would need to consider, and ensure we're not making the UX significantly poorer for those who don't use this workflow. Thanks again.
