### ISSUE TITLE
Getting the error while building a docker image # cd .; git clone https://github.com/pdevine/go-asciisprite /go/src/github.com/pdevine/go-asciisprite Cloning into '/go/src/github.com/pdevine/go-asciisprite'... fatal: unable to access 'https://github.com/pdevine/go-asciisprite/': SSL certificate problem: unable to get local issuer certificate package github.com/pdevine/go-asciisprite: exit status 128 The command '/bin/sh -c go get github.com/pdevine/go-asciisprite' returned a non-zero code: 1

### ISSUE THREAD

**Issue by Atif-byte** [desktop/desktop#9533]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by mishz** [comment]
https://github.com/desktop/desktop/issues/9533#issue-600808545
