### ISSUE TITLE
I use the GitHub desktop.

### ISSUE THREAD

**Issue by choigobin** [desktop/desktop#9534]
Full and all actions are possible for all projects, including private, without logging in. If you log out, you don't have the authority, but why is this possible? There's a security problem.

**Comment by mishz** [comment]
https://github.com/desktop/desktop/issues/9534#issue-600862185

**Comment by billygriffin** [comment]
Thanks for the issue. Since this doesn’t appear to be related to GitHub Desktop, I’m going to close it. If you have problems with GitHub.com, please check out https://support.github.com/
