### ISSUE TITLE
Easily switch between different GitHub accounts

### ISSUE THREAD

**Issue by Marius-Juston** [desktop/desktop#9536]
Hello,

I have multiple GitHub accounts, one for school (nonenterprise) and one for my own personal use. Whenever I want to try to change between accounts I need to sign out of my previous account and then sign in to my new one back and forth. 
I was wondering if it would be possible to make the switch easier, like have the program remembers the login credentials of the previously logged in users. You would see a list of currently logged in users and you would just be able to select that user to switch. Next to the user "card", you would also have a logout button so that you can log that user out.

Many thanks!

**Comment by steveward** [comment]
Thanks for the feedback @Marius-Juston. I'm going to drop this into https://github.com/desktop/desktop/issues/3707 where we are tracking this feature.
