### ISSUE TITLE
open in xcode does not open in xcode

### ISSUE THREAD

**Issue by okaykaylyn** [desktop/desktop#9546]
### Describe the bug

This bug is on the main screen.
After updating my preferences to open all projects in XCode, the button labeled 'Open My Project in XCode' stops working. I went back and changed my preferences to open in VScode, and then to Sublime text, and both those use-cases work as expected. It seems to only be a problem in xcode.

### Version & OS

Desktop version: Version 2.4.1
OS: Catalina 10.15.4
Xcode: Version 11.4 (11E146)

### Steps to reproduce the behavior

1. Go to the main screen on the app where it shows your local changes. Where it says 'Open the repository in your external editor', select xcode as your editor in Preferences. Save your changes.
2. Once back on the home screen, click the button 'Open in Xcode'

### Expected behavior

I expect my project to open in xcode.

### Actual behavior

Nothing happens. Xcode doesn't open. No error is displayed.

### Screenshots

n/a

### Logs

n/a, nothing relevant shows in logs.

### Additional context

It seems like this may be related to #9155, however I'm not seeing an error dialogue. I've moved github desktop from downloads to the applications folder, and the problem remains. I've also tried quitting and reopening github desktop.

**Comment by tierninho** [comment]
@okaykaylyn Thank you for the issue and apologies for the troubles.

Please confirm a few things, as they might help get you in a better state:
- Open Xcode and make it sure it doesn't ask you to update or accept any terms. You are 11.4 so you should be fine. 
- Open Xcode preferences and select Locations tab. Is the Command Line Tools field populated like so:
![Screen Shot 2020-04-16 at 2 27 17 PM](https://user-images.githubusercontent.com/14828183/79519061-6ca63f80-7fee-11ea-8cb5-a6419ff369f5.png)
- Where is Xcode located on your computer? I suggest the Applications folder.

I am on Xcode 11.2, OSX 10.15.4. (I am updating to 11.4 to make sure all is still working.)

**Comment by okaykaylyn** [comment]
@tierninho Thank you for your speedy reply!
I did have an xcode update, but before updating went to Preferences>Locations, and saw that the command line tools field wasn't populated as shown. I clicked on the field and it auto-populated. I went to github desktop, tried the button again, and voila! Totally works now.

I appreciate your help!

**Comment by fneeser** [comment]
I had the same problem (Xcode did not open). Going to Xcode Preferences > Locations and having Xcode auto-populate the (previously empty) command line tools field worked for me, too.
Thank you!

**Comment by jimmykh18** [comment]
Having the same issue. CommandLine Tools populate as "Xcode 14.3.1 (14E300c)". to working tho. Any suggestion?
