### ISSUE TITLE
Pack the code before pulldown if possible

### ISSUE THREAD

**Issue by serfend** [desktop/desktop#9548]
### Describe the feature or problem you’d like to solve

i dont know if is possible to pack the code object to .gz before pulldown for the reason that in the case of any repository having lot of files,its would be lead to net exceptions occur.

### Proposed solution

if just transfer a .gz.zip file and extract on local,may be it would be better on the situation of bad network.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for contributing @serfend. Git compresses files into packfiles using the zlib library. Take a look at this [section of _Pro Git_](https://www.git-scm.com/book/en/v2/Git-Internals-Packfiles) for some more information about how this works. I'm going to close this issue out -- thanks for using GitHub Desktop!
