### ISSUE TITLE
Not Able to delete branch from Desktop Github

### ISSUE THREAD

**Issue by asangvik** [desktop/desktop#9549]
### Describe the bug

I am unable to delete the branch that I have deleted already on Github.com. I am unable to delete the same branch on Github DESKTOP.

### Version & OS

I am using github Version 2.4.1 and My OS is Windows 20 with 64 bit OS

### Expected behavior

I was hoping the branch should have deleted in few seconds from Desktop after I pressed delete option.

### Actual behavior

After I pressed deleted, I can just see being deleted for couple of minutes. and If i close the app and start again it will still show the branch on Github Desktop 

### Screenshots
![Capture_GIT](https://user-images.githubusercontent.com/57007535/79589338-e09e2180-809a-11ea-9334-9b97f0656a84.PNG)

### Logs

[2020-04-17.desktop.production.log](https://github.com/desktop/desktop/files/4493938/2020-04-17.desktop.production.log)

### Additional context

As well as if I try to publish the branch instead of deleting . It is not even publishing it on Github.com

**Comment by billygriffin** [comment]
Hi @asangvik, thanks for the issue. You should be able to delete a non-default branch by selecting the branch, and then clicking "Delete" in the Branch menu. Let us know if that doesn't work. Thanks!

**Comment by asangvik** [comment]
I am still unable to delete it from Desktop Github. I have deleted it from Github.com but Desktop Github is behaving weird from 2 days. I am unable to delete it from DESKTOP GITHUB

**Comment by billygriffin** [comment]
Hi @asangvik, we need more information to dig into this further. I'm adding the bug report template to your original post - would you mind filling that out so that we can have enough information to try to reproduce and identify what might be happening?

**Comment by asangvik** [comment]
How can I fill that template? Where can I find it?

**Comment by steveward** [comment]
@asangvik can you open the repository in the command line (`Repository` -> Open in <command_line_application>) and run the following command for me?

`git fsck`

There are some errors in your log file that make me think there may be an underlying issue with your repository.

**Comment by tierninho** [comment]
@asangvik  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
