### ISSUE TITLE
Cannot publish branch from GitHub Desktop due to authentication failure

### ISSUE THREAD

**Issue by wxhawkins** [desktop/desktop#9552]
### Describe the bug

I have cloned one of my existing private repositories and made some changes to the files.  I successfully committed these changes; however, the app does not let me publish my changes. When I click publish, it asks me to enter my username and password, but when I do, it tells me it failed to authenticate. I know these credentials are correct as I can use the exact same credentials to sign into GitHub both in my web browser and the app. I have already tried signing out and back in -- same issue.

This issue appears identical to https://github.com/desktop/desktop/issues/5905 however, no solutions here fixed my problem.

### Version & OS
GitHub version 2.4.1

OS: Windows 10
Version	10.0.18363 Build 18363

### Steps to reproduce the behavior

1. Launch GitHub desktop
2. Select private repository
3. Click publish
4. Enter correct credentials

### Expected behavior

Upon entering my correct credentials, the changes to the repository should be published

### Actual behavior

Authentication fials

### Screenshots
![image](https://user-images.githubusercontent.com/37159866/79605582-cfaed980-80b5-11ea-8df1-c60bc923a726.png)

Add screenshots to help explain your problem, if applicable.

### Logs

[2020-04-17.desktop.production.log](https://github.com/desktop/desktop/files/4494800/2020-04-17.desktop.production.log)

**Comment by tierninho** [comment]
@wxhawkins Thanks for the issue and apologies for the troubles. 

Can you check to see if your registry has been modified by another application? See this section in our known issues doc for how to do that:

https://github.com/desktop/desktop/blob/development/docs/known-issues.md#authentication-errors-due-to-modified-registry-entries

Let us know how it goes.

**Comment by wxhawkins** [comment]
@tierninho 

Thank you for your quick reply.

I did find an AutoRun value in my Command processor folder.  However, deleting it did not resolve my problem. I also restarted my computer (no idea if that was necessary) but same issue.

**Comment by tierninho** [comment]
Thank you for the update. I noticed the URL you tried to clone was longer than the normal username/repo protocol, as it had `/RNA_seq.git` on the end.

Can you open the command line , `cd` to your repo and run `git remote -v`. The result should match what you paste into the clone repo field in Desktop. Something like this: `https://github.com/username/my-repo.git`. Similarly, you should be able to paste the result in your browser and see your repo (if logged in). 

When I paste your URL, including the `/RNA_seq.git`, I get a "not found" error.  I suggest trying the clone again in Desktop and remove the `/RNA_seq` part.

**Comment by wxhawkins** [comment]
@tierninho Re-cloning appears to have fixed it.  Thank you!
