### ISSUE TITLE
Can't clone private repository

### ISSUE THREAD

**Issue by BulashAS** [desktop/desktop#9556]
### Describe the bug
Can't clone private repository

### Version & OS
GitHub Desktop v.2.4.1 OS  Win10 1903

### Steps to reproduce the behavior
Open Github Desktop
Click 'File'
Click 'Clone repository'
Click on the repository
Click 'Clone'
After a few seconds, error pops up.

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/48426341/79630290-47ded300-817a-11ea-9824-88feafcee5b6.png)

### Logs

2020-04-18T06:37:50.487Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/BulashAS/Sphinx.git - BulashAS (has token)
2020-04-18T06:37:51.711Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/BulashAS/Sphinx.git C:\Android\Sphinx (took 1.131s)
2020-04-18T06:37:51.717Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/BulashAS/Sphinx.git C:\Android\Sphinx` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Android\Sphinx'...
"C:\Users\AT" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
���⥬� �� 㤠���� ���� 㪠����� ����.
error: unable to read askpass response from 'C:\Users\AT&S\AppData\Local\GitHubDesktop\app-2.4.1\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### Additional context

I reinstalled GitHub Desktop. 
Deleted AppData\Local\GitHubDesktop\ and AppData\Roaming\GitHubDesktop\
Find and delete all GitHubDesktop in windows registry
HKEY_CURRENT_USER\Software\Microsoft\Command Processor\ - no such section
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\autorun - no such section

**Comment by rafeca** [comment]
Hey @BulashAS ! Thanks for submitting the issue!

This is in fact a known issue (see https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789). Currently the workaround is to change your username to not contain strange characters.

I'm going to close this for now in favor of https://github.com/desktop/desktop/issues/7064 (even if it's closed we monitor references to it to assess whether it's worth putting resources into fixing it).
