### ISSUE TITLE
Username with parentheses wont allow cloning

### ISSUE THREAD

**Issue by robmarkoski** [desktop/desktop#9557]
### Describe the bug

Cant clone any repository as my username has a parentheses in it

### Version & OS

Version 2.4.1
Windows 10

### Steps to reproduce the behavior

1. Click clone.

### Expected behavior
Repository is cloned

### Actual behavior
Error message is shown.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

'C:\Users\Username' is not recognized as an internal or external command,
operable program or batch file.
error: unable to read askpass response from 'C:\Users\Username(Mine)\AppData\Local\GitHubDesktop\app-2.4.1\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by mishry** [comment]
في سبت، ١٨ أبريل، ٢٠٢٠ في ١١:٣٩ ص، كتب Rob M <notifications@github.com>:

**Comment by rafeca** [comment]
Hey @robmarkoski ! Thanks for submitting the issue!

This is in fact a known issue (see https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789). Currently the workaround is to change your username to not contain strange characters.

I'm going to close this for now in favor of https://github.com/desktop/desktop/issues/7064 (even if it's closed we monitor references to it to assess whether it's worth putting resources into fixing it).
