### ISSUE TITLE
LFS Progress Bars

### ISSUE THREAD

**Issue by garrynewman** [desktop/desktop#9560]
### Describe the feature or problem you’d like to solve

The user experience using LFS to upload and download multi-gb to LFS isn't great right now.

The screen shows "cloning" then "download 1/1 2343432243234/423243432234 <filename>". This text flickers around and is unreadable.

### Proposed solution

Some suggestions, any of these would be useful for both downloads and uploads.

* Friendly format amount of data downloaded
* Friendly format amount of data remaining
* Percentage complete
* Download speed
* Time passed, time remaining
* A cancel button

### Additional context

While traditionally git hasn't supported multi-gb repos, Upload and download speeds are great, I'm finding this the biggest barrier right now.

**Comment by rafeca** [comment]
Thanks for this suggestion @garrynewman !

We have an issue for to improve the progress indicator of LFS transfers: https://github.com/desktop/desktop/issues/3171 . Please feel free to add any additional context you have in that issue 😃
