### ISSUE TITLE
Add support for Notepad++ portable

### ISSUE THREAD

**Issue by Mishasama** [desktop/desktop#9561]
### Describe the bug
#9238 does not work with Notepad++ portable version.

### Version & OS
2.4.1
Windows 10 1809 [Version 10.0.17763.1098]

### Steps to reproduce the behavior
1. Go to 'File'
2. Click on 'Options...'
3. Click on 'Integrations'

### Expected behavior
Support editors by a custom path.

### Actual behavior
No editors found.

### Screenshots
![image](https://user-images.githubusercontent.com/54498172/79636729-be98c200-81b4-11ea-9ab0-fdbc85374ac0.png)
![image](https://user-images.githubusercontent.com/54498172/79636833-9f4e6480-81b5-11ea-9222-fad2540f6b73.png)

### Logs
[2020-04-18.desktop.production.log](https://github.com/desktop/desktop/files/4496575/2020-04-18.desktop.production.log)

### Additional context

Nothing here.

**Comment by say25** [comment]
Do you have a link to the portable version installation?

**Comment by Mishasama** [comment]
> Do you have a link to the portable version installation?

https://github.com/notepad-plus-plus/notepad-plus-plus/releases/

**Comment by rafeca** [comment]
Thanks for filing this @Mishasama ! @say25 do you know if we can easily detect portable apps on Windows?

**Comment by AndreiMaga** [comment]
@rafeca @say25 
```HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store``` should have it but except from that I don't think there is an easy way to get it.

**Comment by Mishasama** [comment]
@rafeca @AndreiMaga 
I recommend detecting the running process to match the signature and process name.

**Comment by say25** [comment]
Can't retitle this but this seems more like an enhancement. Title should be `Add Support for Portable Notepad++`

**Comment by sergiou87** [comment]
Please, try out the latest beta from https://desktop.github.com/beta which includes the changes from #18954 

It should help with this. Thank you for your patience!

**Comment by Mishasama** [comment]
> Please, try out the latest beta from https://desktop.github.com/beta which includes the changes from #18954
> 
> It should help with this. Thank you for your patience!

![スクリーンショット 2024-08-18 044605](https://github.com/user-attachments/assets/23f7c29f-721d-46b8-91d2-9a6d616fe7d5)
@sergiou87 
Still not working. Only the shell can be selected.

**Comment by sergiou87** [comment]
Oops! You ran into an edge case when no editors are found, I fixed it here: https://github.com/desktop/desktop/pull/19160

We will deploy another beta with this as soon as possible. Sorry and thanks for your patience 🙏
