### ISSUE TITLE
Save preference for opening comand line without Git

### ISSUE THREAD

**Issue by kolappannathan** [desktop/desktop#9564]
### Describe the feature or problem you’d like to solve

I have a project that I frequently use command line for. Every time I open windows terminal GitHub desktop throws the following popup asking if I want to open command line without Git,

![Annotation 2020-04-19 095435](https://user-images.githubusercontent.com/8157105/79679459-d196ab00-8223-11ea-81ae-1ba569500075.png)

I don't require Git for my command line tasks

### Proposed solution

An option "Don't ask me again" would be nice.

**Comment by rafeca** [comment]
Thanks for the suggestion @kolappannathan ! 

This indeed looks like a nice improvement, since having `git` should not be required to open the terminal.

What kind of tasks do you normally do from the command line?

**Comment by kolappannathan** [comment]
@rafeca Mainly for building Jekyll sites and running npm tools.
