### ISSUE TITLE
Connect over SSH to a Remote Box

### ISSUE THREAD

**Issue by Xtigyro** [desktop/desktop#9567]
### Describe the feature or problem you’d like to solve

It would be awesome if you could use GitHub Desktop even when your cloned or about to be cloned repos are on a remote machine (Linux boxes in most cases). Something like that: https://code.visualstudio.com/docs/remote/ssh

### Proposed solution

You'll be able to always use GitHub Desktop - no matter you deal with locally clone or remotely cloned repos (which is often the case).

**Comment by steveward** [comment]
Thanks for contributing @Xtigyro! This was brought up in https://github.com/desktop/desktop/issues/9181 -- please refer to my replies there for why we currently have no plans to support this in GitHub Desktop.
