### ISSUE TITLE
remote-https is not a command

### ISSUE THREAD

**Issue by runningCsnail** [desktop/desktop#9568]
### Describe the bug

I want to clone a repository  on GitHub Desktop, whether I clone from the GitHub.com or the URL, I get git: 'remote-https' is not a git command. See 'git --help'.

That`s why? How to solve it?

### Version & OS

Version 2.4.1
Windows 10

### Steps to reproduce the behavior

1. file
2. clone repository
3. select my repository and local path
4. click clone
5. See error

### Expected behavior

I expect to know the reason for the problem, more importantly I eager to clone my repository. 

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/39901127/79696825-9773ea80-82b1-11ea-931d-d8f37c219e4c.png)

### Logs

[2020-04-19.desktop.production.log](https://github.com/desktop/desktop/files/4499952/2020-04-19.desktop.production.log)

**Comment by runningCsnail** [comment]
I have reinstalled but the problem is not solved.

**Comment by steveward** [comment]
Thanks for the report @runningCsnail. Could you try performing a fresh installation of GitHub Desktop by following these steps?

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

**Comment by runningCsnail** [comment]
> Thanks for the report @runningCsnail. Could you try performing a fresh installation of GitHub Desktop by following these steps?
> 
> 1. Close GitHub Desktop
> 2. Open File Explorer
> 3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
> 4. Go to `%AppData%` and delete the `GitHub Desktop` directory
> 5. Reinstall GitHub Desktop from http://desktop.github.com

Thank you very much. That`s a good idea. I solved the problem. 

I don`t know where the %LocalAppData% and %AppData% so I search my  disk C and C:\Users\Username\AppData for  "Github Desktop", delete all the directories with GitHub Desktop in their name. Thank you.

**Comment by steveward** [comment]
I'm glad to hear that got things working for you!
