### ISSUE TITLE
Github won't launch after downloading it. 

### ISSUE THREAD

**Issue by Wix234** [desktop/desktop#9569]
I've downloaded Github for a university project and once the installer finished installing nothing happens. The app also doesn't open when I try to open it in the appdata folder.
I've looked up and tried a few solutions but none of the fix the issue for me. The things I tried are uninstall and reinstall with deleting the folders in appdata local (a folder in roaming doesn't always show up but when it does I delete it as well), deleting the most recent app folder in the github appdata folder. I've unplugged my second monitor since some people said the app opens ina random place on the screen that's hidden.
The only difference I had between all the solutions I found is that Github isn't in task manager for me while it was for all the solutions I looked up.

### Version & OS
The version of Github is 2.4.1 and I'm using window 10 and 64-bit.

### Steps to reproduce the behavior

1. Go to 'https://desktop.github.com/'
2. Click on githubdesktopsetup when installed
3. Wait for it install github
4. Nothing happens

**Comment by steveward** [comment]
Thanks for the report @Wix234. Could you see if there are any logs in the following locations and upload them?

`%AppData%\logs`
`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

**Comment by Wix234** [comment]
@steveward Nothing show up in those places the only thing one that shows up is %LocalAppData%\GitHubDesktop\app-2.4.1\SquirrelSetup.log. I attached that below
[SquirrelSetup.log](https://github.com/desktop/desktop/files/4505738/SquirrelSetup.log).
Also here is a screenshot of all the other squirrelsetup.log that show up in my appdata folder in case I should upload any of them.
![Screenshot (33)_LI](https://user-images.githubusercontent.com/61157446/79792534-fafc2780-8346-11ea-89e8-17981e8f3a37.jpg)

**Comment by steveward** [comment]
@Wix234 unfortunately the log file isn't showing much there. Are you running any security/antivirus software on this machine that could be blocking GitHub Desktop from launching?

**Comment by Wix234** [comment]
@steveward I uninstalled McAfee from my laptop (I didn't have a subscription with it but I never bothered to uninstall after it came with my laptop) and github finally installed and opened properly so I'm assuming that was the issue. Thank you for your help.

**Comment by steveward** [comment]
Closing this out as this was resolved.
