### ISSUE TITLE
Unable to pull requests

### ISSUE THREAD

**Issue by thilakbk** [desktop/desktop#9572]
### Describe the bug

Unable to pull requests after the recent update

### Version & OS

2.4.1

### Steps to reproduce the behavior

1. Go to any existing project.
2. Click on fetch or pull request

### Expected behavior

pull should work as expected

### Actual behavior

thorws error

error: waitpid for C:\Users\ac00470\AppData\Local\GitHubDesktop\app-2.4.1\resources\app\static\ask-pass-trampoline.bat failed: No child processes
error: unable to read askpass response from 'C:\Users\ac00470\AppData\Local\GitHubDesktop\app-2.4.1\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### Screenshots

![image](https://user-images.githubusercontent.com/59877238/79719469-43dabe80-82fc-11ea-81a0-3b9a0e534fab.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report. Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been the modified `Autorun` registry entry. 

Let me know if you have any questions.
