### ISSUE TITLE
Too much delay when I update a repository 2.4.1

### ISSUE THREAD

**Issue by sergioaraque** [desktop/desktop#9573]
After the last update, every time I upload or try to download a change from my repository it takes 5-7 minutes.
Is there any way to go back to an earlier version?
![imagen](https://user-images.githubusercontent.com/25924038/79723971-028be400-82e7-11ea-87a6-36cb6a2f4723.png)

**Comment by sergioaraque** [comment]
Ive got a problem with my antivirus

**Comment by steveward** [comment]
@sergioaraque often we see antivirus software cause performance related problems after we push out updates to GitHub Desktop -- what specific antivirus software are you running?

**Comment by sergioaraque** [comment]
He started to fail me with Avast. This antivirus had an update and the uploads took several minutes. It was solved by updating the antivirus again.
