### ISSUE TITLE
Atom is not being detected as an editor

### ISSUE THREAD

**Issue by gatomo-oficial** [desktop/desktop#9574]
### Describe the bug

Atom está instalado en el ordenador y GitHub Desktop no lo detecta como editor

### Version & OS

GitHub Desktop Version 2.4.1   SO. Windows 10 home

### Steps to reproduce the behavior

1. Ir a Configuración
2. Ir a Integración
3. Desplegar las opciones del editor de código

### Expected behavior

¿?

### Actual behavior

¿?

### Screenshots

No

### Logs

No

### Additional context

No

**Comment by tierninho** [comment]
@gatomo-oficial  Gracias por presentar este problema. Si no se detecta Atom, vaya a la línea de comandos e intente esto:

`cd %LOCALAPPDATA%\Atom\`
`atom --squirrel-updated`

Por favor, háganos saber el resultado.

**Comment by Neustradamus** [comment]
Yes there is a bug, I have already signaled but closed without a real solution.

**Comment by gatomo-oficial** [comment]
Gracias @tierninho lointentaré mañana. Si no funciona te aviso

**Comment by gatomo-oficial** [comment]
@tierninho Se ha resuelto el problema. Muchas gracias por la solución

**Comment by Neustradamus** [comment]
@gatomo-oficial: No it is not a real solution. you install on a new computer, the problem is always here. It is a temporary fix...

**Comment by gatomo-oficial** [comment]
@Neustradamus Lo sé, pero no me compraré un ordenador hasta que sea millonario. No está programado en algo que entienda, pero podrías arreglar el problema
