### ISSUE TITLE
Jayluv

### ISSUE THREAD

**Issue by Jayluv81** [desktop/desktop#9584]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by rafeca** [comment]
Hey @Jayluv81 ! we require issues to be filled with the relevant fields of the issue template. Closing this issue since it's empty.
