### ISSUE TITLE
Jayluv

### ISSUE THREAD

**Issue by Jayluv81** [desktop/desktop#9585]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by rafeca** [comment]
Hey @Jayluv81 ! we require issues to be filled with the relevant fields of the issue template. Closing this issue since it's empty.
