### ISSUE TITLE
there is no way to use github lfs i watched 10 tutorials just to download one thing and i cant 

### ISSUE THREAD

**Issue by djape11** [desktop/desktop#9586]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@djape11 thanks for contributing. GitHub Desktop has GitHub LFS built in, so working with Git LFS enabled repositories should not be an issue. Is there a specific problem you are having with getting Git LFS working? You will need to [configure your tracked files](https://help.github.com/en/github/managing-large-files/configuring-git-large-file-storage) by using the command line or editing your repository's .gitattributes file directly -- GitHub Desktop does not have built-in support for this.

**Comment by steveward** [comment]
@djape11 I'm going to close this issue out -- if you are having problems with GitHub Desktop please fill out the template with more information and update this issue with a reply.
