### ISSUE TITLE
git not working correctly

### ISSUE THREAD

**Issue by poojagoswami2** [desktop/desktop#9587]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
@poojagoswami2 Would you mind sharing additional details please about what is going wrong so we can try to understand better? This is the repository for the GitHub Desktop application, so if your question is about Git more generally, we won't be able to answer that but could point you to some guides if that would be helpful.
