### ISSUE TITLE
Unable to clone repositories from GitHub Deskptop

### ISSUE THREAD

**Issue by prateek-gupta-wawa** [desktop/desktop#9591]
### Describe the bug
Unable to clone repositories on GitHub Desktop - The repositories are part of a private organization, I can clone or make changes through github.com.

When I try through software I get authenticated and authorized, I am unable to clone the available list of private repositories.

### Version & OS

Version: Version 2.4.1
OS: Windows 1- (64-bit version)

### Steps to reproduce the behavior

Steps:
1. Login to GitHub Desktop through either browser or directly through GitHub Desktop.
2. Asked for multi-factor authentication, entered the code generated through authenticator.
3. Github Desktop redirects to authorize single sign on for a private repository (usually one time process in a day).
4. Successfully authenticated and redirects to GitHub Desktop.
5. Able to see the list of private repositories.
6. Tries to clone any repository - Getting authentication error: We were unable to authenticate with github.com

### Expected behavior

I should be able to clone the repositories and commit changes.

### Actual behavior

Repositories are visible but unable to clone them - I get authentication steps, I re-enter the credentials but it redirects to authentication steps.
[2020-04-21.desktop.production.log](https://github.com/desktop/desktop/files/4511811/2020-04-21.desktop.production.log)

### Screenshots
![Github Desktop Error](https://user-images.githubusercontent.com/63592589/79898407-daa49980-8428-11ea-91ee-69e87a3673b2.JPG)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Have read similar issues online, reinstalled the application, logged out and logged in through browser and desktop, nothing seems to work.

**Comment by prateek-gupta-wawa** [comment]
Also, I noticed this weird behavior:
Whenever I login to Github Desktop first time using my correct credentials, it says that the credentials are incorrect. I enter the same credentials again and it works.

Could it be somehow related to the authentication errors that I am getting after login, maybe the software is not registering my credentials?

Note: This does not happen on github.com and I have tried directly logging in through the web browser as well.

**Comment by steveward** [comment]
@prateek-gupta-wawa thanks for the detailed report. 

Can you go to https://github.com/settings/applications, revoke the GitHub Desktop entry, and then switch back to GitHub Desktop and try logging out/logging back in from `File` > `Options` > `Accounts`?

**Comment by prateek-gupta-wawa** [comment]
After hours of struggling with this issue, it turned out there was an agent installed by my organization which was blocking any read/write activity on GitHub desktop.

I am closing the ticket, many thanks for your help.
