### ISSUE TITLE
you pushed a patch and mentioned patching security vulnerability. What was the extent of the security issue?

### ISSUE THREAD

**Issue by peternoges** [desktop/desktop#9592]
you pushed a patch and mentioned patching security vulnerability. What was the extent of the security issue?

**Comment by billygriffin** [comment]
Hi @peternoges, thanks for asking. This blog post shares more detail about the Git patch: https://github.blog/2020-04-20-git-credential-helper-vulnerability-announced-update/

Hope that helps!
