### ISSUE TITLE
Possible error with remotes when you want to checkout upstream PRs on Desktop

### ISSUE THREAD

**Issue by ruggi99** [desktop/desktop#9593]
### Describe the bug

When I'm working with a fork, in my case with Desktop, and want to checkout upstream PRs, github-desktop-desktop remote is created even if upstream remote exists.

### Version & OS

GitHub Desktop 5c0df17.
OS: Windows 10 

### Steps to reproduce the behavior

1. Select a repository fork
2. Checkout a PR (from upstream)
3. se github-desktop-*** remote created

### Expected behavior

No remote is created. Upstream remote used

### Actual behavior

github-desktop-*** (github-desktop-desktop in my case) remote created as duplicate of upstream.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Think the problem is here:
https://github.com/desktop/desktop/blob/5c0df1747a85e0c3f383bb82866faf9d7ad2b5c5/app/src/lib/stores/app-store.ts#L5329-L5330
Should be:
```ts
const isRefInThisRepo = gitHubRepository.fork ?
  head.gitHubRepository.cloneURL === gitHubRepository.parent!.cloneURL :
  head.gitHubRepository.cloneURL === gitHubRepository.cloneURL
```
This works in my case

**Comment by rafeca** [comment]
Thanks for the report @ruggi99 !

I actually recently created a PR that should address this issue: https://github.com/desktop/desktop/pull/9382 😄
