### ISSUE TITLE
Android Studio: Set Up user class

### ISSUE THREAD

**Issue by Flamma-Dup** [desktop/desktop#9594]
### Describe the feature or problem you’d like to solve

Hello, I have a problem here, every time I execute line 49 + 50 I don't get any results, its like the reference on line 23 is not affected by line 26 + 27.... please HELP I am about to break my keyboard!
![Reg1](https://user-images.githubusercontent.com/58793472/79908021-d6717f80-841a-11ea-8606-a078b9d26cdf.JPG)
![user1](https://user-images.githubusercontent.com/58793472/79908024-d70a1600-841a-11ea-8951-6c8d68580bb2.JPG)

**Template**
👇 
---

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@Flamma-Dup Thanks for the issue but I am confused how this relates to the Desktop application. Would love to help, so please fill out the template above.

**Comment by Flamma-Dup** [comment]
I am sorry, I am working on a smart phone app, if its against the regulation, I will delete the issue @tierninho

**Comment by tierninho** [comment]
Closing this as we can only help with specific issues related to Desktop. Good luck with the app!
