### ISSUE TITLE
Use the new v2.4.2 commit timestamps for branch timestamps

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#9595]
### Describe the feature or problem you’d like to solve

Since v2.4.2 has been released, there is now a discrepancy between how the commit timestamps look and how the branch timestamps look.
### Proposed solution

I think the timestamps on the branch dropdown should use the new timestamps introduced in Desktop v2.4.2.

**Comment by rafeca** [comment]
Thanks for the suggestion @JosephTLyons !

This was discussed when the new commit timespans were developed (see the original comment from @ampinsk in https://github.com/desktop/desktop/pull/9494#pullrequestreview-391211510 ), the reason to shorten the dates in the commit list is to have more space to be able to show the tags (see https://github.com/desktop/desktop/pull/9537), while we don't need the extra space on the branch list.

Apart from shorter dates, there's now some difference in how we display very old dates between the two. For example for a date that is a few months old we'll show the full date on the commit list (e.g `Nov 13, 2019`) and a relative timestamp on the branch list (e.g `7 months ago`).

I personally think that this difference makes sense: the purpose of the date shown on the branch list is to give a rough signal of how recent is a branch. In that context the exact day when the branch was last updated may not be that relevant for old branches, while showing the approximate age of the branch may give more clear signal:

![image](https://user-images.githubusercontent.com/408035/79968390-50901b80-8490-11ea-9483-db842fcc12d5.png)

On the commit list, though, there are many scenarios where showing the exact date will be relevant, specially when we show tags (e.g to quickly know when a tag/release was created):

![image](https://user-images.githubusercontent.com/408035/79967945-c8aa1180-848f-11ea-8917-e75354b96551.png)
 
Anyways, I'd like to know @ampinsk and @billygriffin opinion on this 😃

**Comment by billygriffin** [comment]
Thanks @JosephTLyons! I agree 100% with @rafeca's reasoning here, so I'm going to close this - @ampinsk If you disagree though, feel free to reopen and propose something else.
