### ISSUE TITLE
Change default remote instead of setting URL only

### ISSUE THREAD

**Issue by Jasonnor** [desktop/desktop#9596]
### Describe the feature or problem you’d like to solve

We can only change default remote url, but not "remote".
E.g., there is 3 remotes: `origin`, `upstream`, `gitlab`, and default remote is `origin`.
But only the remote URL of `origin` can be changed instead of switching from `origin` to `gitlab`.

### Proposed solution

May add a drop-down menu next to the remote URL to switch remote on `Repository Settings`.

### Additional context

Related issues: #8533

**Comment by steveward** [comment]
Thanks for the feedback @Jasonnor. I'm going to add this feedback to https://github.com/desktop/desktop/issues/1442 where we are tracking support for multiple remotes.
