### ISSUE TITLE
Admin UI and Users UI

### ISSUE THREAD

**Issue by Perezari** [desktop/desktop#9598]
### Admin UI and Users UI

if it possible please can you add option for admin to hide commit section for users that only
doing a pull ?

### Proposed solution

Its will be great for compaines that want to update thier users without afraid that they can commit in mistake to master branch.
simple users need to see this screen without commiting section: 

### Additional context

![image](https://user-images.githubusercontent.com/24621247/79957354-1d4a8e00-848a-11ea-8963-b8928f6b62b6.png)

**Comment by steveward** [comment]
@Perezari thanks for contributing. I would recommend looking into using the [protected branches feature](https://help.github.com/en/github/administering-a-repository/about-protected-branches), which would prevent commits from being pushed directly to the protected branch. GitHub Desktop also warns you when you are attempting to commit to protected branches:

![](https://help.github.com/assets/images/help/desktop/protected-branch-warning.png)

I hope that helps!

**Comment by Perezari** [comment]
can Github Desktop add at least a feature like: 
if the user sign out from his account, hide the section of commiting.
You have created software to make it easier for the user,
so i think this feature can save lots of headache.
