### ISSUE TITLE
cannot fetch/push/pull

### ISSUE THREAD

**Issue by YiDing-EH** [desktop/desktop#9599]
### Describe the bug

cannot fetch/push/pull

### Version & OS

Version 2.4.2, OS: Windows 10 

### Steps to reproduce the behavior

Click "fetch/push/pull" 
error message
warning: url has no scheme: helperselector
fatal: credential url cannot be parsed: helperselector

### Expected behavior

expect to push successfully

### Actual behavior

error message, cannot push

### Logs

2020-04-22T08:14:44.872Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
warning: url has no scheme: helperselector
fatal: credential url cannot be parsed: helperselector

**Comment by Aravind-Belagaje** [comment]
same as #9597 i guess

**Comment by rafeca** [comment]
Thanks for the report! I'm closing this issue in favor of https://github.com/desktop/desktop/issues/9597, where the investigation is taking place
