### ISSUE TITLE
warning: url has no scheme: github.com Error

### ISSUE THREAD

**Issue by NitinBuzz** [desktop/desktop#9600]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

![error](https://user-images.githubusercontent.com/26275600/79984489-e0e95300-84c6-11ea-8fda-528830307773.PNG)

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by rafeca** [comment]
Hey @NitinBuzz ! Thanks for reporting this! We're currently tracking it in https://github.com/desktop/desktop/issues/9600 so I'm going to close this issue.

In the meantime, you can try editing your `.gitconfig` file (Under `C:\Users\<username>`) and replace `[credential "github.com"]` by `[credential "https://github.com"]`, as mentioned in https://github.com/desktop/desktop/issues/9597#issuecomment-617745963

Let me know if this fixes it!

**Comment by Elnora** [comment]
> Hey @NitinBuzz ! Thanks for reporting this! We're currently tracking it in #9597 so I'm going to close this issue.
> 
> In the meantime, you can try editing your `.gitconfig` file (Under `C:\Users\<username>`) and replace `[credential "github.com"]` by `[credential "https://github.com"]`, as mentioned in [#9597 (comment)](https://github.com/desktop/desktop/issues/9597#issuecomment-617745963)
> 
> Let me know if this fixes it!

This worked for me, thanks!

**Comment by NitinBuzz** [comment]
Thanks @Elnora
