### ISSUE TITLE
Commit GUI issue

### ISSUE THREAD

**Issue by Ryan-Afzal** [desktop/desktop#9602]
### Version & OS

Version 2.4.2
Windows 10 Home Version 2004 OS Build 19041.207

### Reproduction

1. Open GitHub Desktop
2. See error on the 'commit to <branch>' UI component.

### Expected behavior

It should show the user's avatar and name, and an input field for the commit message header.

### Actual behavior

Shows placeholder image overlapping with email and username. The input field is the minimum size.

### Screenshots

![image](https://user-images.githubusercontent.com/29133920/80008661-e457ec80-847c-11ea-971b-52967188e039.png)

**Comment by steveward** [comment]
Thanks for the report @Ryan-Afzal. This looks similar to https://github.com/desktop/desktop/issues/5671 and https://github.com/desktop/desktop/issues/6041. 

Could you try resetting GitHub Desktop a fresh state to see if that helps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop (you will need to add your repositories back to the application)

Let me know if that doesn't get things working for you.
