### ISSUE TITLE
Losing focus while creating a new branch changes what desktop thinks is the default branch.

### ISSUE THREAD

**Issue by anarten** [desktop/desktop#9608]
### Describe the bug

While creating a branch from another base branch that is **not** the default branch, if GitHub desktop loses focus it changes the "Create a branch" window to appear like the branch I am basing off of is the default branch. 

### Version & OS

Version 2.4.2
Windows 10 Pro Version 1809 Build 17763

### Steps to reproduce the behavior

1. Make your current branch not the default branch. 
2. Go to menu Branch -> New Branch
3. Click on "Create branch based on..." **currently checked out branch.**
4. Click on another Windows (i.e. not GitHub Desktop) to lose focus from GitHub Desktop.
5. "Create a branch" sub-window in GitHub Desktop will change to state that your current branch is the default branch for the repository. 

A similar issue also occurs by reversing the order of 3 & 4:
1. Make your current branch not the default branch. 
2. Go to menu Branch -> New Branch
3. Click on another Windows (i.e. not GitHub Desktop) to lose focus from GitHub Desktop.
4. With the first click back on GitHub Desktop, hit "Create branch based on..." **currently checked out branch.**
5. "Create a branch" sub-window in GitHub Desktop will change to state that your current branch is the default branch for the repository. 

### Expected behavior

The appearance of what the default branch is should not change. 

### Actual behavior

The appearance of what the default branch is changes to the currently checked out branch. 

### Screenshots

Step 3:
![image](https://user-images.githubusercontent.com/31749093/80115541-18e1ac00-8542-11ea-83b8-59b910c2809a.png)

Step 4 - 5:
![image](https://user-images.githubusercontent.com/31749093/80115575-27c85e80-8542-11ea-98d8-9f7d4cdc59f3.png)

### Logs

N/A

### Additional context

N/A

**Comment by rafeca** [comment]
Thanks for the detailed report @anarten! I've been able to reproduce this problem
