### ISSUE TITLE
I get update notifications on every windows boot

### ISSUE THREAD

**Issue by jasoncollege24** [desktop/desktop#9613]
### Describe the bug

Every time I start Windows lately, I get a notification of a new update to github desktop, but when I actually check for updates, it says I have the latest version.

### Version & OS

GitHub Desktop version 2.4.2.
OS is Windows 10 Pro Open version 19.09

### Steps to reproduce the behavior

1. start, or restart Windows
2. See notification popup

### Expected behavior

Update notifications should only appear when there are actual updates for the branch in use.

### Actual behavior

On Windows startup, I received a notification about an update to GitHub Desktop. When I checked for updates in GitHub Desktop itself, it claimed it was the newest version. Lately, this has happened on every Windows boot.

### Screenshots

Didn't take screenshots

### Logs

Do you need the logs for this?

**Comment by steveward** [comment]
@jasoncollege24 could you share a screenshot of the update notification? GitHub Desktop should only show update notifications within the app itself. Are you possibly seeing notifications for updates to Git for Windows?

**Comment by jasoncollege24** [comment]
Thank you! It was Git for Windows, and not the GitHub Desktop. Can you pass feedback about this experience to the Git for Windows team? Feedback is that clicking “Yes” on the update notification did nothing at all. I had to manually update Git for Windows to resolve this. Regards,Jason College From: Steve WardSent: Thursday, April 23, 2020 4:18 PMTo: desktop/desktopCc: jasoncollege24; MentionSubject: Re: [desktop/desktop] I get update notifications on every windows boot (#9613) @jasoncollege24 could you share a screenshot of the update notification? GitHub Desktop should only show update notifications within the app itself. Are you possibly seeing notifications for updates to Git for Windows?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by steveward** [comment]
@jasoncollege24 if you continue to have specific update issues with Git for Windows I would recommend [opening an issue](https://github.com/git-for-windows/git/issues).
