### ISSUE TITLE
Download GitHub Desktop as corrupted

### ISSUE THREAD

**Issue by capwalker** [desktop/desktop#9618]
Each download of GitHub Desktop for Mac (I run High Sierra) results  in verification. That gives me a pop-up "App is damaged. Move to Trash ? Y/n" .

I've downloaded the zip file 3 times and used multiple unarchivers. I've run under Guest user from separate drive. Same result.

Any ideas ?

**Comment by tierninho** [comment]
@capwalker Thank you for the report. This error is likely has to do with the revocation of the app's authorization.

The workaround is as follows:

- Option I
  For a certain application run in Terminal:

  `sudo xattr -rd com.apple.quarantine /Applications/[LockedApp].app`

- Option II
  To disable checks globally run in Terminal:

  `sudo spctl --master-disable`

Let's us know what happens please. 

cc @outofambit for 👀 as this may have the certificate for the app has been revoked.

**Comment by tierninho** [comment]
@capwalker  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
