### ISSUE TITLE
publish fails with curl error "Send failure: Connection was reset"

### ISSUE THREAD

**Issue by shaunstarbuck** [desktop/desktop#9619]
I am trying to publish a new repository to github. It was previously a repository with a commit and some files, but I ran into this issue during a commit and reset the repo in an attempt to solve the problem. 

When I push in github desktop I get:
```
"error: RPC failed; curl 56 Send failure: Connection was reset
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date"
```

I have tried resetting the `http.postBuffer` to a large value in git bash (although none of the files are especially large) without success. I have created and pushed a new, empty repo since this problem arose and didn't have any problems.

I found a similar issue, https://github.com/desktop/desktop/issues/6485, and per a suggestion there ran Go to Repository > Open in command prompt in GitHub Desktop and run the following commands:
```
set GIT_TRACE=1
set GIT_CURL_VERBOSE=1
git push origin <branch>
```

The results were:
```
Host: github.com
Authorization: Basic UGVyc29uYWxBY2Nlc3NUb2tlbjozYTE4Yzk1NzI5YTljOTEzODkxYTYyMmViY2UwNDE1MmJlZWIwOTAy
User-Agent: git/2.26.2.windows.1
Accept: */*
Accept-Encoding: deflate, gzip
Pragma: no-cache
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: C56E:7765:925EC0:DBF9BE:5EA3800E
< X-Frame-Options: DENY
* Connection #0 to host github.com left intact
18:11:00.387719 run-command.c:663       trace: run_command: 'git credential-manager store'
18:11:00.434529 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
18:11:00.434529 git.c:703               trace: exec: git-credential-manager store
18:11:00.434529 run-command.c:663       trace: run_command: git-credential-manager store
18:11:00.606390 run-command.c:663       trace: run_command: git send-pack --stateless-rpc --helper-status --thin --progress https://github.com/shaunstarbuck/Basic-NLP-.git/ --stdin
18:11:00.606390 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
18:11:00.606390 git.c:439               trace: built-in: git send-pack --stateless-rpc --helper-status --thin --progress https://github.com/shaunstarbuck/Basic-NLP-.git/ --stdin
18:11:00.606390 run-command.c:663       trace: run_command: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
18:11:00.621984 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
18:11:00.621984 git.c:439               trace: built-in: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 8 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (12/12), 69.88 MiB | 344.04 MiB/s, done.
Total 12 (delta 1), reused 12 (delta 1), pack-reused 0
* Found bundle for host github.com: 0x3766eb0 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host github.com
* Connected to github.com (140.82.113.3) port 443 (#0)
* Server auth using Basic with user 'PersonalAccessToken'
> POST /shaunstarbuck/Basic-NLP-.git/git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic UGVyc29uYWxBY2Nlc3NUb2tlbjozYTE4Yzk1NzI5YTljOTEzODkxYTYyMmViY2UwNDE1MmJlZWIwOTAy
User-Agent: git/2.26.2.windows.1
Accept-Encoding: deflate, gzip
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Content-Length: 73277320
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-result
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: C56E:7765:925F38:DBFB9C:5EA38013
< X-Frame-Options: DENY
* OpenSSL SSL_read: Connection was reset, errno 10054
* Closing connection 0
error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

Any help would be appreciated.

**Comment by tierninho** [comment]
@shaunstarbuck Thank you for bringing this to our attention and apologies for the trouble.

I do see you were uploading ~70MB to the remote server, which isn't a whole lot, but may be related to the issue you're seeing. 

```
Writing objects: 100% (12/12), 69.88 MiB | 344.04 MiB/s, done.
Total 12 (delta 1), reused 12 (delta 1), pack-reused 0
```

In general the `error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset` error itself doesn't provide much context, just that the connection was aborted.

Some questions:
- In the issue you mentioned, #6485, I noticed a workaround was published. Any chance you tried it? 

  > For future reference, I solved this issue by repacking:
  `git repack --max-pack-size=100M -a -d`

- Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help > Show Logs in Explorer.` The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

- Also, are using a proxy or do you have firewall/anti-virus software installed?

**Comment by shaunstarbuck** [comment]
I tried the suggestion of git repack --max-pack-size=100M -a -d. The items were packed successfully but it still fails at the push phase with the error error: 
RPC failed; curl 56 OpenSSL SSL_read: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac, errno 0
Is it possible bad record mac means a corrupted file or something along those lines?

 Here is my log from github desktop today, after again replicating the error.
[2020-04-25.desktop.production.log](https://github.com/desktop/desktop/files/4533805/2020-04-25.desktop.production.log)


I don't have a proxy or firewall, and the only antivirus software I have is Kaspersky free. I also was able to upload before this commit so with the same settings.

**Comment by shaunstarbuck** [comment]
Bump

**Comment by tierninho** [comment]
@shaunstarbuck Thank you for the added details. 

> Is it possible bad record mac means a corrupted file or something along those lines?

You may need to change the git config to use TLSv1.2 instead of SSLv3:

`git config http.sslVersion tlsv1.2`

However, let me check with my colleague @steveward who may have seen this before. The buffer was already increased and repacking isn't working. I spotted SSL3 in this error:

`RPC failed; curl 56 OpenSSL SSL_read: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac, errno 0`

Any possible suggestions?

**Comment by shaunstarbuck** [comment]
Thanks for the response. Git is working fine for another repo I just pushed to the server, so it's definitely isolated to this project. I'll hold off on changing the git config until you suggest otherwise.

**Comment by shaunstarbuck** [comment]
I did some testing today and I isolated the file that is causing git to throw an error. I can publish everything in the project successfully except for a .json data file (~82,000 KB) containing a set of ~200,000 small text records. As soon as it is included I get the connection aborted error. What's especially strange is that I had uploaded the file before in a git commit and the file hasn't been changed since April 17th,  well before this problem started occurring. I can still read the file with no issues in Python, so I am confused why this is happening. 

The error occurs even with a freshly downloaded file. I suppose I could download the file from within a Python script, but I'd really prefer to be able to upload the project with the dataset included. I'm also concerned this will happen again with another file/project.

**Comment by tierninho** [comment]
Thanks. 82MB should work fine in general. I wish the `error: RPC failed; curl 56 Send failure: Connection was reset` error was just more specific.

Your antivirus software could be modifying the HTTP packets in transit -- I would try disabling it and attempt the push again. Another cause could be the wifi dropping the connection. If you have connection to LAN, that might help too.

Let us know the outcome please.

**Comment by shaunstarbuck** [comment]
I was able to upload the project today, once with the antivirus turned off and again on a duplicate test project with the antivirus turned on. I don't know if it got unstuck by turning it off and on or what.

My computer is connected by ethernet, but the underlying internet is pretty poor (satellite internet). Could my ISP be throttling uploads to cause this error? If the start of a new billing month was today they may have reset the data cap and no longer be throttling uploads. My upload speed hasn't changed, at about 1.5 Mbps, so I don't know. It's just a thought why the second upload worked with antivirus on. I'll find out in a few weeks if the same problem reoccurs.

Anyways, thanks a lot for the help!

**Comment by hedoshro** [comment]
Hi, I'm trying to push my committed file but I gave this error message: connection was rest. I turned off/on my wifi and also my antivirus but it didn't work. I'm using the VPN because of all the issues on the internet  in Iran Is those problem related to VPN? what should I do? could you please help me? I really appreciate any help you can provide.
