### ISSUE TITLE
proxyconnect tcp: dial tcp: lookup socks5: no such host error:

### ISSUE THREAD

**Issue by cgviver** [desktop/desktop#9620]
i planing to use  Git , Git LFS as version control system for unity Projects. when i tried to
integrate i facing some error while i am trying to push to origin after creating unity project file.

proxyconnect tcp: dial tcp: lookup socks5: no such host
error:

when i tried to push the file to origin using git desktop . i am getting following error below
Post https://github.com/repos/myrepo.git/info/lfs/locks/verify: proxyconnect tcp: dial tcp: lookup socks5: no such host
error: failed to push some refs to 'https://github.com/cgviver/myrepo.git'

**Comment by tierninho** [comment]
@cgviver Thank you for the issue and my apologies for the following request. The Git LFS would be better suited to help resolve this, so please fill out an issue template here: https://github.com/git-lfs/git-lfs/issues/new?assignees=&labels=&template=bug_report.md&title=

Thank you for using Desktop.
