### ISSUE TITLE
cannot publish unborn HEAD

### ISSUE THREAD

**Issue by Adelore** [desktop/desktop#9630]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Adelore** [comment]
A created a new repository, cloned the folder but I can't publish. Tried committing to master but it's not working.

**Comment by tierninho** [comment]
@Adelore Thank you for the issue. Please fill out the above template so we have some more info on the problem.

**Comment by steveward** [comment]
@Adelore usually the `cannot publish unborn HEAD` error results from not having any commits on your current branch. Make sure you have made an initial [commit to your branch](https://help.github.com/en/desktop/contributing-to-projects/committing-and-reviewing-changes-to-your-project) and then try publishing again.

**Comment by BENINDO27** [comment]
great

**Comment by MurtazaShowkat** [comment]
if you are facing this after adding an already existing project then simply commit the changes and then hit publish.
