### ISSUE TITLE
unable to create a new repo or add one 

### ISSUE THREAD

**Issue by jclau69** [desktop/desktop#9631]
Hi

When I'm trying to add or create a repo the button doesn't highlight

--

👇 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@jclau69 Thank you for the issue. Please fill out the template above so we will have more information to address your situation. A screenshot would be helpful based on what you said so far.
