### ISSUE TITLE
No access to a team shared repository usind github desktop

### ISSUE THREAD

**Issue by FulvioSpelta** [desktop/desktop#9633]
### Describe the bug

Accessing (cloning) a repository part of a team always i get request for login information.
**Notes**

1. Using web both my own repository and the repo from the team are ok (I've done a commit using web on the shared repo)
2. The pc I'm using have a configuration with some protection systems (Blue Coat) installed.
3. I'm reporting the issue in order to help you to find compatibility problems with this system

### Version & OS
- github desktop 2.4.2
- Windows 10 Enterprise

### Steps to reproduce the behavior
In the log you'll find:

1. Clone action on my own repo - ok
2. Clone action on shared repo using my user - ko
3. Clone action on shared repo using the user owner of the team - ko

Steps for every test

1. File/Clone repository
2. Select repo and directory (see screeshot attached)
3. Clone
4. If ko insert again my userid/psw (userid and psw of the owner in the second test)

Userid used
- FulvioSpelta
- radiocodogno@gmail.com

Repository used
https://github.com/FulvioSpelta/sstimer - ok
https://github.com/Radio-Codogno/radiocontrol - ko

### Expected behavior

Successful login and use of the cloned repo

### Actual behavior

No login accessing the shared repo

### Screenshots

![image](https://user-images.githubusercontent.com/1832999/80341374-9b2fe000-8862-11ea-81ba-9d5e7b50e41d.png)
![image](https://user-images.githubusercontent.com/1832999/80341384-a1be5780-8862-11ea-84d7-6e777bf04977.png)

### Logs

Log attached

[2020-04-27.desktop.production.log](https://github.com/desktop/desktop/files/4537879/2020-04-27.desktop.production.log)

Pls ignore error messages about the enterprise github i was not connected to my intranet during the tests. USe of github desktop on enterprise github is ok.

edit: removed some typos, added note about github enterprise.

**Comment by tierninho** [comment]
@FulvioSpelta thank you for filing this issue and for providing all the details. 

I believe this is the error which is the causing the issues:

```
\Users\A130754\Dropbox\RadioCodogno\test\radiocontrol` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\A130754\Dropbox\RadioCodogno\test\radiocontrol'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/Radio-Codogno/radiocontrol.git/'
```

We have a handful of auth errors recently, so please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been the modified `Autorun` registry entry. 

Let me know the results and apologies for the troubles.

**Comment by FulvioSpelta** [comment]
Hi Tiernan, thanks for your reply.
Unfortunately i wasn't able to fix the problems following the hint in the post you pointed me out.

In case it can helps some other i leave some notes.

The pc that manifest the problems has installe git for windows too (I don't know if it is the source of the problem)
I've tried github for windows on other Windows 10 pc without any problems.

At last I've setup a workaround to use my main pc that is to use git for windows. In order to connect it to github remote repo i've been forced to setup and use the SSH key to logon because using users/psw schema always prevent me to have a successful login.

Due to the workaround i'll close the issue.
Many thanks again.

**Comment by tierninho** [comment]
Thank you for giving us a detailed update. It is always helpful. 

Apologies for the troubles, and glad you are back in a working state. 

Hopefully, we can find the root cause soon. Have a good day.
