### ISSUE TITLE
User image replaced with full user email leaving no room for commit title

### ISSUE THREAD

**Issue by AssafMiron** [desktop/desktop#9635]
### Describe the bug
On the left, lower side of the screen, the User image is replaced with full user email leaving no room for commit title (I can add text only in the description).

### Version & OS
GitHub Desktop Version 2.4.2
OS Win10

### Steps to reproduce the behavior
1. Open GitHub Desktop
2. See Github user image (avatar) in the lower left side
3. User image is replaced with email text (looks like image alt text)

### Expected behavior

See the user avatar image

### Actual behavior

User email text instead of image
I have a @users.noreply.github.com email suffix

### Screenshots
![image](https://user-images.githubusercontent.com/11990765/80352969-57969f80-887d-11ea-88be-7b59ac9a4ea0.png)

**Comment by tierninho** [comment]
Thanks for the report @AssafMiron . This looks similar to #5671 and #6041.

Could you try resetting GitHub Desktop a fresh state to see if that helps? You will have to re-add your repos back in.

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop (you will need to add your repositories back to the application)

Let me know if that doesn't get things working for you.

**Comment by AssafMiron** [comment]
Thanks for the help @Tiernan
I actually deleted all the files without the folders) and the files from
Cache folder and that solved the problem without me adding the repositories
all over again :)

Thanks,
Assaf

**Comment by tierninho** [comment]
Good news! Thanks for confirming and enjoy Desktop!
