### ISSUE TITLE
Auth error after upgrade

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#9641]
I am having the same issue as the author of the initial post. Tried all recommended steps (logged out/logged in, removed all files from AppData and LocalAppData, reinstalled, generated and activated new SSH key, used HTTPS and SSH), and still getting the same error. I can push/pull from the command line but not from GitHub Desktop. It worked fine a couple weeks ago (new update issue?)

![Annotation 2020-04-27 130505](https://user-images.githubusercontent.com/58671630/80421362-32ac2780-8891-11ea-8df2-a7f0e1769d3d.jpg)

My log file:
[2020-04-27.desktop.production.log](https://github.com/desktop/desktop/files/4542088/2020-04-27.desktop.production.log)

Environment:
Windows 10 Home

Anything else I could try?

_Originally posted by @bartek2101 in https://github.com/desktop/desktop/issues/7982#issuecomment-620240324_

**Comment by bartek2101** [comment]
Edit: Third-party clients work just fine.

**Comment by tierninho** [comment]
@bartek2101 Thanks for notifying us of this issue. It looks like their are two things going on:

1. Auth error
2. `fatal: refusing to merge unrelated histories` error from your log. 

Hopefully if we solve number one, we can avert number 2, which is not resolved fully by us as evidenced by https://github.com/desktop/desktop/issues/1484. 

As for the auth error -- Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been the modified `Autorun` registry entry. 

Let me know if you have any questions.

**Comment by tierninho** [comment]
@bartek2101  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by rubenheymans** [comment]
I have the same issue, created new ssh keys, logged in/out etc., command line works just fine. Github for windows doenst work at all with ssh keys.

**Comment by ArthurAndrews** [comment]
I'm not a frequent user, but I believe I am experiencing the same issue.  I am trying to clone from my company's gitlab.  Github Desktop isn't asking for my login information, and is just displaying an authentication error.

**Comment by tierninho** [comment]
@ArthurAndrews Thanks for the note. This is a known bug and will be fixed very soon! Please follow along here: https://github.com/desktop/desktop/issues/9776

@rubenheymans Thanks for reaching out. Please fill a new issue here: https://github.com/desktop/desktop/issues/new?template=bug_report.md

**Comment by SuperHarmony910** [comment]
I'm a new user to GitHub Desktop, this issue is bugging me. I've tried Git, solved a publickey issue but the app is just not letting me commit. I've tried everything from SSH to HTTPS, would anyone help please?

**Comment by steveward** [comment]
@SuperHarmony910 could you open a new issue and fill out the template? Please be sure to also upload a log file so that we can take a closer look at any errors you are encountering.

**Comment by SuperHarmony910** [comment]
#10363 is my issue @steveward.

**Comment by ziadoz** [comment]
I saw this dialog after I'd accidentally removed `gihtub.com` from my `~/.ssh/known_hosts`. Once I added it back the dialog went away and things worked again.

**Comment by steveward** [comment]
@ziadoz thanks for sharing that. This is a known issue we are tracking in https://github.com/desktop/desktop/issues/2579. There's no way to trust unknown host keys in GitHub Desktop at this time.

**Comment by DAbidou** [comment]
This answer https://stackoverflow.com/a/29380765/2849383 saved my entire life
Please, write it everywhere to save as many lives as possible XD
```
$ eval "$(ssh-agent -s)"
$ ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
```
