### ISSUE TITLE
GitHub Desktop and remote development

### ISSUE THREAD

**Issue by andronat** [desktop/desktop#9642]
Now that [VSCode made remote development a first-class citizen](https://code.visualstudio.com/docs/remote/remote-overview) I was wondering if it GitHub Desktop has (or will) support for controlling git repos over ssh.

**Comment by Xotabu4** [comment]
You can just use git client that already exists in vscode, or setup some ide plugins

**Comment by tierninho** [comment]
@andronat Thanks for the issue. Please follow along at this [issue](https://github.com/desktop/desktop/issues/2579), which is tracking SSH enhancements. Thank for using Desktop!
