### ISSUE TITLE
Getting Fatal Error

### ISSUE THREAD

**Issue by Surya0410** [desktop/desktop#9645]
Getting error saying "fatal: could not read Username for 'https://ne1itcprhas62.ne1.savvis.net': terminal prompts disabled" 

Tried Uninstalling and Reinstalling
Still Same Error getting so much frustration.

**Comment by steveward** [comment]
Thanks for the report. Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been the modified Registry entries. Let me know if you have any questions about the steps.
