### ISSUE TITLE
Unclear naming of branches across forks

### ISSUE THREAD

**Issue by troplolBE** [desktop/desktop#9653]
### Describe the feature or problem you’d like to solve

I wanted to merge a branch from my fork of a project to the same branch of the official repo. When I searched for the names of the branches I had a lot of trouble to find out which branch was from my fork and which one was from the official repository.

### Proposed solution

It will significantly improve the user experience when merging branches across forks by setting the name of the owner of the fork before the name of the branch instead of upstream and origin.

I think it will be less confusing if in the screenshot it would be written `origin/master` instead of `troplolBE/master`. 

### Additional context
![image](https://user-images.githubusercontent.com/12971225/80596317-797f5600-8a26-11ea-875f-7aef959bc4b1.png)

**Comment by steveward** [comment]
@troplolBE apologies for not getting back to you in this issue. It sounds like you are wanting the branch list to indicate the current remote tracking branch for the local branches you have checked out in your repository. Is that the case? 

There is a known issue when checking out a remote branch that has the same name as an existing local branch -- see https://github.com/desktop/desktop/issues/4527 for the tracking issue about that bug. Resolving that would likely provide differentiation in the remote tracking branches of local branches.
