### ISSUE TITLE
List of Changes sorting options

### ISSUE THREAD

**Issue by clu005** [desktop/desktop#9654]
### List of Changes sorting options

There is no sorting options in the list of Changes on Github Desktop. 
As a .Net programmer, after each build, my workplace will have tons of new files. It is hard to find what I want to commit. 

### Proposed solution

Having options to sort the files on the Changes list by file extension or file path.

**Comment by steveward** [comment]
@clu005 thanks for the feedback. I'm going to drop this into https://github.com/desktop/desktop/issues/4739 to consolidate feedback about sorting the `Changes` tab.
