### ISSUE TITLE
github desktop repository issue.

### ISSUE THREAD

**Issue by xKylee** [desktop/desktop#9658]
### Describe the bug

when doing a fresh git pull of a forked repository, it will display the branches and the pull requests of the repo you have forked from.

this is happening for every forked repository.

### Version & OS

Version 2.4.3
Windows 10.

### Steps to reproduce the behavior

File > Clone repository
clone a forked repository
check the branches and PR's.

### Expected behavior

github desktop should allow me to edit my repo, not the upstream.

### Actual behavior

github desktop shows me the branches and pr's from the upstream repo.

any amendments made however, do get pushed to my repo.

### Additional context

this is extremely frustrating when trying to maintain a fork which heavily differs from the upstream, or you do not want to push to the upstream directly. i believe this was changed in around 2.4.1 and i am unsure why. this has made maintaining the projects i work on more difficult.

**Comment by tierninho** [comment]
@xKylee Thanks for filing this. We are tracking this issue at https://github.com/desktop/desktop/issues/9500 so please follow along there. I also added your feedback to the comments.

**Comment by billygriffin** [comment]
Thanks @xKylee for the issue and we really appreciate your feedback. To add to what @tierninho said, we've found that while the majority of people use forks primarily for contributing back to the upstream repo, there are still some people who are using forks in the way you're describing. Sorry that the change was frustrating for you, and that makes sense why that is. We're exploring a repo setting to allow people to prefer the fork (essentially mirroring the previous behavior), so hopefully if we go that route it should help. In the meantime, if you're maintaining a fork entirely distinct from the upstream repo, you can also write to GitHub support and ask them to detach the fork for you so it becomes its own free-standing repo.

**Comment by xKylee** [comment]
the problem is, I use the fork to do upstream PR's to the main repo, rather than using a branch (as i do not have access to do so on the main repo). 

for now, i have reverted to an older version to continue working as i was until this issue is rectified. thankyou.

**Comment by billygriffin** [comment]
@xKylee Would you mind sharing a bit more about your workflow? It sounds like you're using forks exactly how we expect people are using them (primarily to contribute to the upstream repo, usually without write access to the upstream). So I'm confused as to why the previous setup was better than this one? If you don't mind explaining a bit further, and if you could provide screenshots if possible, to help us better understand, that would be awesome. Just want to make sure we're not missing anything in our assumptions. If you don't have time to do so though, no worries. Thanks!

**Comment by xKylee** [comment]
sure not a problem.

the head repository is an open source project which is a fork of another open source project, meaning multiple people will contribute to both projects, however, it is only a select few people have access to create branches.

due to this, should you wish to contribute, you will need to maintain your fork, keep it up to date etc.

the previous setup was better as you could see your PR's, meaning if i wanted to upstream from the head's head i could pull their changes and PR it to my fork's head repo ensuring they are in sync.

due to the new changes, i'm unable to maintain my fork by making a pull request from upstream.

i'm due to do another upstream later this evening should you want to shadow and see how i would primarily use github desktop.


the process would usually be:

1) make a pull request from the heads head repo to my repo.
2) use github desktop to create a "local" branch with the pull request files.
3) use github desktop to create a "local" branch which is a duplicate of the master branch.
4) use github desktop to merge the local pull request branch into the local duplicate master branch.
5) push the newly merged branch to github.
6) do a pull request to the head, so that the head would be insync with commits from the upstream.

with the current method this isnt a method which i can do so as i cannot see local PR's.
