### ISSUE TITLE
Request to allow shallow cloning 

### ISSUE THREAD

**Issue by anshul78** [desktop/desktop#9660]
With open source repositories' size in GBs, the app should allow shallow cloning.

Also, even if a repo has been shallow cloned using terminal, `fetch origin` from app downloads the "entire" repo making shallow cloning futile. 

Moreover, once `fetch origin` started, there was no way to stop it from within app itself. Restarting the app continued with the fetch.

**Comment by tierninho** [comment]
@anshul78 Thank you for the issue and suggestion.

> Also, even if a repo has been shallow cloned using terminal, fetch origin from app downloads the "entire" repo making shallow cloning futile.

Can you tell me more about the steps you took for this? I would like to reproduce this. 

> Moreover, once fetch origin started, there was no way to stop it from within app itself. Restarting the app continued with the fetch.

Yes, I find that a nuisance as well, and we are tracking an issue which prevents that here: https://github.com/desktop/desktop/issues/2082

**Comment by anshul78** [comment]
> Can you tell me more about the steps you took for this? I would like to reproduce this.

- `git clone --depth 1 https://github.com/anshul78/easylist.git`
- Add repo in desktop app
- On selecting repo from sidebar, fetch origin starts automatically immediately (because according to the app, origin has never been fetched).
- Make a branch and commit some changes.
- `Publish branch` button gets disabled after a few seconds and app automatically starts fetching origin.

**Comment by tierninho** [comment]
I was able to see a large repo be cloned into Desktop, despite the shallow clone in the command line. I do not believe Desktop recognizes the difference yet, and the app pulls down all the changes once the repo is added in. cc @desktop/engineering for confirmation on this.

As far as stopping a `fetch` midstream, we are unlikely to support such a feature unless more users request this. I can definitely understand how this would be frustrating if the fetch was taking too long.

**Comment by tierninho** [comment]
Closing this in favor of https://github.com/desktop/desktop/issues/3480. Thank you for the input.
