### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by LubomirV** [desktop/desktop#9662]
### Describe the bug

Github Desktop is using 40% of the CPU resource during the whole day (even when idle) - I have i7-8750H.

### Version & OS

Windows 10, Github Desktop version: 2.4.3

### Steps to reproduce the behavior

1. Just open Github Desktop and it immediately jumps to 40% of CPU usage

### Expected behavior

1-3% of CPU when being idle.

**Comment by sudo-chiranjeevi** [comment]
It could be due to the sync which happens after the app startup.
Being idle doesn't stop the app to sync with the cloud at particular intervals.
It can be the reason.
However, I am waiting for the devs to comment on this.

**Comment by steveward** [comment]
@LubomirV thanks for the report. Did this high CPU usage start after a recent update to GitHub Desktop? One issue we've seen is antivirus/security software causing performance issues after we push out new updates to GitHub Desktop -- are you running any antivirus software on your machine that could be causing this?

**Comment by LubomirV** [comment]
Hi @steveward - I am using GitHub Destkop for more than 2 years, maybe even more, and I've never had such issue. I think it started after the latest update or the one before that one (not sure). Yes I am running the anti virus F-secure and then the basic windows security center.

**Comment by steveward** [comment]
@LubomirV are you able to temporarily disable F-Secure to see if that helps with this issue at all?

**Comment by LubomirV** [comment]
@steveward after uninstalling F-Secure the CPU usage is fine again, however, it is weird that this started to happen only during the last version, previously it was all fine.

**Comment by steveward** [comment]
@LubomirV often this happens when we push out updates to the Git binary we ship with GitHub Desktop. I'm going to close this issue out as we pinpointed it to F-Secure.

**Comment by agungmuliawan** [comment]
same with me
