### ISSUE TITLE
Pull Request for new branch 404 error

### ISSUE THREAD

**Issue by samiam9297** [desktop/desktop#9666]
### Describe the bug

404 error

### Version & OS

v2.4.1
Windows 7 64 bit

### Steps to reproduce the behavior

1. Create new branch.
2. Create pull request.

### Expected behavior

Ability to create pull request from app.

### Actual behavior

404 error

### Screenshots

https://prnt.sc/s80bvz

**Comment by steveward** [comment]
@samiam9297 it looks like you aren't logged in to your GitHub account in your browser, which will cause that URL to 404. Try logging in and let me know if you have any further issues.
