### ISSUE TITLE
When I was installing github It did not want to instal I had to reinstal it.

### ISSUE THREAD

**Issue by R-cloud-pixel** [desktop/desktop#9669]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@R-cloud-pixel  thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by R-cloud-pixel** [comment]
My github was already installed I went to installed it again it did not want to install so I had to reinstalled it again and it is installed.

**Comment by tierninho** [comment]
@R-cloud-pixel Glad you got it resolved. Sorry for the delay, but any chance you still have the logs for that day? See the Help menu in Desktop, click Show Logs in Explorer/Finder, and then find that logs for the day to attach to a comment.

**Comment by R-cloud-pixel** [comment]
I am reading and studying all about the comment of the contributor all about things I did not know Things that I have to start with Things that I have to do and to keep it in mind.    Then I have to write more comment about the #9669 issue.

**Comment by R-cloud-pixel** [comment]
GitHub Desktop   Version 2.5.0     Terms and Conditions   License and Open Source Notices   The latest versions.       OS NAME  Microsoft Windows 10 Home Single Language  Version 10.0.18363 Build 18363

**Comment by R-cloud-pixel** [comment]
2020 - 05 - 21.desktop.production-Notepad       account found for repository   Robert - Robert - u          Loading 1 repository from store.

**Comment by R-cloud-pixel** [comment]
First of all The problem begin with browser problem and computer problem. I went to learning git and GitHub and using them. The computer was working slow. After using git and GitHub the computer begin to work faster. Then the computer begin to work slow again. After that the browser begin sending apps like Virus Total Uploader 2.2 and I had to update the browser more than four times.

**Comment by tierninho** [comment]
Thank you for providing the additional details. If you attach the logs, we can get a better sense of what's going on. Also, the antivirus software may be interfering with Desktop, but hard to tell at this point because we have vert little info.

**Comment by R-cloud-pixel** [comment]
I want to know how to attach logs or what does it means to attach the logs?

**Comment by tierninho** [comment]
Please see the `Help` menu in Desktop, click `Show Logs in Explorer/Finder`, and then find that logs for the day you experienced the problems, and attach them to the comment below.

**Comment by R-cloud-pixel** [comment]
1 fetch Repository:  an error happened for Robert - u/Robert   Type Error: Failed to fetch                           fetch Repository: an error happened for robert - u/Robert    Type Error: Failed to fetch                                 fetch Protected Branches  unable to list protected branches   Type Error: Failed to fetch                              fetchMentionables: Failed for robert - u/Robert

**Comment by R-cloud-pixel** [comment]
Type Error: Failed to fetch  warn: fetch Account: failed with endpoint https://api.github.com.   Type Error: Failed to fetch.        warn: fetch User: failed with endpoint https://api.github.com   warn: Error refreshing Account Robert - u.

**Comment by R-cloud-pixel** [comment]
2020 - 05 - 06    warn: fetch Repository: an error occurred for Robert - u/Robert     warn: fetch Issues: failed for repository Robert - u/Robert    warn: Unable to fetch issues for robert - u/Robert        warn: failed fetching open PRs for repository robert - u/Robert   error: Error refreshing pull request for robert - u/Robert

**Comment by tierninho** [comment]
@R-cloud-pixel It looks like you found the right file, please try to drag and drop that file into the comments here. Are these errors still occurring or did the reinstall fix them?

Here's how to do a fresh installation of Desktop, if needed:

Close GitHub Desktop
Open File Explorer
Go to `%LocalAppData%` and delete the GitHubDesktop directory
Go to `%AppData%` and delete the GitHub Desktop directory
Reinstall GitHub Desktop from http://desktop.github.com

**Comment by R-cloud-pixel** [comment]
Executing get status: git --no - optional - locks status --untracked - files = all --branch --porcelain = 2 -z       launching : 2.4.3 windows 10.0.18363    exe Path: C:\Users\Robert\AppData\Local\GitHubDeskTop.exe        Executing install Global LFS Filter: git LFS install --skip - repo   opening in browser: https://github.com/Robert - u/Robert

**Comment by R-cloud-pixel** [comment]
Executing fetch: git -c credential helper -c protocol version = 2 fetch --progress --prune origin no branches to prune

**Comment by R-cloud-pixel** [comment]
open the repository page on GitHub in your browser     Repository menu or Ctrl shift G     View it on GitHub  I have found: Robert - u/Robert  and then 404 This is not the web page you are looking for

**Comment by R-cloud-pixel** [comment]
https://github.com/Robert - u/  I found this on the repository page.

**Comment by R-cloud-pixel** [comment]
https://github.com/Robert - u/Robert     I have found this on the page when I press on View it on GitHub I did not write completely in the first comment but now it is wright.

**Comment by R-cloud-pixel** [comment]
These errors happened on 2020 - 05 - 06 and 2020 - 05 - 07          but not on 2020 - 05 - 08 account found for repository: Robert  -   Robert  - u       opening in browser: https://github.com/Robert - u/Robert/pull/new/readme - edits     exec Path: C:\Users\Robert\Appdata\Local\GitHubDesktop.exe

**Comment by R-cloud-pixel** [comment]
These errors occurred on 2020 - 05 - 09   2020 - 05 - 10   2020 - 05 - 22   2020 - 05 - 14  on 2020 - 05 - 22 Syntax errors: Unexpected end of JSON input   Errors: API error https://api.github.com/repos/robert - u/Robert: Internal server error

**Comment by R-cloud-pixel** [comment]
2020 - 05 - 14  Type error: failed to fetch      get Fetch Poll Interval: failed for robert - u/Robert
