### ISSUE TITLE
Stashed changes: cannot be performed

### ISSUE THREAD

**Issue by bopoh13** [desktop/desktop#9673]
### Describe the bug

When switching branches, an attempt is made "Stashed changes" to save the changes, but the procedure goes into an endless loop.

### Version & OS

* Version: 2.4.3 (Official site)
* OS: Windows 10 (Version 1909 Build 18363.778) `cmd && winver`

### Steps to reproduce the behavior

1. Create a _separate_ branch through git-console `git checkout --orphan separate`;
2. Open the Github Desktop x64 (without git-console) and Clone repo;
3. Switch to the _master_ branch and make changes to any file;
4. Press 'Current branch (master)' button, and try to switch to a _origin/separate_ branch;
5. Select "Leave my changes on master" and press 'Switch branch' button, press 'Overwrite' button;
6. Seen that the App is trying to made "Stashed changes".

### Expected behavior

It was supposed to switch to a _separate_ branch without saving changes.

### Actual behavior

The App is trying to made "Stashed changes" and goes into an endless loop.

### Screenshots

![err_stash](https://user-images.githubusercontent.com/6163937/80721860-66908280-8b07-11ea-9ada-ba4d6afc268a.png)

### Logs

[2020-04-30.desktop.production.log](https://github.com/desktop/desktop/files/4559005/2020-04-30.desktop.production.log)

### Additional context

The App message after the end of an infinite loop.
``` log
error: unable to unlink old 'vendor/android/phone_scam.csv': Invalid argument
fatal: Could not reset index file to revision 'HEAD'.
```

Added only global settings:
``` ini
[user]
	signingkey = SHA-1
[gpg]
	program = C:\\Program Files (x86)\\gnupg\\bin\\gpg.exe
[commit]
	gpgsign = true
[tag]
	gpgsign = true
```

**Comment by tierninho** [comment]
@bopoh13 Thank you for the issue an apologies for the troubles.

It looks like you are running into something like this:
![Uploading Screen Shot 2020-04-30 at 8.29.46 AM.png…]()

You appear to have two versions of the same file floating around, one version is in the Changes list on the `master` branch and one version is being stashed on `master`. Every time you try to switch branches it attempts to overwrite the stashed file with the working copy. However, this _should_ succeed and not throw you into a loop.

There are a few ways to resolve this, with the easiest being:
- Pick which version of the file you want to keep:
  If the stashed version, then discard the Changes list version by right-clicking on the file
  If the the Changes list version, then go to `View > Show Stashed Changes` and click `discard` button

Let us know how it goes. We will happy to dig into this further if needed.

**Comment by bopoh13** [comment]
@tierninho 
Yes, it was such a menu that suggested "Stashed changes". I pressed the 'Discard' button.

But I still cann't switch between branches until I manually cancel all changes or make a commit.

**Comment by tierninho** [comment]
I believe your repo is in a mixed state. 

Files that had been fetched from a remote before encountering the locked file will appear as modified and unstaged. This prevents pulling again because the files are marked as unable to be overwritten until you manually cancel all changes or make a commit.

You'll need to go through the process of identifying which unstaged files were affected by this mixed state, revert the files, and then you should be able to pull successfully.

**Comment by bopoh13** [comment]
@tierninho 
I did not understand why a file crashed from the index (unstaged), because I only cloned my repository to the local machine.
Thank you for your time.
