### ISSUE TITLE
No Content Change Found

### ISSUE THREAD

**Issue by DevDas** [desktop/desktop#9676]
![Capture](https://user-images.githubusercontent.com/55701713/80742078-66f54180-8b38-11ea-86d9-2c8830f65836.PNG)

I don't Know Some Time This Happens , Sometime It Ask Me To ReLocate The Files But If I Relocate Then It Says It Can't Relocate it Then I Reinstall Github And It Solves Then, Now It Is Saying That -No Content Change !!! How ??? To Many Bug Fix This

---

Template 👇 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@DevDas Thanks for filing this issue. Please fill out the template above so we have a little more info to help triage this issue. Appreciate you meeting us half way.
