### ISSUE TITLE
Provide a way to more easily work with a maintained fork

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#9679]
### Describe the feature or problem you’d like to solve

The 2.4 release improved the way forks work in Desktop assuming people are using their fork to contribute to upstream. We discussed the divergence between people who are using a fork to contribute vs. those who are contributing to a fork independent of the upstream repo in #9170. We were likely too heavy-handed in optimizing the workflow for people using a fork primarily to contribute to upstream, and broke the workflow for those who were contributing to a maintained fork independent of upstream.

The goal with this issue is to ensure people working on forks to contribute are able to benefit from the improvements we made, but also account for those who experienced a regression from the recent release.

### Proposed solution

We're proposing a repo setting that allows users to specify how they're working with their fork, and several things shift based on that:
1. When branches are created, which repo's default branch they're based off of.
2. Which repo's page "View on GitHub" opens in the browser.
3. Which PRs are shown in the PR list, based on which repo the PRs are targeting.
4. Which repo new issues are created in.

We want to ensure that people have the opportunity to make this decision and we aren't making as many default assumptions, so some kind of prompt is likely warranted when they're first opening a fork, and also potentially when cloning a fork into Desktop or creating a fork in Desktop.

### Additional context

This is related to #9670 and #9500.

**Comment by ampinsk** [comment]
## Prompt to ask about fork type

<img width="474" alt="Fork_Decision" src="https://user-images.githubusercontent.com/10404068/80765995-36da7e00-8af9-11ea-9c47-56cfa474ed3d.png">

## Repository setting

<img width="618" alt="Fork_Setting" src="https://user-images.githubusercontent.com/10404068/80765998-380bab00-8af9-11ea-9a92-3919ccd3b611.png">


## Setting behavior

**Contribution Fork:** A fork being used solely to contribute to the upstream repo
**Maintained Fork:** A fork being used for its own purposes

||Contribution Fork|Maintained Fork|
|---|---|---|
|Creating a new branch from default|<img width="400" alt="Fork-New-Branch-Parent" src="https://user-images.githubusercontent.com/10404068/80765694-7b194e80-8af8-11ea-99c8-f5cce61a2992.png">New branch will be created off of the parent repo's default branch|<img width="400" alt="Fork-New-Branch_01" src="https://user-images.githubusercontent.com/10404068/80765691-79e82180-8af8-11ea-85f8-9caa1b949bc0.png">New branch will be created off of the current repo's default branch|
|Creating a new branch from another branch|<img width="416" alt="Fork-New-Branch-Choice-Parent" src="https://user-images.githubusercontent.com/10404068/80765997-37731480-8af9-11ea-875a-4ec526afc734.png">New branch will be created off of the parent repo's default branch|<img width="416" alt="Fork-New-Branch-Choice" src="https://user-images.githubusercontent.com/10404068/80765996-37731480-8af9-11ea-91b8-9dbb8515047d.png">New branch will be created off of the current repo's default branch|
|PR List|<img width="374" alt="PR-List-Parent" src="https://user-images.githubusercontent.com/10404068/80765993-3641e780-8af9-11ea-94b9-34563d141e89.png">Show PRs from the parent repo|<img width="374" alt="PR-List" src="https://user-images.githubusercontent.com/10404068/80765990-34782400-8af9-11ea-884d-0b368797e97e.png">Show PRs from the current repo|
|New Issue|Create issues in the parent repo|Create issues in the current repo|
|View on GitHub|Open the parent repo in the browser|Open the current repo in the browser|

**Comment by edo9300** [comment]
@ampinsk It would be nice to have the option to choose the default behaviour globally, then still being able to toggle it for each repo cloned afterwards.

**Comment by Raymo111** [comment]
Would love to see this happen. Can we get a timeframe as to when this will be released?

**Comment by tierninho** [comment]
The pull request https://github.com/desktop/desktop/pull/9842 is currently in-flight now, so it should go out with the next Beta, in a week or two.  Thank you for the patience.

**Comment by Raymo111** [comment]
Perfect! Thank you!

**Comment by billygriffin** [comment]
This is now shipped to production, so I’m going to close it. We decided to provide a setting upon cloning and then at any point in the repo settings. Thanks for the feedback everyone!

**Comment by elimuhub** [comment]
Open @rafeca
