### ISSUE TITLE
Open in Jetbrains Webstorm Not Working

### ISSUE THREAD

**Issue by b-zurg** [desktop/desktop#9681]
### Describe the bug

Cannot use Jetbrains Webstorm integration to open project.

### Version & OS

Version 2.4.3
Windows 10 (19xx)

### Steps to reproduce the behavior

1. Go to Settings and set the integration to be Jetbrains Webstorm (after installing it)
2. Click on "Open the repository in your external editor"

### Expected behavior

My project should open

### Actual behavior

Did not open but instead see error window.

### Screenshots

![error](https://user-images.githubusercontent.com/57298613/80814640-eb959d80-8bd4-11ea-8f3d-1b2a19a88a26.jpg)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@b-zurg Thanks for the issue.

Based on the screenshot, this looks to be an issue related to the installation of the Webstorm product. Please follow along the instructions here to resolve https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000110030-No-JVM-installations-found-

Let us know if you need further assistance -- happy to help.
