### ISSUE TITLE
organization's private repository not listed

### ISSUE THREAD

**Issue by rakotodavotra** [desktop/desktop#9685]
### Describe the bug

I am the owner of the organization and have private repository in it. My personal repositories are shown correctly, but my organization's repository is not listed in the desktop app. 

### Version & OS

2.1.0-linux1  /  Pop!_OS 19.10

### Steps to reproduce the behavior

1. Go to 'File > clone repositories'

### Expected behavior

My organization's private repository listed 

### Actual behavior

My organization's private repository not listed 

### Screenshots

![all-repositories-in-github](https://user-images.githubusercontent.com/61656074/80832691-cd8c6500-8bf5-11ea-9432-9ef72995d33d.png)
![repository-in-organizaion](https://user-images.githubusercontent.com/61656074/80832707-d4b37300-8bf5-11ea-93d0-97aa5f6b1182.png)
![repositories-listed-in-desktop](https://user-images.githubusercontent.com/61656074/80832728-dda44480-8bf5-11ea-92a3-6c0abe24db49.png)
![repositories-listed-in-desktop2](https://user-images.githubusercontent.com/61656074/80832740-e39a2580-8bf5-11ea-8b30-b227f01dbb2c.png)

**Comment by tierninho** [comment]
@rakotodavotra Thank you for filing the issue. 

Please file an issue over in https://github.com/shiftkey/desktop/releases as we are yet to officially support Linux. 

We appreciate you using Desktop!
