### ISSUE TITLE
2fa not working with new login flow

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#9686]
When attempting to login with 2fa, the screen goes blank after entering in the 6-digit auth code from my Google Auth app. 401 and 410 errors in the console. Can reproduce in Mac/Win, v2.4.4-beta2.

- Start Desktop as a new user and select the user/pw link. 
- Enter credentials and then 2fa code.
- Screen goes partial blank and no browser prompt

![Screen Shot 2020-05-01 at 10 59 06 AM](https://user-images.githubusercontent.com/14828183/80841297-cbe18380-8b9a-11ea-8aad-6f142d776553.png)

Note the 2fa flow in the Preferences works fine, but I still spot the same console errors:

![Screen Shot 2020-05-01 at 11 28 10 AM](https://user-images.githubusercontent.com/14828183/80843041-f0d7f580-8b9e-11ea-8bfd-89b9eb5bbbfd.png)

**Comment by rafeca** [comment]
Ups sorry about that! just realized that the behaviour when I sign in with my github account using user/password is different between development and production: in development after entering my 2fa token I get logged in while in production an additional step to sign in via my browser is asked.

Can it be that the OAuth application used for development has a different configuration/permissions than the production one?
