### ISSUE TITLE
Combine/merge with previous commit

### ISSUE THREAD

**Issue by oleg3790** [desktop/desktop#9689]
### Describe the feature or problem you’d like to solve

I feel like a common problem is the need to make small adjustments to something after you have already committed a change-set, and don't want to add another commit to history. 

### Proposed solution

Would it be feasible to add a feature to combine current changes with the most recent commit? Possibly if the commit button had a drop-down with a new option that allowed users to  "Combine/merge with previous commit" all selected files/changes.

### Additional context

I can assign this issue to work myself if you feel that this is something appropriate to add

**Comment by billygriffin** [comment]
@oleg3790 You should be able to do this by clicking "Undo" to undo the previous commit, which will combine the changes currently in your working directory with those from the last commit. Then you can select the files you want to commit and do so, and that should do exactly what you suggested. One note is that the "Undo" button only appears if you have not yet pushed the commit - we chose to not enable force pushing for this scenario to try to avoid bigger problems. Hope that helps!
