### ISSUE TITLE
display warning message when adding folder which contains repositories

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#969]
re build 0.0.24, OSX 10.11.5

I added a path to a large folder on my local, when following the 'Add Repo' steps like so:

![screen shot 2017-02-21 at 1 19 29 pm](https://cloud.githubusercontent.com/assets/14828183/23185497/777b4590-f838-11e6-91b4-e054b1e2bee9.png)

However, once adding the the path (by typing it in, not choosing folder), the following error surfaced:
`The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes`

![screen shot 2017-02-21 at 1 13 50 pm](https://cloud.githubusercontent.com/assets/14828183/23185504/7e89d824-f838-11e6-961f-62bb6225534b.png)

Error continues to popup each time I select this repo in the dropdown menu.

**Comment by rlabrecque** [comment]
The "create and add" being the same operation while I understand why that decision would have been made... but they are two separate things that do two very different operations and merging them feels wrong. People look for the create repo button and this definitely causes confusion. Good to see that it's being changed.

A separate 'scan for repos' enhancement request is here: #1574

**Comment by iAmWillShepherd** [comment]
> I'm also fine giving the option to turn that folder into a git repo in case that was intentional, but we should punt on that if it'll still lead to that output issue.

I feel it would be much better leaving this feature to the Create portion.

**Comment by SamkitS** [comment]
I am the same problem .. did you find the solution ???

**Comment by joshaber** [comment]
@SamkitS Could you open a new issue so we can track it?

**Comment by ozaal** [comment]
Anyone got a fix?

**Comment by j-f1** [comment]
@ozaal Could you open a new issue and fill out the template so we can fix it or point you in the right direction?

**Comment by rithaknh** [comment]
Getting the same error. I am creating a repository with only one small file in it.

**Comment by j-f1** [comment]
@rithaknh Could you open a new issue and fill out the template so we can fix it or point you in the right direction?

**Comment by Leach456** [comment]
Did anyone find a fix for this? I'm losing my mind.

**Comment by j-f1** [comment]
@Leach456 Could you open a new issue and fill out the template so we can investigate your issue and fix it or point you in the right direction?

**Comment by SHANTH2013** [comment]
@Leach456 Same issue with my Github Desktop: "The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes." However, I haven't imported any repository, I just installed and logged in after few minutes I see this message. This message is not closing either the error message box or the application.
![githubdesktop](https://user-images.githubusercontent.com/5872069/35878723-084f6780-0b71-11e8-90f0-60e42f46468b.PNG)

**Comment by ozaal** [comment]
Delete the ".git" folder where that repository is stored, I had the same issue and that fixed it for me

**Comment by SHANTH2013** [comment]
@ozaal Oh! good to know that, can you please share me the solution?

**Comment by SHANTH2013** [comment]
Sorry, you said to delete .git folder? but I don't have this repository on my computer

**Comment by ozaal** [comment]
I had the same issue, the repository was not saved on the computer but there was a “.git” file created for it on my C drive where it should have been saved. Once I deleted that .git file I never got the error message again.

**Comment by SHANTH2013** [comment]
Yes. I could able to locate.git and now it is backed. Thanks for your quick remedies.

**Comment by shiftkey** [comment]
@ozaal @SHANTH2013 please be careful when you consider removing `.git` folders on disk - these contain the history of a repository and might actually be valuable.

**Comment by SHANTH2013** [comment]
You are absolutely right! But I restored back by reinstalling Git Desktop. Thanks for your response.



Sent with Good (www.good.com)
________________________________

**Comment by GariC88** [comment]
Getting the same error. I am creating a repository! what can I do?  help?

**Comment by SHANTH2013** [comment]
@GariC88: I would recommend you to cleanup existing instead GitDesktop and start over with new. Good Luck 👍🏻

**Comment by jgarza9788** [comment]
I have this issue also

**Comment by GeGeek** [comment]
Maybe that will help, try to delete the .git folder located at C:\Users\Username\ and it will work ;)

**Comment by emma-bxhnkx** [comment]
Is it possible to make it so that the pop up doesn't continually appear, preventing the user from navigating off the window?
