### ISSUE TITLE
Ease down on the updates during lockdown?

### ISSUE THREAD

**Issue by LancePutnam** [desktop/desktop#9692]
### Describe the feature or problem you’d like to solve

There are very frequent automatic updates (like once per week) with no clear way to opt out.

### Proposed solution

Many people are stuck at home around the world due to coronavirus and not everyone has a lightning fast internet connection. Could you please ease down with the updating? As in, not a 100MB forced download every week. Less frequent (once a month) or smaller size would be welcome.

### Additional context

Otherwise, great app. Keep up the good work!

**Comment by steveward** [comment]
Thanks for the feedback @LancePutnam. We are tracking this suggestion in https://github.com/desktop/desktop/issues/3410 -- please follow along there for updates.

**Comment by billygriffin** [comment]
@LancePutnam I just wanted to add that I appreciate your feedback. Unfortunately we've had to release several releases related to Git security vulnerabilities in the past few weeks, and that timing was poor as you noted, but we wanted to make sure people weren't vulnerable to those and that the app was working as expected for them. Apologies.
