### ISSUE TITLE
resource.h and *.rc files are treated as binary files

### ISSUE THREAD

**Issue by ioannis-e** [desktop/desktop#9693]
### Describe the bug

resource.h and *.rc files are treated as binary files, and one cannot view changes or make selective line commits
These files are text files.

### Version & OS

GitHub Desktop v2.4.3
Windows 10

### Expected behavior

Being able to view changes and select which lines to commit in resource.h and *.rc files

### Actual behavior

In preview the following message appears

> This binary file has changed.
> Open file in external program.

**Comment by steveward** [comment]
@ioannis-e thanks for contributing. If Git is detecting the type of your files incorrectly, you can explicitly tell it which file extensions are text by using a `.gitattributes` file in the root of your repository. You can add the following lines to that file to ensure that the file types you mention are recognized as text:

```
*.h text
*.rc text
```

That should get things working for you.
