### ISSUE TITLE
GitHub Desktop - random Log Out

### ISSUE THREAD

**Issue by Dalenmar** [desktop/desktop#9695]
### Problem

So this application keeps logging me out. Whenever I restart my PC, or just sit for long enough, it logs out, kind of. Whenever I try fetch/push something, it throws me an error.

### Solution

In options I have to log out / log in again, and then things work again.

**Comment by steveward** [comment]
@Dalenmar thanks for the report. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by Dalenmar** [comment]
![image](https://user-images.githubusercontent.com/28352937/81020398-64b12100-8e71-11ea-9102-a60f08572318.png)
[2020-05-04.desktop.production.log](https://github.com/desktop/desktop/files/4578154/2020-05-04.desktop.production.log)

**Comment by Dalenmar** [comment]
So it says I have to refresh the token right?
Is it possible to enable auto refresh? Or do something that prevents me logging out? Probably dumb question, but I'm tired of this issue, my friend (the owner of repository we working on) doesn't have this issue, but for me... it happens too often.
I hope the log I applied is enough, I think it contains some info about the issue itself.

**Comment by steveward** [comment]
@Dalenmar does logging out and then logging back in resolve the issue for you? Based on the log file it looks like you have a valid authentication token. I am seeing this error:

```
2020-05-04T08:51:42.417Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin master:master --progress` exited with an unexpected code: 1.
stderr:
To https://github.com/Denzeriko/BaseWars.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/Denzeriko/BaseWars.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

This indicates that your repository got into a state where you need to pull down changes from the remote repository prior to pushing your local changes. GitHub Desktop should detect that and give you the option to pull those changes down, but it doesn't look like that's happening based on the screenshot. You can try to force a pull by going to `Repository` > `Pull` -- let me know if that helps.

**Comment by steveward** [comment]
@Dalenmar I'm going to close this issue out due to inactivity. Let me know if you are still having any issues!
