### ISSUE TITLE
Problem in publishing branch...got this error- error: cannot spawn C:\Users\HP\AppData\Local\GitHubDesktop\app-2.2.4\resources\app\static\ask-pass-trampoline.bat: No error fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by Sm-Skier** [desktop/desktop#9697]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the report @Sm-Skier. Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been modified registry entries, so please check the `Autorun` entry to verify it isn't modified. Let me know if you have any questions about the steps.
