### ISSUE TITLE
Show in Finder/Explorer no longer works

### ISSUE THREAD

**Issue by Clancey** [desktop/desktop#9698]
### Describe the bug

Show in Finder/Explorer used to take you inside the cloned folder where the .git folder is located.  Now it takes you to the parent projects. i.e, `~/Projects/MyRepo`, now it takes you to `~/Projects/`.  When you have a Projects folder with hundreds of projects this is less than helpful.

### Version & OS
Version 2.4.3
Windows and Mac

### Steps to reproduce the behavior

1. Click on Repository Menu Item
2. Click on Show in Finder/Explorer
3. Folder now opens to parent directory instead of the repository directory 

### Expected behavior

I would see a window to `~/Projects/MyRepo`

### Actual behavior

I am taken to `~/Projects/`

**Comment by steveward** [comment]
Thanks for the report @Clancey. I was able to reproduce this issue as well, but only on macOS. Can you confirm you were able to reproduce this on Windows?

**Comment by Clancey** [comment]
I can confirm it is mac only. I thought I saw it on windows.
