### ISSUE TITLE
WSL missing in shell selection

### ISSUE THREAD

**Issue by darkRaspberry** [desktop/desktop#9703]
### Describe the feature or problem you’d like to solve

In option  ->  integration -> shell .  There is no support for WSL. All other shells are available except this one. 

### Proposed solution

WSL support should be added

### Why it should be added

It will integrate WSL2 ability to this app. Also WSL 2 can make this shell much faster.
It provide Linux environment so more app can run , code, test and deployed.  

### Additional context
![Screenshot (22)](https://user-images.githubusercontent.com/56693429/81029413-73fc9280-8ea2-11ea-8f77-cb75a5042a32.png)

**Comment by steveward** [comment]
We added support for opening a WSL shell from within GitHub Desktop in #7821, which is available on the [beta channel](https://github.com/desktop/desktop/#beta-channel) if you'd like to test it out. Let us know if you run into any issues.
