### ISSUE TITLE
Edit, commit and push from desktop itself

### ISSUE THREAD

**Issue by specter78** [desktop/desktop#9705]
### Describe the feature or problem you’d like to solve

Sometimes for bug fix when just one or two lines need to be edited, it it too much of a hassle to open editor, make change, open desktop, commit and push. 

### Proposed solution

Edit file from within desktop. It doesn’t need to be a full-fledged IDE, just a simple text editor.

**Comment by billygriffin** [comment]
Hi @specter78, thanks for the idea. We don't have plans to support inline editing at this time. Though it's tempting to try to do all the things, we try to stay fairly narrowly focused on the GitHub contributing experience, specifically around sharing your work. Thanks again and apologies I can't give you a better answer.
