### ISSUE TITLE
Recent commits wont deploy. to github pages. They show in the repo but not in the launch records.

### ISSUE THREAD

**Issue by dundun305** [desktop/desktop#9707]
### Describe the feature or problem you’d like to solve
Recent commits wont deploy to github pages. They show in the repo but not in the launch records.

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@dundun305 thanks for contributing. This repository is for issues specifically related to GitHub Desktop. To help with GitHub Pages please contact [GitHub Support](https://support.github.com/).
