### ISSUE TITLE
Repository name bug

### ISSUE THREAD

**Issue by turnmeon** [desktop/desktop#9712]
### Describe the bug

I have 2 repos, 1 of them named 'Kalkulator' and the other one named 'turnmeon.github.io'.
but both showed as 'Kalkulator' in my repository list.

### Version & OS
Github Desktop version 2.4.3
Windows 10 home ver. 1909

### Steps to reproduce the behavior

1. Go to repository list
2. See error

see below both repos showed as 'Kalkulator'

![Annotation 2020-05-06 162546](https://user-images.githubusercontent.com/49557224/81154352-659f9b00-8fb6-11ea-9769-ccc2346926b3.png)

but one of them is actually 'turnmeon.github.io'.

![Annotation 2020-05-06 162547](https://user-images.githubusercontent.com/49557224/81154365-689a8b80-8fb6-11ea-84f9-cd7b93ddae5d.png)

**Comment by steveward** [comment]
@turnmeon thanks for the report. This looks similar to https://github.com/desktop/desktop/issues/3855 -- did you rename this repository on GitHub prior to cloning it?

You should be able to resolve this by closing GitHub Desktop, deleting `%AppData%\GitHub Desktop\Cache`, and then restarting GitHub Desktop. Let me know if that doesn't resolve this.

**Comment by turnmeon** [comment]
@steveward thanks, deleting the cache solves the problem 👍

**Comment by tierninho** [comment]
Thanks for the update @turnmeon Glad things got resolved!
