### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by cartershane38** [desktop/desktop#9714]
### Describe the bug

MSI installer acts like it's installing, but never does. EXE file works fine.
### Version & OS
2.4.3; Windows 10 1909
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @cartershane38!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further.
