### ISSUE TITLE
Image Swipe View Removes Visibility of Other Image Options

### ISSUE THREAD

**Issue by justingolden21** [desktop/desktop#9717]
### Describe the bug

Clicking on "Swipe" in the main panel to view the difference between images takes up the entire window, meaning it is impossible to view the other options.

I found a potential workaround, which involves zooming in then out again (<kbd>ctrl</kbd> <kbd>+</kbd>, <kbd>ctrl</kbd> <kbd>-</kbd>) to make the buttons visible again

### Version & OS

Version 2.4.3
Windows 10 Home
![image](https://user-images.githubusercontent.com/30274440/81238665-7997cc80-8fb7-11ea-9385-0aae1b33e372.png)
![image](https://user-images.githubusercontent.com/30274440/81238862-ffb41300-8fb7-11ea-84c8-40b52f8bf603.png)

### Steps to reproduce the behavior

1. Modify an image in a repository
2. Click on "Swipe" on the bottom
3. Four image buttons disappear:

![image](https://user-images.githubusercontent.com/30274440/81238713-9502d780-8fb7-11ea-8721-226156e3ee09.png)

### Expected behavior

The image buttons should remain on the screen

### Actual behavior

The image buttons disappear

### Screenshots

Modified image, after clicking "swipe":
![image](https://user-images.githubusercontent.com/30274440/81238514-258ce800-8fb7-11ea-968d-77cfb3e372f2.png)

Zooming in:
![image](https://user-images.githubusercontent.com/30274440/81238554-3a697b80-8fb7-11ea-995f-fe491fe09dd1.png)

Then zooming back out (the buttons are now visible):
![image](https://user-images.githubusercontent.com/30274440/81238575-45bca700-8fb7-11ea-8839-86e3f557867f.png)

### Logs

N/A

### Additional context

N/A

Thank you for listening to my feedback and improving GitHub Desktop for all users.

**Comment by tierninho** [comment]
@justingolden21 Thanks for this issue! Labeling it a bug and hopefully we can get it fixed soon.

**Comment by justingolden21** [comment]
Thank you for the quick response. It's been frustrating to change zoom every time I want to compare images, so I will be looking forward to the update whenever that may be.

Thank you for looking into this, and have a great day. I'm glad to be able to contribute little bits to this program whenever possible.
