### ISSUE TITLE
push origin error

### ISSUE THREAD

**Issue by Jihobbit8677** [desktop/desktop#9719]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I can't push origin and

warning: failed to restrict file handles (5)

handle #0: 0000000000000110 (type 3, handle info (1) 0
handle #1: 000000000000024c (type 3, handle info (1) 1
handle #2: 0000000000000788 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

	SUPPRESS_HANDLE_INHERITANCE_WARNING=1

error: cannot spawn C:\Users\jihob\AppData\Local\GitHubDesktop\app-2.4.3\resources\app\static\ask-pass-trampoline.bat: Permission denied
fatal: could not read Password for 'https://Jihobbit8677@github.com': terminal prompts disabled

these messages come out
what's the matter and how can I fix this?

**Comment by tierninho** [comment]
@Jihobbit8677 Thanks for filing. Please fill out the rest of the template and attach your logs if possible You can find them under the Help menu in Desktop.

> error: cannot spawn C:\Users\jihob\AppData\Local\GitHubDesktop\app-2.4.3\resources\app\static\ask-pass-trampoline.bat: Permission denied

For this error, please see our help doc here: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789

**Comment by tierninho** [comment]
@Jihobbit8677  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
