### ISSUE TITLE
Custom email address per repository

### ISSUE THREAD

**Issue by MattFenner** [desktop/desktop#9720]
### Describe the feature or problem you’d like to solve

I would like to be able to set custom email addresses (and possibly name) for different repositories.
I have some work repositories and some home repositories on the same machine, and need to use a different email address when committing to each.

### Proposed solution

Needs some thought, but I would probably recommend keeping the global settings. But add a repository setting to be able to override the email address (and name) used for a repository.

**Comment by steveward** [comment]
Thanks for the feedback @MattFenner! This is being tracked in https://github.com/desktop/desktop/issues/9449, and there is a PR being worked on by @say25 to implement this. You can follow along there for updates.
