### ISSUE TITLE
System Cannot find path Specified

### ISSUE THREAD

**Issue by kelle1** [desktop/desktop#9723]
### Describe the bug

I am getting an error when trying to publish a local repo.
![image](https://user-images.githubusercontent.com/44987764/81274129-3c087180-9093-11ea-9396-fb63f608bf3f.png)

### Version & OS

Version 2.4.3
Windows 10

### Steps to reproduce the behavior

1. Create a Local Repository.
2. Click "Publish Branch"
![image](https://user-images.githubusercontent.com/44987764/81274351-838efd80-9093-11ea-8b23-35d92e7dadd1.png)

### Expected behavior

Repo would be published.

### Actual behavior

Getting an error.

### Screenshots

Error:
![image](https://user-images.githubusercontent.com/44987764/81274129-3c087180-9093-11ea-9396-fb63f608bf3f.png)

### Logs

2020-05-07T08:52:52.038Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: JourneyTrend - kelle1 (has token)
2020-05-07T08:52:53.810Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master --set-upstream --progress (took 1.567s)
2020-05-07T08:52:53.811Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin master --set-upstream --progress` exited with an unexpected code: 128.
stderr:
The system cannot find the path specified.
error: unable to read askpass response from 'C:\Users\user\AppData\Local\GitHubDesktop\app-2.4.3\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

Edit:
Forgot to mention, I have seen [this](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) page. First option I have no idea what "see if anything is set" means. I do not have any special characters in my username and I have run as administrator, still same error.

**Comment by steveward** [comment]
Thanks for the report. Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been the modified `Autorun` registry entry, so please be sure to check that to see if it could be causing this. Let me know if you have any questions about the steps.

**Comment by steveward** [comment]
@kelle1 as we have not heard back from you I am going to close this issue out. Let us know if you are still having problems.
