### ISSUE TITLE
I need code that will look for Trojans virus ect.  

### ISSUE THREAD

**Issue by Davidpeche1** [desktop/desktop#9724]
###Describe the feature or problem you’d like to solve: I have a Trojan virus in all my devices, its ni my local network; even my router.
and I have a bootstrap recovery key; https://www.evernote.com/shard/s360/nl/190836040/05e50945-218c-42b2-9623-8a79a6da1128
A clear and concise description of what the feature or problem is.

### Proposed solution I don't have the code for the Trojan but if I get help with it 
I will share the results and as far as the bootstrap recovery key AIP I can help with a the build of a custom rom and Fash image an will share the code for a Samsung Galaxy Note S 10+5G

How will it benefit Desktop and its users? its a win win for everyone who needs the answers to problems.

### Additional context
Thanks for your help if you decide
Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@Davidpeche1 this issue tracker is for GitHub Desktop, and we are unable to assist you with removing a virus from your machine. I would recommend researching antivirus software you can use.
