### ISSUE TITLE
Opening a file via menubar doesn't work

### ISSUE THREAD

**Issue by stefanbauer** [desktop/desktop#9725]
### Describe the bug

Opening a file via menubar doesn't work. It just opens the application but not the file.

### Version & OS

macOS, GitHub Desktop 2.4.3

### Steps to reproduce the behavior

Menubar:

Repository -> Open in XXX doesn't work. 

If you try to use the same via right-click on a file and select `Open in XXX` it works as expected.

### Expected behavior

The file should open in the given application.

### Actual behavior

The file doesn't open. Only the application starts.

**Comment by steveward** [comment]
@stefanbauer thanks for the report. We are aware of the issue with `Show in Finder` not working properly -- see https://github.com/desktop/desktop/issues/9698. I tested out other options in the `Repository` menu and they all worked correctly (`Open in <terminal>`, `Open in <editor>`). Was there a specific one besides `Show in Finder` you were having issues with?

**Comment by tierninho** [comment]
@stefanbauer  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
