### ISSUE TITLE
unable to Clone repository-Proxy CONNECT aborted

### ISSUE THREAD

**Issue by sathiyaraj-github** [desktop/desktop#9726]
### Describe the feature or problem you’d like to solve
Unable to clone the github repository from github desktop client

Error:
Cloning into 'C:\Users\name\Desktop\reponame'...
fatal: unable to access 'https://github.com/reponame.git/': Proxy CONNECT aborted

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@sathiyaraj-github thanks for the report. GitHub Desktop automatically attempts to use your system proxy for Git operations. Are you possibly behind an authenticating proxy? If so, you can configure GitHub Desktop to work with a proxy by running the following command from the command line (you will need to [install Git for Windows](https://git-scm.com/download/win) if you have not already):

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if you run into any issues getting this working.

**Comment by sathiyaraj-github** [comment]
nope, not behind the proxy.
FYI : I am able to access github repository on the browser

**Comment by sathiyaraj-github** [comment]
@steveward 
nope, I am not behind the proxy.
FYI : I am able to access github repository on the browser and able to clone in eclipse (used SSH keys generated)

Please let me know if i need to do any configuration for github desktop?

**Comment by sathiyaraj-github** [comment]
@steveward 
  Please let me know how to diagnose the issue?

**Comment by velasco0606** [comment]
I’m just going through my iPhone now to fix this app from iPhone please delete it all devace please delete

**Comment by codthing** [comment]
@sathiyaraj-github @steveward 
For me, your method has no effect
https://github.com/git/git-scm.com/issues/1588#issue-818219501
