### ISSUE TITLE
black screen when github desktop is opened on notebook - win7-64bit.

### ISSUE THREAD

**Issue by alexandrubetea** [desktop/desktop#9727]
hello,
when i'm trying to open github desktop app, i get an black screen.
Any ideas to fix it ?

thanks

**Comment by steveward** [comment]
@alexandrubetea thanks for the report. Please see [this help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) to see if it resolves the issue for you. Let me know if that doesn't get things working.

**Comment by alexandrubetea** [comment]
Hello,
May you help me please to do what is written there ?i'm not sure if i'm doing right.. maybe you can help me with teamviewer or something ?we can discussed on Facebook ?
thanks a lot for your support    
    Pe joi, 7 mai 2020, 17:03:18 EEST, Steve Ward <notifications@github.com> a scris:  
 
 


Closed #9727.

**Comment by steveward** [comment]
@alexandrubetea here's how you can set an environment variable:

1. Open PowerShell
2. Enter `$env:GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1`
3. Launch GitHub Desktop

I'm opening a PR to add these steps to our documentation.

**Comment by alexandrubetea** [comment]
I did it and it's the same..
    Pe joi, 7 mai 2020, 17:30:08 EEST, Steve Ward <notifications@github.com> a scris:  
 
 


@alexandrubetea here's how you can set an environment variable:
   
   - Open PowerShell
   - Enter $env:GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1
   - Launch GitHub Desktop

I'm opening a PR to add these steps to our documentation.
