### ISSUE TITLE
Github desktop fails to publish local branch with error

### ISSUE THREAD

**Issue by Ipgnosis** [desktop/desktop#9740]
### Describe the bug

I recently create a new repo (Ipgnosis/Python).  However, the local folder I have the code stored in is not publishing to the master.  Error:
The system cannot find the path specified.
error: unable to read askpass response from 'C:\Users\Ipgnosis\AppData\Local\GitHubDesktop\app-2.4.3\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### Version & OS

GitHub Desktop: 2.4.3
Windows 10

### Steps to reproduce the behavior

1. Make change in VS Code.  
2. Go to Github Desktop. Note change displayed in Github Desktop. Click on 'Publish Branch'
3. Error alert renders in GHDT as shown above.
![GHDTerror](https://user-images.githubusercontent.com/18078232/81446621-239a6480-9130-11ea-9795-d2cac83fb30f.jpg)

### Expected behavior

File changes merged with Master branch in Repo

### Actual behavior

GHDT error.  No changes uploaded.

### Screenshots

See above.

### Logs

N/A

### Additional context

None

**Comment by steveward** [comment]
Thanks for the report @Ipgnosis. Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been the modified `Autorun` registry entry issue. Let me know if you have any questions about the steps.

**Comment by Ipgnosis** [comment]
I have been wrestling with this for 2+ hours.  Cut to the chase: the problem is now closed.  However, I can't tell you what cleared it - I tried everything you suggested...and none of them were working.  Then it magically cleared.  Anyway...thanks.
