### ISSUE TITLE
Unable to Pull, Push or Fetch

### ISSUE THREAD

**Issue by IngemannMMDA** [desktop/desktop#9744]
Whenever I make changes I cannot Push it, I cannot click the button that I am suppose to click to Push.

Is that a problem? But the things I change on VS Code, it tracks it really well...

**Version:** Version 2.4.3

**Comment by steveward** [comment]
@IngemannMMDA thanks for the report. Could you share a screenshot of what you are seeing in GitHub Desktop? That may better help me understand the issue.

**Comment by IngemannMMDA** [comment]
Hi,

I have attached a screenshot, what I'm noticing is, that GitHub Fetch
things itself, and I have noticed that my Repository has a "Desktop icon"
even though I made it available for everyone, I mean, I made it on the
website instead of through the Application.

Am I missing something?

><

Inussiarnersumik inuulluaqqusillunga / Med venlig hilsen / Best regards

*Lars Ingemann Larsen*

Assiliinermut side-ra una
<https://www.facebook.com/PixelmagesByLarsIngemann/> toorlugu alakkaruk.
Se min fotograf-side ved at klikke her
<https://www.facebook.com/PixelmagesByLarsIngemann/>.
Check out my photography page by clicking here
<https://www.facebook.com/PixelmagesByLarsIngemann/>.

9000 Aalborg
Danmark

Mail: lars7rii@gmail.com


Den man. 11. maj 2020 kl. 15.49 skrev Steve Ward <notifications@github.com>:

**Comment by tierninho** [comment]
@IngemannMMDA Thanks for the update. It does not look like your screenshot was uploaded. Please try again. If possible, also please share your logs for that day -- see the Help menu in Desktop to find them.

**Comment by grantpezeshki** [comment]
I'm seeing the same problem since upgrading to 2.5 and getting this error: 
fatal: unable to access 'https://github.com/nycehs/AQHub_prototype.git/': Received HTTP code 407 from proxy after CONNECT

**Comment by grantpezeshki** [comment]
To fix I was able to edit the gitconfig file: 
git config --global http.proxy http://:@yourproxyserver:8080/
...but this seems like it should not be necessary

**Comment by steveward** [comment]
@grantpezeshki the team has [made improvements](https://github.com/desktop/desktop/blob/development/docs/technical/proxies.md) towards automatic proxy support, but there are still situations where you will need to configure your proxy settings manually.

**Comment by steveward** [comment]
@IngemannMMDA as we have not heard back from you I am going to close this issue out. Please upload a log file if you are still having issues and we can assist you further.
