### ISSUE TITLE
I cannot publish repository; it says bad credentials

### ISSUE THREAD

**Issue by ProgrammeMitch** [desktop/desktop#9746]
This is my issue.

I have created a new repository on my local machine with the github desktop app.

i am able to commit and view my commits locally.

but when i try to publish the repository on GitHub.com it keeps rejecting me saying bad credentials
![sd](https://user-images.githubusercontent.com/37574625/81483465-4878ff80-9236-11ea-9cea-d452b97fc0a4.JPG)

**Comment by steveward** [comment]
@ProgrammeMitch thanks for the report. Can you go to `File` > `Options` > `Accounts` in GitHub Desktop and try logging out and then logging back in again to your GitHub account? Let me know if that does not get things working for you.

**Comment by ProgrammeMitch** [comment]
Hey Steve,

Thank you very much for taking the time to respond.

The repository was successfully published.

Regards,
ProgrammeMitch

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Ojasvi-97** [comment]
Hey Steve, I'm facing the same issue but when I'm clicking on `File`, `Options` isn't showing up. What do I do ? Thanks in advanced !
![github](https://user-images.githubusercontent.com/16940121/83022309-f6631700-a048-11ea-9113-f588a537e74e.png)

**Comment by phobicdotno** [comment]
Got the same issue on Github Desktop 2.4.2. Same "fix" solved it.

**Comment by Willeduard** [comment]
Gracias por su aporte, pude solucionar el mismo problema.

**Comment by electrify20** [comment]
Hello,

I have the same issue but on a Mac laptop. @steveward I tried to follow you steps in Github desktop but I am unable to location the "option" button.

Can you advise please?
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/81905781/113508068-d5f7c900-9545-11eb-9fb0-b6a11de12a59.png">

**Comment by steveward** [comment]
@electrify20 on macOS it will be `GitHub Desktop` > `Preferences` > `Accounts`. Let me know if that does not get things working.

**Comment by khalidabdou** [comment]
maybe the project is private 
i want to clone my project and i get this message
i fix it by change visibility to public project

**Comment by uday-01** [comment]
had same issue fixed it thank you @steveward

**Comment by bbilly-git** [comment]
Hi, I have the same issue after turning a personal GitHub account into an organization. I've now created a new personal account to manage the organization in GitHub and installed both accounts as apps on Codemagic, but I still have the error message "Cannot access repository xxx Bad credentials", when starting a build in Codemagic. Logging out and in my new personal GitHub account didn't work.
Can someone help? Maybe @steveward?

**Comment by steveward** [comment]
@bbilly-git are you having issues with GitHub Desktop or Codemagic? We can't assist with issues using Codemagic here. I'd recommend reaching out to [GitHub Support](https://support.github.com/).

**Comment by NTpod** [comment]
Hello, I logged out, but I couldn't log in again. it says that it has already issued a token. And I can't link my account back
