### ISSUE TITLE
Deleted branches on the website should sync with the desktop version.

### ISSUE THREAD

**Issue by josh-65** [desktop/desktop#9747]
### Describe the feature or problem you’d like to solve
When I have deleted a branch via the web site it still shows up on the desktop app. This gets confusing as I can still click and use them and messy because it just fills up.

**Comment by outofambit** [comment]
Hi @josh-65 branches merged and deleted in on github.com are automatically removed from desktop after 2 weeks (if they haven't been checked out locally in the meantime). If you'd like to cleanup branches more aggressively than that, you'll have to do that manually in desktop or via the cli. thanks!

**Comment by hmaesta** [comment]
> If you'd like to cleanup branches (...) you'll have to do that manually in desktop or via the cli

How can I do that?

I tried `git remote update origin --prune` on Terminal, but removed branches are still visible on desktop app. Are there any alternatives?
