### ISSUE TITLE
Add folder to .gitignore

### ISSUE THREAD

**Issue by AlbertoCentonze** [desktop/desktop#9750]
As the title says, it would be really useful to add this option when you right-click on a file.

**Comment by steveward** [comment]
@AlbertoCentonze you can ignore a directory in GitHub Desktop by going to `Repository` > `Repository Settings` > `Ignored Files` and adding the following line:

`directory_to_ignore/` 

That will ignore that specific directory in your repository. I hope that helps!

**Comment by steveward** [comment]
@AlbertoCentonze I also forgot to mention that we are tracking this in https://github.com/desktop/desktop/issues/1203 -- you can follow along there for updates.
