### ISSUE TITLE
Provide a list of issues when typing in '#' in commit message

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#9753]
### Describe the feature or problem you’d like to solve

The new [GitHub Pull Requests and Issues Extension for VS Code](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) has a new feature where when you type a `#`, you get a list of issues that are related to you (maybe assigned to you - but I think you can customize this to show all issues).  When hovering over one, you get the information about that issue.  You can select it to insert the issue number into your commit message.  This makes it easy to type out "Added a fix for #2323" without having to switch over to GH.com.  I would love this feature in Desktop.

### Proposed solution

Implement a dropdown that shows relevant issues when typing a '#' in the commit message box.

### Additional context

<img width="689" alt="Screen Shot 2020-05-10 at 8 54 44 PM" src="https://user-images.githubusercontent.com/19867440/81515335-898a1600-9301-11ea-800d-c960dbea3911.png">

**Comment by billygriffin** [comment]
Hi @JosephTLyons, thanks for the idea. The autocomplete with a list of issues exists in Desktop today. Are you not seeing it? One place where it doesn't work as expected is in forks, and we're tracking that in #8509.

<img width="596" alt="Screen Shot 2020-05-11 at 7 01 46 AM" src="https://user-images.githubusercontent.com/5091167/81564986-d992c800-9355-11ea-834a-ffe10f0421fd.png">

**Comment by JosephTLyons** [comment]
Ahh yes, you are right.  I've been working in a fork recently and that is where I tested to see if it existed in GitHub Desktop.  Thanks for the clarification.
