### ISSUE TITLE
DELETE ACCOUNT

### ISSUE THREAD

**Issue by LismithGiTT** [desktop/desktop#9754]
### Describe the feature or problem you’d like to sol

hELLO I WOULD LIKE TO DELETE ACCOUNT LismithGiTT and anything linked to @linnyboop.

Reason I don't use Gitthub. For some reason I have an option to log through GitHub to get into my Microsoft account? is this something you can help with? Is it possible that someones has created a link through GitHub to mimic my Microsoft log in there for trick into logging into my account through a different server?

@linnyboop is something that appeared linked to my name and account which is my work email ( lismith@fmgl.com.au) Can Microsoft teams use gitub to access my microsoft account through the bot app they have in it?

Any answers on why there is a GitHub login to my work account or potentially just using your emblem. Is this even possible?>? If not I would like to remove this account so there is no links to my computer I just cant figure out how.

Thankyou.

lismith@fmgl.com.au

0419333169

**Comment by steveward** [comment]
@LismithGiTT you can read how to delete your account here:

https://help.github.com/en/enterprise/2.13/user/articles/deleting-your-user-account

This issue tracker is for GitHub Desktop -- if you have any further questions about your account please reach out to [GitHub Support](https://support.github.com/).
