### ISSUE TITLE
Cannot close Desktop Github on Mac OS when in full screen mode.

### ISSUE THREAD

**Issue by JFCodes** [desktop/desktop#9757]
### Describe the bug
Cannot close Desktop Github on Mac OS when in full screen mode.

### Version & OS
MacBook Pro (15-inch, 2018) -> macOS Mojave Version 10.14.6 (18G95)

### Steps to reproduce the behaviour
1. Open Github Desktop App
2. Enter full screen mode with mac window 'expand' green button. 
3. Close the window with mac window 'close' red button.

### Expected behaviour
Github Desktop window closes.

### Actual behaviour
Mac tool bar disappears and Github Desktop App does not close.

You must first exit expanded/full screen window state and then close it to finally quite the app.

**Comment by outofambit** [comment]
Hi @JFCodes I was unable to reproduce this locally, though i'm on macOS 10.15.4. Can you share what version of desktop you are using too, please?

**Comment by JFCodes** [comment]
Hey. I am running the latest Version 2.4.3.

https://imgur.com/a/3flnC1R

**Comment by tierninho** [comment]
I was able to reproduce this a few times in a row on v2.4.4-beta4, then it went away. Cannot remember if it took a restart of the app or if it went away on its own, but nonetheless I cannot reproduce it now. I'll be sure to keep checking though.

**Comment by JFCodes** [comment]
Maybe important info

- I usually work with a lot of other apps on full screen mode.
- I work with an external monitor. It happens both on the laptop and on the external monitor.

Also mind, at least for me, its not clear that this may be a problem with the electron instance. Idk to what concerns the window management code - electron's our your own.

**Comment by tierninho** [comment]
I also suspect it is Electron related as there are quite a few full-screen [issues in their repo](https://github.com/electron/electron/issues?q=is%3Aissue+full+screen+) however none are this exact issue. We have some more digging to do.

**Comment by steveward** [comment]
Reported in https://github.com/desktop/desktop/issues/11808, https://github.com/desktop/desktop/issues/12574, and https://github.com/desktop/desktop/issues/12391.

**Comment by steveward** [comment]
When looking at https://github.com/desktop/desktop/issues/15511 I noticed that I was no longer able to reproduce this specific issue. If anyone is still able to reproduce this let me know and we can reopen.
