### ISSUE TITLE
Add "Discard All Selected Changes"

### ISSUE THREAD

**Issue by kolya182** [desktop/desktop#9759]
Current functionally discard only all changes or individual change, either you do 
a) `Discard All Changes` from  menu `Branch` will remove selected and unselected changes.
b) Manually click on each change and `Discard Changes`, but in reality it removes only one changes, so naming referees to plural but not to a single change.
![Screen Recording 2020-05-11 at 1 53 43 PM](https://user-images.githubusercontent.com/3277207/81610820-f5669000-938e-11ea-8217-eff750f5c121.gif)

**Comment by tierninho** [comment]
@kolya182 thanks for the feedback, and apologies if this has caused some extra clicking in your daily workflow.

Currently there is no option to discard multiple individual files at one time. You can use `Discard All Changes` to discard all files, no matter which files are selected, or you can select each file and discard individually.

Reference:
We had a discussion about "Discard All Changes" in #7696 after addressing some UX concerns in #7394. Based on that we shifted the "Discard All Changes" option to the context menu here:
![Screen Shot 2020-05-11 at 11 18 12 AM](https://user-images.githubusercontent.com/14828183/81612905-423f6c00-9379-11ea-9429-fdbe9069e981.png)

If there is anything unique about your workflow, please share. Thanks for using Desktop!
