### ISSUE TITLE
Diffs cannot decide which direction to scroll on macOS

### ISSUE THREAD

**Issue by Boundarybreaker** [desktop/desktop#9763]
### Describe the bug

Scrolling the diff list in either direction on macOS (untested with other operating systems) causes the view to jitter up and down rapidly as it alternates between scrolling up and scrolling down.

### Version & OS

GitHub Desktop ver. 2.4.3, MacOS 10.15.5 Beta 19F83c

### Steps to reproduce the behavior

1. Create a diff longer than the height of the GitHub desktop window.
2. View this diff and attempt to scroll either up or down, using a trackpad (untested with mouse as mine is currently broken)

### Expected behavior

The view should scroll in the proper scroll direction dictated by the OS.

### Actual behavior

While it will sometimes scroll in the proper direction, other times it will scroll in the opposite direction, sometimes causing it to jitter up and down.

### Screenshots
[gif of issue](https://gfycat.com/ConventionalInfiniteHeron)

### Logs

No issue-related logs found

**Comment by steveward** [comment]
Thanks for the report @Boundarybreaker. This looks like another report of https://github.com/desktop/desktop/issues/1380, so I'm going to close this issue out. You can follow along there for updates.
