### ISSUE TITLE
Middle pane has limited size

### ISSUE THREAD

**Issue by Craigjw** [desktop/desktop#9771]
The middle window pane, which shows the file directory text, this has a limited size, which is really quite unhelpful as most of the text is missing.

The size of this window should not be limited when there is space available.  The other window panes can be resized, but why not the middle pane???

Please fix this, as mentally filtering files without being able to see their full paths is really awkward.

**Comment by tierninho** [comment]
@Craigjw Thanks for reaching out with this suggestion. 

Can you add a screenshot if possible so we know exactly which area you are referring to? I believe we have an issue open for this, but once I get the screenshot I will be able to confirm.

**Comment by Craigjw** [comment]
![github issue](https://user-images.githubusercontent.com/2862900/81730675-c97a0600-9485-11ea-861e-d039a3809d58.png)

**Comment by tierninho** [comment]
Many thanks for the confirmation. I am going to role this request into #2745 as they are very similar, so please follow along there. 

In the meantime, you can hover over the file to see the full path in a tooltip. 

We appreciate the suggestion!
