### ISSUE TITLE
GitHub Desktop doesn't restart after closing it.

### ISSUE THREAD

**Issue by IamKraZ** [desktop/desktop#9773]
Now I know this may seem simple, but I don't know how to get it to work. So, here it goes.

When I start GitHub Desktop it comes up fine, but if I close it and try to reopen it it does nothing. It doesn't even show up in the task manager. 
So I rebooted and still the same issue.

I had this problem before and I wound up uninstalling and reinstalling it. The Update.exe doesn't work either.

Is this a bug? or am I doing something wrong?

**Comment by outofambit** [comment]
Hi @IamKraZ thank you for reaching out! That definitely doesn't sound right, could you share what version of Windows you're on and which version of Desktop you're using? (If it doesn't start, can you share where you installed it from? Was this after an update?)

Did you already try uninstalling and reinstalling it this time? Or is that not working either this time?

cc @desktop/support for additional ideas

**Comment by steveward** [comment]
@IamKraZ try deleting the following directory (assuming you are on Windows):

`%LocalAppData%\GitHubDesktop`

Then reinstall the application and let me know if you still run into this issue.

**Comment by IamKraZ** [comment]
I reinstalled it (like I did last time). I am on Windows 10 pro.
Sorry for the late reply.
The update.exe also didn't work as well.

Just wanted you guys to be aware that when an update is out, GitHub Desktop
stops loading.

**Comment by odhran456** [comment]
I think this may be a duplicate issue, see Issue #3757 that is still open.

**Comment by steveward** [comment]
@IamKraZ just to confirm -- did deleting `%LocalAppData%\GitHubDesktop` and reinstalling get things working? I'm going to close this out since we are tracking these issues in #3757 -- thanks for mentioning that @odhran456.

**Comment by IamKraZ** [comment]
Its working after reinstall. But I believe this issue is a repeatable bug.
Every time GitHub Desktop has an update it errors on load. This happened
the last time there was an update. I didn't report it last time because I
assumed it was my error. But when it did it again this time I figured I had
better let you guys know that there may be an update bug. Sorry for my late
replies. I drive for a living and only get a chance to check my mail after
work.

I hope you guys can take a look at the update code and see if there is an
issue with it.

Thanks again for the help and speedy replies.

**Comment by st4rdog** [comment]
Just happened to me. Deleting the most recent %LocalAppData%\GitHubDesktop app worked.

When I closed it, it was taking a long time "Fetching origin: Hang on", then it wouldn't open afterwards.

Windows 7. GitHub Desktop version 2.4.3. Had to delete the 2.5.0 app for it to work.
