### ISSUE TITLE
Support Alacritty as shell integration option

### ISSUE THREAD

**Issue by Spaceghost** [desktop/desktop#9774]
### Describe the feature or problem you’d like to solve

When I look in Preferences -> Integrations, I see a list of terminal emulators. My primary choice is alacritty, but it doesn't show in the list. Kudos to the kitty support though!

### Proposed solution

Add Alacritty to the supported apps if possible.

**Comment by tierninho** [comment]
Thanks for taking the time to create an issue @Spaceghost 

Have a look at our [docs](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) for getting another editor integrated. You can open a PR yourself or wait and see if someone from the community takes it on.

**Comment by say25** [comment]
Closed by https://github.com/desktop/desktop/issues/9774
