### ISSUE TITLE
Authentification error, infinite retry loop. 

### ISSUE THREAD

**Issue by manugd14** [desktop/desktop#9776]
Previously, when cloning a GitLab (or other external host) repo on GitHub desktop, aat some point the app prompted you for your gitab credentials, as it was not able to perform the task with the stored (github) account details.

After today's changes, now it tells you that there is an authentification error, tells you a few possible reasons and let you either retry or cancel. No more options to enter external credentials, so virtually impossible now to clone  private GitLab repo on github desktop.

**Comment by EGGamer** [comment]
Yes, this is happening to me too. Private GitLab repositories just broke. ![Image](https://i.imgur.com/VTO7lDy.png)

**Comment by billygriffin** [comment]
Thanks for letting us know @manugd14 and @EGGamer, and sorry this is causing problems for you. It looks like it may have been a result of https://github.com/desktop/desktop/pull/7080, and we're investigating the cause and potential fix. Apologies that things aren't working for you in the meantime.

**Comment by manugd14** [comment]
Thanks so much for your response. Please let us know how to proceed once there is a solution in place. 
Best wishes

Manuel.

**Comment by manugd14** [comment]
Excuse me, I see you closed the issue. But the issue is still persisting for us. Could you let us know if we are missing any steps to update our client? Thanks.

**Comment by billygriffin** [comment]
@manugd14 Sorry for the confusion. We merged a PR that fixes the problem, but isn't yet released to production. We're going to ship this to beta in the next few days, and at that point you'll hopefully be able to use the beta version, and then in two weeks we're planning to release to production to fix this and a few other things.

**Comment by manugd14** [comment]
@billygriffin thanks for the response. I have tried to install on my computer the beta channel but the installer (linked on the home page of the git repository) seems to install the release version I already have. How should I proceed? Thanks.

**Comment by billygriffin** [comment]
We released this to beta today so downloading the beta channel version in the README should help with this until the next version is released to production. Apologies again!
