### ISSUE TITLE
Rename repository, create new one with old name, Desktop clones the renamed one

### ISSUE THREAD

**Issue by MallNinjaMax** [desktop/desktop#9778]
I want to start my project over with the same repo name, but still retain the old repo. I renamed the old repo on GitHub from "cryptfoot" to "cryptfoot_0". I then created a new repo named "cryptfoot".

When I click "Setup in Desktop", GitHub Desktop, even with all the local repos deleted, clones the old repo, using the link to the old repo. I also tried cloning it from within Desktop both from the repo selection list, and inserting the link directly. It replaces the link I insert with a link to the old repository.  It even does it when that renamed repository is archived.

I looked through all the settings, and I couldn't find anything that gave me control over this. It seems like Desktop is deciding for itself where it wants to clone a repo from, with some kind of cached link. I don't know where it's storing this data.

I had to uninstall Desktop completely (deleting any associated files on my machine just to be safe), and reinstall it. It worked after that.

Desktop 2.5.0
Windows 10

**Comment by tierninho** [comment]
@MallNinjaMax Apologies for the troubles, and glad you got it resolved. You did the correct thing and cleared your cache. Thanks for using Desktop!

ref: This looks like another case of #3855.

**Comment by MallNinjaMax** [comment]
Can you tell me exactly where this cache is, so I can just delete that next time instead of uninstalling the whole program?

**Comment by tierninho** [comment]
Sure thing! Please follow these steps:

Close GitHub Desktop, delete `%AppData%\GitHub Desktop\Cache`, and then restart GitHub Desktop.
