### ISSUE TITLE
Ability to choose SSH over HTTPS remote

### ISSUE THREAD

**Issue by michaelwschultz** [desktop/desktop#9779]
### Describe the feature or problem you’d like to solve

Currently, the Github Desktop app pushes via HTTPS and to change it you must manually change the URI by going to Repository > Repository Settings.

### Proposed solution

It would be great if there were a global setting for using SSH over HTTPS for Github repos so that people who use SSH don't have to manually change the remote every time they clone a repo.

**Comment by steveward** [comment]
Thanks for contributing @michaelwschultz. This is being tracked in the list of SSH issues in #2579, so I'm going to close this out. You can follow along there for updates.
