### ISSUE TITLE
"www.gravatar.com" Certificate expired leadd "Untrusted Server" problem

### ISSUE THREAD

**Issue by codefinger23** [desktop/desktop#9781]
### Describe the bug

The domain 'www.gravatar.com' needs to be accessed when the Desktop starts by https，but the certificate of www.gravatar.com had expired，This leads to untrusted prompt problems，
![image](https://user-images.githubusercontent.com/12182066/81770613-646cf180-9513-11ea-880d-8d23f62d14cc.png)

the certificate
![image](https://user-images.githubusercontent.com/12182066/81770673-91b99f80-9513-11ea-90cc-05471e3eecda.png)

I hope someone can solve this problem，degrade to HTTP or update certificate(I had Emailed to the owner, but no response)

### Version & OS

Desktop: Version 2.5.0
OS: 10.15.4 19E287

### Steps to reproduce the behavior

start Desktop

**Comment by steveward** [comment]
@codefinger23 thanks for reporting this. I'm not seeing this behavior in GitHub Desktop (or in the browser). Is there anything unusual about your network setup that could be causing this? Are you running into any other SSL issues on this machine?

**Comment by codefinger23** [comment]
Thanks for the reminder, but I'm sure it has nothing to do with the network.
The requested address is https://www.gravatar.com，domain administrator(from whois) has not responded so far, I guess there are certain addresses in different regions, such as https://en.gravatar.com/, in some cases, the address www.gravatar.com will be visited;
currently, I have configured the loopback address of www.gravatar.com this problem.
Maybe this is the behavior of a component?
