### ISSUE TITLE
Additional node processes are spun up causing memory overload

### ISSUE THREAD

**Issue by david-shortman** [desktop/desktop#9789]
### Describe the bug

When running the application, node processes start being spawned continually, eating up memory usage.

### Version & OS

GitHub Desktop 2.5.0
macOS 10.14.6 (18G4032)

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. node services begin spawning over time

### Expected behavior

1. Only 1 or whatever normal amount of node services should be spawned.

### Actual behavior

GitHub Desktop goes hog wild

### Screenshots

![Screen Shot 2020-05-13 at 16 04 34](https://user-images.githubusercontent.com/25187726/81859598-778fb980-9533-11ea-8de0-785e29f9a1d7.png)

**Comment by david-shortman** [comment]
I believe the issue might be related to https://github.com/desktop/desktop/issues/9787, since I have a repo with a git hooks

**Comment by steveward** [comment]
@david-shortman thanks for the report. This does look related to #9787. I'm going to add this to that issue.
