### ISSUE TITLE
How can I install (and pin) an older version of Desktop?

### ISSUE THREAD

**Issue by cpcallen** [desktop/desktop#9795]
### Describe the feature or problem you’d like to solve

Unfortunately Desktop 2.5.0 is unusable for me due to #1128.  I'd like to go back to 2.4.3.

Where can I find a downloads for older versions?

How can I pin GitHub desktop to an older version, to prevent it from auto-updating?

### Proposed solution

Provide a link to older versions on the download page.

Provide an option to disable auto-update in preferences.

### Additional context

[Desktop 2.5.0 is now performing unauthorised background pushes](https://github.com/desktop/desktop/issues/1128#issuecomment-628668920).

**Comment by outofambit** [comment]
hi @cpcallen we do not currently support pinning to old desktop versions and that is already an open issue. It sounds like the underlying issue is the `fetchTagsToPush` method running in the background. this is something we'd like to address specifically, could you kindly open a new issue for that? if you include everything you wrote in https://github.com/desktop/desktop/issues/1128#issuecomment-628668920, that would be fantastic. thank you!

**Comment by cpcallen** [comment]
Hi @outofambit,

Having one of the main tools I use every day be broken by its developers (however inadvertently) and having that broken version foisted upon me is a very bad experience—but having them close this bug is a much worse one.

Bugs and breakage happen all the time.  You cannot predict how any individual user will be using the tools you make, and [you cannot predict what changes might break those workflows](https://xkcd.com/1172/).

What you can predict is that _every new version_ of Desktop is likely to break _someone_'s workflow, and even if you're (very commendably) committed to making sure those breakages get fixed, leaving us unable to work in the meantime is **not acceptable.**

Not providing a way to roll back to a known-good version (and pin there) tells me that Desktop is is not a serious tool upon which I can rely—and closing this bug tells me that you do not intend for it to become such.

The fact that on this particular occasion it is unauthorised background network activity which makes the tool unusable for me is irrelevant (except that the fact that [there has been a bug open about this for THREE YEARS already](#1128) tells me that I should not expect it to be fixed soon)—you have broken Desktop for users in the past, and you will break it again in the future.

That is unavoidable.  What is avoidable—or ought to be—is forcing us to stop using Desktop because we are unable to run a known-good version.

I would encourage you to reconsider closing this bug.
