### ISSUE TITLE
Can't clone from url

### ISSUE THREAD

**Issue by SansenSekai** [desktop/desktop#9799]
### Describe the bug

Can't clone from url after last update

### Version & OS

Version 2.5.0 & Windows 7 х64

### Steps to reproduce the behavior

File->Clone repository...
From URL

### Expected behavior

No comments

### Actual behavior

Error without auth window

### Screenshots

![Снимок](https://user-images.githubusercontent.com/48838052/81985385-dd1c9c80-963e-11ea-9941-3481b44275c9.PNG)

### Logs

https://pastebin.com/jTAdPNHQ

### Additional context

What i tried to do:
Logout + Login few times;
Delete Git, Git Bash, all browsers, Git Desktop, clear Credential Manager and AppData;

Use Git Bash and GitKraken for clone this repo - successfully;

What helps:
Clear AppData;
Open Git Desktop;
File-> Add local repo(choose one of repos from this "stash");
Fetch origin;
And i get the auth dialog window.
After this steps I can clone repos from "stash" without any errors.

**Comment by tierninho** [comment]
@SansenSekai Thanks for reaching out. This looks to be the same bug as https://github.com/desktop/desktop/issues/9776.

We have just pushed out a fix in our Beta build which you can download here: https://github.com/desktop/desktop#beta-channel
