### ISSUE TITLE
Perform check for unpushed tags without doing a network request

### ISSUE THREAD

**Issue by rafeca** [desktop/desktop#9800]
## Problem

In order to find out which tags need to be pushed, GitHub Desktop calls `git push --follow-tags --dry-run` and parses its response searching for tags that will get pushed (see https://github.com/desktop/desktop/pull/9576 for details).

This approach gives very reliable information about the tags that need to get pushed and aligns well with the standard way of pushing tags via `git` (which is by using the `--follow-tags` argument), but since it does a network request it has a few drawbacks:

- It's much slower than any other `git` operation (this is why we needed to add a caching layer).
- Doesn't work when the user is offline.

Apart from this, we've discovered an edge case that degrades drastically the experience when using a corporate git server that enforces 2fa on pushes (see https://github.com/desktop/desktop/issues/9787#issuecomment-628676921).

This last scenario is quite severe, since there's no workaround to it and causes major invonveniences to the affected users.

## Proposed solution

A quite simple solution proposed by @niik to avoid doing network requests is to downscope the problem to only track the unpushed tags that get created from Desktop. This way we can just store in a simple list the tags that have been created and treat the tags in that list as unpushed tags.

Then, once a `push` operation finishes correctly, we can clear the list of unpushed tags for that remote.

With this solution, though, we won't be able to rely solely on the `--follow-tags` functionality when pushing, and instead we'll need to modify the `push` command to also include each of the unpushed tags so we can be sure that all of them get pushed.

(this is because the list of unpushed tags will contain every single tag that has not been pushed to the remote, while `--follow-tags`, depending on the circumstances, will only push a subset of them).

## Advantages of this solution

* It doesn't require any network operation (or even any `git` command), so it's way faster.
* Because of the previous point, we won't need any caching layer so it's a much simpler approach.
* Doesn't add potential side-effects to the most common Desktop flows (e.g a user that does not create tags).

## Potential drawbacks of this solution

* We're not going to be able to know if a tag created outside of Desktop has been pushed (we're going to treat all of them as pushed).
* It's possible that the list of unpushed tags gets inconsistent/out of sync (when a push operation fails but some the tags could get pushed, when a user pushes from outside of Desktop, when a tag gets deleted from the remote, ...).
* We're going to possibly have to handle the scenario where there's a conflict when pushing a tag that already exists on the remote.

## Conclusions

Overall, the proposed solution replaces some of the tradeoffs of the current solution that could affect any user (whether they are creating tags or not) by another set of tradeoffs that only affect users when they are actually creating tags. Since creating tags is not a very common action in `git` (a lot of users don't ever create tags and even users who create tags do much more rarely  than e.g creating commits), this seems like a good direction to move.

Another important point is that the identified drawbacks from this solution are mostly cosmetic (an outdated list of unpushed tags won't affect the main behaviour of Desktop, it'll just cause a small temporary inconvinience to users), while with the currently implemented solution we have some issues that are quite severe (like https://github.com/desktop/desktop/issues/9787#issuecomment-628676921).

## Other potential solutions

Another proposed solution was to modify the `refspec` that `git` uses to do the fetches to be able to store the tags for each remote separately (e.g in `refs/remotes/origin/tags/xxx`).

On paper, this solution will solve the tradeoffs of the currently implemented approach while avoiding the new set of tradeoffs from the proposed approach.

The main risk here though is that modifying the `refspec` used for every single `git fetch` command can cause another set of problems and edge cases to users with custom refspecs, and these problems will again affect the users quite severily whether they create tags or not. Therefore, in order to implement this, we would need to spend some time investigating potential edge cases and fix them, so we're instead leaning forward implementing the proposed approach first (which is much simpler), and only considering this alternate solution in the future if we get complains from users.

**Comment by cpcallen** [comment]
I don't have any particular opinion about the proposed solution—in part because I do not fully understand what the overall goal is—but it seems reasonable enough.

I note that my particular issue would be eliminated if were possible to obtain the needed information using `git fetch` instead of `git push --dry-run`, because (in my particular configuration) _fetches_ are not subject to 2FA.
