### ISSUE TITLE
Slow operation on enterprise machine with antivirus

### ISSUE THREAD

**Issue by benplay2** [desktop/desktop#9801]
### Describe the bug

GitHub Desktop runs very slow on my enterprise computer. Typically it is just an annoyance that isn't too terrible, but in some cases such as downloading files from LFS it can take an unreasonable amount of time.

I really like the simplicity of GitHub Desktop, but its poor performance is a notable drawback for me and my team. It just seems odd that something that is so fast and responsive with the command line is so slow when a GUI is essentially calling those same commands.

I should also note: This definitely seems related to antivirus, as for a short period of time my antivirus was not working and it was responsive as it should be.

#### Typical operation: (slow, but okay)
Creating a commit takes about 30-60seconds, half of which is spent with the GUI showing the commit has been created before the summary and description fields have been cleared. If I write in those fields before the entire operation is complete, my text will be cleared.
   - I know this is much slower operation than normal because I have used Desktop on my personal machine and it is lightning fast for these type of operations
   - Apart from the time when my antivirus wasn't enabled, this slow operation has existed for a while (>1yr) so it is not related to a recent update

#### The big issue:
Downloading Git LFS files, especially when initially cloning (I'm not sure if this issue would be present when pulling new files from a previously cloned repository as that's typically not my use case).

In a recent use case, I cloned a repository with >200 LFS files totaling >1.5gb. Most of the size was concentrated in 3 files: 650mb, 280mb, 220mb.

I did a few different tests:
| Utility                       | Clone time |
|-------------------------------|------------|
| GitHub Desktop (work machine) | 29min     |
| GitHub Desktop (personal)     | ~3min      |
| Git Bash                      | ~2min      |
| SourceTree                    | ~2min      |

### Version & OS

GitHub Desktop Version 2.5.0
Operating System: Windows 10 Enterprise 64-bit (10.0.17763)
Antivirus: Symantec Endpoint Protection

#### Sluggish commit operation
1. Select >=1 modified file to stage for commit
2. Type a summary & description into the text boxes
3. Click "Commit to <branchName>"
   - At this point, the operation takes a while (maybe 30-60s)

#### Slow clone with Git LFS files
1. Clone a repository with multiple sizeable files stored with Git LFS

### Expected behavior
Quick, responsive behavior to user interactions, and much faster download speeds.

### Actual behavior

Sluggish UI interaction and slow download of LFS files.

### Logs

Sorry, I cannot share my logs due to security, but here's a snippet:
`2020-05-14T19:34:38.215Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github......../repoName.git C:\Users\myUser\Documents\GitHub\repoName (took 1749.678s)`

### Additional context
When testing the command line performance for cloning the big LFS repository, I tested 2 different variations which both took about 2 minutes.

``` Git
#Basic clone
git clone https://github...../repoName.git repoDestDir

#Command shown in GitHub Desktop log file
#Note: removed '-c credentialhelper=' since I already have my credentials stored... could this be part of the issue?
git clone --recursive --progress -- https://github...../repoName.git C:\Users\myUser\Documents\GitHub\repoName
```

I know this is a very difficult case to reproduce as it is specific to our Enterprise environment, but it does seem to have these same performance issues on all of my coworkers' machines. Maybe this issue can spark some thought into what could be causing sluggish behavior (with antivirus interactions as a large consideration).

Thank you

**Comment by outofambit** [comment]
Hi @benplay2 thanks so much for writing up this detailed report! We've seen this from time to time in the past on windows. @steveward and @niik, have we identified any ways of getting ahead of the curve on this with antivirus software? I know there's likely not a blanket solution but perhaps we could target a couple popular antivirus solutions?

**Comment by steveward** [comment]
@outofambit I've reached out to a couple of vendors in the past to resolve false positives users were seeing (this was mainly in classic Desktop on Windows). A lot of them used to have contact forms where you could report issues with specific applications and then they would push out updates to resolve it. I've also recommended that users reach out to their IT department to see if there are settings that can be adjusted to keep GitHub Desktop from being affected (if they aren't able to themselves). Would it be worth writing up something in our known issues doc about potential mitigation steps?

@benplay2 have you tried reaching out to your IT department to see if there are any settings that could be adjusted to prevent Symantec from scanning GitHub Desktop and affecting performance? Do you see similar performance issues when running Git commands from the command line (Git for Windows)?

**Comment by benplay2** [comment]
@steveward I have not reached out to my IT department yet, but I did do some command line testing which resulted in some interesting results:

## First test: git clone without specification of credential manager
Using the git.exe installed with **git for windows is lightning fast** when running the command:
`git clone --recursive --progress -- https://github...../repoName.git C:\Users\myUser\Documents\GitHub\repoName`
Note that this command uses windows credential manager to lookup the login information.

Using git.exe in the GitHub Desktop folder with the same command prompts for user input since it is not setup to retrieve credentials from the credential manager. Providing credentials manually results in the same operation as the second test below.

## Second test: git clone specifying no credential helper
For this test, I used the following command (which is aligned with the command specified in the Desktop log file):
`git -c credential.helper= clone --recursive --progress -- https://github...../repoName.git C:\Users\myUser\Documents\GitHub\repoName`

Both git for Windows and git from GitHub Desktop prompt for username and password, and I provided my username and token. They begin the clone (at a speedy pace), and **both get stuck after "Updating files"**. I even left this process overnight to make sure it was actually stuck.

I've provided a screenshot below. The process gets stuck at the red line:
![image](https://user-images.githubusercontent.com/24981086/82338280-b356d300-99ba-11ea-938f-be8957309742.png)


## Third test: git clone specifying to use the credential manager
The following command was used for this test:
`git -c credential.helper=manager clone --recursive --progress -- https://github...../repoName.git C:\Users\myUser\Documents\GitHub\repoName`

This **works great for git for Windows**. The clone succeeds in just a couple minutes.

However, the **git executable in the GitHub Desktop folder does not recognize the credential manager**.
![image](https://user-images.githubusercontent.com/24981086/82338993-8820b380-99bb-11ea-9060-606b3a9d5f31.png)

## Command line testing Summary
I hope this helps. I know in general the Git for Windows executable runs quickly, but I wanted to compare with the executable supplied with GitHub Desktop as well just to make sure.

As an added note, for the GitHub Desktop executable I used git.exe inside `...\AppData\Local\GitHubDesktop\app-2.5.0\resources\app\git\cmd`.

These are the versions of git I'm using:
git for Windows - 2.23.0.windows.1
GitHub Desktop git - 2.23.0.windows.5

## One more bit of additional information
When using the GitHub Desktop GUI to clone the repository, the vast majority of the clone is spent displaying status of various LFS files downloading. Maybe the slowdown is specific to this process?
![image](https://user-images.githubusercontent.com/24981086/82342741-00897380-99c0-11ea-9ea9-a8c38ae3bda9.png)

**Comment by benplay2** [comment]
I haven't been able to identify exactly what was going on here, but as of now the performance of GitHub Desktop on my enterprise machine and others in my organization is now much improved and I feel this issue is obsolete.

**Comment by steveward** [comment]
Thanks for following up @benplay2!
