### ISSUE TITLE
Disabled Create Pull Request

### ISSUE THREAD

**Issue by mit-mihohim** [desktop/desktop#9808]
### Describe the bug

"Fetch/Push" button actions correctly but word is wrong.
Perhaps because of above problem, "Create Pull Request"&"View on GitHub" buttons are disabled.
To do "Pull Request" I have to access "github.com" manually.   

GitHub Desktop visually working strange however connection with Remote Repository is fine.

### Version & OS

GitHub Desktop: Version 2.5.0

macOS High Sierra

### Steps to reproduce the behavior

1. Go to 'Desktop GitHub'
2. create 'New Branch'
3. click on "Publish branch"
4. commit some changes
5. button will change to "Push origin"
6. click on "push origin"

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by rafeca** [comment]
Hi @mit-mihohim!

I'm not sure I understand the issue you're describing, is it that you're not able to use the GitHub-specific features that Desktop provides on your repository?

If that's the case, can you check that the remote URL of the repository correctly points to the GitHub repo? You can check that by going to "Repository => Repository Settings":

![image](https://user-images.githubusercontent.com/408035/82196197-b211a180-98f9-11ea-83db-1ff47fc9bc32.png)

**Comment by mit-mihohim** [comment]
Hi @rafeca 

remote URL is correct.
I can use github with command normally but not with github-desktop.

the problem only occurred while working on specific repository so perhaps its repository has wrong components.

I will review files again and see if I can find something.

Thanks you very much for comment.
