### ISSUE TITLE
Support for commit Sign as on web version.

### ISSUE THREAD

**Issue by darkRaspberry** [desktop/desktop#9809]
### Describe the feature or problem you’d like to solve

I'm not able to find the setting to enable commit signature.

### Proposed solution

It can verify commit so that build made after this commit is authentic. and pass all the test.

**Comment by rafeca** [comment]
Hey @darkRaspberry! GitHub Desktop currently does not provide a way to easily configure your git config to sign commits.

Good news is that, as some users report, Desktop should be able to sign your commits if you manually configure your GPG keys on `git` . You can check [this comment](
https://github.com/desktop/desktop/issues/78#issuecomment-460251896) with a link with instructions about how to do so.

You can also subscribe to https://github.com/desktop/desktop/issues/78 to get notified when we add better support for signing commits within Desktop.
