### ISSUE TITLE
no generic credentials found for

### ISSUE THREAD

**Issue by HossienMehdikhah** [desktop/desktop#9810]
I cant Clone Rep From Gitlab.

im Using github 2.5.0 and windows 10 pro im have been installed windows. means that my windows is Clean.

### Logs

2020-05-16T14:51:30.532Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for

**Comment by redubleglen** [comment]
Kindly confirm if it is the same issue with this: https://github.com/desktop/desktop/issues/9816
