### ISSUE TITLE
The procedure entry point SetDefaultDllDirectories could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by joshxyzhimself** [desktop/desktop#9813]
Fixes are as follows:

- https://superuser.com/a/1492065
- https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

**Comment by PaLaAsH-12** [comment]
i have the same issue and i am using windows 7

**Comment by webmaster143** [comment]
Same issue with Windows 7. :(

**Comment by zapryan0v** [comment]
i have the same issue and i am also using windows 7 ...

**Comment by chandanbhagat4** [comment]
i have the same issue and i am using windows 7

**Comment by chandanbhagat4** [comment]
If you get this error during the installation of the POSTMAN app, then install the older version postman app and upgrade the app from the postman.

Thanks,
Chandan.

**Comment by micaiah-effiong** [comment]
> If you get this error during the installation of the POSTMAN app, then install the older version postman app and upgrade the app from the postman.
> 
> Thanks,
> Chandan.

Can you drop a link to any particular version.

**Comment by chandanbhagat4** [comment]
> > If you get this error during the installation of the POSTMAN app, then install the older version postman app and upgrade the app from the postman.
> > Thanks,
> > Chandan.
> 
> Can you drop a link to any particular version.

Please download the Postman any previous version.

**Comment by AlainPascal** [comment]
> > > If you get this error during the installation of the POSTMAN app, then install the older version postman app and upgrade the app from the postman.
> > > Thanks,
> > > Chandan.
> > 
> > 
> > Can you drop a link to any particular version.
> 
> Please download the Postman any previous version.

Find earlier versions of the Postman app [here](https://learning.postman.com/docs/administration/upgrading-to-v8/#installing-earlier-versions-of-Postman)

**Comment by ShivanshMishragit** [comment]
I had this problem when I tried to download Github Desktop

**Comment by KodePizzy** [comment]
I'm facing this issue now and the please i need a solution. i'm using windows 7 ultimate

**Comment by Mulladuncan** [comment]
Also need some help on that ,am using Windows 7
