### ISSUE TITLE
WHILE CLONING A PROJECT ,AFTER 100 % COMPLETION ,THERE IS NO ROJECT PULLLED IN MY GITHUB DESKTOP

### ISSUE THREAD

**Issue by adarshgupta400** [desktop/desktop#9814]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by rafeca** [comment]
Hi @adarshgupta400!

We require issues to fill the provided issue template, this helps us enormously while investigating them. If you're experiencing this error consistently, can you create a new issue with information about your system, the Desktop version you're using and the steps that you take to get the error?

Thanks!
