### ISSUE TITLE
Make it easier to checkout and edit the Wiki

### ISSUE THREAD

**Issue by jeremyzilar** [desktop/desktop#9818]
### Describe the feature or problem you’d like to solve

As a team lead, I am often editing pages in our Wiki to help teams do their work.

Recently, a friend showed me that it is possible to check out a Wiki separately from a repo 🌟🌟🌟🌟 Which is great, except for the fact that through GitHub Desktop the experience is often slower and less clear.

### Slowness when pushing wiki changes through GitHub Desktop
When pushing changes to the wiki through GitHub Desktop, the **Push Origin** button hangs with no indication if it's going to actually push changes... There's no visual indication that it is working, and multiple clicks on the push origin button does nothing _(I'm thinking, oh no, the app crashed. I am going to have to restart it, right? 😬)_.

![image](https://user-images.githubusercontent.com/395641/82155992-9e593300-9846-11ea-8af7-fff52811bc2b.png)

Then, after ~20secs, it all of the sudden switches to having pushed the changes. Did it work? 🤔

![image](https://user-images.githubusercontent.com/395641/82156128-5090fa80-9847-11ea-9562-a2551304b763.png)

### Too many steps to checking out a Wiki
I often work with teams that need to edit the Wiki as part of their daily workflows. These are people who often have the website checked out already. Maybe it can be easier for a team to checkout the Wiki through the GitHub Desktop interface? Currently, they have to:
- get the repo URL
- add `.wiki` at the right place in that URL
- clone that repo (which confuses everyone, and I have to tell them it's not exactly a repo, it's just the Wiki)
- choose a location for that repo (again, letting people know this is not exactly a repo, it's just the Wiki)
- then showing them that they can open that project in ATOM just like they would a website.

### Editing pages in the Wiki on GitHub.com is difficult
Editing pages in the Wiki via the markdown editor on GitHub.com is cumbersome and much harder than the editing and in the markdown editor that you all use for Issues (why is that?).

- Common key commands do not work (bold, italics, command + k, )
- When adding a link, I select the text I want to link, press the link button, then it prompts me to add in the text that I just selected as link text in addition to the URL.
- it's hard to get the URL of other pages in the wiki

This is the main driver for me wanting to edit the wiki in ATOM. I have greater control over the text and can write and format faster and with more confidence. 

### Proposed solution

I don't have a particular solution, I just wanted to say that it would be nice to have less friction when editing the Wiki, and one of those steps is making it easier to check out a wiki in GitHub Desktop for a project that I am already working on. 

---

✋**NOTE:** Most of the people I work with are not developers. They are editors, project managers, designers, photo producers, web producers, writers, etc. — all of whom have learned how to edit our sites on GitHub and use it as a tool for collaborating as a team. These are not people who are familiar with the command line beyond copying a few commands and pasting them in the terminal. GitHub Desktop + ATOM are essential tools for our team, and through them, we've been able to increase the digital literacy of everyone on our team, and provide them with the tools for working in the open. Thank you for doing what you do ❤️

**Comment by rafeca** [comment]
Thanks for filling this detailed issue @jeremyzilar , and thanks a lot for the kind words, I'll share them with the rest of the team ❤️ 

Unfortunately, the issues you describe all have to do with wikis not being properly supported in GitHub Desktop at the moment. This is something we have an issue for in #3839 with more information and some context, so I'm going to close this issue to focus the conversation there. I still suggest you to write there (with the same contents as this issue if you want) since your explanations here can be helpful on the original issue.

Note that we're a very small team and it's not likely that we'll be able to prioritize fixing wikis anytime soon because cloning .wiki repos locally is a relatively uncommon use case compared to many other things we're planning to work on in the near future.
