### ISSUE TITLE
Day counter is counter-intuitive

### ISSUE THREAD

**Issue by shieldgenerator7** [desktop/desktop#9823]
Each commit in the history says how long ago it was committed. This number is helpful but is often counter-intuitive in the way it is displayed. For example, a commit that was made 47 hours ago still displays as "1d", even though no one would intuitively consider that only one day ago.

![image](https://user-images.githubusercontent.com/3438834/82248955-feb7a580-9916-11ea-82ca-8bbeb7611cc5.png)

In this case at least, it should display "2d" because the commit was made nearly two days ago.
The displayed time lapse between now and each commit should be more intuitive. I propose it rounds the hour count to the nearest day:
* 24 hrs ago -> 1d
* 35 hrs ago -> 1d
* 36 hrs ago -> 2d
* 37 hrs ago -> 2d
* 48 hrs ago -> 2d
* 59 hrs ago -> 2d
* 60 hrs ago -> 3d
* 61 hrs ago -> 3d
* 72 hrs ago -> 3d
* etc...

**Comment by rafeca** [comment]
Thanks for the suggestion @shieldgenerator7 ! We're currently using [`moment-duration-format`](https://github.com/jsmreese/moment-duration-format) for showing these shortened dates, but I agree that in some situations this doesn't show an accurate value.

We should mimic the relative time logic that is displayed in GitHub.com, which is quite similar to the logic that you describe.

The GitHub.com logic is implemented by the `<relative-time/>` web component. Source: https://github.com/github/time-elements/blob/master/src/relative-time.js#L59-L89

**Comment by a2937** [comment]
@rafeca Pardon me but I believe this issue needs closing if this is any indication. 

https://github.com/desktop/desktop/blob/607230a3f2111d13103734888bb5d411cdb4c3d3/app/src/lib/format-relative.ts#L17-L23

**Comment by steveward** [comment]
Thanks for pointing that out @a2937! I'll close this out since this has been updated.
