### ISSUE TITLE
Authentication error in the latest version of Github Desktop: version-2.5.0

### ISSUE THREAD

**Issue by k-nagaraj** [desktop/desktop#9825]
Hi Team

Authentication errors in the latest version of Github desktop.
Our internal working tree:
code integration from azure repos to local (includes developing code and commit)

For new project repos, cannot authenticate with azure repos with correct credentials and which was working fine with older version-2.4.2 (uninstalled latest version and installed 2.4.2 version)

this latest version authentication issue with all of our teams.

Please find the screenshot attached
I hope this will be fixed in the next version.

NOTE: 

In the Github logs, same logs are generation which was in the screenshot attached.

![Screenshot_2](https://user-images.githubusercontent.com/65541965/82319363-0ea2b880-99ef-11ea-9dd4-8a09cc4d448d.jpg)

Thanks for the support.

**Comment by nag14481** [comment]
We are authenticating with HTTPS credentials

**Comment by garethrampton** [comment]
Have the exact issue. 2.5 is unusable right now with Azure Repos/DevOps because of this.

**Comment by k-nagaraj** [comment]
2.5 is not un-usable. We can able to work on existing configured repos. But the issue raises for newly created repos and authentication with github with that newly created repos.

**Comment by steveward** [comment]
Thanks for the report. This was initially reported in https://github.com/desktop/desktop/issues/9776. You can [download the beta version](https://github.com/desktop/desktop#beta-channel) of GitHub Desktop to get the beta release with the fix for this issue.

**Comment by k-nagaraj** [comment]
This issue solved by the update. 
Now its working fine for cloning repository.
