### ISSUE TITLE
Ctrl+W shortcut on dialogs sometimes doesn't work

### ISSUE THREAD

**Issue by ruggi99** [desktop/desktop#9826]
### Describe the bug

Depending on where you click on the dialog, Ctrl+W shortcut may not work.

### Version & OS

Version: 2.5.0
OS: Windows 10

### Steps to reproduce the behavior

1. Open Clone Repo dialog
2. Click on the header "Clone a repository" (or other areas that are not interactive)
3. Trigger shortcut Ctrl+W

### Expected behavior

Dialog closes.

### Actual behavior

Nothing happens.

### Logs

Logs not helpful in my opinion.

### Additional context

The problem is that when you press on the header (or other areas..), focus is put on `body` (you can see with `document.activeElement`) and so onKeyDown listener (of the dialog element) is not triggered.
My idea is to put `tabIndex={-1}` to the `dialog` element. So, when header is pressed, focus is put on `dialog` element and `onKeyDown` listener is triggered correctly.
I Think that addressing this issue can make #3629 and #5911 easily fixable

**Comment by tierninho** [comment]
@ruggi99 Good catch, thanks! Confirming this can reproduced and is a Windows-only bug.

**Comment by ruggi99** [comment]
@tierninho thank you.
Can I open PR for that?

**Comment by tierninho** [comment]
Opening a PR should be okay 👍 , but let's allow this issue to sit for one day so others have a chance to weigh in. Thanks!
