### ISSUE TITLE
GitHub Desktop suddenly refusing my credentials

### ISSUE THREAD

**Issue by PhantomNimbi** [desktop/desktop#9829]
### Describe the bug

GitHub Desktop has suddenly started refusing my GitLab credentials. It was working fine befor ebut now it won't even let me push to my repo.

### Version & OS

Version 2.5.0
Windows 10 Home 1909

### Expected behavior

It should be uploading my changes.

### Actual behavior

It fails to authenticate and asks me to provide my username and password. I type them in and it refuses them. I know they are correct as I can login with them fine via browser.

### Screenshots

![Untitled](https://user-images.githubusercontent.com/17615050/82372514-f15ef180-99d0-11ea-83bf-1d7769852ae3.png)

### Logs

[2020-05-19.desktop.production.log](https://github.com/desktop/desktop/files/4652837/2020-05-19.desktop.production.log)

**Comment by billygriffin** [comment]
Thanks for the report. This was initially reported in #9776. You can download the [beta version of GitHub Desktop](https://github.com/desktop/desktop#beta-channel) to get the beta release with the fix for this issue.
