### ISSUE TITLE
Credential Dialog Not Showing when trying to Clone non-GitHub Repository

### ISSUE THREAD

**Issue by RedHoodedWraith** [desktop/desktop#9830]
### Describe the bug

When cloning an external non-GitHub repository via URL, I keep receiving an _Authentication Failed_ error with no option nor opportunity to enter the correct credentials to log in.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to `File` > `Clone Repository`
2. Click on the `URL` tab
3. Enter the URL "https://gitlab.ecs.vuw.ac.nz/rathodrowa/test-project.git" then choose a directory
4. Click `Clone`
5. See Error

### Expected behavior

A dialog requesting for username and password to be entered in order to correctly authenticate.

### Actual behavior

An error dialog titled "Retry Clone" with "Authentication Failed." in the first sentence and no option to input correct authentication details. See image:

### Screenshots

![image](https://user-images.githubusercontent.com/19381986/82395335-6e589c80-9a9f-11ea-817e-c17b0e955d06.png)

### Logs

2020-05-20T01:36:38.162Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'https://gitlab.ecs.vuw.ac.nz/rathodrowa/test-project.git'
2020-05-20T01:36:39.087Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://gitlab.ecs.vuw.ac.nz/rathodrowa/test-project.git D:\OneDrive Folders\OneDrive - Victoria University of Wellington - STUDENT\SWEN303\test-project` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\OneDrive Folders\OneDrive - Victoria University of Wellington - STUDENT\SWEN303\test-project'...
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.ecs.vuw.ac.nz/rathodrowa/test-project.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

### Additional context
I am trying to clone a repo from a privately hosted GitLab server.
I have been successful at logging into repositories from that server in the past using GitHub Desktop.
I've checked the Settings in GitHub Desktop and found no options to log into an external non-GitHub account nor any options to add a token.

**Comment by kai902000** [comment]
Having same issue here

**Comment by davidmiddlewicktpr** [comment]
I am also having this issue - 'Authentication Failed'  with no login dialogue available to enter correct details.

**Comment by rafeca** [comment]
Thanks for the report @RedHoodedWraith!

This was initially reported in #9776. We have recently fixed the issue and published a beta version of Desktop with the fix. You can download GitHub Desktop beta following [these instructions](https://github.com/desktop/desktop#beta-channe).
