### ISSUE TITLE
Add Windows Terminal Preview

### ISSUE THREAD

**Issue by Studio384** [desktop/desktop#9831]
### Describe the feature or problem you’d like to solve

Microsoft released Windows Terminal Preview yesterday. It would be nice if GitHub Desktop was able to detect it.

### Proposed solution

Adds an option to the shells available to use.

### Additional context

N/A

**Comment by rafeca** [comment]
Hey @Studio384! Thanks for this suggestion.

Windows Terminal support was added a few versions ago (see https://github.com/desktop/desktop/pull/9047). You can configure the preferred terminal app from the Integrations pane on the settings modal.

I have just upgraded my local installation of Windows Terminal to v1.0 and Desktop keeps detecting it correctly.

I'm going to close this issue, but please feel free to reopen with repro steps if for some reason you can't manage to get it working.

**Comment by Studio384** [comment]
Windows Terminal != Windows Terminal Preview

Terminal Preview is the beta release channel for Windows Terminal. It cannot be detected by Desktop right now.

**Comment by rafeca** [comment]
Thanks for the clarification @Studio384 !

You're right then, I think support to it can easily be added by following the same approach we use for Windows Terminal ([source](https://github.com/desktop/desktop/blob/development/app/src/lib/shells/win32.ts#L338-L356)). Would you be open to contribute on this?

**Comment by Studio384** [comment]
I've never done it before, but will give it a try.

**Comment by say25** [comment]
So this sorta isn't required. Basically trying to debug myself https://github.com/microsoft/terminal/issues/7188 it would appear that both Windows Terminal and Window Terminal Preview share `wt.exe`. Basically you could uninstall Windows Terminal and only leave Window Terminal Preview and the existing integration would open Windows Terminal Preview. 

I believe effectively the Windows Terminal would need to expose a different Exe or hook to differentiate between the two.

**Comment by Splatterxl** [comment]
ermmm... I'm not that good with this kinda stuff, but maybe you could check for the `wt.exe` *inside* a containing folder?

**Comment by AndreiMaga** [comment]
As far as I know of how wt and wtp work, they both use the same executable to run, which is exposed at ```C:\Users\<User>\AppData\Local\Microsoft\WindowsApps\wt.exe```. And you can choose the one you want to actually run by changing the alias of the wt.exe from inside the App execution aliases ( [source of information ](https://github.com/microsoft/terminal/issues/7188#issuecomment-677699216)). So the desired behavior can be obtained from Windows itself so desktop won't have to add support for a beta version of something it already has. TL:DR, Desktop already supports Windows Terminal Preview, you just have to turn it on from a windows setting.

**Comment by just1a-person** [comment]
@AndreiMaga You are correct! GitHub Desktop already supports Windows Terminal Preview. You have to choose in the app execution aliases setting (in Windows Settings)

**Comment by jenniferlahr5** [comment]
I would like to have a chance to work in your company and help it wrow.I am very ambitious and adventurous

**Comment by yakryder** [comment]
Hey there, long time listener first time caller! Thanks for building such an awesome program :)

Came here browsing open issues, couldn't help but notice there seems to be not just a workaround but in fact a good working solution outlined by @AndreiMaga. On the surface it's hard for me to think of a good reason to support launching out into sometimes windows terminal, sometimes windows terminal preview. In the seemingly unlikely event that a user's on-the-fly shell needs are really that precise and they want some nice UX with it, it seems reasonable they could shoulder the burden of figuring out the simple piping to flip the alias. But then again, I've happily used GHD for years and didn't even know this was a feature until today 😅

@Studio384 Sorry I guess I'm trying to broker an issue closure. Were you able to implement the suggestion for launching wtp?

**Comment by Aminadad27** [comment]
#13721

**Comment by Aminadad27** [comment]
- [ ] 

- [ ] 

- [ ] [html.git](url)

**Comment by Aminadad27** [comment]
\{□□€.!

**Comment by Aminadad27** [comment]
😀

**Comment by Aminadad27** [comment]
:+1: 5:7:1:3:7:3:1:1:1:0

**Comment by mon-jai** [comment]
@tidy-dev It seems that Windows Terminal Preview isn't available as shell option in the latest version of GitHub Desktop.

Can you reopen the issue?

**Comment by steveward** [comment]
@mon-jai have you verified that Windows Terminal Preview has been configured correctly? See [this comment](https://github.com/desktop/desktop/issues/9831#issuecomment-736704845) for details.

**Comment by mon-jai** [comment]
Yes AFAIK, but still, GitHub Desktop opened the stable version instead.

![image](https://user-images.githubusercontent.com/91261297/168145375-2ba571ce-124a-48a8-aa5c-34a704f628d9.png)

---

Edit: it works after turning off the "Terminal Preview" option, then turning it back on.

Maybe we should include https://github.com/microsoft/terminal/issues/7188 in documentation. so that it would be more easily to be found?

**Comment by mon-jai** [comment]
In addition, I think it would be better if all versions of Windows Terminal could be available as options regardless of system configurations.
