### ISSUE TITLE
Can you provide the ability to rename

### ISSUE THREAD

**Issue by justsuccess** [desktop/desktop#9835]

**Comment by justsuccess** [comment]
![image](https://user-images.githubusercontent.com/22443909/82515070-e67b9c80-9b49-11ea-8893-8135657b225e.png)

**Comment by rafeca** [comment]
Thanks for filling this issue @justsuccess !

We're tracking this enhancement in https://github.com/desktop/desktop/issues/7856 so feel free to subscribe to that issue to get updates (or comment if you want to share your use case for having multiple copies of the same repository).
