### ISSUE TITLE
Add Linux Support

### ISSUE THREAD

**Issue by micaelillos** [desktop/desktop#9841]
Add Linux Support

**Comment by goldyydev** [comment]
Already availabel at https://aur.archlinux.org/packages/github-desktop-bin/

**Comment by steveward** [comment]
Thanks for contributing @micaelillos.

At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

We are also tracking official Linux support in https://github.com/desktop/desktop/issues/1525.
