### ISSUE TITLE
Application does not authenticate to a network repository

### ISSUE THREAD

**Issue by arbourp** [desktop/desktop#9843]
### Describe the bug

Install the desktop application and attempt to clone a repository from the internet, not github, it fails to request any authentication.

### Version & OS

2.5.0  On Windows 10.18362.175

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/4433169/82597471-037a9480-9b77-11ea-8af6-ab4f7ef7bfc3.png)

We then get this error
![image](https://user-images.githubusercontent.com/4433169/82597494-0d9c9300-9b77-11ea-9156-0cab2f846949.png)

It isn't clear why the application isn't requesting authentication.  It doesn't display anything between those two windows.

If we manually clone the repository and then add it into the app from the hard disk, then the application will request a login and password before fetching or other activities.

### Expected behavior

Expect the application to prompt for a login to the git repository

### Actual behavior

Fails telling me I haven't logged in.

### Screenshots

Attached above

### Logs

N/A

**Comment by tierninho** [comment]
Hey @arbourp ! Thanks for filling this issue and apologies for the caused inconvenience.

What you describe seems the same issue as described in #9776, feel free to download [the Desktop beta](https://github.com/desktop/desktop#beta-channel) since this issue has been fixed there. If this doesn't work please reopen this issue so we can investigate further.

**Comment by AHMED0504492442** [comment]
Greetings to you, please, I am a user, I learn from you, please consider, and appreciate mistakes, ... and inform me right and correct

**Comment by rafeca** [comment]
Hi everyone! The fix has already been shipped to the stable version of Desktop (v2.5.2), so please upgrade to it if you're experiencing this issue.

**Comment by hoangytm** [comment]
I am facing the same issue when I log in gitlab.

**Comment by nitroman123** [comment]
I cant clone my repo in gitlab... still i have to download the beta version ?

**Comment by samanthewebdev** [comment]
i have similar problem to this before i was seeing this error but not its just not cloning or even if it works it still the same in github live url?
