### ISSUE TITLE
Cannot restore stashed changes

### ISSUE THREAD

**Issue by Maddaddam42** [desktop/desktop#9844]
While trying to restore changes to my branch from the stash I get this error warning

```
warning: refname 'stash' is ambiguous.
warning: refname 'stash' is ambiguous.
warning: refname 'stash' is ambiguous.
warning: refname 'stash' is ambiguous.
warning: refname 'stash' is ambiguous.
warning: refname 'stash' is ambiguous.
```

Github desktop Version 2.4.3

### Steps to reproduce the behavior

1. Go to branch
2. Click on stashed changes
3. Click on restore stash

my changes should get pulled back into the branch

my changes stay in the stash

**Comment by tierninho** [comment]
@Maddaddam42 Thanks for filing this and apologies you got stuck.

It sounds like you have a branch named "stash" which would leave you in the state. If you try to change to that branch, it should leave you in a detached HEAD state.

Easiest way to rename the branch:

- Open up the Command line tool under the Repository menu
- Type: `git branch -m <oldname> <newname>`. 
- Go back to Desktop and try to restore the stash in the branch that was affected.

Let us know how it goes!
