### ISSUE TITLE
please remove the "create a branch based on" dialog or default selection to the current branch.

### ISSUE THREAD

**Issue by dexmagic** [desktop/desktop#9845]
### Describe the feature or problem you’d like to solve

When using git, new branches are always based on the branch that is checked out. For example, no where in the history of git, has the git command line tool asked the question "Create branch based on ...". Any git client can answer that question for for free by simply using the current branch.

Because of this, when the create branch dialog popped up, I never even noticed the text asking me to pick the branch to base my new branch on. I only saw the text box that asked me for the new branch name. But my eye never even registered that the rest of the text box was there, asking me to pick a branch. And the idea that I would have to pick what branch to use as a base never entered my mind.  

Why would anyone even look for that when for many years this particular selection has never been part of the git workflow?

The end result of this issue is that today, while working very fast, I created a new branch on the wrong base. It threw off the entire release pipeline for a time.

### Proposed solution

Please do this:

1. remove the entire "Create branch based on..." selection choice. The only thing that dialog box needs from me is the name of the new branch. the branch it's based on is always the current branch.

2. If you absolutely HAVE to have this dialog box, then please (for the love of all that is sane in the world), default the selection to the current branch.

3. If you can't do number #1 or #2, then please give me an option to turn off the "Create branch based on..." in a settings somewhere, and also an option to default to the current branch.

### Additional context

Please take more care and time to understand the developer's work flow as it's designed in the original git command line tool. We often have to make changes extremely fast and we don't have time to absorb seemingly off-hand dialog boxes like this one.

![202005211717-githubdesktop-branch-feedback-dialog](https://user-images.githubusercontent.com/43413210/82619342-878a4780-9b8a-11ea-8de4-25a1d0c5660e.PNG)

![202005211717-githubdesktop-branch-feedback](https://user-images.githubusercontent.com/43413210/82619353-8ce79200-9b8a-11ea-8ffd-41217242b75b.PNG)

**Comment by rafeca** [comment]
Hey @dexmagic ! Thanks for creating this issue and being so thoughtful in your explanations.

To give you a bit of context, initially we used to select by default the current branch in that dialog but a few years ago we changed this behaviour intentionally to select the default repo branch instead. This was the reasoning (see https://github.com/desktop/desktop/issues/1137 for more details):

> We've operated under the assumption that we should switch what branch is selected by default from the current branch to the default branch. This is probably the most contentious issue and I'd love some discussion around it. Our thinking was that creating a branch that's not based off of master (in the majority of cases) is the exception rather than the norm. The counter argument to that is that it deviates from how the CLI works by default.

I personally think that this reasoning is still valid. Our thinking hasn't changed regarding the most common user workflow, where a branch is created to start a new feature and end up creating a Pull Request: The current behaviour aligns well with the workflow in GitHub, where by default Pull Requests get merged on the default repository branch.

I've done a search through our issues and couldn't find any other complain about this behaviour, so I think it's fair to assume that the current behaviour satisfies most of our users (unfortunately we currently don't have metrics to know the percentage of people that select each of the options, but we could add some logging if we see more people complaining to get another datapoint).

Maybe, we can try to tweak something in the design of that dialog to reduce the chances that a user misses that option, based on your comment here:

> Because of this, when the create branch dialog popped up, I never even noticed the text asking me to pick the branch to base my new branch on. I only saw the text box that asked me for the new branch name. But my eye never even registered that the rest of the text box was there, asking me to pick a branch. And the idea that I would have to pick what branch to use as a base never entered my mind.

I cannot think of any actual solution at the moment, but it's possible that a small tweak can improve things substantially.

**Comment by dexmagic** [comment]
Thanks for taking the time. I don't want to make more work for people or second guess product decisions. 

Yes - the commenters are right. People often start a new branch based on default. That's why I'm hoping some additional settings will be of value.   Settings are perfect for this kind of situation.

When it comes to steps that involve set procedures (e.g. switching branches) - if I can select settings that coerces github desktop to omit or include specific steps then I can more easily incorporate it into my normal workflow.

**Comment by adymoussa** [comment]
Under [Options > Git] you already have these options:
* main
* master
* Other...

Just add "Current branch", please. Would that really be such a big problem?

**Comment by Rexogamer** [comment]
That's the default branch name for new repos - I agree that a setting in the Git section would be good, but this is not related to that. (The naming of that setting is a bit confusing, though.)
