### ISSUE TITLE
how to change external editor in github desktop

### ISSUE THREAD

**Issue by SagarShresthaNP03A180082** [desktop/desktop#9852]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hi @SagarShresthaNP03A180082, you can select which external editor to use by opening Preferences `Github Desktop  -> Preferences` on macOS or Options `File -> Options` on Windows.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/634063/82794252-72efcd00-9e72-11ea-9583-d6dd2dcacb83.png">

For more details and a list of supported editors, see https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

**Comment by Fawn-verse9** [comment]
how do you add an external editor

**Comment by niik** [comment]
@Fawn-verse9 How to build support for a new editor in GitHub Desktop is documented in the same document I linked to above: https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md
