### ISSUE TITLE
No support for IntellijIDEA by JetBrains on Windows

### ISSUE THREAD

**Issue by Ghoulboy78** [desktop/desktop#9853]
### Describe the feature or problem you’d like to solve

The problem is that I am starting to develop Java, and each time I try to open, I have to open IntellijIDEA and then navigate to the directory each time

### Proposed solution

It would help greatly those who are using GitHub Desktop and doing Java programming with IntellijIDEA.

### Additional context

I'm afraid I do not know TypeScript, and am unfortunately therefore unable to submit a pr with a fix.

**Comment by steveward** [comment]
Thanks for requesting this @Ghoulboy78. I'm going to drop this into https://github.com/desktop/desktop/issues/9453 where we are tracking broader support for Jetbrains IDEs.
