### ISSUE TITLE
Allow configuration of custom commands

### ISSUE THREAD

**Issue by RithikaChowta** [desktop/desktop#9856]
### Describe the feature or problem you’d like to solve

Add an option to configure custom commands for common use cases like commits so that extra parameters can be configured if needed. 

### Proposed solution

Useful for use cases where we may want to add parameters like --no-verify to skip pre-commit hooks

**Comment by tierninho** [comment]
Thank you for the suggestion @RithikaChowta !

We are not quite at the point in development to add custom preferences but we will take note of your request and re-evaluate it at a future date.

If you think there are any additional details that would be helpful for us, please edit your original comment. Much appreciated!
