### ISSUE TITLE
Switching branch runs in a loop

### ISSUE THREAD

**Issue by saakshig** [desktop/desktop#9860]
### Describe the bug

I am trying to switch branches but it keeps running in loops and switch doesn't complete for long. Also, I am not able to switch to any other branch. If I try, it stays on the old branch.

### Version & OS

version 2.5.0. MacOS Catalina 10.15.4

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1.  Click on Branch tab
2.  Select another branch
3. Branch doesn't get switched but keeps running in loop

### Expected behavior

Branch should get switched

### Actual behavior

Branch doesn't get switched but keeps running in loop

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

[2020-05-25.desktop.production.log](https://github.com/desktop/desktop/files/4676023/2020-05-25.desktop.production.log)

**Comment by saakshig** [comment]
Another log: [2020-05-25.desktop.production.log](https://github.com/desktop/desktop/files/4676047/2020-05-25.desktop.production.log)

**Comment by steveward** [comment]
@saakshig thanks for the report. Are you seeing any notifications appear when you switch branches (to prompt you to stash or bring your changes)? Do you have uncommitted changes in your working directory?

This is the error I'm seeing repeated:

```
2020-05-25T07:47:52.309Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress partialSB --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	src/classes/submitCCRValidationTest.cls
Please commit your changes or stash them before you switch branches.
Aborting
```

**Comment by tierninho** [comment]
@saakshig  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
