### ISSUE TITLE
 Problems with Spanish characters, á, é, etc

### ISSUE THREAD

**Issue by gjrivero** [desktop/desktop#9863]
### Describe the bug

Problems with Spanish characters, á, é, etc

Is not working.

Problems with Spanish characters, á, é, etc
My source showing unreadable character.

### Version & OS
GitHub Desktop 2.5.0
Windows 10

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@gjrivero thanks for the report. Where specifically are the characters unreadable in GitHub Desktop? Could you share a screenshot of the issue?

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
