### ISSUE TITLE
Use Repository Templates to Create New Repos 

### ISSUE THREAD

**Issue by bbertucc** [desktop/desktop#9866]
You can create a repo from a template on github.com, but you can't via GitHub desktop. 

Using the template tool on GitHub desktop would save me the step of going to github.com and cloning the new repo back to my local machine.

**Comment by steveward** [comment]
@bbertucc thanks for contributing! There's an open tracking issue about this feature in https://github.com/desktop/desktop/issues/7902, so I am going to close this issue out. You can follow along there for updates.

**Comment by bbertucc** [comment]
Thanks!
