### ISSUE TITLE
Provide a way to group the repository list

### ISSUE THREAD

**Issue by OysteinAmundsen** [desktop/desktop#9867]
### Describe the feature or problem you’d like to solve

I work as a consultant and I therefore have a lot of git repositories I switch back and forth from. But I lack a way of organizing them so that I can find them more easily. 

### Proposed solution

I would like a way to group the repositories using a label of my choosing. This would make it way easier to find which repositories belong together.

**Comment by tierninho** [comment]
@OysteinAmundsen Thanks for the suggestion!

We took this scenario into account as part of #6460, which included a range of possibilities and trade-offs that were made to accommodate multiple requests and features around repository organization. At this point, we are holding off on custom grouping and labeling for now. We have two previous issues, [here](https://github.com/desktop/desktop/issues/1533) and [here](https://github.com/desktop/desktop/issues/2324) that cover such requests. They will be reopened when the time comes to re-examine repository organization. Thank you for using Desktop.
