### ISSUE TITLE
"Push 1 commit to origin" constantly shows

### ISSUE THREAD

**Issue by uus-it** [desktop/desktop#9868]
### Describe the bug
The fetch/push button constantly shows "Push origin" with 1 commit, even if there is nothing to push.

### Version & OS
Version 2.5.0
OS: Windows 10 Pro

### Steps to reproduce the behavior

1. Open Github Desktop
2. Look at the push/fetch button
3. See that it always shows "Push origin" with 1 commit

### Expected behavior
Should not show that one commit is waiting to be pushed when there are no commit that can be pushed.

### Actual behavior
The fetch/push button constantly shows "Push origin" with 1 commit, even if there is nothing to push.

### Screenshots
![image](https://user-images.githubusercontent.com/55781925/82873715-333de980-9f35-11ea-9664-c7d573b70c58.png)

**Comment by steveward** [comment]
@uus-it thanks for the report. Does the commit indicator update when there are multiple commits to be pushed or is it stuck on 1?

**Comment by uus-it** [comment]
@steveward It updated if there are multiple commits, but was at least stuck on 1.

But oddly I just checked again now, and the bug seems to be fixed. I can't reproduce it now.

**Comment by steveward** [comment]
@uus-it thanks for the update. I'm going to close this out since we have not seen this reported elsewhere, but let us know if you run into it again.
