### ISSUE TITLE
gps

### ISSUE THREAD

**Issue by Furion199** [desktop/desktop#9872]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Furion199** [comment]
fasdfsfd

**Comment by Furion199** [comment]
dada

**Comment by steveward** [comment]
@Furion199 this issue tracker is for GitHub Desktop. If you are having problems with GitHub Desktop please fill out the template so that we can assist you further. Thanks!
