### ISSUE TITLE
 README.md 

### ISSUE THREAD

**Issue by wiji2523** [desktop/desktop#9874]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@wiji2523 please fill out the template if you are having issues with GitHub Desktop so that we can assist you further. Thanks!
