### ISSUE TITLE
Can not clone ANY repositories

### ISSUE THREAD

**Issue by L1nd** [desktop/desktop#9876]
Hey guys,

I have the following problem:
I cannot clone repositories on my PC. I get the specified error message every time (It does not matter wheter the repo is public or private).
What I've already tried:
- log out and log in again
- delete all auth-tokens
- reinstall the program

I have no idea what it could be. I would be happy if you could help me.
Everything works fine on my laptop.

Jannick

![Anmerkung 2020-05-27 101611](https://user-images.githubusercontent.com/32546825/82995290-b463b200-a003-11ea-8390-7b6ec1f1941e.png)
[2020-05-27.desktop.production.log](https://github.com/desktop/desktop/files/4687459/2020-05-27.desktop.production.log)

**Comment by L1nd** [comment]
UPDATE:

The problem must be my PC. It is not possible for me to clone this repo via Git-Bash or other software.

**Comment by steveward** [comment]
Thanks for the report @L1nd. Here's the error I'm seeing in the log:

```
2020-05-27T08:15:55.677Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/L1nd/LAPI.git C:\Users\X-USER-X\Documents\Development\Java\LAPI` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\X-USER-X\Documents\Development\Java\LAPI'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

This is interesting because you are cloning via HTTPS but Git is throwing a SSH error that it can't find your public key. Do you have anything set in your `.gitconfig` that could be forcing Git to use SSH instead of HTTPS on this machine? To check this you can run `git config --list` and look to see if there is a line like this:

`git config --global url."git@github.com:".insteadOf "https://github.com/"`

Let me know what you find.

**Comment by L1nd** [comment]
Thanks for your answer @steveward, 
you are right!
Here is the output:

```
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=Jannick Marcel Vieluf
user.email=jannick@vieluf.eu
url.git@github.com:.insteadof=https://github.com/
core.autocrlf=true
```

**Comment by steveward** [comment]
Removing that line from your `~/.gitconfig` should get things working for you. You can run `git config --global --edit` to launch directly into that file quickly. Let me know if you have any further issues!

**Comment by L1nd** [comment]
Thank you @steveward, now it works all fine!
