### ISSUE TITLE
signing in from desktop

### ISSUE THREAD

**Issue by t243** [desktop/desktop#9877]
### my downloaded app doesnot allow signing in

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@t243 you can [read this article](https://help.github.com/en/desktop/getting-started-with-github-desktop/installing-and-authenticating-to-github-desktop) for information about how to log in to your GitHub account in GitHub Desktop. If you are running into any specific errors when authenticating please let us know.
