### ISSUE TITLE
bug about clone https://github.com/MahApps/MahApps.Metro 

### ISSUE THREAD

**Issue by FriedrichWilhelmNietzsche** [desktop/desktop#9878]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots
![image](https://user-images.githubusercontent.com/30073072/83020628-5498f580-a05b-11ea-905b-5f18705edcd6.png)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@FriedrichWilhelmNietzsche could you fill out the template and also upload a log file from GitHub Desktop? You can access the logs by going to `Help` > `Show Logs...`. Please upload a log file from the day you experienced the issue.

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
