### ISSUE TITLE
Push partial changes

### ISSUE THREAD

**Issue by Gabrielfcs** [desktop/desktop#9880]
### Describe the feature or problem you’d like to solve
Currently we received a message saying that it is not possible to merge with local changes, but it would be interesting if when making changes, committing some of them and pushing these commits, it was possible to merge without losing the current changes.

### Proposed solution

I think a solution for this is, instead of showing an error message saying that the merge will replace local changes, show another message stating that for that it would be necessary to stash the changes and then after stashing, resolve the conflicts of commits made with the current branch and then as soon as the problems are solved and merge, return the changes from the stash to the branch

I hope I have made myself clear!

**Comment by tierninho** [comment]
@Gabrielfcs Thanks for the suggestion and hope Desktop didn't cause any issue for you.

For what I read, please let me know if this sums up your request:

When a merge conflict is presented, provide an option to stash all unconflicted files, leaving those files with conflicts only. Once the conflicts are resolved, the user can restore the files and commit them all.

- Any chance you have a screenshot of the error message? 
- You mentioned "merging without losing current changes". Can you elaborate on this?

**Comment by Gabrielfcs** [comment]
@tierninho the idea is to make all my changes that have not yet been committed, remain stashed changes and those that have already been committed can be merged.
So, after the merge we can get the stashed changes back to continue with development.

More details in the image.

![github-feature](https://user-images.githubusercontent.com/8412815/83361424-47338200-a35f-11ea-8731-43795302ab85.png)

**Comment by tierninho** [comment]
Thank you for the clarification. We are looking at adding the ability to stash without switching branches -- see #8197 . I believe this is what you are looking for. Please let me know if I missed something, and I will be happy to comment further.

**Comment by Gabrielfcs** [comment]
Well I'm not sure if I'm managing to be straightforward with my messages, but it seems to me that in case #8197 the problem would be in the exchange of branches, in my case it is about the same branch, but the problem is between doing the merge of what I have done the commit and what other people have already changed on the same branch. That the App currently forces me to discard changes that I haven't committed yet and that are files present in the merge conflict.
So the solution would be to stash even before committing the commits.

I hope you understand what I'm talking about 😅

In order to reduce possible mismatches of information, I created a scheme based on the timeline of the master branch and detailing how I arrived at this conclusion

![github-stash-100](https://user-images.githubusercontent.com/8412815/83471820-0ff6cb00-a45c-11ea-8b6a-31300a96a4f3.jpg)

**Comment by tierninho** [comment]
Thanks for the added color.

> So the solution would be to stash even before committing the commits.

This is the feature we are weighing. We will provide the ability to click a button to stash your changes, without the need to switch branches.

**Comment by billygriffin** [comment]
Given that I think this overlaps with #8197, I'm going to close this issue in favor of that one. I do think there's potentially more we could do around this specific problem if we see it coming up more so the person doesn't know they need to stash, but rather we include some verbiage like that in the error dialog or possibly even a CTA to stash right from there.
