### ISSUE TITLE
Hard to distinguish multiple clones in the same directory for enterprise

### ISSUE THREAD

**Issue by benplay2** [desktop/desktop#9881]
### Describe the bug

When multiple clones of the same enterprise repository exist in the same directory, the repository drop-down does not distinguish them except for the tooltip of the full path.

In addition, desktop detects that there are multiple clones of the same repository name getting tracked which causes it to place the parent GitHub organization/user or before the name, but when from the same source this is not helpful.

Interestingly, I noticed the naming behavior of the repositories in the drop-down is different between enterprise and public repositories. For enterprise repositories, the name of the repository itself is displayed, but for public repositories, the name displayed is the folder where it is cloned in.

### Version & OS

Version 2.5.0, Windows 10 64bit enterprise

### Steps to reproduce the behavior

1. Clone a repository from GitHub enterprise site to `GitHub` folder
2. Clone the same repository to `GitHub` folder, but save to a different folder name
3. Look in the repository drop-down, try to distinguish which selection is for which clone

### Expected behavior

I would expect the folder name to be displayed.

Could possibly be in the following format:
`repoName (repoFolderName)`

or maybe if the repoFolderName is the same, but they live in different paths:
`repoPath/repoName`

### Actual behavior

Desktop reacts to the duplicate repositories by adding the containing folder before the name.

### Screenshots

Clones showing up with duplicate names:
![image](https://user-images.githubusercontent.com/24981086/83070406-6f5a7280-a039-11ea-943c-0555c08073a1.png)

Directory where I have stored the duplicate clones:
![image](https://user-images.githubusercontent.com/24981086/83070047-ddeb0080-a038-11ea-8de4-c40c691282c4.png)

**Comment by tierninho** [comment]
@benplay2 Thanks for the suggestion and apologies if this caused any confusion.

We took this scenario into account as part of #6460, which included a range of possibilities and trade-offs that were made to accommodate multiple requests and features around repository organization. At this point, we are holding off on custom grouping and labeling for now. We have two previous issues, [here](https://github.com/desktop/desktop/issues/1533) and [here](https://github.com/desktop/desktop/issues/2324) that cover such requests. They will be reopened when the time comes to re-examine repository organization. 

Thank you for using Desktop!
