### ISSUE TITLE
Cloning from GitLab repository is not possible, there's no way to authenticate.

### ISSUE THREAD

**Issue by rafaelf82** [desktop/desktop#9888]
When I try to clone from gitlab it fails with authentication error, but there's no way to put the authentication info anywhere, it also doesn't ask for one when it fails.

Using Windows 10.

### Steps to reproduce the behavior

Try to clone a private repository on gitlab.com

### Expected behavior

A way to put authentication credentials.

### Actual behavior

Cloning fails.

**Comment by billygriffin** [comment]
Hi @rafaelf82, thanks for the issue. This is the same as https://github.com/desktop/desktop/issues/9843#issuecomment-632302292, so please feel free to use the beta version with instructions in that issue until we get a production release out with the fix for this. Thanks!
