### ISSUE TITLE
Lock icon doesn't update in Header

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#989]
After changing a repo from private to public on dotcom, the icon in the menu changed to unlocked after `update origin`, however the icon in the header remained locked up until I switched repos.

![screen shot 2017-02-27 at 2 17 41 pm](https://cloud.githubusercontent.com/assets/14828183/23382623/cbd7c988-fcf7-11e6-8f27-f7b345db899f.png)

Expected result: Both the header and menu icons should change immediately.

Additionally, when push a new repo up, the lock icon only updates in the menu bar:
![screen shot 2017-04-27 at 10 16 39 am](https://cloud.githubusercontent.com/assets/14828183/25495663/cc283760-2b32-11e7-97de-9e4cb6b89169.png)

Build 0.0.24, OSX 10.11.5

**Comment by JaspalSuri** [comment]
I can confirm this, except that it shows the lock on both the header and in the row of the table containing the list of repositories. I have the latest version of Github desktop as of today. 

I started with a private repo and changed it to public via the repo settings on Github.

**Comment by tierninho** [comment]
@JaspalSuri I cannot reproduce this. I changed from private to public and back, and all icons updated accordingly. There is a slight lag, but that is expected. 

Did the icon on your repos eventually update?

**Comment by JaspalSuri** [comment]
Over the course of three days and one update, it does not change.
