### ISSUE TITLE
Usernames in the repository list view are shown with full lowercase characters

### ISSUE THREAD

**Issue by RA80533** [desktop/desktop#9890]
### Describe the bug

Usernames in the repository list view are shown with full lowercase characters; in other words, usernames in the view have their capitalization stripped.

With the exception of #9997, usernames are correctly cased and displayed elsewhere in the application.

### Version & OS

2.5.1-beta2 (Mac OS 10.14.6)

### Steps to reproduce the behavior

1. Open a repository belonging to a user with at least one uppercase character in their GitHub username (e.g., "RA80533")
2. Click on the **Current Repository** dropdown on the left-hand side
3. Note how the capitalization in the username has been stripped

### Expected behavior

The username should have the same character casing as it does elsewhere in the application.

### Actual behavior

The username is displayed in full lowercase characters.

> Usernames in the repository list view are shown with full lowercase characters; in other words, usernames in the view have their capitalization stripped.

### Screenshots

<img width="960" alt="Screen Shot 2020-05-28 at 9 47 36 PM" src="https://user-images.githubusercontent.com/32469082/83213055-2b499980-a12f-11ea-961c-f2cd15afe02d.png">

### Logs

```console
$ cat "~/Library/Application Support/GitHub Desktop/logs/2020-05-29.desktop.beta.log"
2020-05-29T02:06:52.434Z - info: [ui] [AppStore] loading 1 repositories from store
2020-05-29T02:06:52.436Z - info: [ui] [AppStore] found account: RA80533 (RA80533)
2020-05-29T02:06:52.904Z - info: [ui] launching: 2.5.1-beta2 (Mac OS 10.14.6)
2020-05-29T02:06:52.905Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2020-05-29T02:06:52.963Z - info: [ui] [BranchPruner] No branches to prune.
```

### Additional context

Related: #9997

**Comment by tierninho** [comment]
@RA80533 Thanks for this! Labelling it as a bug as it should be capitalized.

**Comment by tierninho** [comment]
Related to #9997 which also needs fixing and should be a part of any resulting PR.
