### ISSUE TITLE
cloning from url forever impossible after wrong credentials

### ISSUE THREAD

**Issue by robindewitte** [desktop/desktop#9891]
### Describe the bug

I wanted to clone a repo from the gitlab of my school to which I have acces however, weirdly it wanted to get authenticated, which it should not ask. I could not remember the credentials at first but I found them out later, however, cloning the URL from then on obly gave an error and made it absolutely impossible to attempt to clone again.

### Version & OS

Windows 10, github 2.5.0

### Steps to reproduce the behavior

file
clone repository
by url
school link
error

### Expected behavior

I want either that the cloning just succeeds or the authentication gets requested again.

### Actual behavior

Error about authentication

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@robindewitte see https://github.com/desktop/desktop/issues/9843#issuecomment-632302292. This will be fixed in the next release of GitHub Desktop. Let me know if you run into any problems with using the beta version.
