### ISSUE TITLE
Updating remote repository does not work

### ISSUE THREAD

**Issue by mr5z** [desktop/desktop#9892]
### Describe the bug

Modifying the address of the remote does not reflect when making any git commands. The old address of the remote is still shown from the error after any git operation attempt.

### Version & OS

GitHub Desktop version 2.5.0, macOS Catalina

### Steps to reproduce the behavior

1. Go to Repository > Repository Settings > Remote > Update > Save

### Expected behavior

The new address of the remote should be seen in case git operation failed or no error at all.

### Actual behavior

Showing the old remote address.

### Screenshots

NA

### Logs

NA

### Additional context

NA

**Comment by tierninho** [comment]
@mr5z Thanks for filing this and apologies for the troubles. Can you elaborate on the issue you are having? Where are you seeing the "old remote address"? 

Once you have saved the new remote address in Desktop, you can verify the it is correct by opening the Terminal (Repository menu > Open in Terminal) and type `git remote -v`.

Any screenshots or logs (See the Help menu in Desktop) would be helpful.

**Comment by tierninho** [comment]
@mr5z   As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by AHMED0504492442** [comment]
Please return the hard disk that was compromised by you and crash it and out of the operating system. Why did you do that?
________________________________
