### ISSUE TITLE
100% cpu usage on macOS Catalina while waiting at permissions elevation prompt for auto update helper

### ISSUE THREAD

**Issue by thesyntaxinator** [desktop/desktop#9901]
### Describe the bug

When Github desktop is running and has an update, it attempts to auto-apply this update. This causes a permissions elevation prompt to display for the GitHub desktop update helper. While the prompt is showing, GitHub desktop takes 100% CPU usage until the user responds to the prompt.

### Version & OS
Just updated to 2.5.0 (issue occurred on the previous version I had) on macOS Catalina

### Steps to reproduce the behavior
See above

### Expected behavior
Github Desktop should not take 100% CPU while waiting for the user to respond to the permissions elevation prompt.

### Actual behavior
See above

**Comment by silenceman65** [comment]
Who is owner azure/ Mac OS ?

**Comment by alastaircoote** [comment]
Just wanted to comment to say that I also get this 100% of the time. Barring a bug fix can we just get an option to disable auto update checks? My laptop has been pegged at 100% CPU overnight...

**Comment by steveward** [comment]
Closing as stale since we haven't seen further reports of this with more recent versions of macOS.
