### ISSUE TITLE
Cloning Repo Failed with SSL certificate problem.

### ISSUE THREAD

**Issue by BingHo1013** [desktop/desktop#9902]
### Describe the bug

When I was trying to clone a repo, the desktop kept pushing warning of SSL certificate problem.

### Version & OS

Github Desktop V2.4.0, macOS Catalina 10.15.4

### Expected behavior

Need the SSL certification issue to be resolved which I could not get which certificate shall I do.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/61045304/83352918-8246ad00-a381-11ea-998c-6ac5d4acf065.png)

### Logs

[2020-05-31.desktop.production.log](https://github.com/desktop/desktop/files/4707671/2020-05-31.desktop.production.log)

**Comment by niik** [comment]
Hi @BingHo1013, sorry to hear you're having problems. There's two common reasons for seeing certificate errors like this, one is the system clock being incorrect, the other being a SSL-intercepting proxy.

Are you using GitHub Desktop at a corporation or behind some other sort of proxy that might intercept and decrypt your traffic?

It would be helpful if you could check the [system proxy configuration](https://support.apple.com/guide/mac-help/enter-proxy-server-settings-on-mac-mchlp2591/mac) as well as make sure that you don't have a manually configured Git proxy by running the command `git config http.proxy` and making sure that the output is empty.

**Comment by tierninho** [comment]
@BingHo1013 Potentially a coincidence, but thought I'd share just in case. On the exact day you experienced this issue (May 29th)`crt.sh/?id=1` expired, which affected a bunch of SSL certs. 

CRT.SH is a web interface to a distributed database called the certificate transparency logs.

Some links to explore that may help you or your sys-admin:
https://twitter.com/sleevi_/status/1266647545675210753
https://github.com/openssl/openssl/issues/12006
https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT
Cert checker: https://ohdear.app/tools/certificate

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
