### ISSUE TITLE
Cannot see Webstorm on my code editors

### ISSUE THREAD

**Issue by snowy1000** [desktop/desktop#9903]
I want to use and set Webstorm as my code editor, but I cannot see it on my settings.

I believe adding Webstorm to settings of Github code editor can really be useful for Desktop app.

**Comment by tierninho** [comment]
@snowy1000 Thanks for the issue.

This could be an issue related to the installation of the Webstorm product. Please follow along the instructions here to resolve https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000110030-No-JVM-installations-found-

Let us know if you need further assistance -- happy to help.
