### ISSUE TITLE
Cloning: error: filename in tree entry contains backslash" '\'

### ISSUE THREAD

**Issue by nikolapeja6** [desktop/desktop#9904]
### Describe the bug

When cloning the [MicrosoftDocs/azure-docs](https://github.com/MicrosoftDocs/azure-docs) repository though the GitHub Desktop app, it failed. The logs showed the following error:

```
error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/MicrosoftDocs/azure-docs.git C:\_repos\azure-docs` exited with an unexpected code: 128.
...
Receiving objects:  80% (2707986/3353572), 8.32 GiB | 17.28 MiB/s
error: filename in tree entry contains backslash: '\media'
fatal: Not all child objects of cfb022b5e95f43eb589592e5c3633fc41f36dba4 are reachable
fatal: index-pack failed
```
From the logs, the command that executed the clone was this:

```
git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/MicrosoftDocs/azure-docs.git C:\_repos\azure-docs
```

However, when I tried to manually execute the command it passed. Not sure what is causing the problem.

### Version & OS

GitHub Desktop Version 2.5.0 on Windows 10 (also tried on Windows Server, failed there as well).

### Steps to reproduce the behavior

Clone the repo `https://github.com/MicrosoftDocs/azure-docs` form the GitHub Desktop application.

### Expected behavior

Cloning should be successful.

### Actual behavior

Cloning fails.

**Comment by steveward** [comment]
@nikolapeja6 thanks for the report. It looks like you are running into https://github.com/git-for-windows/git/issues/2435. When we [update the version of Git](https://github.com/desktop/dugite/pull/399) that ships with GitHub Desktop it should resolve this issue. Here's the relevant bit from the release notes:

> * An earlier update to Git for Windows declared that a tree object is
   invalid if it has a path component with backslash in it, which was
   overly strict, which has been corrected.  The only protection the
   Windows users need is to prevent such path (or any path that their
   filesystem cannot check out) from entering the index.
   (merge 224c7d70fa js/mingw-loosen-overstrict-tree-entry-checks later to maint).

[Full Release Notes](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.25.0.txt)

**Comment by steveward** [comment]
A workaround for this bug can be found in this [comment in issue #10004](https://github.com/desktop/desktop/issues/10004#issuecomment-644075555) by @niik.
