### ISSUE TITLE
when I clone a gitlab registry, it shows a popwindow that "authentication failed....",but there is no other window to let me login in. 

### ISSUE THREAD

**Issue by Liusq-Cindy** [desktop/desktop#9907]
### Describe the bug

when i choose to clone a new gitlab registry,there will open a pop window,show that "authentication failed....."like below:
![image](https://user-images.githubusercontent.com/41781513/83370002-a2fa1b80-a3f0-11ea-8a29-70d48b19820a.png)
I want to login in,but there is no where let me login in my account. I remenber the old version of 'github desktop' will open a login in window,but now, the new version miss the window, so , cloud you please give me a solusion? (except  command line and use ssh url)

### Version & OS
Version 2.5.0  Mac os 10.15.2

### Steps to reproduce the behavior

1. Go to 'clone repository'
2. Click on 'URL'
3. input a 'http url' of a gitlab 
![image](https://user-images.githubusercontent.com/41781513/83370610-80690200-a3f2-11ea-9bd7-9bcb85870669.png)

4. See error: authentication failed, but nerver pop a winodw to let me login in.

**Comment by niik** [comment]
Hey @Liusq-Cindy, sorry to hear you're having problems. This is a known issue with the last release, see https://github.com/desktop/desktop/issues/9843. We have fixed the problem and fix is available on [our beta channel](https://github.com/desktop/desktop#beta-channel) and it will be included in the next release of the production version of the app. If you need a fix right now we recommend [downloading the beta version](https://github.com/desktop/desktop#beta-channel).
