### ISSUE TITLE
Unable to delete a tag

### ISSUE THREAD

**Issue by tschlarman** [desktop/desktop#9915]
### Describe the bug

Deleting a tag on the server does not remove it from the local GH desktop client. Local wants to push it back to the server again on the next push origin.

### Version & OS

Windows v2.5.0

### Steps to reproduce the behavior

1. Create a tag in GH Desktop
2. Push it to GH
3. Remove the tag on the GH website
4. Fetch/Pull origin on GH desktop client

### Expected behavior

The tag would disappear from GH desktop. Other git clients handle this correctly.

### Actual behavior

Tag does not disappear from GH Desktop and wants to re-add it to the server on the next push to origin.

**Comment by billygriffin** [comment]
Hi @tschlarman, thanks for the issue! We shipped the ability to delete an unpushed tag to beta (https://github.com/desktop/desktop/pull/9796). After that goes out to production (likely this week), we'll see if that solves the problem or if there's a broader surface area we need to consider. Tag syncing with remotes is really tough so we're hoping our relatively limited scope might help alleviate some of that, but we're certainly open to feedback after that ships. Thanks again.
