### ISSUE TITLE
Remove max width limit while resizing panes

### ISSUE THREAD

**Issue by specter78** [desktop/desktop#9922]
### Describe the feature or problem you’d like to solve

Presently, there is a max width limit on size of middle pane while viewing commit history. 

In commits involving (multiple) file rename, it is not possible to properly know what changed since most of the space is taken by directory path, leaving very little for filename.

### Proposed solution

Remove max width limit

**Comment by niik** [comment]
Hi @specter78, thanks for opening this. We're tracking this issue in https://github.com/desktop/desktop/issues/2745 so please follow that issue for any updates and feel free to give it a 👍 to indicate your support of it but this issue will also be cross-referenced so we'll see it whenever we look at #2745.
