### ISSUE TITLE
 Data clone error from bitbucket.org

### ISSUE THREAD

**Issue by tuanskyxox** [desktop/desktop#9924]
I got an error when I downloaded the code from bitbucket.org and found it on many computers and I installed windows several times and logged in the correct username and password

![image](https://user-images.githubusercontent.com/52083837/83553665-b9f65600-a535-11ea-8752-547acb70cf7d.png)

**Comment by tierninho** [comment]
Hello @tuanskyxox Thanks for filing. 

Please see the workaround here which address this issue.
https://github.com/desktop/desktop/issues/9843#issuecomment-632302292
