### ISSUE TITLE
Clone GitLab repository using HTTPS.

### ISSUE THREAD

**Issue by GusMCoutinho** [desktop/desktop#9926]
### Describe the bug

I'm working on Windows x64 and I'm using GitHub Desktop to clone a GitLab repository (via HTTPS). When trying to clone the repository I got an error window that shows some actions to perform but they are not suitable for my case. The log message can be found down below.

### Version & OS
Windows x64
GitHub Desktop Version 2.5.0

### Steps to reproduce the behavior

1. Go to 'File > Clone Repository...'
2. Click on 'URL'
3. Copy the HTTPS url from GitLab project (Repository > Clone > HTTPS) and paste in 'Repository URL'
4. Choose 'Local path' 
5. Starts clonning (but without progress) and error message appears after couple seconds.

### Expected behavior

A window pop-up with the title 'Authentication failed' and with two fields to be filled: Username and Password. (where i can add the GitLab username and access token generated in GitLab for my user)

### Actual behavior

Error window appear mentioning some actions to take (actions also mentioned in log).

### Logs

Note: I edited the URL for security reasons.

" (...)
2020-06-03T08:50:46.479Z - error: [ui] git -c credential.helper= clone --recursive --progress -- https://.../my-repository.git C:\Temp\GitHubDesktop-Repositories\my-repository exited with an unexpected code: 128. stderr: Cloning into 'C:\Temp\GitHubDesktop-Repositories\my-repository'... remote: HTTP Basic: Access denied fatal: Authentication failed for 'https://.../my-repository.git/' (The error was parsed as 3: Authentication failed. Some common reasons include:

You are not logged in to your account: see File > Options.
You may need to log out and log back in to refresh your token.
You do not have permission to access this repository.
The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)"

### Additional context

I already tried to:

- Unistall GitHub Desktop

- Delete C:\Users\MyUser\Roaming\AppData\GitHub Desktop

- Confirm that Control Panel\All Control Panel Items\Credential Manager does not have any GitHub credential

- I'm not logged in GitHub, as the repository is from GitLab and no login is necessary in this case (except from the necessary authentication i would like to configure "username and password/access token" that should pop-up when trying to clone).

- Restart laptop after everything above was done.

## Proposal

Is it possible to include some section to configure the username and password (access token) before start clonning via HTTPS?

**Comment by niik** [comment]
Hey @GusMCoutinho, sorry to hear you're having problems. This is a known issue with the last release, see https://github.com/desktop/desktop/issues/9843. We have fixed the problem and fix is available on [our beta channel](https://github.com/desktop/desktop#beta-channel) and it will be included in the next release of the production version of the app (which we're hoping to release today).

If you need a fix right now we recommend [downloading the beta version](https://github.com/desktop/desktop#beta-channel).
