### ISSUE TITLE
Can't download GitHub Desktop for Windows

### ISSUE THREAD

**Issue by MARICEL30** [desktop/desktop#9932]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by MARICEL30** [comment]
I get entry point no found.

**Comment by tierninho** [comment]
@MARICEL30 Thanks for the issue. Are you downloading from here: https://desktop.github.com/ or upgrading to the latest version?

What version of Windows are you on?

**Comment by MARICEL30** [comment]
Hi, Yes I'm new to the desktop version, I was trying to download it today from that website you provided.  I have Windows 7, version 6.1 ..do you think it is too old?

**Comment by steveward** [comment]
@MARICEL30 are you using a 32-bit version of Windows 7? GitHub Desktop only supports 64-bit versions of Windows 7 and above.

**Comment by MARICEL30** [comment]
64-bit

**Comment by steveward** [comment]
To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please upload that as an attachment.

**Comment by MARICEL30** [comment]
How do you find that? I looked everywhere,..I'm looking at Google Chrome downloads, and there are some GitHubDesktopSetup.exe links there, but it doesn't let me send that and I'm not sure you're looking for that...I think I'm going to leave it, as I'm kinda newbie..thanks anyway..
![Screenshot 2020-06-03 21 21 06](https://user-images.githubusercontent.com/42100507/83686240-cd5efb00-a5e1-11ea-90ad-fe86c2395bab.png)

**Comment by steveward** [comment]
@MARICEL30 you can open up File Explorer and enter those locations (`%LocalAppData%\SquirrelTemp\` and `%LocalAppData%\GitHubDesktop\`) into the File Explorer Address Bar.

**Comment by MARICEL30** [comment]
Hi Steve, I just done that, but nothing shows up, no worries...I'll try again in the future, thanks for all the help and the super cool work you're doing.
