### ISSUE TITLE
Changes in commit sorted by type

### ISSUE THREAD

**Issue by specter78** [desktop/desktop#9947]
Presently, the app sorts the changes by name. This results in additions, deletions, renamed files getting mixed. 

Instead, the changes should be sorted by type (preferably add, delete and then rename) and within each, sorted by name.

**Comment by billygriffin** [comment]
Hi @specter78, thanks for the issue! While I'm personally attracted to your idea, this would represent an enormous change to how people are accustomed to using Desktop for the core commit workflow, and the icons serve the purpose of visualizing how files have changed. So I'm going to close this to indicate it's not something we intend to change, but really appreciate you sharing.

**Comment by specter78** [comment]
> this would represent an enormous change

Please elaborate on this. 

In what I’m suggesting, everything remains the same same (including icons and other things). The only change is that the files in middle pane of commits get reordered (here too there doesn’t need to be a distinction, the icons will do).

**Comment by specter78** [comment]
And there is also a possibility of providing user preference for old order or new order.
