### ISSUE TITLE
git@github.com:github/gitignore.git

### ISSUE THREAD

**Issue by oyyunttt** [desktop/desktop#9957]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@oyyunttt if you have a specific feature request for GitHub Desktop please fill out the issue template. Thanks!
