### ISSUE TITLE
View on GitHub doesn't go to latest repository

### ISSUE THREAD

**Issue by denserras** [desktop/desktop#9958]
### Describe the bug

In previous versions of GitHub Desktop, going to the View on GitHub would take you to the repository listed in the Repository Settings. On the latest version, 2.5.2, the command takes me to the parent repository if the repo is a fork. Note the Compare feature still works using the current repository.

### Version & OS

GitHub Desktop 2.5.2 on MacOS 10.14.6

### Steps to reproduce the behavior

1. Go to View on Github
2. See error

### Expected behavior

Should take you to the repository as listed in the Repository Settings

### Actual behavior

If the repo is a fork, it takes you to the parent repository

### Screenshots

My repos aren't public so I can't share a screenshot

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by rafeca** [comment]
Hey @denserras ! Thanks for reporting this issue. This settings screen has been introduced in v2.5.2, so I'm glad that you're using it!

I've tried reproducing the issue but the "View on GitHub" button takes me correctly to the fork when I set the option to use the repository for my own purposes.

Can you try reproducing this on a public repository and then give some reproduction steps if you're able to?

Thanks!

**Comment by tierninho** [comment]
@denserras  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
