### ISSUE TITLE
github desktop error : cannot spawn

### ISSUE THREAD

**Issue by EunaGo** [desktop/desktop#9961]
### Describe the feature or problem you’d like to solve
I can use 'commit' but when I use 'push' the error is occured.

error: cannot spawn C:\Users\BIT02-03\AppData\Local\GitHubDesktop\app-2.5.2\resources\app\static\ask-pass-trampoline.bat: No error
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### Proposed solution 

A similar case: https://github.com/desktop/desktop/issues/1916
other solution: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789
(I tried 'ask-pass-trampoline.bat errors' part)

I tried all solution which Git offer to solve this error, but error is not solved.

### Additional context
![image](https://user-images.githubusercontent.com/63032830/83990917-20400600-a986-11ea-8c79-f60d61b942d6.png)

**Comment by steveward** [comment]
Thanks for the report. Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to resolve this issue on your machine. One of the more common causes has been the modified registry entries. Let me know if you have any questions about the steps, or if you are unable to resolve the issue.

**Comment by EunaGo** [comment]
Thanks for the comment !!

The help document you said has already been seen. My error seems to be part of ask-pass-trampoline.bat. I tried everything, but the problem was not solved.

-------------------------------------------------------------------
*modified registry entries(#6789, #2623):
As a result of checking, there is no Autorun in my registry.

*Whether the user name has special characters(#7064):
Although the original user's name included special characters, the problem did not occur when using the desktop for the first time. The user's name has also been changed, but the problem remains.

*Antivirus program:
I have never installed an antivirus program.

*Run as administrator(#5082):
I tried but the problem is not solved

*try performing a fresh installation of GitHub Desktop:
I tried very much. According to the manual... but faild
--------------------------------------------------------------------
Please let me know if there is another way. Thank you.

![image](https://user-images.githubusercontent.com/63032830/84095730-03193f00-aa3b-11ea-8d95-46d7d80b4abe.png)
![image](https://user-images.githubusercontent.com/63032830/84095738-0a404d00-aa3b-11ea-99f0-f4beed605ae7.png)

**Comment by bharatkathuria** [comment]
I got this same issue and tried everything mentioned above, can any one help me?

**Comment by aktarzaman** [comment]
I am also facing the same issue. Is there any update on this?

**Comment by Brennan-W-Curtis** [comment]
I'm also experiencing this issue. It's weird because I haven't encountered any issues like this and didn't have any issues pushing commits until today.

**Comment by steveward** [comment]
@Brennan-W-Curtis we'll be shipping a fix for this issue in an upcoming release, but if you would like to give it a try now you can install the [beta version](https://github.com/desktop/desktop#beta-channel). Let me know if that does not get things working.

**Comment by Brennan-W-Curtis** [comment]
Beautiful. Thank you for the head's up!

**Comment by Humna-Asad** [comment]
i'm facing the same issue

**Comment by steveward** [comment]
@Humna-Asad please see my comment above for a link to the beta version of GitHub Desktop that resolved this issue. Let us know if that does not get things working.

**Comment by chris-will** [comment]
Version 2.8.4-Beta 5 didn't solve the problem either guys. And here we are in July of 2021.

**Comment by steveward** [comment]
@chris-will we have not had any further reports of this error -- can you please open an issue, fill out the template, and share your log file so we can investigate?
