### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by neptunesoft** [desktop/desktop#9963]
Can you make a multi - language package to support Chinese

**Comment by steveward** [comment]
Thanks for contributing @neptunesoft. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/GitHub-Desktop-Chinese-Language-Pack
