### ISSUE TITLE
Mass select files from highlight

### ISSUE THREAD

**Issue by softsound** [desktop/desktop#9976]
### Describe the feature or problem you’d like to solve
Highlight and select, I would like to highlight around 3000 files and select them out of 60,000 changes. 
Currently I have not found a way to quickly select more then one file at a time. I can highlight them but not select them.

I'm trying to slowly commit a large project I was given and currently have not found an easy way to select a group of highlighted files. These are various files of numerous size so I do not want to commit the full 60k as it will timeout.

### Proposed solution

It will benefit everyone using this. Please allow me the ability to either select all highlighted with a button or let me right click and select them from a menu option. Currently all I see is a select all button, but I only want to select the highlighted files.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
![Select](https://user-images.githubusercontent.com/1772703/84210506-8445f580-aa7e-11ea-9595-3487d5627434.PNG)

**Comment by tierninho** [comment]
@softsound Thanks for that issue. To select multiple files and toggle the checkbox, please try using tapping your `spacebar`. We could do a better job at exposing this hidden feature as it has caused some frustration. 

@desktop/design Any thoughts on how we can surface this `spacebar` feature so it's not so hidden?

**Comment by softsound** [comment]
[Could you add that spacebar note to your shortcut page? ](https://help.github.com/en/desktop/getting-started-with-github-desktop/keyboard-shortcuts-in-github-desktop)

**Comment by tierninho** [comment]
> Could you add that spacebar note to your shortcut page?

Yes! Thank you for pointing it out.

Glad you got it working 🥳

**Comment by tierninho** [comment]
Circling back as `space` key is now added to the shortcuts page: https://help.github.com/en/desktop/getting-started-with-github-desktop/keyboard-shortcuts-in-github-desktop#branches

**Comment by niik** [comment]
> ..Ah nvm it worked, guess there was a delay. All good thanks!

> Circling back as `space` key is now added to the shortcuts page: https://help.github.com/en/desktop/getting-started-with-github-desktop/keyboard-shortcuts-in-github-desktop#branches

Looks like this one was resolved, gonna close it out, thanks y'all!
