### ISSUE TITLE
Git Desktop hangs while cloning

### ISSUE THREAD

**Issue by PriyankaJuneja** [desktop/desktop#9980]
While cloning a repository, all the files are copied, and deltas resolved. Post that Git Desktop screen hangs and displays below screen:

![image](https://user-images.githubusercontent.com/40831581/84311691-5c8b8600-ab81-11ea-9d44-836b44cc1295.png)

The files are copied into the local drive, but the repository disappears from the list of repositories.

**Comment by tierninho** [comment]
@PriyankaJuneja  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
