### ISSUE TITLE
"git commit --amend" feature is missing

### ISSUE THREAD

**Issue by Neustradamus** [desktop/desktop#9981]
### Describe the feature or problem you’d like to solve

Current repository -> History -> Right click on last commit:

We have not possibility to change the title and the description of the last commit.

### Proposed solution

Add the function in GitHub Desktop.

### Additional context

Do not forget the "git push -f" after the "git commit --amend".

**Comment by billygriffin** [comment]
Thanks @Neustradamus! We’re tracking this in #1644. Also just wanted to note that for commits that haven’t been pushed, you can use “Undo” immediately below the commit button.

**Comment by Neustradamus** [comment]
@billygriffin: Thanks but the cited ticket is closed...

You have not understand: After done "git commit --amend", it is needed to do a "git push -f".

**Comment by Neustradamus** [comment]
@billygriffin: ?
