### ISSUE TITLE
After its new update , the processing is very slow - Version 2.5.2

### ISSUE THREAD

**Issue by psiservices-sbakre** [desktop/desktop#9991]
Please resolve this problem as its affecting the daily work.

**Comment by steveward** [comment]
@psiservices-sbakre thanks for the report. This type of performance degradation is often caused by antivirus or other security software on your system. Are you running any security software on this system that could be causing this?

**Comment by tierninho** [comment]
@psiservices-sbakre  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
