### ISSUE TITLE
Changelists would be very useful

### ISSUE THREAD

**Issue by SebastianEma** [desktop/desktop#9992]
### Describe the feature or problem you’d like to solve
I Think it would be highly useful if the Github client had a changelists feature, where I could put a lot of Changes that I cant commit for now, but save for later without those Changes clogging up my current list of items.

**Comment by steveward** [comment]
Thanks for contributing @SebastianEma. It sounds like you are interested in GitHub Desktop providing full support for stashing, which allows you to temporarily store changes. Currently GitHub Desktop only allows you to stash changes when switching branches, but we [have plans](https://github.com/desktop/desktop/issues/8197#issuecomment-640931392) to add the ability to stash all changes in the future. I hope that helps!

**Comment by saipavanbhanu** [comment]
It's not about stashing. 
Change list feature will help on below scenarios.
1. When we are working on different features at the same time, it would be good if we can have one commit for different features.
2. local changes only for dev environment which we don't want to include for every commit.

More about this feature in this link.
https://www.jetbrains.com/help/idea/managing-changelists.html#:~:text=If%20you're%20working%20with,automatically%20placed%20in%20this%20changelist.
