### ISSUE TITLE
Failed Authentication due to malware

### ISSUE THREAD

**Issue by djswagmaster** [desktop/desktop#9994]
### Describe the bug

After booting up github desktop, I am trying to publish a new branch to github. However, it does not allow me to, saying authentication failed, despite the correct password and username being typed in. 

### Version & OS

Version 2.5.2
Windows 10

### Steps to reproduce the behavior

1. Go to Github Desktop
2. Click on Publish Branch

### Expected behavior

For Github Desktop to publish the master branch to the website.

### Actual behavior

For a moment it says find: FirewallModule.exe no such file or directory, and then it comes up with Authentication failed. Some common reasons include: blah blah blah. 

### Logs

```
2020-06-12T23:04:00.742Z - info: [ui] [AppStore] loading 1 repositories from store
2020-06-12T23:04:00.742Z - info: [ui] [AppStore] found account: djswagmaster (djswagmaster)
2020-06-12T23:04:01.159Z - info: [ui] launching: 2.5.2 (Windows 10.0.18362)
2020-06-12T23:04:01.160Z - info: [ui] execPath: 'C:\Users\User\AppData\Local\GitHubDesktop\app-2.5.2\GitHubDesktop.exe'
2020-06-12T23:04:04.687Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: freakoutnewest - djswagmaster (has token)
2020-06-12T23:04:06.060Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master --set-upstream --progress (took 1.289s)
2020-06-12T23:04:07.760Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.315s)
2020-06-12T23:04:07.760Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
find: '/I': No such file or directory
find: '/N': No such file or directory
find: 'FirewallModule.exe': No such file or directory
find: '/I': No such file or directory
find: '/N': No such file or directory
find: 'FirewallModule.exe': No such file or directory
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/djswagmaster/freakoutnewest.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
```

### Additional context

This has worked before but after opening it recently it does not anymore. It also didn't let me update existing branches on other projects, or clone branches.

I have tried reinstalling Github, clearing credentials, restarting my PC.

**Comment by tierninho** [comment]
@djswagmaster Thank you for the issue. We can seen [this issue](https://github.com/desktop/desktop/issues/3604) popped once before due to malware.

Here was the solution. Please give it a go and let us know!
> This time with "FirewallModule" and "FirewallModule.exe" instead of "SoundMixer" and "SoundMixer.exe". The same instructions [here](https://social.technet.microsoft.com/Forums/windows/en-US/9fb738ab-2f3d-4a07-ac8a-173d63a47f87/cmd-not-working-due-to-an-error-the-error-occurs-on-practically-everything?forum=win10itprogeneral) fixed the issue

**Comment by djswagmaster** [comment]
After a full scan using AVG and Windows Defender, the issue still arises.. Also I deleted the Firewall Module folder

**Comment by tierninho** [comment]
Thanks for the update. Did you also delete the HKEY registry keys as well, as mentioned in the link?

**Comment by Ren-123** [comment]
I had the same problem and can't deal with it.

**Comment by tierninho** [comment]
@Ren-123 Please open a new issue https://github.com/desktop/desktop/issues/new?template=bug_report.md

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
