### ISSUE TITLE
como hago para crear un repositorio en la rama master con github desktop?

### ISSUE THREAD

**Issue by sergio3231** [desktop/desktop#9998]
![github](https://user-images.githubusercontent.com/65269238/84570257-e9853980-ad51-11ea-8db5-2525d95f02f0.png)

**Comment by tierninho** [comment]
@sergio3231 No estoy seguro de entender tu problema por completo. Escriba el problema como un comentario y no incrustado como texto en una imagen. Además, comparta sus registros desde el menú: GitHub Desktop > Help > Show Logs in Explorer. Gracias!

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
