### ISSUE TITLE
Cloning bug

### ISSUE THREAD

**Issue by sinand99** [desktop/desktop#9999]
### Describe the bug

Cloning fails with a meaningless error message. Your horrible GUI doesn't even let me see the buttons below in the modal dialogbox.

### Version & OS

Version 2.5.2 on windows 10 x64

### Steps to reproduce the behavior

1. Click on Clone a repository from internet
2. Select URL
3. Paste following wiki: https://github.com/FNA-XNA/FNA.wiki.git
4. Click clone

### Expected behavior

A proper local clone

### Actual behavior

Error message with invisible buttons

### Screenshots

![Clipboard01](https://user-images.githubusercontent.com/5251826/84576602-b036e300-adbe-11ea-8a50-0d7c453af6d4.jpg)

**Comment by jjwagner** [comment]
I was having a similar problem, so I tried to reproduce yours to see if we were having the same issue. You can view the logs with Help->Show logs in Explorer.

In your case, there's an error:
> 2020-06-15T01:32:01.304Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/FNA-XNA/FNA.wiki.git D:\GitHub\FNA.wiki` exited with an unexpected code: 128.
stderr:
...
error: invalid path '1:-Download-and-Update-FNA.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by steveward** [comment]
@sinand99 it looks like the `1:-Download-and-Update-FNA.md` file has a colon in the filename, which is an illegal character on Windows. This is causing the clone operation to fail. You can rename the file directly on GitHub to resolve this issue. 

I'd also like to note that GitHub Desktop does not have great support for wikis at this time (see https://github.com/desktop/desktop/issues/3839), so please be aware there will be issues if you try to work with a wiki repository.
